<?php

/**
 * @file
 * Alshaya West Elm brand module file.
 */

/**
 * Implements hook_alshaya_performance_preload_alter().
 */
function alshaya_we_transac_alshaya_performance_preload_alter(array &$preload) {
  // WestElm's icon font comes from whitelabel.
  $icon_directory_path = '/' . drupal_get_path('theme', 'alshaya_white_label') . '/fonts';

  $preload[] = [
    'as' => 'font',
    'href' => $icon_directory_path . '/alshaya-icons.woff?D7b5iT',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff',
  ];

  $themeHandler = \Drupal::service('theme_handler');
  $themePath = $themeHandler->getTheme($themeHandler->getDefault())->getPath();
  $fonts_directory_path = '/' . $themePath . '/fonts';

  $preload[] = [
    'as' => 'font',
    'href' => $fonts_directory_path . '/GTEestiDisplay-Light.woff2',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff2',
  ];
  $preload[] = [
    'as' => 'font',
    'href' => $fonts_directory_path . '/GTEestiDisplay-Medium.woff2',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff2',
  ];
  $preload[] = [
    'as' => 'font',
    'href' => $fonts_directory_path . '/GEDinarTwoMedium.woff2',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff2',
  ];
  $preload[] = [
    'as' => 'font',
    'href' => $fonts_directory_path . '/GEDinarOneMedium.woff2',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff2',
  ];
}
