<?php

/**
 * @file
 * Contains Fit calculator related translations.
 */

/**
 * Appointment translation.
 */
function _alshaya_fit_calculator_translations() {
  return [
    'The Perfect Fit Calculator' => [
      'ar' => 'حاسبة المقاس المثالي',
    ],
    'Show measurements in:' => [
      'ar' => 'تُظهر المقاسات كالتالي:',
    ],
    'Inches' => [
      'ar' => 'بوصات',
    ],
    'Centimeters' => [
      'ar' => 'سنتيمترات',
    ],
    'band size' => [
      'ar' => 'محيط أسفل الصدر',
    ],
    'bust size' => [
      'ar' => 'محيط منتصف الصدر',
    ],
    'get my size' => [
      'ar' => 'احصلي على مقاسك',
    ],
    'Sorry, we don\u2019t carry your size yet but we are always working to expand our collections.' => [
      'ar' => 'عذراً، مقاسك غير متوفر لدينا بعد لكننا نعمل دائماً على توسيع تشكيلاتنا',
    ],
    'Your size is ' => [
      'ar' => 'مقاسك هو',
    ],
    'shop your size' => [
      'ar' => 'تسوقي حسب مقاسك',
    ],
    'Size Conversion Chart' => [
      'ar' => 'جدول تحويل المقاسات',
    ],
  ];
}
