<?php

/**
 * @file
 * Contains Fit calculator related translations.
 */

/**
 * Appointment translation.
 */
function _alshaya_fit_calculator_translations() {
  return [
    'The Perfect Fit Calculator' => [
      'ar' => '',
    ],
    'Show measurements in:' => [
      'ar' => '',
    ],
    'Inches' => [
      'ar' => '',
    ],
    'Centimeters' => [
      'ar' => '',
    ],
    'band size' => [
      'ar' => '',
    ],
    'burst size' => [
      'ar' => '',
    ],
    'get my size' => [
      'ar' => '',
    ],
    'Sorry, we don\u2019t carry your size yet but we are always working to expand our collections.' => [
      'ar' => '',
    ],
    'Your size is ' => [
      'ar' => '',
    ],
    'shop your size' => [
      'ar' => '',
    ],
    'Size Conversion Chart' => [
      'ar' => '',
    ],
  ];
}
