<?php

/**
 * @file
 * Module file for alshaya_country.
 */

use Drupal\Core\Locale\CountryManager;

/**
 * Helper function to set default regional information.
 *
 * This function set the default country and timezone for the site, based on
 * the country selected at installation time.
 *
 * @param string $country_code
 *   The country code.
 */
function alshaya_country_set_default_regional_info($country_code, $store_search_placeholder) {
  // Set default country for site.
  \Drupal::configFactory()->getEditable('system.date')
    ->set('country.default', $country_code)
    ->save();

  // Try to get timezone from country code.
  $timezones = \DateTimeZone::listIdentifiers(\DateTimeZone::PER_COUNTRY, $country_code);

  // Use given timezone by default, use first one from the result if found.
  $timezone = reset($timezones);

  // Set default timezone from settings.
  \Drupal::configFactory()->getEditable('system.date')
    ->set('timezone.default', $timezone)
    ->save();

  // Re-save store finder view to ensure country code is updated.
  \Drupal::configFactory()->getEditable('views.view.stores_finder')->save();
  
  // Set Country specific placeholder for store finder search.
  \Drupal::configFactory()->getEditable('alshaya_stores_finder.settings')
  ->set('store_search_placeholder', $store_search_placeholder)
  ->save();
}

/**
 * Utility function to get the country name.
 *
 * @return string
 *   Country name.
 */
function _alshaya_country_get_site_level_country_name() {
  $default_site_country = _alshaya_custom_get_site_level_country_code();
  $countries = CountryManager::getStandardList();
  if (isset($countries[$default_site_country])) {
    $default_site_country = $countries[$default_site_country]->getUntranslatedString();
  }
  return $default_site_country;
}
