<?php

/**
 * @file
 * Module file with hooks specific to Muji brand.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_mu_transac_rcs_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'rcs_product') {
    $build['#attached']['library'][] = 'alshaya_mu_transac_rcs/product';
  }
}

/**
 * Implements hook_alshaya_rcs_product_query_fields_alter().
 */
function alshaya_mu_transac_rcs_alshaya_rcs_product_query_fields_alter(array &$fields) {
  $product_attributes = \Drupal::config('alshaya_mu_transac_rcs.settings')->get('product_attributes');
  array_push($fields['items'], ...$product_attributes);
}
