FROM jenkins/jenkins:latest

USER root
RUN apt-get update && apt-get install -y apt-transport-https
RUN apt-get install ca-certificates curl gnupg lsb-release -y
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update
# Install Docker
RUN apt-get install docker-ce docker-ce-cli containerd.io -y
RUN apt-get install docker-compose-plugin -y

RUN ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
RUN apt-get install openjdk-11-jdk -y

# Install Jenkins plugins
RUN jenkins-plugin-cli --plugins cucumber-reports rebuild

# Copy default jobs.
COPY jobs/local-smoke-pull-requests.xml /usr/share/jenkins/ref/jobs/local-smoke-pull-requests.xml/config.xml
COPY jobs/parameterized.xml /usr/share/jenkins/ref/jobs/parameterized.xml/config.xml
