<?php

/**
 * @file
 * The Module file.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\block\Entity\Block;

/**
 * Implements hook_form_alter().
 */
function alshaya_d_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::moduleHandler()->moduleExists('alshaya_email_signup') && $form_id == 'webform_submission_alshaya_email_signup_add_form') {
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $uuid = '19207aad-0e43-4d3a-96d7-c74141f75bb1';
    $entity_manager = \Drupal::getContainer()->get('entity.manager');
    $block = $entity_manager->loadEntityByUuid('block_content', $uuid);
    if (!empty($block)) {
      $block_content = BlockContent::load($block->id());
      $build = $entity_manager->getViewBuilder('block_content')->view($block, 'full', $lang);

      // Add the title to text so it is searchable.
      $build['search_title'] = [
        '#prefix' => '<h2>',
        '#plain_text' => $block_content->getTranslation($lang)->label(),
        '#suffix' => '</h2>',
        '#weight' => -1000
      ];

      $form['info_block'] = [
        '#type' => 'item',
        '#markup' => \Drupal::getContainer()->get('renderer')->renderPlain($build),
        '#weight' => -100,
        '#prefix' => '<div class="form--content">',
        '#suffix' => '</div>'
      ];
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_d_module_implements_alter(&$implementations, $hook) {
  // Alter page_attachments implementation for alshaya_d to call at last.
  if ($hook == 'page_attachments') {
    unset($implementations['back_to_top']);
  }
}

/**
 * Implements hook_block_access().
 *
 * Can't handle visibility for content type from visibility settings.
 *
 * We have two vertical tabs for content type on block settings page and the
 * one which allows "negate the condition", is not working as expected. so, we
 * had to write this hook to hide page title block from advanced page CT.
 */
function alshaya_d_block_access(Block $block, $operation, AccountInterface $account) {
  // Not allow 'page_title_block' block on advanced page content type.
  if ($operation == 'view' && $block->getPluginId() == 'page_title_block') {
    $route = \Drupal::routeMatch();
    if ($route->getRouteName() == 'entity.node.canonical') {
      /* @var \Drupal\node\Entity\Node $node */
      $node = $route->getParameter('node');
      return AccessResult::forbiddenIf($node->bundle() == 'advanced_page');
    }
  }
}
