<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function alshaya_stores_finder_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'alshaya_stores_finder/store_finder';
}

/**
 * Implements hook_form_alter().
 */
function alshaya_stores_finder_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if ($form['#id'] == 'views-exposed-form-stores-finder-block-3' || $form['#id'] == 'views-exposed-form-stores-finder-block-2') {
      $form['list_view'] = [
        '#title' => t('List view'),
        '#type' => 'link',
        '#url' => Url::fromRoute('alshaya_stores_finder.view_toggle', ['view_type' => 'list_view']),
        '#attributes' => [
          'class' => ['use-ajax'],
        ],
        '#weight' => 100,
      ];
      $form['map_view'] = [
        '#title' => t('Map view'),
        '#type' => 'link',
        '#url' => Url::fromRoute('alshaya_stores_finder.view_toggle', ['view_type' => 'map_view']),
        '#attributes' => [
          'class' => ['use-ajax'],
        ],
        '#weight' => 100,
      ];
    }
  }
}
