<?php

/**
 * @file
 * Alshaya AY Transac module file.
 */

use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_preprocess_html().
 */
function alshaya_ay_transac_preprocess_html(&$variables) {
  $config = \Drupal::config('alshaya_super_category.settings');
  // Check super category feature status.
  if (!$config->get('status')) {
    return;
  }

  // Add class to body tag if super-category feature is enabled.
  $variables['attributes']['class'][] = 'super-category-enabled';

  // Add super category css library to show super catgeory menus.
  $variables['#attached']['library'][] = 'alshaya_white_label/super-category';

  // We need an additional class on body tag for showing search input field
  // expanded when the current page is a super category home page except the
  // site home page.
  /** @var \Drupal\alshaya_acm_product_category\ProductCategoryTree $product_category_tree */
  $super_category_tree = \Drupal::service('alshaya_acm_product_category.product_category_tree');

  // Get the product category term from the URL.
  $term_from_route = $super_category_tree->getCategoryTermFromRoute();

  // Get all root terms or super categories.
  $super_categories = $super_category_tree->getCategoryRootTerms();

  // Check if we have term from route exist in super/root category list and add
  // a helper class for FE to update styles.
  if (!empty($term_from_route) && isset($super_categories[$term_from_route->id()])) {
    $variables['attributes']['class'][] = 'super-category-home';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_ay_transac_library_info_alter(&$libraries, $extension) {
  // Attach mobile_menu library wherever the alshaya_algolia_react
  // library is loaded.
  if ($extension === 'alshaya_algolia_react' && isset($libraries['autocomplete'])) {
    $libraries['autocomplete']['dependencies'][] = 'alshaya_ay_transac/mobile_menu';
  }
}

/**
 * Implements hook_preprocess_block().
 */
function alshaya_ay_transac_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] == 'alshaya_rcs_shop_by_block') {
    $variables['#cache']['contexts'][] = 'super_category';
    // Get current super category term from route.
    $term = \Drupal::service('alshaya_acm_product_category.product_category_tree')->getCategoryTermFromRoute();
    if ($term instanceof TermInterface) {
      /** @var \Drupal\Core\Entity\EntityRepositoryInterface $entity_repository */
      $entity_repository = \Drupal::service('entity.repository');
      $term_en = $entity_repository->getTranslationFromContext($term, 'en');
      // Default block label is Shop By.
      // Only update block label for footer menu block as per
      // current super category if not on `Shop` super category.
      if (strtolower($term_en->label()) !== 'shop') {
        $term = $entity_repository->getTranslationFromContext($term);
        $variables['label'] = $term->label();
      }
    }
  }
}
