<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_alshaya_acm_product_media_items_alter().
 */
function alshaya_cos_images_alshaya_acm_product_media_items_alter(array &$media, SKU $sku) {
  /** @var \Drupal\alshaya_cos_images\SkuAssetManager $assetsManager */
  $assetsManager = \Drupal::service('alshaya_cos_images.skuassetsmanager');
  $assets = $assetsManager->getAssets($sku);

  foreach ($assets ?? [] as $asset) {
    if (!empty($asset['drupal_uri'])) {
      $asset['media_type'] = $assetsManager->getAssetType($asset);;
      $media[] = $asset;
    }
  }
}

/**
 * Implements hook_block_view_alter().
 */
function alshaya_cos_images_block_view_alter(array &$build, BlockPluginInterface $block) {
  if ($build['#configuration']['id'] == 'alshaya_algolia_react_autocomplete') {
    $build['#attached']['library'][] = 'alshaya_cos_images/cos_images';
  }
}

/**
 * Implements hook_alshaya_acm_product_pdp_swath_type_alter();
 */
function alshaya_cos_images_alshaya_acm_product_pdp_swath_type_alter(SKUInterface $sku, array &$color_options_list, SKUInterface $variant_sku) {
  /** @var \Drupal\alshaya_cos_images\SkuAssetManager $sku_asset_manager */
  $sku_asset_manager = \Drupal::service('alshaya_cos_images.skuassetsmanager');
  $swatch = $sku_asset_manager->getSkuSwatch($variant_sku);

  if (!empty($swatch)) {
    $color_options_list[key($color_options_list)]['display_value'] = '<img loading="lazy" src="' . $swatch['url'] . '">';
    $color_options_list[key($color_options_list)]['swatch_type'] = $swatch['type'];
  }
}
