<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_cos_images module.
 */

/**
 * Installs alshaya_pims_assets module.
 */
function alshaya_cos_images_update_9001() {
  \Drupal::service('module_installer')->install(['alshaya_pims_assets']);
}

/**
 * Installs alshaya_pims_assets module.
 */
function alshaya_cos_images_install() {
  \Drupal::service('module_installer')->install(['alshaya_pims_assets']);
}
