<?php

/**
 * @file
 * Module file for alshaya_promo_panel.
 */

use Drupal\Core\Url;

/**
 * Implements hook_preprocess_block().
 */
function alshaya_promo_panel_preprocess_block(&$variables) {
  switch ($variables['base_plugin_id']) {
    case 'block_content':

      $config = \Drupal::config('alshaya_promo_panel.settings');
      $promo_panel_block_content = $config->get('promo_panel_block_content');
      // Get machine of block content from current block.
      $block_content = $variables['content']['#block_content'];
      $machine_name = $block_content->get('machine_name')->value;

      if ($machine_name !== $promo_panel_block_content) {
        return;
      }

      $promo_panel_block = $config->get('promo_panel_block');
      $promo_panel_page = $config->get('promo_panel_page_url');

      // Get current language object.
      $lang = \Drupal::languageManager()->getCurrentLanguage();
      // Get the language code.
      $lang_code = $lang->getId();
      // @todo: Make this config configurable based on super category feature.
      $variables['#cache']['contexts'][] = 'url.path';

      if ($variables['content']) {
        // If the block is placed in "Block Layout".
        if (isset($variables['elements']['#id']) && $variables['elements']['#id'] == $promo_panel_block) {
          // Make label a link to redirect to Promo panel page on mobile.
          $label = $variables['label'];
          $element['label'] = [
            '#type' => 'link',
            '#title' => $label,
            '#url' => Url::fromUri('internal:' . $promo_panel_page, ['language' => $lang]),
            '#options' => [
              'attributes' => [
                'class' => ['mobile-link'],
              ],
            ],
          ];

          // Change default label with link.
          $variables['label'] = [
            '#markup' => \Drupal::service('renderer')->render($element),
          ];


          $variables['attributes']['class'][] = 'block-promo-panel-wrapper';
          $variables['title_attributes']['class'][] = 'promo-panel-label';
          $variables['content']['#attached']['library'][] = 'alshaya_promo_panel/promo-panel';
        }
        // If the block is added to "block reference" paragraph type.
        else {
          // Get the referer path.
          $referrer_path = parse_url(\Drupal::request()->headers->get('referer'))['path'];
          $referrer_path = preg_replace('/^(\/' . $lang_code . ')(.*)/g', '', $referrer_path);
          $empty = !empty($referrer_path) ? $referrer_path : 'home';

          // Create the back link.
          $element['back'] = [
            '#type' => 'link',
            '#title' => t('Back'),
            '#url' => Url::fromUri('internal:/' . $empty, ['language' => $lang]),
            '#options' => [
              'attributes' => [
                'class' => ['mobile-back-link'],
              ],
            ],
          ];
        }
      }
      break;
  }
}
