<?php

/**
 * @file
 * Contains wishlist related translations.
 */

/**
 * Wishlist feature translation.
 */
function _alshaya_wishlist_translations() {
  return [
    'Items are saved for this visit only. To save them for later, sign in to your account or register a new one.' => [
      'ar' => 'يتم حفظ العناصر لهذه الزيارة فقط. لحفظها في وقت لاحق ، قم بتسجيل الدخول إلى حسابك أو تسجيل حساب جديد.',
      'context' => 'wishlist',
    ],
    'Add to wishlist' => [
      'ar' => 'أضف إلى قائمة الامنيات',
      'context' => 'wishlist',
    ],
    'my @wishlist_label' => [
      'ar' => 'لي @wishlist_label',
      'context' => 'wishlist',
    ],
    '@productName saved to your @wishlist_label on this visit' => [
      'ar' => 'تم حفظ @productName في @wishlist_label في هذه الزيارة',
      'context' => 'wishlist',
    ],
    'Keep it for next time?' => [
      'ar' => 'احتفظ بها في المرة القادمة؟',
      'context' => 'wishlist',
    ],
    'Sign in to your account or register a new one.' => [
      'ar' => 'تسجيل الدخول إلى حسابك أو تسجيل حساب جديد.',
      'context' => 'wishlist',
    ],
    'Sign in' => [
      'ar' => 'تسجيل الدخول',
      'context' => 'wishlist',
    ],
    'Register' => [
      'ar' => 'سجل الآن',
      'context' => 'wishlist',
    ],
    'Do you want to move the product to @wishlist_label?' => [
      'ar' => 'هل تريد نقل المنتج إلىwishlist_label؟',
      'context' => 'wishlist',
    ],
    'Move to basket' => [
      'ar' => 'انتقل إلى السلة',
      'context' => 'wishlist',
    ],
  ];
}
