<?php

/**
 * @file
 * Contains alshaya_wishlist.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function alshaya_wishlist_theme($existing, $type, $theme, $path) {
  return [
    'my_wishlist' => [
      'variables' => [
        'strings' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_wishlist_node_view(array &$build, Node $entity, EntityViewDisplay $display, $view_mode) {
  // Add cache tag.
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], ['config:alshaya_wishlist.settings']);

  // Return if the feature is not enabled and applicable to display mode.
  if (!in_array($view_mode, ['modal', 'full']) || !\Drupal::service('alshaya_wishlist.helper')->isWishListEnabled()) {
    return;
  }

  // Attach wishlist libraries and add a wishlist markup for FE icon rendering.
  // @todo we need this library only for PDP and basket page.
  $build['#attached']['library'][] = 'alshaya_wishlist/wishlist';
  $build['wishlist_enabled'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => [
      'class' => [
        'wishlist-pdp-'.$view_mode,
      ]
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_wishlist_page_attachments_alter(array &$page) {
  $wishlist_helper = \Drupal::service('alshaya_wishlist.helper');
  $settings['enabled'] = $wishlist_helper->isWishListEnabled();

  // Pass the feature status in drupal settings.
  $page['#attached']['drupalSettings']['wishlist'] = $settings;
  $wishlist_settings = \Drupal::config('alshaya_wishlist.settings');
  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'], $wishlist_settings->getCacheTags());

  // Do not proceed if wishlist is not enabled.
  if ($settings['enabled'] !== TRUE) {
    return;
  }

  // Get additional config if feature is enabled.
  $settings['config'] = $wishlist_helper->getWishListConfig();
  $settings['userDetails'] = $wishlist_helper->getWishListUserDetails();
  $page['#attached']['drupalSettings']['wishlist'] = $settings;
}

/**
 * Implements hook_preprocess_page().
 */
function alshaya_wishlist_preprocess_page(array &$variables) {
  $wishlist_helper = \Drupal::service('alshaya_wishlist.helper');
  // Return if wishlist feature is not enabled or current path
  // doesn't matche with the wishlist product listing page.
  if (!$wishlist_helper->isWishListEnabled() || !$wishlist_helper->isWishListPage()) {
    return;
  }

  // Add classes similar to PLP without left sidebar.
  $variables['attributes']['class'][] = 'c-plp c-plp-only l-one--w lhn-without-sidebar';
}
