<?php

/**
 * @file
 * Contains alshaya_wishlist.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\node\Entity\Node;
use Drupal\acq_commerce\SKUInterface;

/**
 * Implements hook_theme().
 */
function alshaya_wishlist_theme($existing, $type, $theme, $path) {
  return [
    'my_wishlist' => [
      'variables' => [
        'strings' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_alshaya_acm_product_build_alter().
 */
function alshaya_wishlist_alshaya_acm_product_build_alter(&$build, SKUInterface $sku, $context = 'pdp') {
  // Add cache tag.
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], ['config:alshaya_wishlist.settings']);

  // Return if the feature is not enabled and applicable to display mode.
  if (!in_array($context, ['matchback', 'pdp', 'modal']) || !\Drupal::service('alshaya_wishlist.helper')->isWishListEnabled()) {
    return;
  }

  /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
  $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
  $productNode = $skuManager->getDisplayNode($sku->getSku());

  // Get the current pdp layout.
  $acm_product_config = \Drupal::config('alshaya_acm_product.settings');
  $product_pdp_layout = $acm_product_config->get('pdp_layout');

  if (!empty($productNode->get('field_select_pdp_layout')->getValue()[0]['value'])) {
    $product_pdp_layout = $productNode->get('field_select_pdp_layout')->getValue()[0]['value'];
  }
  // Attach wishlist libraries and add a wishlist markup for FE icon rendering.
  // @todo we need this library for PDP and basket page.
  if ($product_pdp_layout !== 'magazine_v2') {
    $build['wishlist_enabled']['#markup'] = '<div id="wishlist-pdp-full"></div>';
    $build['#attached']['library'][] = 'alshaya_wishlist/wishlist';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_wishlist_page_attachments_alter(array &$page) {
  $wishlist_helper = \Drupal::service('alshaya_wishlist.helper');
  $settings['enabled'] = $wishlist_helper->isWishListEnabled();

  // Pass the feature status in drupal settings.
  $page['#attached']['drupalSettings']['wishlist'] = $settings;
  $wishlist_settings = \Drupal::config('alshaya_wishlist.settings');
  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'], $wishlist_settings->getCacheTags());

  // Do not proceed if wishlist is not enabled.
  if ($settings['enabled'] !== TRUE) {
    return;
  }

  // Get additional config if feature is enabled.
  $settings['config'] = $wishlist_helper->getWishListConfig();
  $settings['userDetails'] = $wishlist_helper->getWishListUserDetails();
  $page['#attached']['drupalSettings']['wishlist'] = $settings;
}
