<?php

/**
 * @file
 * Contains wishlist related translations.
 */

/**
 * Wishlist feature translation.
 */
function _alshaya_wishlist_translations() {
  return [
    'Items are saved for this visit only. To save them for later, sign in to your account or register a new one.' => [
      'ar' => 'يتم حفظ العناصر لهذه الزيارة فقط. لحفظها في وقت لاحق ، قم بتسجيل الدخول إلى حسابك أو تسجيل حساب جديد.',
    ],
    'Add to wishlist' => [
      'ar' => 'أضف إلى قائمة الامنيات',
    ],
    'my %wishlist_label' => [
      'ar' => 'لي %wishlist_label',
    ],
    '%productName saved to your %wishlist_label on this visit' => [
      'ar' => 'تم حفظ %productName في %wishlist_label في هذه الزيارة',
    ],
    'Keep it for next time?' => [
      'ar' => 'احتفظ بها في المرة القادمة؟',
    ],
    'Sign in to your account or register a new one.' => [
      'ar' => 'تسجيل الدخول إلى حسابك أو تسجيل حساب جديد.',
    ],
  ];
}
