<?php

/**
 * @file
 * Contains wishlist related static strings and translations.
 */

/**
 * Wishlist strings.
 */
function _alshaya_wishlist_strings() {
  return [
    [
      'key' => 'add_to_wishlist',
      'value' => t('Add to @wishlist_label', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'added_to_wishlist',
      'value' => t('Added to @wishlist_label', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'move_to_wishlist',
      'value' => t('Move to @wishlist_label', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'remove_from_wishlist',
      'value' => t('Remove', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'empty_wishlist',
      'value' => t('Your @wishlist_label is empty.', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'share_your_list',
      'value' => t('Share Your List', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'share_your_list_text',
      'value' => t('Share all your @wishlist_label with friends and family.', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'wishlist_email_button',
      'value' => t('Email', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'wishlist_link_copied',
      'value' => t('Link Copied', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'wishlist_link_copy',
      'value' => t('Copy Link', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'wishlist_share_all',
      'value' => t('Share All', [], ['context' => 'wishlist']),
    ],
    [
      'key' => 'wishlist_go_shipping',
      'value' => t('go shopping', [], ['context' => 'wishlist']),
    ],
  ];
}
