#!/usr/bin/env bash

for file in $(find /home/travis/.drush/cache/default -name "*.cache")
do
  cache_file=${file##*/}
  grep -v '"created":' $cache_file > /home/travis/.drush/cache/default/tmp
  mv /home/travis/.drush/cache/default/tmp /home/travis/.drush/cache/default/$cache_file
done