#!/usr/bin/env bash

set -ev

#  The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to test the site.
yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'

if ([ $TRAVIS_PULL_REQUEST == "false" ])
then
  echo "No need to run validations."
else
  blt validate:all
  blt setup --define drush.alias='${drush.aliases.ci}' --define environment=ci --no-interaction --yes -v
  # Disabling Behat tests on CI.
  #blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --define environment=ci --yes -v
fi

set +v
