#!/usr/bin/env bash

set -e

if ([ $TRAVIS_PULL_REQUEST == "false" ])
then
  echo "No need to run validations."
else
  #  The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to test the site.
  yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'
  yaml-cli update:value blt/project.yml project.profile.name ${PROFILE}

  echo -en "travis_fold:start:Validate\r"
  blt validate:all
  echo -en "travis_fold:end:Validate\r"

  echo -en "travis_fold:start:Setup\r"
  blt setup --define drush.alias='${drush.aliases.ci}' --define environment=ci --no-interaction --yes -v
  drush @self status

  echo -en "travis_fold:end:Setup\r"
  # Disabling Behat tests on CI.
  #blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --define environment=ci --yes -v
fi
