<?php

/**
 * @file
 * Install, uninstall and update for alshaya_tbs_transac_rcs.
 */

/**
 * Implements hook_install().
 */
function alshaya_tbs_transac_rcs_install() {
  \Drupal::service('module_installer')->install(['alshaya_rcs']);
}

/**
 * Implements hook_uninstall().
 */
function alshaya_tbs_transac_rcs_uninstall() {
  \Drupal::service('module_installer')->uninstall(['rcs_placeholders']);
}
