<?php

/**
 * @file
 * Module file for acq_checkoutcom.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function acq_checkoutcom_theme() {
  return [
    'payment_card_info' => [
      'variables' => [
        'card_info' => NULL,
        'user' => NULL,
      ],
    ],
    'payment_card_teaser' => [
      'variables' => [
        'card_info' => NULL,
      ],
    ],
  ];
}

/**
 * Preprocess payment_card_info theme.
 *
 * @param array $variables
 *   The array of variables.
 */
function template_preprocess_payment_card_info(array &$variables) {
  $variables['delete_operation'] = [
    'title' => t('Delete'),
    'url' => Url::fromRoute(
      'acq_checkoutcom.payment_card.remove_card',
      [
        'user' => $variables['user']->id(),
        'card_id' => $variables['card_info']['id'],
      ],
      [
        'attributes' => [
          'class' => ['use-ajax'],
          'data-dialog-type' => "modal",
          'data-dialog-options' => '{"width":"auto"}',
        ],
      ]
    ),
  ];
}
