<?php

/**
 * @file
 * Constains hooks and alters for Alshaya Rcs Main Menu.
 */

use Drupal\node\Entity\Node;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;

/**
 * Check for given path, department page exists.
 *
 * Check for given path, department page exists. If department page exists
 * then return that department page node id or return false.
 *
 * @param string $path
 *   The current route path.
 *
 * @return int|bool
 *   Department page node id or false.
 */
function alshaya_rcs_main_menu_is_department_page(string $path) {
  $data = [];
  // Check for cache first.
  $cache = \Drupal::cache('data')->get('alshaya_rcs_main_menu:slug:nodes');
  if ($cache) {
    $data = $cache->data;
    // If cache hit.
    if (!empty($data[$path])) {
      return $data[$path];
    }
  }

  // Get all department pages.
  $department_pages = alshaya_rcs_main_menu_get_department_pages();
  // If there is department page available for given term.
  if (isset($department_pages[$path])) {
    $nid = $department_pages[$path];
    /** @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
    if (is_object($node)) {
      if ($node->isPublished()) {
        $data[$path] = $nid;
        \Drupal::cache('data')->set('alshaya_rcs_main_menu:slug:nodes', $data, Cache::PERMANENT, $node->getCacheTags());
        return $nid;
      }
    }
  }

  return FALSE;
}

/**
 * Helper function to fetch list of department pages.
 *
 * @return array
 *   Nids of department pages keyed by slug.
 */
function alshaya_rcs_main_menu_get_department_pages() {
  static $department_pages = [];

  // We cache the nid-tid relationship for a single page request.
  if (empty($department_pages)) {
    $query = \Drupal::database()->select('node__field_category_slug', 'nfcs');
    $query->addField('nfcs', 'field_category_slug_value', 'tid');
    $query->addField('nfcs', 'entity_id', 'nid');
    $department_pages = $query->execute()->fetchAllKeyed();
  }

  return $department_pages;
}

/**
 * Implements hook_form_alter().
 */
function alshaya_rcs_main_menu_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_advanced_page_form' || $form_id == 'node_advanced_page_edit_form') {
    $form['field_category_slug']['#states'] = [
      'visible' => [
        ':input[name="field_use_as_department_page[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_category_slug']['widget'][0]['value']['#states'] = [
      'required' => [
        ':input[name="field_use_as_department_page[value]"]' => ['checked' => TRUE],
      ],
    ];
    // Remove the validate function for product category and also make this
    // field non required.
    $form['field_product_category']['#access'] = FALSE;
    unset($form['field_product_category']['widget']['#states']['required']);
    $form['#validate'] = array_diff($form['#validate'], ['alshaya_advanced_page_node_form_validate']);
  }
}
