<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_sprinklr_page_attachments_alter(array &$page) {
  $sprinklr_settings = \Drupal::config('alshaya_sprinklr.settings');
  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'] ?? [], $sprinklr_settings->getCacheTags());

  $sprinklr_helper = \Drupal::service('alshaya_sprinklr.helper');
  // Skip the processing of sprinklr chatbot if sprinklr feature is disabled.
  if (!$sprinklr_helper->isSprinklrFeatureEnabled()) {
    return;
  }

  $app_id = $sprinklr_settings->get('app_id');
  // Skip the processing of sprinklr chatbot if app id is not provided.
  if (empty($app_id)) {
    return;
  }

  // Return if sprinklr is not enabled on current path.
  if (!$sprinklr_helper->isEnabledOnCurrentPath()) {
    return;
  }

  // Attach alshaya_sprinklr library to the allowed urls only if
  // sprinklr app id is provided.
  $page['#attached']['drupalSettings']['alshaya_sprinklr']['appId'] = $app_id;
  // Attach custom library for sprinklr chatbot feature.
  $page['#attached']['library'][] = 'alshaya_sprinklr/alshaya_sprinklr';
  // Attach sprinklr chatbot js script.
  $page['#attached']['library'][] = 'alshaya_sprinklr/sprinklr_chatbot';
}
