<?php

/**
 * @file
 * Contains install/update/uninstall hooks for alshaya_paragraphs_transac.
 */

/**
 * Implements hook_update_N().
 *
 * Make fields inside paragraph translatable.
 */
function alshaya_paragraphs_transac_update_8001() {
  $configs = [
    'field.field.paragraph.product_carousel_category.field_category_carousel_title',
  ];

  alshaya_config_install_configs($configs, 'alshaya_paragraphs_transac', 'optional');
}
