<?php

/**
 * @file
 * Contains update hook for alshaya_shoeai module.
 */

/**
 * Implements hook_update_N().
 *
 * Add the new landing page setting to alshaya_shoeai.settings config.
 */
function alshaya_shoeai_update_9001() {
  /** @var \Drupal\alshaya_config\AlshayaConfigManager $manager */
  $manager = \Drupal::service('alshaya_config.manager');
  $manager->updateConfigs([
    'alshaya_shoeai.settings',
  ],
    'alshaya_shoeai',
  );
}
