<?php

/**
 * @file
 * File for shoe AI Implementation.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_view().
 */
function alshaya_shoeai_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product' && $view_mode == 'full') {
    $shoeAi = \Drupal::service('alshaya_shoeai.helper');
    if ($shoeAi->isShoeAiFeatureEnabled()) {
      $alshaya_shoeai_settings = \Drupal::config('alshaya_shoeai.settings');
      $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], $alshaya_shoeai_settings->getCacheTags());
      $build['#attached']['library'][] = 'alshaya_shoeai/shoeai_js';
      $build['#attached']['drupalSettings']['shoeai']['status'] = TRUE;
      $build['#attached']['drupalSettings']['shoeai']['shopId'] = $shoeAi->getShoeAiShopId();
      $build['#attached']['drupalSettings']['shoeai']['scale'] = $shoeAi->getShoeAiScale();
      $build['#attached']['drupalSettings']['shoeai']['zeroHash'] = $shoeAi->getShoeAiZeroHash();
    }
  }
}

/**
 * Implements hook_taxonomy_term_view().
 */
function alshaya_shoeai_taxonomy_term_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product_category' && $view_mode == 'full') {
    $shoeAi = \Drupal::service('alshaya_shoeai.helper');
    if ($shoeAi->isShoeAiFeatureEnabled()) {
      $alshaya_shoeai_settings = \Drupal::config('alshaya_shoeai.settings');
      $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], $alshaya_shoeai_settings->getCacheTags());
      $build['#attached']['library'][] = 'alshaya_shoeai/shoeai_js';
      $build['#attached']['drupalSettings']['shoeai']['status'] = TRUE;
      $build['#attached']['drupalSettings']['shoeai']['shopId'] = $shoeAi->getShoeAiShopId();
      $build['#attached']['drupalSettings']['shoeai']['scale'] = $shoeAi->getShoeAiScale();
      $build['#attached']['drupalSettings']['shoeai']['zeroHash'] = $shoeAi->getShoeAiZeroHash();
    }
  }
}
