<?php

/**
 * @file
 * Contains Style Finder related translations.
 */

/**
 * DY translation.
 */
function _alshaya_stylefinder_translations() {
  return [
    'Suggestions for you' => [
      'ar' => 'مقترحاتنا لكِ:',
    ],
    'You’re so close!' => [
      'ar' => 'لقد شارفتِ على الانتهاء!',
    ],
    'Complete the steps above to find your perfect bra.' => [
      'ar' => 'أكملي الخطوات أعلاه لتحصلي على حمالة الصدر المثالية لكِ.',
    ],
    'No recommendations found.' => [
      'ar' => 'لا يوجد اقتراحات.',
    ],
    'Here are the personalized bra styles we think you’ll love!' => [
      'ar' => 'إليكِ حمالات الصدر الأنيقة والمخصصة لكِ بالكامل!',
    ],
    'See More Styles' => [
      'ar' => 'تعرفي على مزيد من التصاميم',
    ],
  ];
}
