<?php

/**
 * @file
 * Bazaarvoice.module for hook implementations.
 */
use Drupal\Core\Site\Settings;

/**
 * Implements hook_page_attachments().
 */
function bazaar_voice_page_attachments(array &$page) {
  /** @var \Drupal\bazaar_voice\BazaarVoiceApiHelper $bazaar_voice */
  $bazaar_voice = \Drupal::service('bazaar_voice.api_helper');

  // Check if BV script to be loaded as per current route.
  if ($bazaar_voice->isCurrentRouteInBvList()) {
	  // Add BV pixel script to header.
	  $page['#attached']['html_head'][] = [
			[
				'#type' => 'html_tag',
				'#tag' => 'script',
				'#attributes' => [
					'async' => TRUE,
					'src' => $bazaar_voice->getBvDynamicScriptCode(),
				],
			],
			'bvpath',
		];
  }
}
