<?php

/**
 * @file
 * Bazaarvoice.module for hook implementations.
 */

/**
 * Implements hook_module_implements_alter().
 */
function bazaar_voice_module_implements_alter(&$implementations, $hook) {
  // To call the page_attachments of bazaar_voice fist.
  // We want to load bv javascript first for analytics js to work.
  if ($hook == 'page_attachments' && isset($implementations['bazaar_voice'])) {
    $group = $implementations['bazaar_voice'];
    unset($implementations['bazaar_voice']);
    $implementations = ['bazaar_voice' => $group] + $implementations;
  }
}

/**
 * Implements hook_page_attachments().
 */
function bazaar_voice_page_attachments(array &$page) {
  /** @var \Drupal\bazaar_voice\BazaarVoiceApiHelper $bazaar_voice */
  $bazaar_voice = \Drupal::service('bazaar_voice.api_helper');

  // Check if BV script to be loaded as per current route.
  if ($bazaar_voice->isCurrentRouteInBvList()) {
    // Add BV pixel script to header.
    $page['#attached']['library'][] = 'bazaar_voice/bazaar_voice';
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function bazaar_voice_local_tasks_alter(&$local_tasks) {
  // Change config translation local task hierarchy.
  if (isset($local_tasks['config_translation.local_tasks:config_translation.item.overview.bazaar_voice.review_settings_form'])) {
    $local_tasks['config_translation.local_tasks:config_translation.item.overview.bazaar_voice.review_settings_form']['parent_id'] = 'bazaar_voice.review_settings_form';
    $local_tasks['config_translation.local_tasks:config_translation.item.overview.bazaar_voice.review_filter_settings_form']['parent_id'] = 'bazaar_voice.review_filter_settings_form';
    $local_tasks['config_translation.local_tasks:config_translation.item.overview.bazaar_voice.error_messages_settings_form']['parent_id'] = 'bazaar_voice.error_messages_settings_form';
  }
}

/**
 * Implements hook_library_info_build().
 */
function bazaar_voice_library_info_build() {
  /** @var \Drupal\bazaar_voice\BazaarVoiceApiHelper $bazaar_voice */
  $bazaar_voice = \Drupal::service('bazaar_voice.api_helper');
  $bazaar_voice_url = $bazaar_voice->getBvDynamicScriptCode();
  $libraries = [];

  if (!empty($bazaar_voice_url)) {
    $libraries['bazaar_voice'] = [
      'js' => [
        $bazaar_voice_url => [
          'type' => 'external',
          'attributes' => [
            'defer' => TRUE,
          ],
        ],
      ],
    ];
  }
  return $libraries;
}
