<?php

/**
 * @file
 * Contains eGift related translations.
 */

/**
 * eGift translation.
 */
function _alshaya_egift_card_translations() {
  $strings = [
    'v1' => [
      'Check Balance & Validity' => [
        'ar' => 'Check Balance & Validity',
        'context' => 'egift',
      ],
      'Enter gift card details to check balance & validity.' => [
        'ar' => 'Enter gift card details to check balance & validity.',
        'context' => 'egift',
      ],
      'eGift Card Number' => [
        'ar' => 'eGift Card Number',
        'context' => 'egift',
      ],
      'Terms & Conditions' => [
        'ar' => 'Terms & Conditions',
        'context' => 'egift',
      ],
      'Please enter your email address.' => [
        'ar' => 'Please enter your email address.',
        'context' => 'egift',
      ],
      'CHECK BALANCE' => [
        'ar' => 'CHECK BALANCE',
        'context' => 'egift',
      ],
      'Here is your current balance' => [
        'ar' => 'Here is your current balance',
        'context' => 'egift',
      ],
      'for eGift card ending in ..' => [
        'ar' => 'for eGift card ending in ..',
        'context' => 'egift',
      ],
      'Card Valid Up To ' => [
        'ar' => 'Card Valid Up To ',
        'context' => 'egift',
      ],
      'TOP UP CARD' => [
        'ar' => 'TOP UP CARD',
        'context' => 'egift',
      ],
      'CHECK ANOTHER CARD' => [
        'ar' => 'CHECK ANOTHER CARD',
        'context' => 'egift',
      ],
      'Style:' => [
        'ar' => 'Style:',
        'context' => 'egift',
      ],
      'Send to:' => [
        'ar' => 'Send to:',
        'context' => 'egift',
      ],
      'Message:' => [
        'ar' => 'Message:',
        'context' => 'egift',
      ],
      'Alshaya eGift card' => [
        'ar' => 'Alshaya eGift card',
        'context' => 'egift',
      ],
      'eGift Card Top-up' => [
        'ar' => 'eGift Card Top-up',
        'context' => 'egift',
      ],
      'Please enter the amount.' => [
        'ar' => 'Please enter the amount.',
        'context' => 'egift',
      ],
      'Insufficient balance, Please topup the card or lower the redeem amount.' => [
        'ar' => 'Insufficient balance, Please topup the card or lower the redeem amount.',
        'context' => 'egift',
      ],
      'Verify eGift Card to redeem from card balance' => [
        'ar' => 'Verify eGift Card to redeem from card balance',
        'context' => 'egift',
      ],
      'We’ll send a verification code to your email to verify eGift card' => [
        'ar' => 'We’ll send a verification code to your email to verify eGift card',
        'context' => 'egift',
      ],
      'Edit amount to use' => [
        'ar' => 'Edit amount to use',
        'context' => 'egift',
      ],
      'Applied card amount - ' => [
        'ar' => 'Applied card amount - ',
        'context' => 'egift',
      ],
      'Remaining Balance - @currencyCode @remainingAmount' => [
        'ar' => 'Remaining Balance - @currencyCode @remainingAmount',
        'context' => 'egift',
      ],
      'Link this card for faster payment next time' => [
        'ar' => 'Link this card for faster payment next time',
        'context' => 'egift',
      ],
      'Verification code is send to email address registered with the card number.' => [
        'ar' => 'Verification code is send to email address registered with the card number.',
        'context' => 'egift',
      ],
      'Resend Code' => [
        'ar' => 'Resend Code',
        'context' => 'egift',
      ],
      'Change Card?' => [
        'ar' => 'Change Card?',
        'context' => 'egift',
      ],
      'add to bag' => [
        'ar' => 'add to bag',
        'context' => 'egift',
      ],
      'checkout' => [
        'ar' => 'checkout',
        'context' => 'egift',
      ],
      'No eGift cards found.' => [
        'ar' => 'No eGift cards found.',
        'context' => 'egift',
      ],
      '1. Select your style and card amount' => [
        'ar' => '1. Select your style and card amount',
        'context' => 'egift',
      ],
      '2. Enter Gift card details' => [
        'ar' => '2. Enter Gift card details',
        'context' => 'egift',
      ],
      'Buying this gift for' => [
        'ar' => 'Buying this gift for',
        'context' => 'egift',
      ],
      'Friends and family' => [
        'ar' => 'Friends and family',
        'context' => 'egift',
      ],
      'Myself' => [
        'ar' => 'Myself',
        'context' => 'egift',
      ],
      'Recipient Details' => [
        'ar' => 'Recipient Details',
        'context' => 'egift',
      ],
      'My Details' => [
        'ar' => 'My Details',
        'context' => 'egift',
      ],
      'Name*' => [
        'ar' => 'Name*',
        'context' => 'egift',
      ],
      'Email*' => [
        'ar' => 'Email*',
        'context' => 'egift',
      ],
      'Write a message' => [
        'ar' => 'Write a message',
        'context' => 'egift',
      ],
      'Message' => [
        'ar' => 'Message',
        'context' => 'egift',
      ],
      'Please enter amount or select from above.' => [
        'ar' => 'Please enter amount or select from above.',
        'context' => 'egift',
      ],
      'Please enter amount in the range of @amountFrom to @amountTo' => [
        'ar' => 'Please enter amount in the range of @amountFrom to @amountTo',
        'context' => 'egift',
      ],
      'Amount @currencyCode' => [
        'ar' => 'Amount @currencyCode',
        'context' => 'egift',
      ],
      'Please add a email id in your account to perform this operation.' => [
        'ar' => 'Please add a email id in your account to perform this operation.',
        'context' => 'egift',
      ],
      'Please enter a valid amount' => [
        'ar' => 'Please enter a valid amount',
        'context' => 'egift',
      ],
      'Verification code sent successfully.' => [
        'ar' => 'Verification code sent successfully.',
        'context' => 'egift',
      ],
      'Redeem amount should be less than or equal to the cart value.' => [
        'ar' => 'Redeem amount should be less than or equal to the cart value.',
        'context' => 'egift',
      ],
      'Pay using egift card ' => [
        'ar' => 'Pay using egift card ',
        'context' => 'egift',
      ],
      'Available Balance: ' => [
        'ar' => 'Available Balance: ',
        'context' => 'egift',
      ],
      'Paid With eGfit card' => [
        'ar' => 'Paid With eGfit card',
        'context' => 'egift',
      ],
      'Balance Payable' => [
        'ar' => 'Balance Payable',
        'context' => 'egift',
      ],
      'Pay using egift card (Remaining Balance: @currencyCode @amount)' => [
        'ar' => 'Pay using egift card (Remaining Balance: @currencyCode @amount)',
        'context' => 'egift',
      ],
      'Pay using egift card (Card is expired)' => [
        'ar' => 'Pay using egift card (Card is expired)',
        'context' => 'egift',
      ],
      'Pay ' => [
        'ar' => 'Pay ',
        'context' => 'egift',
      ],
      ' using another payment method to complete purchase' => [
        'ar' => ' using another payment method to complete purchase',
        'context' => 'egift',
      ],
      'Top-up' => [
        'ar' => 'Top-up',
        'context' => 'egift',
      ],
      'Top-up for' => [
        'ar' => 'Top-up for',
        'context' => 'egift',
      ],
      'My Card' => [
        'ar' => 'My Card',
        'context' => 'egift',
      ],
      'Other\'s Card' => [
        'ar' => 'Other\'s Card',
        'context' => 'egift',
      ],
      'Card Balance:' => [
        'ar' => 'Card Balance:',
        'context' => 'egift',
      ],
      'Card No:' => [
        'ar' => 'Card No:',
        'context' => 'egift',
      ],
      'eGift Card Number*' => [
        'ar' => 'eGift Card Number*',
        'context' => 'egift',
      ],
      'Card Details' => [
        'ar' => 'Card Details',
        'context' => 'egift',
      ],
      'My eGift Card' => [
        'ar' => 'My eGift Card',
      ],
      'Balanace:' => [
        'ar' => 'Balanace:',
        'context' => 'egift',
      ],
      'Expires on' => [
        'ar' => 'Expires on',
        'context' => 'egift',
      ],
      'This card has expired.' => [
        'ar' => 'This card has expired.',
        'context' => 'egift',
      ],
      'Card Type' => [
        'ar' => 'Card Type',
        'context' => 'egift',
      ],
      'Top up' => [
        'ar' => 'Top up',
        'context' => 'egift',
      ],
      'Link my egift card' => [
        'ar' => 'Link my egift card',
        'context' => 'egift',
      ],
      'eGift Card' => [
        'ar' => 'eGift Card',
        'context' => 'egift',
      ],
      'You dont have any eGift card linked to your account, link card to use it for your purchases' => [
        'ar' => 'You dont have any eGift card linked to your account, link card to use it for your purchases',
        'context' => 'egift',
      ],
      'We\'ll send a verification code to your email to verify and link eGift card' => [
        'ar' => 'We\'ll send a verification code to your email to verify and link eGift card',
        'context' => 'egift',
      ],
      'Get Code' => [
        'ar' => 'Get Code',
        'context' => 'egift',
      ],
      'Enter verification code' => [
        'ar' => 'Enter verification code',
        'context' => 'egift',
      ],
      'Didn\'t receive?' => [
        'ar' => 'Didn\'t receive?',
        'context' => 'egift',
      ],
      'Verify' => [
        'ar' => 'Verify',
        'context' => 'egift',
      ],
      'Please enter an eGift card number.' => [
        'ar' => 'Please enter an eGift card number.',
        'context' => 'egift',
      ],
      'Please enter a valid eGift card number.' => [
        'ar' => 'Please enter a valid eGift card number.',
        'context' => 'egift',
      ],
      'Please enter verification code.' => [
        'ar' => 'Please enter verification code.',
        'context' => 'egift',
      ],
      'Please enter a valid verification code.' => [
        'ar' => 'Please enter a valid verification code.',
        'context' => 'egift',
      ],
      'You cannot redeem the same card which you\'re trying to topup.' => [
        'ar' => 'You cannot redeem the same card which you\'re trying to topup.',
        'context' => 'egift',
      ],
      'Buy Alshaya eGift Card' => [
        'ar' => 'Buy Alshaya eGift Card',
      ],
      'Top-up eGift card' => [
        'ar' => 'Top-up eGift card',
      ],
      'eGift card to:' => [
        'ar' => 'eGift card to:',
      ],
      'eGift card will be sent immediately' => [
        'ar' => 'eGift card will be sent immediately',
      ],
      'Top-up to:' => [
        'ar' => 'Top-up to:',
      ],
      'Top-up amount will reflect immediately in card' => [
        'ar' => 'Top-up amount will reflect immediately in card',
      ],
    ],
  ];

  return $strings;
}

/**
 * Get translations for given version.
 *
 * @param string $version
 *   Version number like 'v1' etc.
 *
 * @return array
 *   Translations.
 */
function _alshaya_egift_card_get_translations(string $version = '') {
  $translations = _alshaya_egift_card_translations();
  // If no version mentioned, return all version strings.
  if (empty($version)) {
    $trans_data = [];
    foreach ($translations as $trans) {
      $trans_data = array_merge($trans_data, $trans);
    }

    return $trans_data;
  }

  return $translations[$version] ?? [];
}
