<?php

/**
 * @file
 * Contains eGift related translations.
 */

/**
 * eGift translation.
 */
function _alshaya_egift_card_translations() {
  $strings = [
    'v1' => [
      'Check Balance & Validity' => [
        'ar' => 'تحقق من الرصيد والصلاحية',
        'context' => 'egift',
      ],
      'Enter gift card details to check balance & validity.' => [
        'ar' => 'أدخل تفاصيل بطاقة الهدايا للتحقق من الرصيد والصلاحية.',
        'context' => 'egift',
      ],
      'eGift Card Number' => [
        'ar' => ' رقم بطاقة الهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'Terms & Conditions' => [
        'ar' => 'الشروط والأحكام',
        'context' => 'egift',
      ],
      'Please enter your email address.' => [
        'ar' => 'أدخل عنوان البريد الإلكتروني الخاص بك.',
        'context' => 'egift',
      ],
      'CHECK BALANCE' => [
        'ar' => 'تحقق من الرصيد',
        'context' => 'egift',
      ],
      'Here is your current balance' => [
        'ar' => 'رصيدك الحالي هو',
        'context' => 'egift',
      ],
      'for eGift card ending in ..' => [
        'ar' => 'تنتهي بطاقة الهدايا الإلكترونية في',
        'context' => 'egift',
      ],
      'Card valid up to ' => [
        'ar' => 'البطاقة صالحة حتى ',
        'context' => 'egift',
      ],
      'TOP UP CARD' => [
        'ar' => 'بطاقة شحن الرصيد',
        'context' => 'egift',
      ],
      'CHECK ANOTHER CARD' => [
        'ar' => ' تحقق من بطاقة أخرى',
        'context' => 'egift',
      ],
      'Style:' => [
        'ar' => 'التصميم:',
        'context' => 'egift',
      ],
      'Send to:' => [
        'ar' => 'مرسلة إلى:',
        'context' => 'egift',
      ],
      'Message:' => [
        'ar' => 'الرسالة:',
        'context' => 'egift',
      ],
      'Alshaya eGift card' => [
        'ar' => 'بطاقة الشايع للهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'eGift Card Top up' => [
        'ar' => 'تعبئة بطاقة الهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'Please enter the amount.' => [
        'ar' => 'يرجى إدخال المبلغ.',
        'context' => 'egift',
      ],
      'Insufficient balance, Please topup the card or lower the redeem amount.' => [
        'ar' => 'الرصيد غير كافٍ، يرجى تعبئة البطاقة أو تقليل مبلغ الاسترداد.',
        'context' => 'egift',
      ],
      'Verify eGift Card to redeem from card balance' => [
        'ar' => 'قم بتفعيل بطاقة الهدايا الإلكترونية للاستفادة من رصيد البطاقة',
        'context' => 'egift',
      ],
      'We’ll send a verification code to your email to verify eGift card' => [
        'ar' => 'سنرسل رمز تحقق إلى بريدك الإلكتروني لتفعيل بطاقة الهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'Edit amount to use' => [
        'ar' => 'قم بتعديل المبلغ المراد استخدامه ',
        'context' => 'egift',
      ],
      'Applied card amount - ' => [
        'ar' => 'مبلغ البطاقة المستخدم - ',
        'context' => 'egift',
      ],
      'Remaining Balance - ' => [
        'ar' => 'الرصيد المتبقي - ',
        'context' => 'egift',
      ],
      'Link this card for faster payment next time' => [
        'ar' => 'اربط هذه البطاقة للدفع بشكل أسرع في المرة القادمة',
        'context' => 'egift',
      ],
      'Verification code is send to email address registered with the card number.' => [
        'ar' => 'يتم إرسال رمز التحقق إلى عنوان البريد الإلكتروني المسجل برقم البطاقة.',
        'context' => 'egift',
      ],
      'Resend Code' => [
        'ar' => ' أعد إرسال الرمز',
        'context' => 'egift',
      ],
      'Change Card?' => [
        'ar' => 'ترغب في تغيير البطاقة؟',
        'context' => 'egift',
      ],
      'add to bag' => [
        'ar' => ' أضف الى الحقيبة',
        'context' => 'egift',
      ],
      'checkout' => [
        'ar' => ' الدفع',
        'context' => 'egift',
      ],
      'No eGift cards found.' => [
        'ar' => 'لا توجد بطاقات هدايا إلكترونية',
        'context' => 'egift',
      ],
      '1. Select your style and card amount' => [
        'ar' => '1. اختر المبلغ والتصميم',
        'context' => 'egift',
      ],
      '2. Enter Gift card details' => [
        'ar' => '2. أدخل تفاصيل بطاقة الهدايا',
        'context' => 'egift',
      ],
      'Buying this gift for' => [
        'ar' => 'أقوم بشراء الهدية من أجل ',
        'context' => 'egift',
      ],
      'Friends and family' => [
        'ar' => 'الأصدقاء والعائلة ',
        'context' => 'egift',
      ],
      'Myself' => [
        'ar' => 'نفسي ',
        'context' => 'egift',
      ],
      'Recipient Details' => [
        'ar' => 'تفاصيل المستلم ',
        'context' => 'egift',
      ],
      'My Details' => [
        'ar' => 'تفاصيلي ',
        'context' => 'egift',
      ],
      'Name*' => [
        'ar' => 'الاسم* ',
        'context' => 'egift',
      ],
      'Email*' => [
        'ar' => 'البريد الإلكتروني* ',
        'context' => 'egift',
      ],
      'Write a message' => [
        'ar' => 'اكتب رسالة ',
        'context' => 'egift',
      ],
      'Message' => [
        'ar' => 'الرسالة ',
        'context' => 'egift',
      ],
      'Please enter amount or select from above.' => [
        'ar' => 'الرجاء إدخال المبلغ أو الاختيار من أعلاه. ',
        'context' => 'egift',
      ],
      'Please enter amount in the range of @amountFrom to @amountTo' => [
        'ar' => 'الرجاء إدخال المبلغ من @amountFrom إلى @amountTo  ',
        'context' => 'egift',
      ],
      'Amount @currencyCode' => [
        'ar' => 'المبلغ @currencyCode ',
        'context' => 'egift',
      ],
      'Please enter a valid amount' => [
        'ar' => ' يرجى إدخال مبلغ صالح',
        'context' => 'egift',
      ],
      'Verification code sent successfully.' => [
        'ar' => 'تم إرسال رمز التحقق بنجاح.',
        'context' => 'egift',
      ],
      'Redeem amount should be less than or equal to the balance payable.' => [
        'ar' => 'يجب أن يكون مبلغ الاسترداد بقيمة أقل أو مساوية لقيمة حقيبة التسوق',
        'context' => 'egift',
      ],
      'Pay using eGift card' => [
        'ar' => ' الدفع باستخدام بطاقة الهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'Available Balance: ' => [
        'ar' => ' الرصيد المتوفر:',
        'context' => 'egift',
      ],
      'Paid With eGift Card' => [
        'ar' => ' مدفوعة عبر بطاقة الهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'Balance Payable' => [
        'ar' => ' الرصيد مستحق الدفع',
        'context' => 'egift',
      ],
      'Amount Paid' => [
        'ar' => 'المبلغ المدفوع',
        'context' => 'egift',
      ],
      'Pay using eGift card (Remaining Balance: @currencyCode @amount)' => [
        'ar' => ' الدفع باستخدام بطاقة الهدايا الإلكترونية (الرصيد المتبقي: @currencyCode @amount)',
        'context' => 'egift',
      ],
      'Pay using eGift card (Card is expired)' => [
        'ar' => ' الدفع باستخدام بطاقة الهدايا الإلكترونية (البطاقة منتهية الصلاحية)',
        'context' => 'egift',
      ],
      'Pay ' => [
        'ar' => 'الدفع',
        'context' => 'egift',
      ],
      ' using another payment method to complete purchase' => [
        'ar' => ' استخدم طريقة دفع أخرى لإتمام الشراء',
        'context' => 'egift',
      ],
      'Top up' => [
        'ar' => 'اشحن رصيد',
        'context' => 'egift',
      ],
      'Top up for' => [
        'ar' => ' اشحن رصيد لـ',
        'context' => 'egift',
      ],
      'My Card' => [
        'ar' => ' بطاقتي',
        'context' => 'egift',
      ],
      'Other\'s Card' => [
        'ar' => ' بطاقة أخرى',
        'context' => 'egift',
      ],
      'Card Balance:' => [
        'ar' => ' رصيد البطاقة:',
        'context' => 'egift',
      ],
      'Card No:' => [
        'ar' => 'رقم البطاقة:',
        'context' => 'egift',
      ],
      'Card Details' => [
        'ar' => ' تفاصيل البطاقة',
        'context' => 'egift',
      ],
      'eGift Card' => [
        'ar' => 'بطاقة الهدايا الإلكترونية',
        'context' => 'egift',
      ],
      'Balance:' => [
        'ar' => 'الرصيد:',
        'context' => 'egift',
      ],
      'Expires on' => [
        'ar' => ' تنتهي صلاحيته في',
        'context' => 'egift',
      ],
      'This card has expired.' => [
        'ar' => ' هذه البطاقة منتهية الصلاحية.',
        'context' => 'egift',
      ],
      'Card Type' => [
        'ar' => ' نوع البطاقة',
        'context' => 'egift',
      ],
      'Link eGift card to account' => [
        'ar' => 'ربط بطاقة الهدايا الإلكترونية الخاصة بي',
        'context' => 'egift',
      ],
      'You dont have any eGift card linked to your account, link card to use it for your purchases' => [
        'ar' => ' ليس لديك أي بطاقة هدايا إلكترونية مرتبطة بحسابك، قم بربط حسابك ببطاقة هدايا لاستخدامها في عملية الشراء',
        'context' => 'egift',
      ],
      'We\'ll send a verification code to your email to verify and link eGift card' => [
        'ar' => ' سنرسل رمز تحقق إلى بريدك الإلكتروني لتفعيل بطاقة الهدايا الإلكترونية وربطها',
        'context' => 'egift',
      ],
      'Get Code' => [
        'ar' => ' الحصول على رمز',
        'context' => 'egift',
      ],
      'Enter verification code' => [
        'ar' => ' أدخل رمز التحقق',
        'context' => 'egift',
      ],
      'Didn\'t receive?' => [
        'ar' => ' لم تستلم الرمز؟',
        'context' => 'egift',
      ],
      'Verify' => [
        'ar' => 'تفعيل',
        'context' => 'egift',
      ],
      'Please enter an eGift card number.' => [
        'ar' => ' الرجاء إدخال رقم بطاقة الهدايا الإلكترونية. ',
        'context' => 'egift',
      ],
      'Please enter a valid eGift card number.' => [
        'ar' => 'الرجاء إدخال رقم صالح لبطاقة الهدايا الإلكترونية. ',
        'context' => 'egift',
      ],
      'Please enter verification code.' => [
        'ar' => 'الرجاء إدخال رمز التحقق. ',
        'context' => 'egift',
      ],
      'Please enter a valid verification code.' => [
        'ar' => 'الرجاء إدخال رمز تحقق صالح. ',
        'context' => 'egift',
      ],
      'You cannot redeem the same card which you\'re trying to topup.' => [
        'ar' => 'لا يمكنك استرداد نفس البطاقة التي تحاول إعادة شحنها. ',
        'context' => 'egift',
      ],
      'Buy Alshaya eGift Card' => [
        'ar' => 'شراء بطاقة هدايا الشايع الإلكترونية لشحن رصيدك',
      ],
      'Top up eGift card' => [
        'ar' => 'قم بتعبئة بطاقة الهدايا الإلكترونية',
      ],
      'eGift Card To:' => [
        'ar' => ' بطاقة الهدايا الإلكترونية لـ:',
        'context' => 'egift',
      ],
      'eGift card will be sent immediately' => [
        'ar' => ' سيتم إرسال بطاقة الهدايا الإلكترونية على الفور',
        'context' => 'egift',
      ],
      'Top up to:' => [
        'ar' => ' تعبئة الرصيد لـ:',
        'context' => 'egift',
      ],
      'Top up amount will reflect immediately in card' => [
        'ar' => ' سيتم إضافة مبلغ التعبئة على الفور في البطاقة',
        'context' => 'egift',
      ],
      'Please enter recipient name' => [
        'ar' => 'يرجى إدخال اسم صحيح',
        'context' => 'egift',
      ],
      'Please enter valid email address' => [
        'ar' => 'أدخل عنوان البريد الإلكتروني الخاص بك.',
        'context' => 'egift',
      ],
      'Amount' => [
        'ar' => 'المبلغ',
        'context' => 'egift',
      ],
      'Edit Amount' => [
        'ar' => 'قم بتعديل المبلغ',
        'context' => 'egift',
      ],
      'Choose Top up Amount (@currencyCode)' => [
        'ar' => '(@currencyCode) اختر مبلغ التعبئة',
        'context' => 'egift',
      ],
      'Cancel' => [
        'ar' => 'إلغاء',
        'context' => 'egift',
      ],
      'Redeem eGift Card' => [
        'ar' => 'استرداد بطاقة الهدايا',
        'context' => 'egift',
      ],
      'Enter amount' => [
        'ar' => 'إدخال المبلغ',
        'context' => 'egift',
      ],
      'The eGift card balance is not sufficient to pay remaining amount, Please use another payment method.' => [
        'ar' => 'رصيد بطاقة الهدايا الإلكترونية غير كافي لدفع المبلغ المتبقي، يرجى استخدام وسيلة دفع أخرى',
        'context' => 'egift',
      ],
      'Do you want to unlink this card from this account?' => [
        'ar' => 'هل تريد إلغاء ربط هذه البطاقة بهذا الحساب؟',
        'context' => 'egift',
      ],
      'You can only redeem full pending balance or use other payment method.' => [
        'ar' => 'يمكنك استرداد الرصيد المعلق بالكامل أو استخدام وسيلة دفع أخرى.',
        'context' => 'egift',
      ],
      'Please pay full amount via eGift card or use other payment method.' => [
        'ar' => 'يرجى دفع المبلغ بالكامل عبر بطاقة الهدايا الإلكترونية أو استخدام طريقة دفع أخرى.',
        'context' => 'egift',
      ],
      'My eGift Card' => [
        'ar' => 'بطاقة الهدايا الإلكترونية الخاصة بي',
        'context' => 'egift',
      ],
      'Remove' => [
        'ar' => 'إزالة',
        'context' => 'egift',
      ]
    ],
    'v2' => [
      'Unlink' => [
        'ar' => 'مختلف',
        'context' => 'egift',
      ],
      'eGift Card' => [
        'ar' => 'بطاقة الهدايا',
        'context' => 'egift',
      ],
      'Buy eGift Card' => [
        'ar' => 'اشترِ بطاقة الهدايا',
        'context' => 'egift',
      ],
    ]
  ];

  return $strings;
}

/**
 * Get translations for given version.
 *
 * @param string $version
 *   Version number like 'v1' etc.
 *
 * @return array
 *   Translations.
 */
function _alshaya_egift_card_get_translations(string $version = '') {
  $translations = _alshaya_egift_card_translations();
  // If no version mentioned, return all version strings.
  if (empty($version)) {
    $trans_data = [];
    foreach ($translations as $trans) {
      $trans_data = array_merge($trans_data, $trans);
    }

    return $trans_data;
  }

  return $translations[$version] ?? [];
}
