<?php

/**
 * @file
 * Contains egift card related static strings.
 */

/**
 * egift card static strings.
 */
function _alshaya_egift_card_static_strings() {
  return [
    [
      'key' => 'expires_label',
      'value' => t('Expires on'),
    ],
    [
      'key' => 'gift_card_number_label',
      'value' => t('Gift Card number'),
    ],
    [
      'key' => 'card_type_label',
      'value' => t('Card Type'),
    ],
    [
      'key' => 'top_up',
      'value' => t('Top UP'),
    ],
    [
      'key' => 'my_efit_card',
      'value' => t('My eGift Card'),
    ],
  ];
}
