<?php

/**
 * @file
 * Contains alshaya_egift_card.module.
 */

 use Drupal\Core\Cache\Cache;
 use Drupal\node\NodeInterface;

/**
 * Implements hook_alshaya_spc_checkout_build_alter().
 */
function alshaya_egift_card_alshaya_spc_checkout_build_alter(array &$build) {
  // Do not proceed if egift card is not enabled.
  $egiftCard_settings = \Drupal::service('alshaya_egift_card.egift_card_helper');
  $build['#attached']['drupalSettings']['egiftCard'] = [
    'enabled' => $egiftCard_settings->isEgiftCardEnabled(),
    'notSupportedPaymentMethods' => array_filter($egiftCard_settings->getNotSupportedPaymentMethods(), function($method) {
      return $method !== '0';
    }),
  ];
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'], \Drupal::config('alshaya_egift_card.settings')->getCacheTags());
  $build['#attached']['library'][] = 'alshaya_white_label/egift-card-checkout';

  $build['#strings'][] = [
    'key' => 'form_egift_card_number',
    'value' => t('Please enter your card number.', [], [
      'context' => 'egift'
    ]),
  ];
  $build['#strings'][] = [
    'key' => 'form_egift_code',
    'value' => t('Please enter the code.', [], [
      'context' => 'egift'
    ]),
  ];
  $build['#strings'][] = [
    'key' => 'form_egift_amount',
    'value' => t('Please enter the amount.', [], [
      'context' => 'egift'
    ]),
  ];
  $build['#strings'][] = [
    'key' => 'egift_insufficient_balance',
    'value' => t('Insufficient balance, Please topup the card or lower the redeem amount.', [], [
      'context' => 'egift'
    ]),
  ];
  $build['#strings'][] = [
    'key' => 'egift_amount_update_failed',
    'value' => t('Amount updated failed! Please try again after sometime.', [], [
      'context' => 'egift'
    ]),
  ];
  $build['#strings'][] = [
    'key' => 'egift_valid_amount',
    'value' => t('Please enter a valid amount.', [], [
      'context' => 'egift'
    ]),
  ];
  $build['#strings'][] = [
    'key' => 'egift_valid_card_number',
    'value' => t('Please enter a valid card number.', [], [
      'context' => 'egift',
    ]),
  ];
}

/**
 * Implements hook_alshaya_spc_cart_build_alter().
 */
function alshaya_egift_card_alshaya_spc_cart_build_alter(array &$build) {
  // Do not proceed if egift card is not enabled.
  $egiftCard_settings = \Drupal::service('alshaya_egift_card.egift_card_helper');
  // Add egift card settings in drupalSettings.
  $build['#attached']['drupalSettings']['egiftCard']['enabled'] = $egiftCard_settings->isEgiftCardEnabled();
  $build['#attached']['library'][] = 'alshaya_white_label/egift-cart';
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'], \Drupal::config('alshaya_egift_card.settings')->getCacheTags());
}

/**
 * Implements hook_theme().
 */
function alshaya_egift_card_theme() {
  return [
    'egift_balance_check_block' => [
      'variables' => [
        'block_title' => '',
        'block_description' => '',
        'check_balance_button' => '',
      ]
    ],
    'egift_topup_terms_conditions' => [
      'variables' => [
        'content' => '',
      ],
    ],
    'egift_topup_page' => [
      'variables' => [
        'terms_block_content' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_alshaya_my_account_links_alter().
 */
function alshaya_egift_card_alshaya_my_account_links_alter(array &$links) {
  // Do not proceed if Egift card is not enabled.
  if (!\Drupal::service('alshaya_egift_card.egift_card_helper')->isEgiftCardEnabled()) {
    return;
  }

  // Add My egift card link.
  $links['alshaya_my_egift_card'] = [
    'text' => t('eGift Card', [], ['context' => 'egift']),
    'route' => 'alshaya_egift_card.my_egift_card',
    'weight' => 11,
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function alshaya_egift_card_preprocess_html(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  // Add custom class for advanced page content type for egift landing page.
  if ($node instanceof NodeInterface && $node->bundle() === 'advanced_page') {
    if (!empty($node->get('field_use_as_egift_landing_page')->getValue()) && $node->get('field_use_as_egift_landing_page')->getValue()[0]['value'] == 1) {
      $variables['attributes']['class'][] = 'egift-landing-page';
      $variables['#attached']['library'][] = 'alshaya_white_label/egift-landing-page';
    }
  }
}
