<?php

/**
 * @file
 * Module file for seo transac.
 */

use Drupal\acq_sku\Entity\SKU;
use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_seo_transac_preprocess_html(&$variables) {
  if (_alshaya_seo_process_gtm()) {
    /** @var \Drupal\alshaya_seo_transac\AlshayaGtmManager $gtmManager */
    $gtm_manager = \Drupal::service('alshaya_seo_transac.gtm_manager');
    $variables['attributes']['gtm-currency'] = \Drupal::configFactory()->get('acq_commerce.currency')->getRawData()['currency_code'];
    $variables['attributes']['gtm-container'] = $gtm_manager->convertCurrentRouteToGtmPageName($gtm_manager->getGtmContainer());
    $variables['attributes']['gtm-list-name'] = $gtm_manager->convertCurrentRouteToGtmListName($gtm_manager->getGtmContainer());
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_seo_transac_page_attachments_alter(&$page) {
  if (_alshaya_seo_process_gtm()) {
    $page['#attached']['library'][] = 'alshaya_seo_transac/gtm';
    $page['#attached']['drupalSettings']['gtm']['disabled_vars'] = \Drupal::config('alshaya_seo.disabled_gtm_vars')->get('disabled_vars');
  }
}

/**
 * Implements template_preprocess_node().
 */
function alshaya_seo_transac_preprocess_node(&$variables) {
  if (!_alshaya_seo_process_gtm()) {
    return;
  }

  $view_mode = $variables['view_mode'];
  /** @var \Drupal\node\Entity\Node $entity */
  $entity = $variables['node'];

  if (($entity->bundle() === 'acq_product') &&
    (\Drupal::languageManager()->getCurrentLanguage()->getId() === $entity->language()->getId())) {
    /** @var \Drupal\alshaya_seo_transac\AlshayaGtmManager $alshayaGtmManager */
    $gtm_manager = \Drupal::service('alshaya_seo_transac.gtm_manager');
    $product_node = $gtm_manager->fetchProductGtmAttributes($entity, $view_mode);
    $variables['gtm_attributes']['#markup'] = $gtm_manager->convertAttrsToString($product_node);
  }
}

/**
 * Adding google rich snippet to product.
 *
 * @param array $snippet
 *   Rich snippet array.
 *
 * @return array
 *   Rich snippet array.
 */
function _alshaya_seo_transac_pdp_rich_snippet(array $snippet = []) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() == 'entity.node.canonical') {
    /* @var \Drupal\node\Entity\Node $node */
    $node = $route_match->getParameter('node');
    // If 'product' node.
    if ($node && $node->getType() == 'acq_product') {
      if ($sku_field = $node->get('field_skus')) {
        $sku_id = $sku_field->first()->getString();
        $sku_entity = SKU::loadFromSku($sku_id);

        if (empty($sku_entity)) {
          return [];
        }

        $product_title = "";

        // Including the utility file.
        \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');
        $product_image = _alshaya_acm_get_product_display_image_url($sku_entity);

        $product_description = _alshaya_seo_get_node_meta_description();
        $final_price = "";
        $currency = \Drupal::configFactory()->get('acq_commerce.currency')->get('currency_code');

        // If sku name is available.
        if ($sku_entity->get('name')) {
          $product_title = $sku_entity->get('name')->getString();
        }

        // If final price is available.
        if ($sku_entity->get('final_price')) {
          $final_price = (float) $sku_entity->get('final_price')->getString();
        }

        // Prepare rich snippet.
        $snippet['@type'] = 'Product';
        $snippet['name'] = $product_title;
        $snippet['description'] = $product_description;
        $snippet['image'] = $product_image;
        // @Todo: Change this once brand field is available.
        $snippet['brand'] = [
          '@type' => 'Thing',
          'name' => \Drupal::config('system.site')->get('name'),
        ];
        $snippet['offers'] = [
          '@type' => "Offer",
          'priceCurrency' => $currency,
          'price' => $final_price,
        ];
      }
    }
  }

  return $snippet;
}

/**
 * Implements hook_datalayer_alter().
 */
function alshaya_seo_transac_datalayer_alter(&$data_layer) {
  if (!_alshaya_seo_process_gtm()) {
    return;
  }

  /** @var \Drupal\alshaya_seo_transac\AlshayaGtmManager $gtm_manager */
  $gtm_manager = \Drupal::service('alshaya_seo_transac.gtm_manager');
  $currency_code = \Drupal::configFactory()->get('acq_commerce.currency')->getRawData()['currency_code'];

  try {
    $current_route = $gtm_manager->getGtmContainer();
    $general_dl_attributes = $gtm_manager->fetchGeneralPageAttributes($data_layer);

    // Preserve attributes before overriding the datalayer attributes.
    if (isset($data_layer['deliveryCity'])) {
      $general_dl_attributes['deliveryCity'] = $data_layer['deliveryCity'];
    }

    if (isset($data_layer['deliveryArea'])) {
      $general_dl_attributes['deliveryArea'] = $data_layer['deliveryArea'];
    }

    $data_layer = $general_dl_attributes;

    $page_type = $gtm_manager->convertCurrentRouteToGtmPageName($gtm_manager->getGtmContainer());
    switch ($current_route['route_name']) {
      case 'entity.node.canonical':
        if (isset($current_route['route_params'], $current_route['route_params']['node'])) {
          /** @var \Drupal\node\Entity\Node $node */
          $node = $current_route['route_params']['node'];
          if ($node->bundle() === 'acq_product') {
            $attributes = $gtm_manager->fetchProductGtmAttributes($node, 'full');
            $processed_attributes = $gtm_manager->processAttributesForPdp($attributes);
            $data_layer = array_merge($data_layer, $processed_attributes);
            $data_layer['pageType'] = $gtm_manager->convertCurrentRouteToGtmPageName($gtm_manager->getGtmContainer());
          }
        }
        break;

      case 'acq_checkout.form':
        if (in_array($current_route['route_params']['step'],
          ['login', 'delivery', 'payment'], TRUE)) {

          $cart_item_attributes = $gtm_manager->fetchCartItemAttributes();

          $products = [];
          $data_layer['privilegeCustomer'] = $cart_item_attributes['privilegeCustomer'];
          $data_layer['privilegesCardNumber'] = $cart_item_attributes['privilegesCardNumber'];
          $step = isset($cart_item_attributes['step']) ? $cart_item_attributes['step'] : NULL;
          unset($cart_item_attributes['privilegeCustomer'], $cart_item_attributes['privilegesCardNumber'], $cart_item_attributes['step']);

          foreach ($cart_item_attributes as $key => $cart_item) {
            $product = $gtm_manager->convertHtmlAttributesToDatalayer($cart_item);
            $product['quantity'] = $cart_item['quantity'];
            $products[] = $product;
          }

          // Set the correct step id.
          switch ($current_route['route_params']['step']) {
            case 'login':
              $step = 1;
              break;

            case 'delivery':
              $step = !empty($step) ? $step : 2;
              break;

            case 'payment':
              $step = 4;
              break;
          }

          $data_layer_cart = [
            'ecommerce' => [
              'currencyCode' => $currency_code,
              'checkout' => [
                'actionField' => [
                  'step' => $step,
                ],
                'products' => $products,
              ],
            ],
          ];

          $data_layer = array_merge($data_layer, $data_layer_cart);

        }
        elseif (in_array($current_route['route_params']['step'], ['confirmation'], TRUE)) {
          $order = _alshaya_acm_checkout_get_last_order_from_session();

          // We check if we have valid order id.
          if (empty($order)) {
            return;
          }

          $cookie_key = 'alshaya_gtm_confirmation_visited_' . $order['order_id'];

          $already_visited = (int) \Drupal::request()->cookies->get('Drupal_visitor_' . $cookie_key);

          // Send order complete confirmation to GTM only once.
          if ($already_visited !== 1) {
            $attributes = $gtm_manager->fetchCompletedOrderAttributes($order);
            $data_layer = array_merge($data_layer, $attributes['general']);

            $data_layer['privilegeOrder'] = $attributes['privilegeCustomer'] ? 'order with privilege club' : 'order without privilege club';

            $data_layer['ecommerce'] = [
              'currencyCode' => $currency_code,
              'purchase' => [
                'actionField' => $attributes['actionField'],
                'products' => $attributes['products'],
              ],
            ];

            /** @var \Drupal\alshaya_acm_checkout\CheckoutOptionsManager $checkout_options_manager */
            $checkout_options_manager = \Drupal::service('alshaya_acm_checkout.options_manager');
            if ($attributes['general']['deliveryOption'] === $checkout_options_manager->getClickandColectShippingMethod()) {
              $data_layer['event'] = 'VirtualPageView';
              $data_layer['virtualPageUrl'] = '/virtualpv/click-and-collect/step4/order-success';
              $data_layer['virtualPageTitle'] = 'C&C Step 4 – Order Success';
            }

            user_cookie_save([$cookie_key => 1]);
          }
        }
        break;
    }

    // Generic handling of page type for user pages.
    $current_route = $gtm_manager->getGtmContainer();
    $current_path = $current_route['pathinfo']->getpath();

    // General logic to calculate page-type in case of my account pages &
    // undefined pages.
    $path_parts = explode('/', $current_path);

    // Remove characters not suitable for page type.
    $blacklisted_user_url_parts = [
      'user',
      '',
      '{user}',
      '{order_id}',
      '{uid}',
      '{timestamp}',
      '{hash}',
      'new',
      '{profile_type}',
      '{webform}',
    ];

    foreach ($path_parts as $key => $part) {
      if (is_numeric($part) ||
        (in_array($part, $blacklisted_user_url_parts))) {
        unset($path_parts[$key]);
      }
    }

    if (strpos($current_path, '/user') === 0) {
      $page_type = trim('myaccount ' . implode('', $path_parts));
    }
    elseif ($page_type === 'not defined') {
      $page_type = ltrim(implode('-', $path_parts), '-');
    }

    $data_layer['pageType'] = $page_type;
    $page_dl_attributes = $gtm_manager->fetchPageSpecificAttributes($page_type, $current_route);
    $data_layer = array_merge($data_layer, $page_dl_attributes);

    // Unset few attributes specifically for HD page.
    if (($current_route['route_name'] === 'acq_checkout.form') &&
      ($current_route['route_params']['step'] == 'delivery') &&
      (!isset($current_route['query']['method']) || $current_route['query']['method'] === 'hd')) {
      unset($data_layer['storeAddress'], $data_layer['storeLocation'], $data_layer['deliveryOption'], $data_layer['deliveryType']);
    }
  }
  catch (Exception $e) {
    \Drupal::logger('alshaya_seo')->error('Error while fetching GTM attributes: @message', ['@message' => $e->getMessage()]);
  }
}

/**
 * Implements template_preprocess_alshaya_cart_product_name().
 */
function alshaya_seo_transac_preprocess_alshaya_cart_product_name(&$variables) {
  \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');
  if (empty($variables['item_code'])) {
    return;
  }

  /** @var \Drupal\alshaya_seo_transac\AlshayaGtmManager $gtmManager */
  $gtm_manager = \Drupal::service('alshaya_seo_transac.gtm_manager');

  $sku_attributes = $gtm_manager->fetchSkuAtttributes($variables['item_code']);

  // Fetch product for this sku to get the category.
  $product_node = alshaya_acm_product_get_display_node($variables['item_code']);

  if ($product_node instanceof NodeInterface) {
    $sku_attributes['gtm-category'] = implode('/', $gtm_manager->fetchProductCategories($product_node));
    $sku_attributes['gtm-main-sku'] = $product_node->get('field_skus')->first()->getString();
  }

  $sku_attributes['gtm-type'] = 'gtm-remove-cart-wrapper';
  $sku_attributes['gtm-size'] = isset($variables['sku_attributes'], $variables['sku_attributes']['attr_size']) ? $variables['sku_attributes']['attr_size']['value'] : '';

  $variables['gtm_attributes']['#markup'] = $gtm_manager->convertAttrsToString($sku_attributes);
}

/**
 * Implements hook_alshaya_seo_google_knowledge_graph_alter().
 */
function alshaya_seo_transac_alshaya_seo_google_knowledge_graph_alter(&$gkg_data) {
  $gkg_data = _alshaya_seo_transac_pdp_rich_snippet($gkg_data);
}

/**
 * Implements template_preprocess_alshaya_main_menu_level2().
 */
function alshaya_seo_transac_preprocess_alshaya_main_menu_level2(&$variables) {
  $sub_nav_label = str_replace(' ', '-', strtolower($variables['data']['label']));
  $sub_nav_class = 'sub-nav-' . $sub_nav_label;
  $variables['data']['sub_nav_class'] = 'sub-nav-' . $sub_nav_label;
  foreach ($variables['data']['child'] as $key1 => $value) {
    $variables['data']['child'][$key1]['sub_nav_class'] = $sub_nav_class;
    foreach ($value['child'] as $key2 => $value2) {
      $variables['data']['child'][$key1]['child'][$key2]['sub_nav_class'] = $sub_nav_class;
    }
  }
}

/**
 * Implements hook_theme().
 */
function alshaya_seo_transac_theme($existing, $type, $theme, $path) {
  return [
    'alshaya_sitemap' => [
      'template' => 'alshaya-sitemap',
      'variables' => [
        'term_tree' => NULL,
      ],
    ],
  ];
}
