<?php

/**
 * @file
 * Alshaya email signup mdoule file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function alshaya_email_signup_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_alshaya_email_signup_form') {
    $form['exclusive_deals']['#suffix'] = \Drupal::config('alshaya_user.settings')->get('terms_conditions.value');
  }
}
