<?php

/**
 * @file
 * Alshaya email signup module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alshaya_email_signup_form_webform_submission_alshaya_email_signup_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add terms and conditions suffix.
  $form['elements']['exclusive_deals']['#suffix'] = \Drupal::config('alshaya_user.settings')->get('terms_conditions.value');
}
