<?php

/**
 * @file
 * Module file for alshaya_social_facebook.
 */

/**
 * Implements hook_alshaya_social_SOICAL_NETWORK_alter().
 */
function alshaya_social_facebook_alshaya_social_social_auth_facebook_alter(&$network, $route_name) {
  $login_routes = ['user.login', 'acq_checkout.form'];

  $network['text_link'] = in_array($route_name, $login_routes)
    ? t('sign in with Facebook')
    : t('sign up with Facebook');
}
