<?php

/**
 * @file
 * Module file.
 */

 /**
 * Implements hook_theme().
 */
function alshaya_rcs_promotion_theme($existing, $type, $theme, $path) {
  return [
    'node__rcs_promotion' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function alshaya_rcs_promotion_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::request()->attributes->get('node');
    if ($node->bundle() == 'rcs_promotion') {
      $suggestions[] = 'page__plp';
    }
  }
}
