<?php

/**
 * @file
 * Module file.
 */

 /**
 * Implements hook_theme().
 */
function alshaya_rcs_promotion_theme($existing, $type, $theme, $path) {
  return [
    'node__rcs_promotion' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function alshaya_rcs_promotion_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::request()->attributes->get('node');
    if ($node->bundle() == 'rcs_promotion') {
      $suggestions[] = 'page__plp';
    }
  }
}

/**
 * Implements hook_rcs_placeholders_graphql_query().
 */
function alshaya_rcs_promotion_rcs_placeholders_graphql_query() {
  $query_fields = [];

  $query_fields['promotions'] = [
    'id',
    'title',
    'description',
  ];

  return $query_fields;
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_promotion_library_info_alter(&$libraries, $extension) {
  // Alter the promotion label library to replace the base JS file with the
  // promotion label file provided by this module.
  if (isset($libraries['label_manager']['js']['assets/js/alshaya_promotions_label.js'])) {
    // Retains the options of the existing js file.
    $options = $libraries['label_manager']['js']['assets/js/alshaya_promotions_label.js'];
    unset($libraries['label_manager']['js']['assets/js/alshaya_promotions_label.js']);
    $self_module_path = drupal_get_path('module', 'alshaya_rcs_promotion');
    $libraries['label_manager']['js']["/$self_module_path/js/alshaya_rcs_promotion_label.js"] = $options;
    array_push($libraries['label_manager']['dependencies'],
      'rcs_magento_placeholders/rcs_magento_placeholders',
      'alshaya_rcs_promotion/alshaya_rcs_promotion',
    );
  }
}
