<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_alshaya_spc_checkout_confirmation_order_build_alter().
 */
function alshaya_tamara_alshaya_spc_checkout_confirmation_order_build_alter(array &$build, $order) {
  $tamaraApiConfig = \Drupal::service('alshaya_tamara.api_helper')->getTamaraApiConfig();
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], $tamaraApiConfig->getCacheTags());

  // Return false if `is_active` is set to false or not set.
  if (!isset($tamaraApiConfig['is_active'])
    || !((bool) $tamaraApiConfig['is_active'])) {
    return FALSE;
  }

  // Attach the tamara library.
  $build['#attached']['library'][] = 'alshaya_white_label/tamara';
}
