<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_alshaya_spc_checkout_confirmation_order_build_alter().
 */
function alshaya_tamara_alshaya_spc_checkout_confirmation_order_build_alter(array &$build, $order) {
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], ['config:alshaya_tamara.settings']);

  // Return if the Tamara payment method is not enabled.
  if (!\Drupal::service('alshaya_tamara.helper')->isTamaraEnabled()) {
    return;
  }

  // Attach the tamara library.
  $build['#attached']['library'][] = 'alshaya_white_label/tamara';
}

/**
 * Implements hook_alshaya_acm_customer_orders_details_build_alter().
 */
function alshaya_tamara_alshaya_acm_customer_orders_details_build_alter(array &$order, array &$build) {
  // If order is placed using Tamara payment method, we need to show `Tamara`
  // as a payment method in customer's order details section.
  if (isset($build["#order_details"]["payment_method_code"])
    && $build["#order_details"]["payment_method_code"] == 'tamara') {
    $build["#order_details"]["payment_method"] = t('Tamara', [], ['context' => 'tamara']);
  }
}
