<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_alshaya_spc_checkout_confirmation_order_build_alter().
 */
function alshaya_tamara_alshaya_spc_checkout_confirmation_order_build_alter(array &$build, $order) {
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], ['config:alshaya_tamara.settings']);

  // Return if the Tamara payment method is not enabled.
  if (!\Drupal::service('alshaya_tamara.helper')->isTamaraEnabled()) {
    return;
  }

  // Attach the tamara library.
  $build['#attached']['library'][] = 'alshaya_white_label/tamara';
}

/**
 * Implements hook_alshaya_acm_customer_orders_details_build_alter().
 */
function alshaya_tamara_alshaya_acm_customer_orders_details_build_alter(array &$order, array &$build) {
  // If order is placed using Tamara payment method, we need to show `Tamara`
  // as a payment method in customer's order details section.
  if (isset($build["#order_details"]["payment_method_code"])
    && $build["#order_details"]["payment_method_code"] == 'tamara') {
    $build["#order_details"]["payment_method"] = t('Tamara', [], ['context' => 'tamara']);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function alshaya_tamara_preprocess_node(&$variables) {
  if (in_array($variables['node']->bundle(), ['acq_product', 'rcs_product'])) {
    $tamara_enabled = \Drupal::service('alshaya_tamara.helper')->isTamaraEnabled();
    // Add tamara status for full mode only so that it can be used in
    // v2 magazine view mode by PDP react components.
    if ($variables['view_mode'] == 'full') {
      $variables['#attached']['drupalSettings']['isTamaraEnabled'] = $tamara_enabled;
    }
    // Pass tamara status to node template for all view modes.
    $variables['tamara_enabled'] = $tamara_enabled;
  }
}

/**
 * Implements hook_preprocess_template().
 */
function alshaya_tamara_preprocess_alshaya_magazine(&$variables) {
  // Pass tamara status to alshaya magazine template.
  // TRUE if tamara is enabled and FALSE when tamara module/feature
  // is disabled.
  $variables['tamara_enabled'] = \Drupal::service('alshaya_tamara.helper')
    ->isTamaraEnabled();
}
