<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function alshaya_product_options_theme() {
  $items = [];

  $items['facets_result_item_with_swatch'] = [
    'variables' => [
      'value' => '',
      'show_count' => FALSE,
      'count' => NULL,
      'is_active' => FALSE,
      'swatch_image' => NULL,
      'swatch_text' => NULL,
      'swatch_color' => NULL,
    ],
    'template' => 'facets-result-item-with-swatch',
  ];

  return $items;
}

/**
 * Implements hook_drush_command_alter().
 */
function alshaya_product_options_drush_command_alter(&$command) {
  $sync_options_commands = [
    'sync-commerce-product-options',
    'acspo',
  ];

  if (in_array($command['command'], $sync_options_commands) && (drush_drupal_major_version() >= 8)) {
    $command['command'] = 'alshaya-sync-commerce-product-options';
    $command['command-hook'] = 'alshaya-sync-commerce-product-options';
    $command['primary function'] = FALSE;
    drush_set_command($command);
  }
}
