<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\alshaya_product_options\Brand\AlshayaBrandListHelper;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_theme().
 */
function alshaya_product_options_theme() {
  $items = [];

  $items['facets_result_item_with_swatch'] = [
    'variables' => [
      'value' => '',
      'show_count' => FALSE,
      'count' => NULL,
      'is_active' => FALSE,
      'swatch_image' => NULL,
      'swatch_text' => NULL,
      'swatch_color' => NULL,
    ],
    'template' => 'facets-result-item-with-swatch',
  ];

  $items['alshaya_brand_carousel'] = [
    'render element' => 'elements',
    'variables' => [
      'brand_details' => [],
    ],
  ];

  return $items;
}

/**
 * Implements hook_taxonomy_term_presave().
 */
function alshaya_product_options_taxonomy_term_presave(TermInterface $term) {
  if ($term->bundle() === AlshayaBrandListHelper::BRAND_VID) {
    if ($term->get('field_sku_attribute_code')->value === AlshayaBrandListHelper::BRAND_ATTRIBUTE_CODE) {
      // Invalidate page cache.
      Cache::invalidateTags([AlshayaBrandListHelper::BRAND_CACHETAG]);
    }
  }
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function alshaya_product_options_taxonomy_term_delete(TermInterface $term) {
  if ($term->bundle() === AlshayaBrandListHelper::BRAND_VID) {
    if ($term->get('field_sku_attribute_code')->value === AlshayaBrandListHelper::BRAND_ATTRIBUTE_CODE) {
      // Invalidate page cache.
      Cache::invalidateTags([AlshayaBrandListHelper::BRAND_CACHETAG]);
    }
  }
}
