<?php

/**
 * @file
 * Module file for RCS Seo.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Url;
use Drupal\rcs_placeholders\Service\RcsPhPathProcessor;

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_seo_library_info_alter(&$libraries, $extension) {
  if ($extension !== 'datalayer') {
    return;
  }

  $new_source = '/' . drupal_get_path('module', 'alshaya_rcs_seo') . '/js/datapush.js';
  $options = $libraries['datapush']['js']['js/datapush.js'];
  unset($libraries['datapush']['js']['js/datapush.js']);
  $libraries['datapush']['js'][$new_source] = $options;

  $libraries['datapush']['dependencies'] = [
    'core/jquery',
    'core/drupal',
    'core/drupalSettings',
    'rcs_placeholders/helpers',
    'alshaya_rcs_seo/alshaya_rcs_product_seo',
  ];

  // Load it in the footer as the files which contain the event handlers will
  // be loaded in the footer only.
  unset($libraries['datapush']['header']);
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_rcs_seo_page_attachments_alter(&$attachments) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  if ($route_name === 'alshaya_spc.checkout.confirmation') {
    // This adds the library to the top of the array and above the
    // datalayer/datapush library.
    // If we put the weight=-1 for this, then the library dependencies are
    // loaded later, thus causing issues.
    // Hence we follow this approach.
    array_unshift($attachments['#attached']['library'], 'alshaya_rcs_seo/order_confirmation');
  }

  // This adds 'hreflang' to 'rcs_category' and 'rcs_product' page.
  if ($route_name === 'entity.taxonomy_term.canonical' || $route_name === 'entity.node.canonical') {

    // If the current route has no parameters, return.
    $route = $route_match->getRouteObject();
    $parameters = $route ? $route->getOption('parameters') : [];
    if (empty($parameters)) {
      return;
    }

    // Determine if the current route represents an entity.
    foreach ($parameters as $name => $options) {
      if (!isset($options['type']) || !str_starts_with($options['type'], 'entity:')) {
        continue;
      }

      $entity = $route_match->getParameter($name);

      if ($entity instanceof ContentEntityInterface &&
        ($entity->bundle() === 'rcs_category' || $entity->bundle() === 'rcs_product')) {

        foreach ($entity->getTranslationLanguages() as $language) {
          $hreflang = $language->getId();

          $url = Url::fromRoute(
            '<front>',
            [],
            ['absolute' => TRUE, 'language' => $language]
          )->toString();

          // Add the URL as is, RCS expects the URL to be same in all languages.
          $url .= RcsPhPathProcessor::getFullPath();

          // Unset "html_head_link" structure coming from 'content_translation'.
          foreach ($attachments['#attached']['html_head_link'] as $key => $element) {
            if (isset($element[0]['hreflang']) && $element[0]['hreflang'] === $hreflang) {
              unset($attachments['#attached']['html_head_link'][$key]);

              break;
            }
          }

          $attachments['#attached']['html_head_link'][] = [
            [
              'rel' => 'alternate',
              'hreflang' => $hreflang,
              'href' => $url,
            ],
          ];
        }
      }
    }
  }

}

/**
 * Implements hook_simple_sitemap_links_alter().
 */
function alshaya_rcs_seo_simple_sitemap_links_alter(array &$links, $sitemap_variant) {
  if ($sitemap_variant === 'default') {
    // Change the sitemap domain based on config value.
    $sitemap_domain = \Drupal::config('alshaya_rcs_seo.settings')->get('sitemap_domain_to_use') ?? 'drupal';
    switch ($sitemap_domain) {
      case 'magento':
        // Prepare the sitemap domain URL.
        $sitemap_domain_url = \Drupal::config('alshaya_api.settings')->get('magento_host');
        break;

      default:
        global $base_url;
        $sitemap_domain_url = $base_url;
        break;
    }

    $variant_links = [];
    $country_code = _alshaya_custom_get_site_level_country_code();
    $url = $sitemap_domain_url . '/media/sitemap/' . strtolower($country_code) . '/sitemap.xml';
    $variant_links[] = [
      'url' => $url,
      'priority' => '0.5',
    ];

    $links = array_merge($variant_links, $links);

    // Unset the image-sitemap from the default sitemap variant.
    $endsWith = '/image-sitemap';
    $len = strlen($endsWith);
    foreach ($links as $key => $value) {
      if (substr($value['url'], -$len) === $endsWith) {
        unset($links[$key]);
      }
    }
  }
}

/**
 * Implements hook_alshaya_rcs_category_query_fields_alter().
 */
function alshaya_rcs_seo_alshaya_rcs_category_query_fields_alter(&$fields) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  if ($current_route === 'alshaya_seo.sitemap') {
    $fields[] = 'description';
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_rcs_seo_module_implements_alter(&$implementations, $hook) {
  // To call the alshaya_rcs_seo_rcs_placeholders_graphql_query_alter at the end
  // for RCS Seo specific changes.
  if ($hook == 'rcs_placeholders_graphql_query_alter'
    && isset($implementations['alshaya_rcs_seo'])) {
    $group = $implementations['alshaya_rcs_seo'];
    unset($implementations['alshaya_rcs_seo']);
    $implementations['alshaya_rcs_seo'] = $group;
  }
}

/**
 * Implements hook_rcs_placeholders_graphql_query_alter().
 */
function alshaya_rcs_seo_rcs_placeholders_graphql_query_alter(&$query_fields) {
  // Adding a check for categories just in case if categories doesn't exists.
  if (array_key_exists('categories', $query_fields)) {
    array_push($query_fields['categories']['query']['query($urlKey: [String])']['categories(filters: { url_path: { in: $urlKey }})']['items'], 'gtm_name');
    array_push($query_fields['categories']['query']['query($urlKey: [String])']['categories(filters: { url_path: { in: $urlKey }})']['items']['breadcrumbs'], 'category_gtm_name');
  }
  // Add the GTM attributes for pdp product query as well.
  if (array_key_exists('pdp_product', $query_fields)) {
    array_push($query_fields['pdp_product']['query']['query($url: String)']['products(filter: {url_key: {eq: $url}})']['items']['categories'], 'gtm_name');
    array_push($query_fields['pdp_product']['query']['query($url: String)']['products(filter: {url_key: {eq: $url}})']['items']['categories']['breadcrumbs'], 'category_gtm_name');
  }
  // Get the GTM attributes in single_product_by_color_sku.
  if (array_key_exists('single_product_by_color_sku', $query_fields)) {
    $items = $query_fields['single_product_by_color_sku']['query']['query($sku: String)']['products(filter: {sku: {eq: $sku}})']['items'];
    $items = array_merge($items, [
      'gtm_attributes' => [
        'name',
      ],
    ]);
    $query_fields['single_product_by_color_sku']['query']['query($sku: String)']['products(filter: {sku: {eq: $sku}})']['items'] = $items;
  }
}

/**
 * Implements hook_metatags_attachments_alter().
 */
function alshaya_rcs_seo_metatags_attachments_alter(array &$attachments) {

  // Do not process for Authenticated user.
  if (\Drupal::currentUser()->isAuthenticated()) {
    return;
  }

  // Check if the SSR is enabled for metatag.
  if (!\Drupal::config('alshaya_rcs_seo.settings')->get('enable_ssr_metatag')) {
    return;
  }

  // Get page type from request i.e. product, category or promotion.
  $page_type = \Drupal::service('rcs_placeholders.path_prefix_helper')->getRcsPathPageType();
  if (empty($page_type)) {
    return;
  }

  /** @var \Drupal\alshaya_rcs_seo\Services\AlshayaRcsMetatagHelper $rcs_metatag_helper */
  $rcs_metatag_helper = \Drupal::service('alshaya_rcs_seo.metatag_helper');
  $rcs_metatags = &drupal_static(__FUNCTION__);
  // Get metatag details using graphQL call to magento for page type.
  if (!isset($rcs_metatags)) {
    $rcs_metatags = $rcs_metatag_helper->getRcsMetatagFromMagento($page_type);
    // Process meta details w.r.t page type.
    $rcs_metatag_helper->processMetaForPageType($page_type, $rcs_metatags);
  }

  // We will not process if data is not available.
  if (empty($rcs_metatags)) {
    return;
  }

  // Replace the rcs placeholders in metatags with actual data.
  foreach ($attachments['#attached']['html_head'] as &$attachment) {
    $attribute_type = $rcs_metatag_helper->getRcsSeoMetatagAttribute($attachment);
    if (empty($attribute_type)) {
      continue;
    }

    // Do the replacement based on RCS data.
    $attribute_data = &$attachment[0]['#attributes'][$attribute_type];
    if (strpos($attribute_data, "#rcs.$page_type") > -1) {
      $rcs_key = explode('#', $attribute_data)[1];
      $rcs_metatag = str_replace("rcs.$page_type.", '', $rcs_key);
      if (array_key_exists($rcs_metatag, $rcs_metatags)) {
        $attribute_data = str_replace("#$rcs_key#", $rcs_metatags[$rcs_metatag], $attribute_data);
      }
    }
  }
}
