<?php

/**
 * @file
 * Creating image sitemap for Google using media module.
 */

/**
 * Add image sitemap to the sitemap.
 *
 * @param array &$arbitrary_links
 *   Pramater link.
 */
function alshaya_image_sitemap_simple_sitemap_arbitrary_links_alter(array &$arbitrary_links) {
  $url = 'public://alshaya_image_sitemap/image_sitemap.xml';
  $url = file_create_url($url);
  $arbitrary_links[] = [
    'url' => $url,
    'priority' => '0.5',
    'lastmod' => date("c"),
    'changefreq' => 'weekly',
  ];
}
