<?php

/**
 * @file
 * Creating image sitemap for Google using media module.
 */

/**
 * Implements hook_simple_sitemap_arbitrary_links_alter().
 */
function alshaya_image_sitemap_simple_sitemap_arbitrary_links_alter(&$arbitrary_links) {
  $url = $GLOBALS['base_url'] . '/image-sitemap';
  $arbitrary_links[] = [
    'url' => $url,
    'priority' => '0.5',
    'lastmod' => date("c"),
    'changefreq' => 'weekly',
  ];
}
