<?php

/**
 * @file
 * Primary module hooks for Alshaya Matchback module.
 */

use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_view().
 */
function alshaya_matchback_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() !== 'acq_product') {
    return;
  }
  // @todo Alter the crossel build and add the settings and libraries.
  $build['#attached']['library'][] = 'alshaya_matchback/alshaya_matchback';
  $build['#attached']['library'][] = 'alshaya_matchback/alshaya_matchback_utility';
  /** @var \Drupal\alshaya_add_to_bag\Services\AddToBagHelper $add_to_bag_helper */
  $add_to_bag_helper = \Drupal::service('alshaya_add_to_bag.helper');
  $add_to_bag_helper->setAddToBagCommonSettingsToBuild($build);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_matchback_preprocess_node(&$variables) {
  if (!($variables['node']->bundle() === 'acq_product'
    && $variables['view_mode'] === 'matchback_mobile')) {
    return;
  }

  /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
  $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
  $sku = $skuManager->getSkuForNode($variables['node']);
  $sku_entity = SKU::loadFromSku($sku);

  $variables['attributes']['data-sku_type']['#markup'] = $sku_entity->bundle();
  $variables['attributes']['data-is_buyable']['#markup'] = alshaya_acm_product_is_buyable($sku_entity)
    ? 'true'
    : 'false';
  $variables['attributes']['data-sku_type']['#markup'] = $sku_entity->bundle();

  /** @var \Drupal\alshaya_acm_product\Service\SkuInfoHelper $sku_info_helper */
  $sku_info_helper = \Drupal::service('alshaya_acm_product.sku_info');
  // @todo Find out what to do when stock is 0.
  $variables['attributes']['data-stock']['#markup'] = strval($sku_info_helper->stockInfo($sku_entity)['stock']);

  // Display add to bag button.
  $variables['content']['show_matchback_add_to_bag'] = TRUE;
}

/**
 * Implements hook_alshaya_acm_product_recommended_products_data_alter().
 */
function alshaya_matchback_alshaya_acm_product_recommended_products_data_alter(array &$data) {
  // We only want to alter the crossel products section title here.
  // The json format is used by magazine v2 layout, so we don't want to alter
  // that.
  if ($data['type'] !== 'crosssell' || $data['format'] === 'json') {
    return;
  }

  $data['data']['section_title'] = t('Frequently Bought Together', [], ['context' => 'alshaya_static_text|pdp_matchback_title']);
}
