<?php

/**
 * @file
 * Contains Hello Member related static strings.
 */

/**
 * Hello Member static strings.
 */
function _alshaya_hello_member_static_strings() {
  return [
    [
      'key' => 'membership_title',
      'value' => t('H&M Membership', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_details',
      'value' => t('You are one click away from becoming a H&M member. Get free delivery and 10% off on your first purchase.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_info_button',
      'value' => t('Continue', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_info_link',
      'value' => t('Membership info', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_terms',
      'value' => t('Terms & conditions', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_privacy',
      'value' => t('Privacy policy', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'qr_code_title',
      'value' => t('QR Code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'view_qr_code',
      'value' => t('View QR code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'qr_code_redeem',
      'value' => t('To redeem in store use this QR code.', [], ['context' => 'hello_member']),
    ],
  ];
}
