<?php

/**
 * @file
 * Contains Hello Member related static strings.
 */

/**
 * Hello Member static strings.
 */
function _alshaya_hello_member_static_strings() {
  return [
    [
      'key' => 'membership_title',
      'value' => t('Congrats!', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_sub_title',
      'value' => t('You are now a H&M member.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_details',
      'value' => t('Get free delivery and 10% off on your first purchase.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'qr_code_title',
      'value' => t('QR Code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'view_qr_code',
      'value' => t('View QR code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'qr_code_redeem',
      'value' => t('To redeem in store use this QR code.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'points_label',
      'value' => t('Points', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'hi',
      'value' => t('Hi', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'show_less',
      'value' => t('SHOW LESS', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'show_all',
      'value' => t('SHOW ALL', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'membership_renew_message',
      'value' => t('Your memership will be renewed on @expiry_date and points will be reset every year.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'earned_points',
      'value' => t('@points pt', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'purchase',
      'value' => t('Purchase', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'points_earned',
      'value' => t('Points earned', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'submit_review',
      'value' => t('Submit Rating and Review', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'profile_complete',
      'value' => t('Complete your profile', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'purchanse_message',
      'value' => t('Every time you shop online or in store, you will earn points. @currency_value @currency_code = @points_value points.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'write_review_message',
      'value' => t('Review your latest online purchase and earn @review_points points.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'profile_complete_message',
      'value' => t('Add your date of birth, Gender, Mobile Number to earn @profile_completion_value points.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'load_more',
      'value' => t('Load more', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'sent_otp_message',
      'value' => t('Please enter the OTP sent to', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'resend_otp_desc',
      'value' => t('Not recieved the code?', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'resend_code_label',
      'value' => t('Resend Code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'verify_label',
      'value' => t('Verify', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'send_otp_label',
      'value' => t('Send OTP', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'benefit_expire',
      'value' => t('Expires on @expire_date', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'benefit_add_to_bag',
      'value' => t('Add to Bag', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'member_id_title',
      'value' => t('Membership Id QR Code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'coupon_id_title',
      'value' => t('Coupon QR Code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'offer_id_title',
      'value' => t('Offer QR Code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'benefit_expire_no_date',
      'value' => t('Expires on', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'view_all_benefits',
      'value' => t('View all Benefits', [], ['context' => 'hello_member']),
    ],
  ];
}

/**
 * Hello Member aura static strings.
 */
function _alshaya_hello_member_aura_static_strings() {
  return [
    [
      'key' => 'enter_aura_details',
      'value' => t('Enter Aura Details', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_details_tooltip',
      'value' => t('Add your mobile number, Aura account number or email address below to link this purchase.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_accout_number',
      'value' => t('Aura account number', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'signup_empty_mobile',
      'value' => t('A phone number is required to sign-up. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'link_card_empty_mobile',
      'value' => t('A phone number is required to link your card. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'form_error_mobile_number',
      'value' => t('Please enter phone number.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'link_card_empty_email',
      'value' => t('An email address is required to link your card. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'form_error_email',
      'value' => t('Please enter email.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'signup_empty_email',
      'value' => t('An email address is required to sign-up. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'link_card_empty_card_number',
      'value' => t('A card number is required to link your card. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'form_error_empty_card',
      'value' => t('Please enter card number.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'something_went_wrong',
      'value' => t('Your request couldn’t be processed. Please try again shortly.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'form_error_full_name',
      'value' => t('Your full name is required to sign-up. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'mobile_label',
      'value' => t('Mobile Number', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'checkout_points_to_be_credited_message',
      'value' => t('Your points for this purchase will be added to your account.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'not_you_question',
      'value' => t('Not you?', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_partially_enrolled_message',
      'value' => t('To redeem points compelete the full enrollment.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'checkout_you_have',
      'value' => t('You have', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'redeem_points_message',
      'value' => t('Do you want to redeem Aura points?', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'redeem_points_button',
      'value' => t('Redeem Points', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'link_card_empty_mobile',
      'value' => t('A phone number is required to link your card. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'link_card_empty_email',
      'value' => t('An email address is required to link your card. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'link_card_empty_card_number',
      'value' => t('A card number is required to link your card. Please enter your details to proceed.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'mobile_not_registered',
      'value' => t('This phone number isn’t registered.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'email_not_registered',
      'value' => t('This email address isn’t registered.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'invalid_card_number',
      'value' => t('Incorrect Aura card number. Please re-enter a valid Aura card number.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'mobile_number',
      'value' => t('Mobile Number', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'email_address',
      'value' => t('E-mail address', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'country_code',
      'value' => t('Country code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'card_submit',
      'value' => t('Submit', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'form_error_invalid_otp',
      'value' => t('Incorrect OTP. Please enter a valid OTP.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'form_error_send_otp_failed_message',
      'value' => t('Error in sending OTP. Please try again.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'otp_label',
      'value' => t('One Time Pin', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_otp_sent_to_mobile',
      'value' => t('A One Time Password (OTP) has been sent to your mobile number @mobile', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'otp_label',
      'value' => t('One Time Pin', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'resend_code',
      'value' => t('Resend code', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_otp_sent_to_mobile',
      'value' => t('A One Time Password (OTP) has been sent to your mobile number @mobile', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'otp_send_message',
      'value' => t('We’ve sent the one time PIN to your mobile number.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'didnt_receive_otp_message',
      'value' => t('Didn’t receive your one time PIN?', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'send_otp_helptext',
      'value' => t('We’ll send a one time PIN to your mobile number.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'enter_otp',
      'value' => t('Enter OTP', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_points_earn_message',
      'value' => t('You will earn @points Aura points with this purchase.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'use_your_points_text',
      'value' => t('Use your points', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'checkout_use_points',
      'value' => t('Use points', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'remove',
      'value' => t('Remove', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_points_redeemed_successfully_msg',
      'value' => t('<b>@points points</b> worth <b>@currencyCode @money</b> have been successfully redeemed for this purchase', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'points_exceed_order_total',
      'value' => t('The number of points exceeds your order total. Please re-enter the number of points you’d like to redeem.'),
    ],
    [
      'key' => 'you_can_redeem_maximum',
      'value' => t('You can redeem maximum'),
    ],
    [
      'key' => 'points',
      'value' => t('points'),
    ],
    [
      'key' => 'form_error_empty_points',
      'value' => t('Please enter points.'),
    ],
  ];
}
