<?php

/**
 * @file
 * Contains Hello Member aura related static strings.
 */

/**
 * Hello Member aura static strings.
 */
function _alshaya_hello_member_aura_static_strings() {
  return [
    [
      'key' => 'enter_aura_details',
      'value' => t('Enter Aura Details', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_details_tooltip',
      'value' => t('Add your mobile number, Aura account number or email address below to link this purchase.', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'aura_accout_number',
      'value' => t('Aura account number', [], ['context' => 'hello_member']),
    ],
    [
      'key' => 'signup_empty_mobile',
      'value' => t('A phone number is required to sign-up. Please enter your details to proceed.'),
    ],
    [
      'key' => 'link_card_empty_mobile',
      'value' => t('A phone number is required to link your card. Please enter your details to proceed.'),
    ],
    [
      'key' => 'form_error_mobile_number',
      'value' => t('Please enter phone number.'),
    ],
    [
      'key' => 'link_card_empty_email',
      'value' => t('An email address is required to link your card. Please enter your details to proceed.'),
    ],
    [
      'key' => 'form_error_email',
      'value' => t('Please enter email.'),
    ],
    [
      'key' => 'signup_empty_email',
      'value' => t('An email address is required to sign-up. Please enter your details to proceed.'),
    ],
    [
      'key' => 'link_card_empty_card_number',
      'value' => t('A card number is required to link your card. Please enter your details to proceed.', [], ['context' => 'aura']),
    ],
    [
      'key' => 'form_error_empty_card',
      'value' => t('Please enter card number.'),
    ],
    [
      'key' => 'something_went_wrong',
      'value' => t('Your request couldn’t be processed. Please try again shortly.'),
    ],
    [
      'key' => 'form_error_full_name',
      'value' => t('Your full name is required to sign-up. Please enter your details to proceed.'),
    ],
    [
      'key' => 'mobile_label',
      'value' => t('Mobile Number'),
    ],
    [
      'key' => 'checkout_points_to_be_credited_message',
      'value' => t('Your points for this purchase will be added to your account.'),
    ],
    [
      'key' => 'not_you_question',
      'value' => t('Not you?'),
    ],
    [
      'key' => 'aura_partially_enrolled_message',
      'value' => t('To redeem points compelete the full enrollment.'),
    ],
    [
      'key' => 'checkout_you_have',
      'value' => t('You have'),
    ],
    [
      'key' => 'redeem_points_message',
      'value' => t('Do you want to redeem Aura points?'),
    ],
    [
      'key' => 'redeem_points_button',
      'value' => t('Redeem Points'),
    ],
  ];
}
