<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_hello_member_page_attachments_alter(array &$page) {
  /** @var \Drupal\alshaya_hello_member\Helper\HelloMemberHelper */
  $hello_member_helper = \Drupal::service('alshaya_hello_member.hello_member_helper');
  $settings['enabled'] = $hello_member_helper->isHelloMemberEnabled();
  $page['#cache']['tags'] = array_merge($page['#cache']['tags'] ?? [], \Drupal::config('alshaya_hello_member.settings')->getCacheTags());

  // Do not proceed if hello member is not enabled.
  if ($settings['enabled'] !== TRUE) {
    return;
  }

  $current_route = \Drupal::routeMatch();
  $current_route_name = $current_route->getRouteName();
  if ($current_route_name === 'entity.user.canonical') {
    $page['#attached']['library'][] = 'alshaya_hello_member/alshaya_hello_member_my_accounts';
  }
  $page['#attached']['drupalSettings']['hello_member'] = $settings;
}

/**
 * Implements hook_theme().
 */
function alshaya_hello_member_theme() {
  $theme = [
    'my_accounts_hello_member_block' => [
      'variables' => [
        'strings' => [],
      ],
    ],
  ];

  return $theme;
}
