<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_hello_member_page_attachments_alter(array &$page) {
  /** @var \Drupal\alshaya_hello_member\Helper\HelloMemberHelper */
  $hello_member_helper = \Drupal::service('alshaya_hello_member.hello_member_helper');
  $settings['enabled'] = $hello_member_helper->isHelloMemberEnabled();
  $page['#cache']['tags'] = array_merge($page['#cache']['tags'] ?? [], \Drupal::config('alshaya_hello_member.settings')->getCacheTags());

  // Do not proceed if hello member is not enabled.
  if ($settings['enabled'] !== TRUE) {
    return;
  }

  $page['#attached']['drupalSettings']['hello_member'] = $settings;
}

/**
 * Implements hook_theme().
 */
function alshaya_hello_member_theme() {
  $theme = [
    'my_accounts_hello_member_block' => [
      'variables' => [
        'strings' => [],
      ],
    ],
    'my_membership_info_block' => [
      'variables' => [
        'strings' => [],
      ],
    ],
    'my_accounts_points_history' => [
      'variables' => [
        'strings' => [],
      ],
    ],
    'hello_member_benefits_page' => [
      'variables' => [
        'strings' => [],
      ],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_hello_member_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\alshaya_hello_member\Helper\HelloMemberHelper */
  $hello_member_helper = \Drupal::service('alshaya_hello_member.hello_member_helper');
  // Only add if hello member enabled.
  if (!$hello_member_helper->isHelloMemberEnabled()) {
    return;
  }
  $form['#title'] = t('Become a Member', [], ['context' => 'hello_member']);
  $form['hello_member_sub_title'] = [
    '#weight' => -12,
    '#markup' => '<div class="section-title">' . t('Become a member — don’t miss out on deals, offers, discounts and bonus vouchers.', [], ['context' => 'hello_member']) . '</div>',
  ];
  $form['hello_member'] = [
    '#type' => 'details',
    '#title' => '<div class="hello-member-add-more">' . t('Add More & Get More', [], ['context' => 'hello_member']) . '</div>',
    '#open' => FALSE,
    '#weight' => '5',
  ];
  $form['hello_member']['teasing'] = [
    '#type' => 'markup',
    '#markup' => t('Did you know that if you add some more information below you will earn more points and get a more personalised experience? How great is that?', [], ['context' => 'hello_member']),
    '#prefix' => '<div class="hello-member-accordion-wrapper">',
  ];
  $form['hello_member']['dob'] = [
    '#title' => t('Date of birth', [], ['context' => 'hello_member']),
    '#suffix' => '<div class="hello-member-gift-info">' . t('H&M wants to give you special treat on your birthday', [], ['context' => 'hello_member']) . '</div>',
    '#type' => 'date',
    '#title_display' => 'before',
  ];
  $form['hello_member']['select'] = [
    '#type' => 'select',
    '#empty_option' => t('Select Gender', [], ['context' => 'hello_member']),
    '#options' => [
      'male' => t('Male', [], ['context' => 'hello_member']),
      'female' => t('Female', [], ['context' => 'hello_member']),
      'nosay' => t('Prefer not to say', [], ['context' => 'hello_member']),
    ],
    '#prefix' => '<div class="hello-member-gender">',
    '#suffix' => '</div>',
    '#suffix' => '</div>',
  ];
  $form['actions']['submit']['#value'] = t('Become a Member', [], ['context' => 'hello_member']);
  $form['#attached']['library'][] = 'alshaya_white_label/hello-member-registration';
  $form['#attached']['library'][] = 'alshaya_white_label/convert_to_select2';
}

/**
 * Implements hook_alshaya_my_account_links_alter().
 */
function alshaya_hello_member_alshaya_my_account_links_alter(array &$links) {
  // Do not proceed if Hello member is not enabled.
  if (!\Drupal::service('alshaya_hello_member.hello_member_helper')->isHelloMemberEnabled()) {
    return;
  }

  // Add Points history link.
  $links['hm_points_history'] = [
    'text' => t('Points History', [], ['context' => 'hello_member']),
    'route' => 'alshaya_hello_member.my_accounts.hm_points_history',
    'weight' => 41,
  ];
  $links['contact_details'] = [
    'text' => t('My Details', [], ['context' => 'hello_member']),
    'route' => 'entity.user.edit_form',
    'weight' => 30,
  ];
}

/**
 * Implements hook_alshaya_user_breadcrumb_routes_alter().
 */
function alshaya_hello_member_alshaya_user_breadcrumb_routes_alter(array &$routes) {
  $routes['alshaya_hello_member.my_accounts.hm_points_history'] = [
    'user' => \Drupal::currentUser()->id(),
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_hello_member_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\alshaya_hello_member\Helper\HelloMemberHelper */
  $hello_member_helper = \Drupal::service('alshaya_hello_member.hello_member_helper');
  // Only add if hello member enabled.
  if (!$hello_member_helper->isHelloMemberEnabled()) {
    return;
  }
  $form['#title'] = t('My Details', [], ['context' => 'hello_member']);
  $form['hello_member'] = [
    '#type' => 'details',
    '#title' => '<div class="hello-member-add-more">' . t('Add More & Get More', [], ['context' => 'hello_member']) . '</div>',
    '#open' => FALSE,
    '#weight' => '5',
  ];
  $form['hello_member']['teasing'] = [
    '#type' => 'markup',
    '#markup' => t('Did you know that if you add some more information below you will earn more points and get a more personalised experience? How great is that?', [], ['context' => 'hello_member']),
    '#prefix' => '<div class="hello-member-accordion-wrapper">',
  ];
  $form['hello_member']['dob'] = [
    '#title' => t('Date of birth', [], ['context' => 'hello_member']),
    '#suffix' => '<div class="hello-member-gift-info">' . t('H&M wants to give you special treat on your birthday', [], ['context' => 'hello_member']) . '</div>',
    '#type' => 'date',
    '#title_display' => 'before',
  ];
  $form['hello_member']['select'] = [
    '#type' => 'select',
    '#title' => t('Select Gender', [], ['context' => 'hello_member']),
    '#options' => [
      'male' => t('Male', [], ['context' => 'hello_member']),
      'female' => t('Female', [], ['context' => 'hello_member']),
      'nosay' => t('Prefer not to say', [], ['context' => 'hello_member']),
    ],
    '#prefix' => '<div class="hello-member-gender">',
    '#suffix' => '</div></div>',
  ];
}

/**
 * Implements hook_page_title().
 */
function alshaya_hello_member_preprocess_page_title(&$variables) {
  // Do not proceed if Hello member is not enabled.
  if (!\Drupal::service('alshaya_hello_member.hello_member_helper')->isHelloMemberEnabled()) {
    return;
  }

  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'entity.user.canonical') {
    $variables['title'] = t('Benefits', [], ['context' => 'hello_member']);
  }
}
