<?php

/**
 * @file
 * Install file for alshaya_ksa.
 */

/**
 * Implements hook_update_N().
 */
function alshaya_sa_update_8001() {
  // Re-install config for the override to take effect.
  alshaya_config_install_configs(['alshaya_master.mobile_number_settings'], 'alshaya_master');
}

/**
 * Implements hook_install().
 */
function alshaya_sa_install() {
  // Country code and timezone for Saudi Arabia.
  alshaya_country_set_default_regional_info('SA');
}
