<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_api module.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_install().
 */
function alshaya_api_install() {
  // Configure alshaya_api settings.
  $config = \Drupal::configFactory()->getEditable('alshaya_api.settings');

  $alshaya_api_settings = Settings::get('alshaya_api.settings');

  foreach ($alshaya_api_settings as $key => $value) {
    $config->set($key, $value);
  }

  $config->save();
}
