<?php

/**
 * @file
 * Install file.
 */

/**
 * Implements hook_modules_installed().
 */
function alshaya_captcha_modules_installed($modules) {
  $config_factory = \Drupal::configFactory();
  // Set captcha setting.
  $config_factory->getEditable('captcha.settings')->set('default_challenge', 'recaptcha/reCAPTCHA')->save();
  // Set captcha-point setting.
  $config_factory->getEditable('captcha.captcha_point.user_register_form')->set('status', TRUE)->save();
}
