<?php

/**
 * @file
 * Module file for alshaya_user.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_user_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change submit button text.
  $form['actions']['submit']['#value'] = t('Create');

  // Change email label.
  $form['account']['mail']['#title'] = t('Email address');

  // Reset help text for the fields.
  $form['account']['mail']['#description'] = '';
  $form['account']['name']['#description'] = '';
  $form['account']['pass']['#description'] = '';

  // We don't want to show the terms and conditions field to logged in users.
  if (\Drupal::currentUser()->isAuthenticated()) {
    $form['field_terms_and_condition']['#access'] = FALSE;
  }
  else {
    // Update title from description for terms and conditions field.
    $form['field_terms_and_condition']['widget']['#title'] = $form['field_terms_and_condition']['widget']['#description'];
    $form['field_terms_and_condition']['widget']['value']['#title'] = $form['field_terms_and_condition']['widget']['value']['#description'];

    // Set description to NULL for terms and conditions field.
    $form['field_terms_and_condition']['widget']['#description'] = NULL;
    $form['field_terms_and_condition']['widget']['value']['#description'] = NULL;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_user_form_user_register_form_alter(&$form, FormStateInterface $form_state) {
  // Add our custom submit handler function.
  $form['actions']['submit']['#submit'][] = 'alshaya_user_form_user_register_form_submit';
}

/**
 * Form submit callback for user registration form.
 *
 * Store the email address in session and redirect to completion page.
 */
function alshaya_user_form_user_register_form_submit($form, FormStateInterface $form_state) {
  // @TODO: I'm not sure how this will behave with varnish. It works with
  // normal Drupal cache.
  $_SESSION['alshaya_user']['last_registered_mail'] = $form_state->getValue('mail');
  return $form_state->setRedirect('alshaya_user.user_register_complete');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_user_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add forgot password link.
  $form['account']['forgot_password'] = [
    '#markup' => Link::createFromRoute(t('Forgot password'), 'user.pass')->toString(),
  ];

  // Change submit button text.
  $form['actions']['submit']['#value'] = t('sign in');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_user_form_user_pass_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['forgot_text'] = [
    '#markup' => t('Please enter your email address.') . '</br>' . t('We will send you an email with a password reminder.'),
    '#weight' => -10,
  ];
}
