<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function alshaya_checkout_tracker_theme() {
  $theme = [
    'checkout_tracker_block' => [
      'variables' => [
        'stepMap' => [],
        'activeMapKey' => [],
      ],
      'template' => 'checkout-tracker-block',
    ],
  ];

  return $theme;
}

/**
 * Implements hook_page_title().
 */
function alshaya_checkout_tracker_preprocess_page_title(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (in_array($route_name, [
    'acq_cart.cart',
    'alshaya_spc.checkout.login',
    'alshaya_spc.checkout',
    'alshaya_spc.checkout.confirmation',
  ])) {
    unset($variables['title']);
  }
}
