<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function alshaya_checkout_tracker_theme() {
  $theme = [
    'checkout_tracker_block' => [
      'variables' => [
        'stepMap' => [],
        'activeMapKey' => [],
      ],
      'template' => 'checkout-tracker-block',
    ],
  ];

  return $theme;
}

/**
 * Implements hook_page_title().
 */
function alshaya_checkout_tracker_preprocess_page_title(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $checkoutTrackerSettings = \Drupal::service('alshaya_checkout_tracker.checkout_tracker_helper');
  if ($checkoutTrackerSettings->isCheckoutTrackerEnabled() && in_array($route_name, [
    'acq_cart.cart',
    'alshaya_spc.checkout.login',
    'alshaya_spc.checkout',
    'alshaya_spc.checkout.confirmation',
  ])) {
    unset($variables['title']);
  }
}

/**
 * Implements hook_alshaya_spc_cart_build_alter().
 */
function alshaya_checkout_tracker_alshaya_spc_cart_build_alter(array &$build) {
  $checkoutTrackerSettings = \Drupal::service('alshaya_checkout_tracker.checkout_tracker_helper');
  // Add Checkout tracker settings in drupalSettings.
  $build['#attached']['drupalSettings']['checkoutTracker']['enabled'] = $checkoutTrackerSettings->isCheckoutTrackerEnabled();
  $build['#cache']['tags'] = array_merge($build['#cache']['tags'] ?? [], $checkoutTrackerSettings->getCacheTags());
}
