<?php

/**
 * @file
 * Module file for RCS Placeholders.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;
use Drupal\Core\Session\AccountInterface;
use Drupal\rcs_placeholders\Graphql\ArrayGraphQL;
use Drupal\rcs_placeholders\Service\RcsPhPathProcessor;

/**
 * Implements hook_theme().
 */
function rcs_placeholders_theme($existing, $type, $theme, $path) {
  return [
    'taxonomy_term__rcs_category' => [
      'variables' => [],
    ],
    'node__rcs_product' => [
      // Need this so that the node preprocess hooks get executed.
      'base hook' => 'node',
      'variables' => [],
    ],
    // A generic field template to render fields as placeholder blocks.
    'field__rcs_placeholder_block' => [
      'variables' => [
        'items' => [],
        'content_attributes' => [],
        'title' => NULL,
        'label_display' => NULL,
        'language' => NULL,
        'field_name' => NULL,
        'field_type' => NULL,
        'field_translatable' => NULL,
        'entity_type' => NULL,
        'bundle' => NULL,
        'object' => NULL,
        'formatter' => NULL,
        'is_multiple' => NULL,
        'third_party_settings' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_field__rcs_placeholder_block().
 */
function rcs_placeholders_preprocess_field__rcs_placeholder_block(&$variables) {
  $variables['label'] = $variables['title'];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function rcs_placeholders_preprocess_html(&$variables) {
  $config = \Drupal::config('rcs_placeholders.settings');

  // Attach required JS. We must be cautious to only add new values or replace
  // on purpose as some previous hooks may have already set some values.
  $variables['#attached']['library'][] = 'rcs_placeholders/rcs_placeholders';
  $variables['#attached']['drupalSettings']['rcsPhSettings']['categoryPathPrefix'] = $config->get('category.path_prefix');
  $variables['#attached']['drupalSettings']['rcsPhSettings']['productPathPrefix'] = $config->get('product.path_prefix');

  // Attach additional JS settings based on the current page type and
  // enrichment.
  if (!empty(RcsPhPathProcessor::$entityType)) {
    $variables['#attached']['drupalSettings']['rcsPage']['type'] = RcsPhPathProcessor::$entityType;
    $variables['#attached']['drupalSettings']['rcsPage']['urlKey'] = RcsPhPathProcessor::getUrlKey();
    $variables['#attached']['drupalSettings']['rcsPage']['fullPath'] = RcsPhPathProcessor::getFullPath();

    if ($config->get(RcsPhPathProcessor::$entityType . '.enrichment')) {
      $variables['#attached']['drupalSettings']['rcsPage']['enrichment'] = RcsPhPathProcessor::$entityData;
    }
  }

  // We need to override default cache context as we use the placeholder term
  // for different categories.
  $variables['#cache']['contexts'][] = 'url';

  // Add page type to node markup to be able to do the initial skeleton.
  $variables['attributes']['class'][] = 'rcs-page';
  $variables['attributes']['class'][] = 'page-type-' . RcsPhPathProcessor::$entityType;
}

/**
 * Implements hook_preprocess_node().
 */
function rcs_placeholders_preprocess_node(&$variables) {
  if ($variables['node']->bundle() !== 'rcs_product') {
    return;
  }

  $config = \Drupal::config('rcs_placeholders.settings');

  switch ($variables['view_mode']) {
    case 'full':
      $token = '#rcs.product.slug#';

      $variables['#cache']['contexts'][] = 'url';

      // Add list cache tag for nodes for which we do not have any enrichment
      // yet.
      if ($variables['node']->id() === $config->get('product.placeholder_nid')) {
        $variables['#cache']['tags'][] = 'node_list';
      }

      break;

    default:
      $token = '#rcs.productItem.slug#';
      break;
  }

  // RDF module is adding an "about" attribute based on the "url" variable.
  // If we don't set it, all the products will have "node/1" as "about".
  $variables['url'] = '/' . $config->get('product.path_prefix') . $token;
}

/**
 * Implements hook_preprocess_taxonomy_term().
 */
function rcs_placeholders_preprocess_taxonomy_term(&$variables) {
  if ($variables['term']->bundle() !== 'rcs_category') {
    return;
  }

  $config = \Drupal::config('rcs_placeholders.settings');

  // RDF module is adding an "about" attribute based on the "url" variable.
  // If we don't set it, all the categories will have "taxonomy/term/1" as
  // "about".
  $variables['url'] = '/' . $config->get('category.path_prefix') . '#rcs.category.slug#';

  $variables['#cache']['contexts'][] = 'url';

  // Add list cache tag for terms for which we do not have any enrichment yet.
  if ($variables['term']->id() === $config->get('category.placeholder_tid')) {
    $variables['#cache']['tags'][] = 'taxonomy_term_list';
  }
}

/**
 * Wrapper function to get template for view mode of specific entity type.
 *
 * @param string $entity_type
 *   Entity Type.
 * @param string $view_mode
 *   View Mode.
 *
 * @return string|null
 *   Rendered entity template if entity type supported.
 */
function _rcs_placeholders_get_placeholder_entity_view(string $entity_type, string $view_mode) {
  /** @var \Drupal\rcs_placeholders\Service\RcsPhEntityHelper $helper */
  $helper = \Drupal::service('rcs_placeholders.entity_helper');
  return $helper->getRcsPhEntityView($entity_type, $view_mode);
}

/**
 * Implements hook_page_attachments().
 */
function rcs_placeholders_page_attachments(array &$attachments) {
  // These are the attributes that will be processed for replacement of tokens.
  // Use hook_page_attachments_alter() to add/remove attributes in this list.
  $attachments['#attached']['drupalSettings']['rcsPhSettings'] = [];

  $attributes = [
    'href',
    'src',
    'alt',
    'about',
    'content',
    'title',
    'class',
    'name',
    'id',
    'value',
  ];

  $attachments['#attached']['drupalSettings']['rcsPhSettings']['placeholderAttributes'] = $attributes;
}

/**
 * Clear route cache after enriched entity is created or deleted.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity object.
 */
function _rcs_placeholders_clear_route_cache(EntityInterface $entity) {
  if (($entity->getEntityTypeId() === 'taxonomy_term' && $entity->bundle() === 'rcs_category')
    || ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'rcs_product')) {
    Cache::invalidateTags(['4xx-response', 'route_match', 'http_response']);
  }
}

/**
 * Implements hook_entity_insert().
 */
function rcs_placeholders_entity_insert(EntityInterface $entity) {
  _rcs_placeholders_clear_route_cache($entity);
}

/**
 * Implements hook_entity_delete().
 */
function rcs_placeholders_entity_delete(EntityInterface $entity) {
  _rcs_placeholders_clear_route_cache($entity);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function rcs_placeholders_menu_local_tasks_alter(&$data, $route_name) {
  $config = \Drupal::config('rcs_placeholders.settings');

  $node = \Drupal::routeMatch()->getParameter('node');
  $term = \Drupal::routeMatch()->getParameter('taxonomy_term');

  // We only alter the links for the products and categories.
  if ((!$node || $node->bundle() !== 'rcs_product') && (!$term || $term->bundle() !== 'rcs_category')) {
    return;
  }

  $entity_type = $node ? 'node' : 'taxonomy_term';

  if (isset($data['tabs'][0]['entity.' . $entity_type . '.edit_form'])) {
    $edit_tab = &$data['tabs'][0]['entity.' . $entity_type . '.edit_form'];
  }
  else {
    $edit_tab = NULL;
  }

  // If the entity is enriched, we only alter the tabs label.
  if (($node && $node->nid->value !== $config->get('product.placeholder_nid')) || ($term && $term->tid->value !== $config->get('category.placeholder_tid'))) {
    if ($edit_tab) {
      $edit_tab['#link']['title'] = t('Edit the enrichment');
    }
    if (isset($data['tabs'][0]['entity.' . $entity_type . '.delete_form'])) {
      $data['tabs'][0]['entity.' . $entity_type . '.delete_form']['#link']['title'] = t('Delete the enrichment');
    }
  }
  // If the entity is not enriched, alter the tabs links.
  else {
    // We don't want the contributors to delete the default placeholder entity.
    unset($data['tabs'][0]['entity.' . $entity_type . '.delete_form']);

    // We alter the edit link so it actually redirects to the entity add form
    // with the title and slug as query arguments. We need to build the url
    // that way because using query options of url methods is encoding the #
    // and so the placeholders are not replaced on the frontend.
    if ($node) {
      $url = Url::fromUserInput('/node/add/rcs_product?title=#rcs.product.name#&slug=' . $config->get('product.path_prefix') . '#rcs.product.slug#');
    }
    else {
      $url = Url::fromUserInput('/admin/structure/taxonomy/manage/rcs_category/add?name=#rcs.category.name#&slug=' . $config->get('category.path_prefix') . '#rcs.category.slug#');
    }

    if ($edit_tab) {
      $edit_tab['#link']['url'] = $url;
      $edit_tab['#link']['title'] = t('Enrich');
    }
  }
}

/**
 * Helper function to alter both product and category forms.
 *
 * @param array $form
 *   Form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form State.
 */
function _rcs_placeholders_enrichment_form_alter(array &$form, FormStateInterface $form_state) {
  $entity = $form_state->getFormObject()->getEntity();

  // We only alter the form for new product/category.
  if (!$entity->isNew()) {
    return;
  }

  // @todo Check if need to secure the $q values.
  // Assuming it is safe for now as it is only accessible to contributors.
  $q = \Drupal::request()->query->all();

  // @todo We may want to determine the title/name field using an entity
  // method.
  $title_field = $entity->getEntityTypeId() == 'node' ? 'title' : 'name';
  $slug_field = $entity->getEntityTypeId() == 'node' ? 'field_product_slug' : 'field_category_slug';

  // Pre-fill the title and slug fields with values from the query.
  if (isset($q[$title_field])) {
    $form[$title_field]['widget'][0]['value']['#default_value'] = $q[$title_field];
  }
  if (isset($q['slug'])) {
    $form[$slug_field]['widget'][0]['value']['#default_value'] = $q['slug'];
  }
}

/**
 * Implements hook_form_taxonomy_term_VOCABULARY_form_alter().
 */
function rcs_placeholders_form_taxonomy_term_rcs_category_form_alter(&$form, FormStateInterface $form_state) {
  _rcs_placeholders_enrichment_form_alter($form, $form_state);
}

/**
 * Implements hook_form_node_NODE_TYPE_form_alter().
 */
function rcs_placeholders_form_node_rcs_product_form_alter(&$form, FormStateInterface $form_state) {
  _rcs_placeholders_enrichment_form_alter($form, $form_state);
}

/**
 * Implements hook_block_access().
 */
function rcs_placeholders_block_access(Block $block, $operation, AccountInterface $account) {
  // We only want to alter the access rule for the breadcrumb blocks.
  if ($operation !== 'view'
    || !in_array($block->getPluginId(), [
      'system_breadcrumb_block',
      'rcs_ph_breadcrumb',
    ])
  ) {
    return AccessResult::neutral();
  }

  $route_name = \Drupal::routeMatch()->getRouteName();

  $entity = FALSE;
  if ($route_name == 'entity.taxonomy_term.canonical') {
    $entity = \Drupal::routeMatch()->getParameter('taxonomy_term');
  }
  elseif ($route_name == 'entity.node.canonical') {
    $entity = \Drupal::routeMatch()->getParameter('node');
  }

  $rcs_entity = $entity
    && in_array($entity->bundle(), [
      'rcs_category',
      'rcs_product',
      'rcs_promotion',
    ]);

  // We don't want to display the default breadcrumb on PLP/PDP.
  if ($rcs_entity && $block->getPluginId() === 'system_breadcrumb_block') {
    return AccessResult::forbidden();
  }

  // We don't want to display the "placeholder" breadcrumb outside PLP/PDP.
  if (!$rcs_entity && $block->getPluginId() === 'rcs_ph_breadcrumb') {
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_language_switch_links_alter().
 */
function rcs_placeholders_language_switch_links_alter(array &$links, $type, Url $url) {
  if (empty(RcsPhPathProcessor::$entityType)) {
    return;
  }

  foreach (\Drupal::languageManager()->getLanguages() as $language) {
    $url = Url::fromRoute(
      '<front>',
      [],
      ['absolute' => TRUE, 'language' => $language]
    )->toString();

    // Add the URL as is, RCS expects the URL to be same in all languages.
    $url .= RcsPhPathProcessor::getFullPath(FALSE);

    // We use absolute url below to make sure Drupal does not modify it.
    $links[$language->getId()]['url'] = Url::fromUri($url);
  }
}

/**
 * Implements hook_page_bottom().
 */
function rcs_placeholders_page_bottom(array &$page_bottom) {
  // Skip some special routes which are marked as admin_route but that
  // can be accessed by non-admin users as well.
  if (\Drupal::service('router.admin_context')->isAdminRoute()
    && !in_array(\Drupal::routeMatch()->getRouteName(), [
      'change_pwd_page.change_password_form',
      'entity.user.edit_form',
    ])) {
    return;
  }

  // Invoke hook to get default values.
  $queries = \Drupal::moduleHandler()->invokeAll('rcs_placeholders_graphql_query');

  // Allow other modules to alter the data.
  \Drupal::moduleHandler()->alter('rcs_placeholders_graphql_query', $queries);

  // Store cache data an unset in original array so that no further processing
  // for it occurs in the array.
  $cache_meta_data = $queries['#cache'] ?? [];
  unset($queries['#cache']);

  // Convert array to graphql.
  foreach ($queries as $query => $fields) {
    $queries[$query] = ArrayGraphQL::convert($fields);
  }

  // Add inline script to the page bottom.
  $page_bottom['rcs_placeholders_graphql_query'] = [
    '#type'  => 'html_tag',
    '#tag'   => 'script',
    '#value' => Markup::create('var rcsPhGraphqlQuery = ' . json_encode($queries) . ';'),
    '#cache' => $cache_meta_data,
  ];
}
