<?php

/**
 * @file
 * Module file for alshaya_social_google.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_social_google_preprocess_alshaya_social(&$variables) {
  if (!isset($variables['social_networks']['social_auth_google'])) {
    return;
  }
  $route = \Drupal::routeMatch();
  $link_texts = [
    'user.login' => t('sign in with google'),
    'user.register' => t('sign up with google'),
  ];
  if (in_array($route->getRouteName(), ['user.login', 'acq_checkout.form'])) {
    $variables['social_networks']['social_auth_google']['text_link'] = $link_texts['user.login'];
  }
  elseif ($route->getRouteName() == 'user.register') {
    $variables['social_networks']['social_auth_google']['text_link'] = $link_texts['user.register'];
  }
}
