<?php

/**
 * @file
 * Module file for alshaya_social_google.
 */

/**
 * Implements hook_alshaya_social_SOICAL_NETWORK_alter().
 */
function alshaya_social_google_alshaya_social_social_auth_google_alter(&$network, $route_name) {
  $login_paths = in_array($route_name, [
    'user.login',
    'acq_checkout.form',
    'alshaya_spc.login',
  ]);
  $network['text_link'] = $login_paths
    ? t('sign in with Google')
    : t('sign up with Google');
}
