<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_pb_transac_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product') {
    /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
    $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
    $sku = $skuManager->getSkuForNode($entity);
    $sku_entity = SKU::loadFromSku($sku);

    if ($sku_entity instanceof SKU && $view_mode == 'full') {
      /** @var \Drupal\alshaya_acm_product\ProductHelper $productHelper */
      $productHelper = \Drupal::service('alshaya_acm_product.helper');

      $description = [];

      if ($body = $entity->get('body')->getValue()) {
        $description['value'] = [
          '#markup' => $body[0]['value'],
        ];

        $build['description'][] = $description;

        $productHelper->updateShortDescription($build, $body[0]['value']);

        if (!empty($build['short_desc'])) {
          $build['short_desc']['value']['#markup'] = $productHelper->processShortDescEllipsis($build['short_desc']['value']['#markup']);
        }
      }

      $product_info = $sku_entity->get('attr_short_description')->getValue();
      if (!empty($product_info) && !empty($product_info[0]['value'])) {
        $build['dimensions_and_care'] = [
          '#theme' => 'pdp_description_accordion',
          '#title' => t('Dimensions and Care'),
          '#class' => 'dimensions-and-care',
          '#text' => [
            '#markup' => $product_info[0]['value'],
          ],
        ];
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_pb_transac_acq_sku_view(array &$build, EntityInterface $sku_entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'modal') {
    /** @var \Drupal\alshaya_acm_product\ProductHelper $productHelper */
    $productHelper = \Drupal::service('alshaya_acm_product.helper');

    $body = $sku_entity->get('attr_description')->getValue();
    if ($body) {
      $description['value'] = [
        '#markup' => $body[0]['value'],
      ];
      $build['description'][] = $description;
      $productHelper->updateShortDescription($build, $body[0]['value']);
    }
  }
}

/**
 * Implements template_preprocess_alshaya_cart_product_name().
 */
function alshaya_pb_transac_preprocess_alshaya_cart_product_name(&$variables) {
  if (empty($variables['item_code'])) {
    return;
  }

  $sku = SKU::loadFromSku($variables['item_code']);

  if (!($sku instanceof SKU)) {
    return;
  }

  /** @var \Drupal\acq_sku\ProductInfoHelper $productInfoHelper */
  $productInfoHelper = \Drupal::service('acq_sku.product_info_helper');
  $title = $productInfoHelper->getTitle($sku, 'basket');
  // Use title of child product in cart only for PB.
  if ($title) {
    isset($variables['name']['#title']) ? $variables['name']['#title'] = $title : $variables['name'] = $title;
  }
}

/**
 * Implements hook_alshaya_acm_product_build_alter().
 */
function alshaya_pb_transac_alshaya_acm_product_build_alter(&$build, SKUInterface $sku, $context = 'pdp') {
  if ($context == 'search') {
    /** @var \Drupal\alshaya_acm_product\ProductHelper $productHelper */
    $productHelper = \Drupal::service('alshaya_acm_product.helper');
    // Display swatches on PLP/Search/Promo. We use sku gallery formatter for
    // all these cases and context received here is 'search' for that.
    $productHelper->updateSwatches($build, $sku);
  }
}

/**
 * Implements hook_alshaya_search_facet_price_alter().
 */
function alshaya_pb_transac_alshaya_search_facet_price_alter($range, &$displayValue) {
  // Fetch the config.
  $config = \Drupal::configFactory()->get('acq_commerce.currency');

  // Remove decimal points from price block filter.
  $displayValue = str_replace('.' . str_repeat('0', $config->get('decimal_points')), '', $displayValue);
}
