<?php

/**
 * @file
 * Alshaya PotteryBarn Transac module file.
 */

/**
 * Implements hook_alshaya_performance_preload_alter().
 */
function alshaya_pb_transac_alshaya_performance_preload_alter(array &$preload) {
  $themeHandler = \Drupal::service('theme_handler');
  $themePath = $themeHandler->getTheme($themeHandler->getDefault())->getPath();
  $fonts_directory_path = '/' . $themePath . '/fonts';

  $preload[] = [
    'as' => 'style',
    'href' => $fonts_directory_path . '/alshaya-icons.woff2?3ajdhs',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff2',
  ];
}
