<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_tabby_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() != 'acq_product') {
    return;
  }

  // Need processing only for products with Full, Modal, Matchback view mode.
  if (in_array($view_mode, ['full', 'modal', 'matchback'])) {
    /** @var \Drupal\alshaya_tabby\AlshayaTabbyWidgetHelper $alshayaTabbyHelper */
    $alshayaTabbyHelper = \Drupal::service('alshaya_tabby.widget_helper');
    $alshayaTabbyHelper->getTabbyPaymentBuild($build);
  }
}
