<?php

/**
 * @file
 * Module file for alshaya_social.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function alshaya_social_theme() {
  return [
    'alshaya_social' => [
      'variables' => [
        'social_networks' => NULL,
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function alshaya_social_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['user_register_form', 'user_login_form'])) {
    alshaya_social_display_social_authentication_links($form, $form_id);
  }
}

/**
 * Implements hook_checkout_login_alter().
 */
function alshaya_social_checkout_login_alter(array &$pane_form, $form_state, $complete_form) {
  alshaya_social_display_social_authentication_links($pane_form, 'user_login_form');
}

/**
 * Helper class to add social auth links to given form.
 *
 * @param array $form
 *   The array of form elements.
 * @param string $form_id
 *   The current form id.
 */
function alshaya_social_display_social_authentication_links(array &$form, $form_id) {
  if (
    \Drupal::configFactory()->get('alshaya_social.settings')->get('social_login')
    && !empty($social_networks = \Drupal::configFactory()->get('social_auth.settings')->get('auth'))
  ) {
    $form['#attributes']['class'][] = 'social-signup-form';
    $form['social_media_auth_links'] = [
      '#theme' => 'alshaya_social',
      '#social_networks' => $social_networks,
      '#form' => $form_id,
      '#weight' => 1000,
    ];
    $form['#cache']['tags'][] = 'config:alshaya_social.settings';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_social_form_alshaya_user_settings_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['social'] = [
    '#type' => 'details',
    '#title' => t('Social authentication settings'),
    '#open' => TRUE,
    '#tree' => FALSE,
  ];

  $form['social']['social_login'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable social login.'),
    '#default_value' => \Drupal::configFactory()->get('alshaya_social.settings')->get('social_login'),
  ];

  array_unshift($form['#submit'], 'alshaya_social_user_settings_submit');
}

/**
 * Submit callback for alshaya_user_settings form.
 */
function alshaya_social_user_settings_submit(array &$form, FormStateInterface $form_state) {
  \Drupal::configFactory()
    ->getEditable('alshaya_social.settings')
    ->set('social_login', (bool) $form_state->getValue('social_login'))
    ->save();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_social_preprocess_alshaya_social(&$variables) {
  $variables['base_path'] = base_path();
}
