<?php

/**
 * @file
 * Module file for alshaya_social.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function alshaya_social_theme() {
  return [
    'alshaya_social' => [
      'variables' => [
        'social_networks' => NULL,
        'form' => NULL,
        'section_title' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_social_form_user_login_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['alshaya_social_login_form_title'] = [
    '#weight' => -10,
    '#markup' => '<div class="section-title">' . t('Sign in with email address') . '</div>',
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_social_form_user_register_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['alshaya_social_register_form_title'] = [
    '#weight' => -10,
    '#markup' => '<div class="section-title">' . t('Sign up with email address') . '</div>',
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_social_form_alshaya_user_settings_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['social'] = [
    '#type' => 'details',
    '#title' => t('Social authentication settings'),
    '#open' => TRUE,
    '#tree' => FALSE,
  ];

  $form['social']['social_login'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable social login.'),
    '#default_value' => \Drupal::configFactory()->get('alshaya_social.settings')->get('social_login'),
  ];

  array_unshift($form['#submit'], 'alshaya_social_user_settings_submit');
}

/**
 * Submit callback for alshaya_user_settings form.
 */
function alshaya_social_user_settings_submit(array &$form, FormStateInterface $form_state) {
  \Drupal::configFactory()
    ->getEditable('alshaya_social.settings')
    ->set('social_login', (bool) $form_state->getValue('social_login'))
    ->save();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_social_preprocess_alshaya_social(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'acq_checkout.form') {
    $variables['destination'] = Url::fromRoute('acq_checkout.form', ['step' => 'delivery'])->toString();
  }

  $variables['base_path'] = base_path();
}
