<?php

/**
 * @file
 * Module file for alshaya_social_facebook.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_social_facebook_preprocess_alshaya_social(&$variables) {
  $routmatch = \Drupal::routeMatch();
  if ($routmatch->getRouteName() === 'user.login' && isset($variables['social_networks']['social_auth_facebook'])) {
    $variables['social_networks']['social_auth_facebook']['text_link'] = t('Sign in with facebook');
  }
  elseif ($routmatch->getRouteName() === 'user.register' && isset($variables['social_networks']['social_auth_facebook'])) {
    $variables['social_networks']['social_auth_facebook']['text_link'] = t('Sign up with facebook');
  }
}
