<?php

/**
 * @file
 * Module file for alshaya_social_facebook.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_social_facebook_preprocess_alshaya_social(&$variables) {
  if (!isset($variables['social_networks']['social_auth_facebook'])) {
    return;
  }

  $link_texts = [
    'user.login' => t('sign in with facebook'),
    'user.register' => t('sign up with facebook'),
  ];
  $routmatch = \Drupal::routeMatch();
  if (in_array($routmatch->getRouteName(), array_keys($link_texts))) {
    $variables['social_networks']['social_auth_facebook']['text_link'] = $link_texts[$routmatch->getRouteName()];
  }
}
