<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_rcs_magazine_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if (($entity->bundle() == 'magazine_article')) {
    $build['#attached']['library'][] = 'alshaya_rcs_magazine/main';
  }
}

/**
 * Implements hook_rcs_handlebars_templates_alter().
 */
function alshaya_rcs_magazine_rcs_handlebars_templates_alter(&$templates, $entity) {
  if (!$entity || $entity->bundle() !== 'magazine_article') {
    return;
  }

  // Provide template for product teaser.
  $path = drupal_get_path('module', 'alshaya_rcs_magazine');
  $templates['field']['magazine_article'] = [
    'product_teaser' => "$path/templates/product-teaser.handlebars",
  ];
}

/**
 * Implements hook_rcs_placeholders_graphql_query_alter().
 */
function alshaya_rcs_magazine_rcs_placeholders_graphql_query_alter(&$queries) {
  // Add media fields.
  array_push($queries['products']['items'],
    'asset_ids',
    'asset_type',
    'assets_pdp',
    'assets_cart',
    'assets_swatch',
    'assets_teaser',
  );

  $queries['products']['items']['... on ConfigurableProduct'] = [
    'variants' => [
      'product' => [
        'asset_ids',
        'asset_type',
        'assets_pdp',
        'assets_plp',
        'assets_cart',
        'assets_swatch',
        'assets_teaser',
        'rgb_color',
        'color',
        'swatch_image',
      ]
    ]
  ];
}
