<?php

/**
 * @file
 * Install file for alshaya_non_transac_product module.
 */

/**
 * Implements hook_install().
 */
function alshaya_non_transac_product_install() {
  // Entity is not updated with translations and throws error while creating
  // the content. Solution is implemnted from
  // https://www.drupal.org/node/2599228#comment-11224143.
  // Ensure the translation fields are created in the database.
  \Drupal::service('entity.definition_update_manager')->applyUpdates();
}
