<?php

/**
 * @file
 * Module file for alshaya_eg.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_element_info_alter().
 */
function alshaya_eg_element_info_alter(array &$info) {
  if (isset($info['address']['#process'])) {
    $info['address']['#process'][] = '_alshaya_eg_country_process';
  }
}

/**
 * Processor for the country in address field.
 */
function _alshaya_eg_country_process(array &$element, FormStateInterface $form_state) {
  // Validation for postal code.
  $element['postal_code']['#element_validate'][] = '_alshaya_eg_postalcode_validate';

  $element['postal_code']['#required'] = TRUE;

  return $element;
}

/**
 * Adding validation for the postal code.
 */
function _alshaya_eg_postalcode_validate($element, FormStateInterface $form_state) {
  $postal_code = $element['#default_value'];
  if (!empty($postal_code) && _alshaya_custom_get_site_level_country_code() == 'EG' && !preg_match('/^[0-9]{5}$/', $postal_code)) {
    $form_state->setError($element, t('@postalcode field is not in the right format', ['@postalcode' => 'Postal code']));
  }
}
