<?php

use Drupal\acq_cart\Entity\Order;
use Drupal\acq_cart\Entity\LineItem;
use Drupal\acq_product\Entity\Product;

/**
 * @file
 * Provides base hooks to the cart functionality of Acquia Commerce connector.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function acq_cart_preprocess_acq_sku(&$variables) {
  // We would rather allow modules to implement the preprocess hook directly,
  // however the main issue there is that we can't disable cart separately so
  // we provide a hook that's only called if this module is enabled on display.
  \Drupal::moduleHandler()->alter('add_to_cart_display', $variables);
}
