<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\user\Entity\User;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_addressbook_form_profile_address_book_add_form_alter(array &$form, FormStateInterface $form_state) {
  $user_id = \Drupal::currentUser()->getAccount()->id();
  /* @var \Drupal\user\Entity\User $user */
  $user = User::load($user_id);
  /** @var \Drupal\profile\Entity\ProfileInterface|bool $default_address */
  $default_address = \Drupal::entityTypeManager()->getStorage('profile')
    ->loadByUser($user, 'address_book');

  // If user doesn't have any default address yet.
  if (!$default_address) {
    $form['actions']['submit']['#access'] = FALSE;
  }

  // Get the default country from 'admin/config/regional/settings' site
  // regional settings.
  $default_site_country = _alshaya_custom_get_site_level_country_code();

  // Set the default country.
  $form['field_address']['widget'][0]['address']['#default_value']['country_code'] = $default_site_country;
}

/**
 * Processor for the country in address field.
 */
function _alshaya_addressbook_country_process(array &$element, FormStateInterface $form_state) {
  $default_country_code = $element['#default_value']['country_code'];
  $element['country_code'] = [
    '#type' => 'hidden',
    '#value' => $default_country_code,
  ];
  return $element;
}

/**
 * Implements hook_element_info_alter().
 */
function alshaya_addressbook_element_info_alter(array &$info) {
  if (isset($info['address']['#process'])) {
    $info['address']['#process'][] = '_alshaya_addressbook_country_process';
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function alshaya_addressbook_profile_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // If the address is default address, not allow user to delete it.
  if ($operation == 'delete' && $entity->getType() == 'address_book') {
    if ($entity->isDefault() && $entity->getOwnerId() == $account->id()) {
      return AccessResult::forbidden();
    }
  }
}

/**
 * Implements hook_user_view_alter().
 */
function alshaya_addressbook_user_view_alter(&$build) {
  // Remove/Hide the 'address_book' info on 'user/uid' page.
  if (isset($build['profile_address_book'])) {
    unset($build['profile_address_book']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_addressbook_form_profile_address_book_edit_form_alter(array &$form, FormStateInterface $form_state) {
  $form['#title'] = t('Edit address');
}

/**
 * Implements hook_entity_type_alter().
 */
function alshaya_addressbook_entity_type_alter(array &$entity_types) {
  /* @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['profile']->setFormClass('delete', 'Drupal\alshaya_addressbook\Form\AlshayaProfileDeleteForm');
  $entity_types['profile']->setFormClass('add', 'Drupal\alshaya_addressbook\Form\AlshayaProfileForm');
  $entity_types['profile']->setFormClass('edit', 'Drupal\alshaya_addressbook\Form\AlshayaProfileForm');
}
