<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\RedirectCommand;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\user\Entity\User;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_addressbook_form_profile_address_book_add_form_alter(array &$form, FormStateInterface $form_state) {
  $user_id = \Drupal::currentUser()->getAccount()->id();
  /* @var \Drupal\user\Entity\User $user */
  $user = User::load($user_id);
  /** @var \Drupal\profile\Entity\ProfileInterface|bool $default_address */
  $default_address = \Drupal::entityTypeManager()->getStorage('profile')
    ->loadByUser($user, 'address_book');

  $form['#prefix'] = '<div id="address-book-form-open">';
  $form['#suffix'] = '</div>';

  // If user doesn't have any default address yet.
  if (!$default_address) {
    $form['actions']['submit']['#access'] = FALSE;
    $form['actions']['set_default']['#value'] = t('add address');
  }
  else {
    $form['actions']['set_default']['#access'] = FALSE;
    $form['actions']['submit']['#value'] = t('add address');
    $form['actions']['submit']['#ajax'] = [
      'callback' => 'alshaya_addressbook_save_ajax_callback',
      'wrapper' => 'address-book-form-open',
    ];
  }

  // Get the default country from 'admin/config/regional/settings' site
  // regional settings.
  $default_site_country = _alshaya_custom_get_site_level_country_code();

  // Set the default country.
  $form['field_address']['widget'][0]['address']['#default_value']['country_code'] = $default_site_country;

  // Alter the profile add form.
  _alshaya_addressbook_form_alter($form, $form_state);
}

/**
 * Submit Ajax callback to reload the page.
 */
function alshaya_addressbook_save_ajax_callback(&$form, FormStateInterface $form_state) {
  if (!$form_state->getErrors()) {
    $entity   = $form_state->getFormObject()->getEntity();
    $response = new AjaxResponse();
    $response->addCommand(new RedirectCommand(Url::fromRoute('entity.profile.type.address_book.user_profile_form', [
      'user'         => $entity->getOwnerId(),
      'profile_type' => $entity->bundle(),
    ])->toString()));
    return $response;
  }

  return $form;
}

/**
 * Processor for the country in address field.
 */
function _alshaya_addressbook_country_process(array &$element, FormStateInterface $form_state) {
  $default_country_code = $element['#default_value']['country_code'];
  $element['country_code'] = [
    '#type' => 'hidden',
    '#value' => $default_country_code,
  ];

  // Validation for first and last name.
  $element['given_name']['#element_validate'][] = '_alshaya_addressbook_firstname_validate';
  $element['given_name']['#maxlength'] = 255;
  $element['family_name']['#element_validate'][] = '_alshaya_addressbook_lastname_validate';
  $element['family_name']['#maxlength'] = 255;
  return $element;
}

/**
 * Validation for first name.
 */
function _alshaya_addressbook_firstname_validate(array &$element, FormStateInterface $form_state) {
  _alshaya_addressbook_name_validation($element, $form_state, 'given_name');
}

/**
 * Validation for the last name.
 */
function _alshaya_addressbook_lastname_validate(array &$element, FormStateInterface $form_state) {
  _alshaya_addressbook_name_validation($element, $form_state, 'family_name');
}

/**
 * Adding validation for the name.
 */
function _alshaya_addressbook_name_validation(array &$element, FormStateInterface $form_state, $field_name) {
  $string = $form_state->getValue('field_address')[0]['address'][$field_name];
  if (preg_match('/[#$\_\!@%^&*()+=\-\[\]\';,.\/{}|":<>?~\\\\]/', $string)) {
    $field_name = $field_name == 'given_name' ? 'first name' : 'last name';
    $form_state->setError($element, t('Invalid @name', ['@name' => $field_name]));
  }
}

/**
 * Implements hook_element_info_alter().
 */
function alshaya_addressbook_element_info_alter(array &$info) {
  if (isset($info['address']['#process'])) {
    $info['address']['#process'][] = '_alshaya_addressbook_country_process';
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function alshaya_addressbook_profile_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // If the address is default address, not allow user to delete it.
  if ($operation == 'delete' && $entity->bundle() == 'address_book') {
    if ($entity->isDefault() && $entity->getOwnerId() == $account->id()) {
      return AccessResult::forbidden();
    }
  }
}

/**
 * Implements hook_user_view_alter().
 */
function alshaya_addressbook_user_view_alter(&$build) {
  // Remove/Hide the 'address_book' info on 'user/uid' page.
  if (isset($build['profile_address_book'])) {
    unset($build['profile_address_book']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_addressbook_form_profile_address_book_edit_form_alter(array &$form, FormStateInterface $form_state) {
  $form['#prefix'] = '<div id="address-book-form-open">';
  $form['#suffix'] = '</div>';

  // Save profile form.
  $form['actions']['submit']['#ajax'] = [
    'callback' => 'alshaya_addressbook_save_ajax_callback',
    'wrapper' => 'address-book-form-open',
  ];
  // Set default profile profile form.
  $form['actions']['set_default']['#ajax'] = [
    'callback' => 'alshaya_addressbook_save_ajax_callback',
    'wrapper' => 'address-book-form-open',
  ];

  // Alter the profile edit form.
  _alshaya_addressbook_form_alter($form, $form_state);
}

/**
 * Implements hook_entity_type_alter().
 */
function alshaya_addressbook_entity_type_alter(array &$entity_types) {
  /* @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['profile']->setFormClass('delete', 'Drupal\alshaya_addressbook\Form\AlshayaProfileDeleteForm');
  $entity_types['profile']->setFormClass('add', 'Drupal\alshaya_addressbook\Form\AlshayaProfileForm');
  $entity_types['profile']->setFormClass('edit', 'Drupal\alshaya_addressbook\Form\AlshayaProfileForm');
}

/**
 * Implements hook_alshaya_i18n_onetime_translation_add().
 */
function alshaya_addressbook_alshaya_i18n_onetime_translation_add() {
  $strings = [
    'First name' => [
      'ar' => 'الاسم الأول',
      'context' => 'Address label',
    ],
    'Last name' => [
      'ar' => 'اسم العائلة',
      'context' => 'Address label',
    ],
    'Company' => [
      'ar' => 'الشركة',
      'context' => 'Address label',
    ],
    'Street address' => [
      'en' => 'Street',
      'context' => 'Address label',
    ],
    'Street address' => [
      'ar' => 'الشارع',
      'context' => 'Address label',
    ],
    'City' => [
      'ar' => 'المدينة',
      'context' => 'Address label',
    ],
    'Postal code' => [
      'ar' => 'الرمز البريدي',
      'context' => 'Address label',
    ],
  ];

  // Save the translation.
  alshaya_i18n_save_translations($strings);
}

/**
 * Altering the address book form.
 */
function _alshaya_addressbook_form_alter(&$form, FormStateInterface $form_state) {
  // Get site level country code.
  $default_site_country = _alshaya_custom_get_site_level_country_code();

  // If default country is 'KW'.
  if ($default_site_country == 'KW') {
    $form['field_address']['widget'][0]['address']['#after_build'][] = '_alshaya_address_book_after_build';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_addressbook_form_profile_address_book_form_alter(&$form, FormStateInterface $form_state) {
  // Alter the profile form if embed somewhere.
  _alshaya_addressbook_form_alter($form, $form_state);
}

/**
 * After build for the address book add/edit form.
 */
function _alshaya_address_book_after_build($element, FormStateInterface $form_state) {
  $element['locality']['#title'] = t('Emirate/city');
  $element['administrative_area']['#title'] = t('Area');
  $element['administrative_area']['#theme'] = 'select';
  $element['administrative_area']['#type'] = 'select';
  $element['administrative_area']['#options'] = ['' => t('Select Area')] + _alshaya_addressbook_area_list();
  $element['address_line1']['#title'] = t('Street name/number');
  $element['dependent_locality']['#title'] = t('Building name/number');
  $element['organization']['#title'] = t('Block');
  $element['address_line2']['#title'] = t('Floor (optional)');
  $element['address_line2']['#title_display'] = 'before';
  return $element;
}

/**
 * Returns list of areas for a given country.
 *
 * @param string $country_code
 *   The country code.
 *
 * @return array
 *   List or areas.
 */
function _alshaya_addressbook_area_list($country_code = 'KW') {
  $term_tree = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('area_list', 0, NULL, TRUE);
  $area_list = [];
  if (!empty($term_tree)) {
    /* \Drupal\taxonomy\Entity\Term $term */
    foreach ($term_tree as $term) {
      $term = \Drupal::service('entity.repository')->getTranslationFromContext($term);
      $area_list[$term->id()] = $term->getName();
    }
  }

  return $area_list;
}
