<?php

namespace Drupal\alshaya_seo_transac\PathProcessor;

use Drupal\Core\PathProcessor\InboundPathProcessorInterface;
use Drupal\Core\PathProcessor\OutboundPathProcessorInterface;
use Symfony\Component\HttpFoundation\Request;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Class Alshaya Path Processor Sitemap Variant.
 *
 *   This path processor converts routes in the format:
 *   /sitemap-1.xml, /sitemap-2.xml etc. to
 *   /sitemap.xml?page=1, /sitemap.xml?page=2.
 *   The requirement was to have the sitemaps in the format /sitemap-1.xml
 *   instead of what is by default generated by the simple_sitemap module.
 *   So this path processor's inbound processor will process those in the new
 *   format and convertit to the old format which is recognized by the system.
 */
class AlshayaPathProcessorSitemapVariant implements InboundPathProcessorInterface, OutboundPathProcessorInterface {

  /**
   * {@inheritdoc}
   */
  public function processInbound($path, Request $request) {
    $path = preg_replace_callback('/sitemap(-(\d+))?\.xml/', function ($matches) use ($request) {
      if (isset($matches[2])) {
        $request->query->set('page', $matches[2]);
      }
      return 'sitemap.xml';
    }, $path);

    return $path;
  }

  /**
   * {@inheritdoc}
   */
  public function processOutbound($path, &$options = [], Request $request = NULL, BubbleableMetadata $bubbleable_metadata = NULL) {
    // This has been added but does not do any additional work as without this
    // we were getting 404 error.
    return $path;
  }

}
