<?php

/**
 * @file
 * Contains hooks for alshaya_rcs_bazaar_voice.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_preprocess_node().
 */
function alshaya_rcs_bazaar_voice_preprocess_node(&$variables) {
  if ($variables['node']->bundle() === 'rcs_product') {
    /** @var \Drupal\alshaya_rcs_bazaar_voice\Service\AlshayaRcsBazaarVoice $alshayaBazaarVoice */
    $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
    // Add bazaar voice related strings.
    $variables['bazaarvoice_strings'] = $alshayaBazaarVoice->getBazaarvoiceStrings();
  }
}

/**
 * Implements hook_page_attachments_schema_data_alter().
 */
function alshaya_rcs_bazaar_voice_page_attachments_schema_data_alter(array &$attachments, array &$product_schema_data) {
  $route_match = \Drupal::routeMatch();
  /** @var \Drupal\alshaya_rcs_bazaar_voice\Service\AlshayaRcsBazaarVoice $alshayaBazaarVoice */
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');

  if ($route_match->getRouteName() == 'entity.node.canonical') {
    /** @var \Drupal\node\Entity\Node $node */
    $node = $route_match->getParameter('node');
    if (!$node) {
      return;
    }
    $bundle = $node->getType();
    // If 'product' node.
    if ($bundle === 'rcs_product') {
      // Get the request parameters with a placeholder SKU value.
      $productReviewStats = $alshayaBazaarVoice->getProductReviewSchema('SKU_VAL');
      $attachments['#attached']['drupalSettings']['alshaya_bazaar_voice']['product_review_schema_request_data'] = $productReviewStats;
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_rcs_bazaar_voice_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() !== 'rcs_product') {
    return;
  }

  /** @var \Drupal\alshaya_rcs_bazaar_voice\Service\AlshayaRcsBazaarVoice $alshaya_bazaar_voice */
  $alshaya_bazaar_voice = \Drupal::service('alshaya_bazaar_voice.service');
  $basic_configs = $alshaya_bazaar_voice->getBasicConfigurations();
  // Disable BazaarVoice Rating and Review in PDP
  // if checkbox is checked in bazaarVoice Settings Form.
  if ($basic_configs['pdp_rating_reviews']) {
    return;
  }

  $settings = $alshaya_bazaar_voice->getProductBazaarVoiceDetails(NULL, $basic_configs);

  // Get the current pdp layout.
  $product_pdp_layout = \Drupal::service('alshaya_acm_product.skumanager')->getPdpLayout($entity);

  $build['reviews_rating']['#markup'] = '<div id="reviews-rating"></div>';
  $build['reviews_section']['#markup'] = '<div id="reviews-section"></div>';

  if ($product_pdp_layout !== 'magazine_v2') {
    $build['#attached']['library'][] = 'alshaya_bazaar_voice/ratingV2';
    $build['#attached']['library'][] = 'alshaya_bazaar_voice/reviewsV2';
  }

  $build['#attached']['library'][] = 'alshaya_bazaar_voice/iovation';
  $build['#cache']['contexts'][] = 'url.query_args:bv_authtoken';
  $build['#attached']['drupalSettings']['alshaya_bazaar_voice'] = $settings;
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_bazaar_voice_library_info_alter(&$libraries, $extension) {
  $self_module_path = drupal_get_path('module', 'alshaya_rcs_bazaar_voice');
  if ($extension === 'alshaya_bazaar_voice') {
    if (isset($libraries['utility'])
      && isset($libraries['utility']['js']['js/assets/alshaya_bazaar_voice.utility.js'])) {
      $options = $libraries['utility']['js']['js/assets/alshaya_bazaar_voice.utility.js'];
      unset($libraries['utility']['js']['js/assets/alshaya_bazaar_voice.utility.js']);
      $libraries['utility']['js']["/$self_module_path/js/alshaya_rcs_bazaar_voice.utility.js"] = $options;
      $libraries['utility']['dependencies'] = [
        'alshaya_master/common_functions',
      ];
    }
  }
}

/**
 * Implements hook_alshaya_acm_customer_orders_details_build_alter().
 */
function alshaya_rcs_bazaar_voice_alshaya_acm_customer_orders_details_build_alter(array &$order, array &$build) {
  /** @var \Drupal\alshaya_rcs_bazaar_voice\Service\AlshayaRcsBazaarVoice $alshaya_bazaar_voice */
  $alshaya_bazaar_voice = \Drupal::service('alshaya_bazaar_voice.service');
  $build['#attached']['drupalSettings']['alshaya_bazaar_voice'] = $alshaya_bazaar_voice->getRcsBazaarVoiceSettings();
}

/**
 * Implements hook_alshaya_acm_customer_recent_order_build_alter().
 */
function alshaya_rcs_bazaar_voice_alshaya_acm_customer_recent_order_build_alter(array &$build) {
  /** @var \Drupal\alshaya_rcs_bazaar_voice\Service\AlshayaRcsBazaarVoice $alshaya_bazaar_voice */
  $alshaya_bazaar_voice = \Drupal::service('alshaya_bazaar_voice.service');
  $build['#attached']['drupalSettings']['alshaya_bazaar_voice'] = $alshaya_bazaar_voice->getRcsBazaarVoiceSettings();
}

/**
 * Implements hook_rcs_placeholders_graphql_query().
 */
function alshaya_rcs_bazaar_voice_rcs_placeholders_graphql_query() {
  $query_fields = [];
  /** @var \Drupal\alshaya_rcs_bazaar_voice\Service\AlshayaRcsBazaarVoice $alshaya_bazaar_voice */
  $alshaya_bazaar_voice = \Drupal::service('alshaya_bazaar_voice.service');
  $product_query_fields = $alshaya_bazaar_voice->getBvProductQueryFields();

  $query_fields['bv_product'] = [
    'query' => [
      'query($sku: String)' => [
        'products(filter: {sku: {eq: $sku}})' => $product_query_fields,
      ],
    ],
    'variables' => [
      'sku' => NULL,
    ],
  ];

  return $query_fields;
}
