<?php

/**
 * @file
 * Contains SPC related translations.
 */

/**
 * SPC translation.
 */
function _alshaya_spc_translations() {
  $strings = [
    'v1' => [
      'have a promo code?' => [
        'ar' => 'هل لديك رمز عرض ؟',
      ],
      'Promo code' => [
        'ar' => 'رمز عرض',
      ],
      'subtotal' => [
        'ar' => 'المبلغ',
      ],
      'Excluding delivery' => [
        'ar' => 'قبل التوصيل',
      ],
      'Shopping Bag' => [
        'ar' => 'حقيبة التسوق',
      ],
      'continue to checkout' => [
        'ar' => 'إتمام الشراء بأمان',
      ],
      'my shopping bag' => [
        'ar' => 'حقيبة التسوق',
      ],
      '(@qty items)' => [
        'ar' => '(قطعة @qty)',
      ],
      'Total (excluding delivery)' => [
        'ar' => '(المبلغ الإجمالي (قبل التوصيل',
      ],
      'remove this item' => [
        'ar' => 'أزل هذا البند',
      ],
      'applied' => [
        'ar' => 'تم تفعيل',
      ],
      'complete purchase' => [
        'ar' => 'سجل الطلبية',
      ],
      'order summary' => [
        'ar' => 'ملخص الطلبية',
      ],
      'Order total (@count items)' => [
        'ar' => '(@count قطعة) المبلغ الإجمالي',
      ],
      'billing information' => [
        'ar' => 'معلومات إرسال الفواتير',
      ],
      'change address' => [
        'ar' => 'تغيير العنوان',
      ],
      'select' => [
        'ar' => 'تحديد',
      ],
      'selected' => [
        'ar' => 'المحدد',
      ],
      'Please add your contact details & address' => [
        'ar' => 'يرجى تزويدنا ببيانات الاتصال الخاصة بكم والعنوان',
      ],
      'deliver to my location' => [
        'ar' => 'التوصيل إلى موقعي',
      ],
      'contact information' => [
        'ar' => 'معلومات الاتصال',
      ],
      'select your preferred collection store' => [
        'ar' => 'حدد متجر المجموعة المفضل لديك',
      ],
      'please add your contact details and address.' => [
        'ar' => 'يرجى تزويدنا ببيانات الاتصال الخاصة بكم والعنوان',
      ],
      'select @label' => [
        'ar' => 'label@ تحديد',
      ],
      'Full Name' => [
        'ar' => 'الاسم الكامل',
      ],
      'Email' => [
        'ar' => 'البريد الإلكتروني',
      ],
      'CVV' => [
        'ar' => 'CVV الرقم السري',
      ],
      'Expiry' => [
        'ar' => 'تاريخ انتهاء البطاقة',
      ],
      'Your shopping bag is empty.' => [
        'ar' => 'حقيبة التسوق الخاصة بك فارغة.',
      ],
      'We will send you a text message once your order is ready for collection.' => [
        'ar' => 'سنقوم بإرسال رسالة قصيرة عندما تكون الطلبية جاهزة للاستلام',
      ],
      'We have set your billing address same as delivery address. You can select a different one by clicking the change button above.' => [
        'ar' => 'لقد قمنا بتعيين عنوان الفاتورة الخاص بك مثل عنوان التسليم. يمكنك تحديد واحد مختلف عن طريق النقر فوق زر التغيير أعلاه.',
      ],
      '@distance miles' => [
        'ar' => '@distance ميل',
      ],
      'Here\'s a confirmation of your order and all the details you may need.' => [
        'ar' => '.فيما يلي تأكيد لطلبك وكل التفاصيل التي قد تحتاجها',
      ],
      'Card Number' => [
        'ar' => 'رقم البطاقة',
      ],
      'card no' => [
        'ar' => 'رقم البطاقة',
      ],
      'Thanks for shopping with us.' => [
        'ar' => '.شكراً لتسوقكم معنا عبر الموقع',
      ],
      'Order Confirmation page' => [
        'ar' => 'صفحة تأكيد الطلبية',
      ],
      'confirmation email sent to' => [
        'ar' => 'تم إرسال رسالة التأكيد إلى',
      ],
      'order number' => [
        'ar' => 'ارقم الطلبية',
      ],
      'order detail' => [
        'ar' => 'تفاصيل الطلبية',
      ],
      'delivery to' => [
        'ar' => 'التوصيل إلى',
      ],
      'delivery type' => [
        'ar' => 'نوع التوصيل',
      ],
      'expected delivery within' => [
        'ar' => 'التوصيل متوقع خلال',
      ],
      'Same day' => [
        'ar' => 'نفس اليوم',
      ],
      'number of items' => [
        'ar' => 'عدد القطع',
      ],
      'Collection details' => [
        'ar' => 'ببيانات الاستلام',
      ],
      'Collect in store from' => [
        'ar' => 'استلم من المحل التالي',
      ],
      'Selected store' => [
        'ar' => 'المحل المختار',
      ],
      'Sorry, something went wrong. Please try again later' => [
        'ar' => 'عذرا ، حدث خطأ ما. يرجى المحاولة مرة أخرى لاحقًا',
      ],
      'Dismiss' => [
        'ar' => 'حذف',
      ],
      'Find your nearest store' => [
        'ar' => 'ابحث عن المحلات القريبة إليك لاستلام طلبيتك',
      ],
      'Access to your location access has been denied by your browser. You can reenable location services in your browser settings.' => [
        'ar' => 'تم رفض الوصول إلى موقعك من قبل المستعرض الخاص بك. يمكنك تفعيل خدمات تحديد الموقع من إعدادات المتصفح الخاص بك',
      ],
      'You are browsing outside @country' => [
        'ar' => '@country انت تتصفح خارج',
      ],
      'We don\'t support delivery outside @country.' => [
        'ar' => '.@country لا ندعم التوصيل خارج',
      ],
      'Please enter an address with in country @country below to continue.' => [
        'ar' => 'أدناه للمتابعة @country يرجى إدخال عنوان في البلد.',
      ],
      'Please select a store with in country @country below to continue.' => [
        'ar' => 'أدناه للمتابعة @country يرجى اختيار محلا في البلد.',
      ],
      'Sorry, we couldn’t fetch your location precisely, please' => [
        'ar' => 'عذرًا ، لم نتمكن من جلب موقعك بدقة ، يرجى',
      ],
      'enter your address' => [
        'ar' => 'إدخال عنوانك',
      ],
      'Please enter your full name.' => [
        'ar' => 'يرجى إدخال اسمك الكامل.',
      ],
      'Please enter email.' => [
        'ar' => 'يرجى إدخال البريد الإلكتروني.',
      ],
      'Please enter mobile number.' => [
        'ar' => 'يرجى إدخال رقم الجوال.',
      ],
      'Please enter valid mobile number.' => [
        'ar' => 'يرجى إدخال رقم الجوال صحيح.',
      ],
      'Customer already exists.' => [
        'ar' => 'الحساب موجود مسبقا.',
      ],
      'Your bag has been updated successfully.' => [
        'ar' => 'تم تحديث حقيبتك بنجاح.',
      ],
      'Search for @label' => [
        'ar' => '@label البحث عن',
      ],
      'Select @label' => [
        'ar' => '@label اختر',
      ],
      'Please enter @label.' => [
        'ar' => '@label يرجى إدخال',
      ],
      'The email address %mail is not valid.' => [
        'ar' => 'عنوان البريد الإلكتروني %mail غير صحيح.',
      ],
      'Transaction ID' => [
        'ar' => 'رمز العملية',
      ],
      'Payment ID' => [
        'ar' => 'رمز الدفع',
      ],
      'Result code' => [
        'ar' => 'رمز النتيجة',
      ],
      'available instore within' => [
        'ar' => 'متوفر في المحل خلال',
      ],
      'please enter promo code.' => [
        'ar' => 'يرجى ادخال رمز العرض.',
      ],
      'please add your billing address.' => [
        'ar' => 'يرجى إدخال عنوان إرسال الفواتي',
      ],
      'Collection by' => [
        'ar' => 'الاستلام من طرف',
      ],
      'select my location' => [
        'ar' => 'اختيار موقعي',
      ],
      'Invalid Debit / Credit Card number' => [
        'ar' => 'رقم البطاقة غير صالح',
      ],
      'Incorrect credit card expiration date' => [
        'ar' => 'تاريخ انتهاء البطاقة غير صالح',
      ],
      'change payment card' => [
        'ar' => 'تغيير بطاقة الدفع',
      ],
      'Save this card for faster payment next time you shop. (CVV number will not be saved)' => [
        'ar' => 'احفظ هذه البطاقة للدفع بشكل أسرع في المرة القادمة التي تتسوق فيها. (CVV لن يتم حفظ رقم)',
      ],
      'expires' => [
        'ar' => 'تنتهي صلاحيته في',
      ],
      'add new card' => [
        'ar' => 'إضافة بطاقة جديدة',
      ],
      "This address doesn't contain all the required information, please update it." => [
        'ar' => 'لا يحتوي هذا العنوان على جميع المعلومات المطلوبة ، يرجى تحديثه.',
      ],
    ],
  ];

  $strings['v2'] = [
    'Date' => [
      'ar' => 'تاريخ',
    ],
    'Transaction ID: @transaction_id Payment ID: @payment_id Result code: @result_code' => [
      'ar' => 'معرف المعاملة: transaction_id@ معرف الدفع: payment_id@ رمز النتيجة: result_code@',
    ],
    'Transaction ID: @transaction_id<br>Payment ID: @payment_id<br>Result code: @result_code<br>Amount: @amount<br>Date: @date' => [
      'ar' => 'معرّف المعاملة: @transaction_id <br> معرّف الدفع: @payment_id <br> رمز النتيجة: @result_code <br> المبلغ: @amount <br> التاريخ: @date',
    ],
  ];

  // Strings related to Fawry payment method.
  $strings['v3'] = [
    'Once the product is successfully requested, we will send you Fawry Ref. No. to the below contact details' => [
      'ar' => 'سوف يصلك الرقم المرجعي لخدمة فوري على تفاصيل الاتصال أدناه، بمجرد إتمام الطلبية.',
    ],
    "Pay for your order through any of <a href='@fawry_link' target='_blank'>Fawry's cash points</a> at your convenient time and location across Egypt." => [
      'ar' => "قم بدفع مبلغ الطلبية عن طريق خدمة فوري من أي <a href='@fawry_link'target='_blank'>نقطة دفع نقدي،</a> وفي أي وقت ومكان في جميع أرجاء مصر.",
    ],
    "Please complete your payment at the nearest <a href='@fawry_link' target='_blank'>Fawry Cash Point</a> using your reference number." => [
      'ar' => "يرجى استكمال الدفع عن طريق أقرب <a href='@fawry_link'target='_blank'>نقطة دفع لفوري</a> عن طريق استخدام رقم المرجع",
    ],
    'Complete payment by' => [
      'ar' => 'إتمام الدفع من خلال',
    ],
    'Amount Due' => [
      'ar' => 'المبلغ المستحق',
    ],
    'Reference number' => [
      'ar' => 'رقم المرجع',
    ],
    'Reference No' => [
      'ar' => 'رقم المرجع',
    ],
  ];

  // Strings related to V2.
  $strings['v4'] = [
    'We have upgraded your experience, please refresh the page and try again.' => [
      'ar' => '.لقد قمنا بترقية تجربتك ، يرجى تحديث الصفحة والمحاولة مرة أخرى',
    ],
  ];

  // Strings related to collection point feature.
  $strings['v5'] = [
    'Collection Point' => [
      'ar' => 'نقطة الاستلام',
    ],
    'select your preferred collection point' => [
      'ar' => 'اختر نقطة الاستلام المفضلة',
    ],
    'find your collection point' => [
      'ar' => 'اكتشف أقرب نقطة استلام',
    ],
    'Please ensure that the person collecting this order has a valid government ID and printed copy of the invoice.' => [
      'ar' => 'يرجى التأكد من إحضار هوية شخصية صالحة ونسخة مطبوعة من الفاتورة عند الاستلام.',
    ],
    'Selected collection point' => [
      'ar' => 'نقطة الاستلام المختارة.',
    ],
    'Important Note:' => [
      'ar' => 'ملاحظة مهمة:',
    ],
    'Collect in' => [
      'ar' => 'الاستلام في',
    ],
    'Your order will be available for pickup at the following collection point' => [
      'ar' => 'سوف يكون طلبك جاهزاً في نقطة الاستلام هذه',
    ],
  ];

  $strings['v6'] = [
    'Transaction Failed: Invalid CVV' => [
      'ar' => 'فشلت المعاملة: رقم CVV غير صالح',
    ],
  ];

  // Strings related to Advantage card.
  $strings['v7'] = [
    'Please enter valid Advantage card code.' => [
      'ar' => 'يرجى إدخال رقم بطاقة خصم الشايع صالح.',
    ],
    'Advantage Card Discount' => [
      'ar' => 'خصم بطاقة الشايع',
    ],
    'This product is not eligible for the Advantage card discount.' => [
      'ar' => 'هذا المنتج غير مؤهل للحصول على خصم بطاقة الشايع',
    ],
  ];

  // Strings related to Benefit Pay payment method.
  $strings['v8'] = [
    'Continue with Benefit pay' => [
      'ar' => 'أكمل مع بينفت باي',
    ],
    'Please complete your payment by scanning the QR code.' => [
      'ar' => 'أكمل عملية الدفع عبر مسح رمز QR.',
    ],
    'Scan to Pay' => [
      'ar' => 'امسح وادفع',
    ],
    'Pay using BenefitPay App' => [
      'ar' => 'ادفع باستخدام تطبيق بينفت باي',
    ],
    'BenefitPay' => [
      'ar' => 'بينفت باي',
    ],
    'Merchant' => [
      'ar' => 'التاجر',
    ],
    'Amount' => [
      'ar' => 'المبلغ',
    ],
    'Reference number' => [
      'ar' => 'الرقم المرجعي',
    ],
    'How to pay using BenefitPay?' => [
      'ar' => 'كيفية الدفع باستخدام بينفت باي؟',
    ],
  ];

  // Strings related to collection point feature.
  $strings['v9'] = [
    'Collection Charge' => [
      'ar' => 'رسوم الاستلام',
    ],
    'available in collection point within' => [
      'ar' => 'متوفر في نقطة الاستلام خلال',
    ],
    'Holiday' => [
      'ar' => 'عطلة',
    ],
  ];

  // Strings related to express delivery feature.
  $strings['v10'] = [
    'Express Delivery Available' => [
      'ar' => 'خدمة التوصيل السريع متوفرة',
    ],
    'Explore the delivery options applicable to your area.' => [
      'ar' => 'اكتشف خيارات التوصيل المتاحة في منطقتك',
    ],
    'Check availability in your area' => [
      'ar' => 'تحقق من التوفر في منطقتك',
    ],
    'Select' => [
      'ar' => 'اختر',
    ],
    'Search area' => [
      'ar' => 'ابحث عن منطقة',
    ],
    'Select an area' => [
      'ar' => 'اختر المنطقة',
    ],
    'Same Day Delivery Available' => [
      'ar' => 'التوصيل في نفس اليوم متاح',
    ],
    'Selected Area' => [
      'ar' => 'مناطق معينة',
    ],
    'Deliver to' => [
      'ar' => 'التوصيل إلى',
    ],
    'Select area' => [
      'ar' => 'اختيار المنطقة',
    ],
    'Select this area' => [
      'ar' => 'اختر هذه المنطقة',
    ],
    'Do you want to change your current Delivery Area from @currentAreaLabel to @storageAreaLabel?' => [
      'ar' => 'هل تريد تغيير منطقة التسليم الحالية من @currentAreaLabel إلى @storageAreaLabel؟',
    ],
    'Delivery Type' => [
      'ar' => 'نوع التوصيل',
    ],
    'Standard' => [
      'ar' => 'العادي',
    ],
    'Same Day' => [
      'ar' => 'نفس اليوم',
    ],
    'Express' => [
      'ar' => 'دمة التوصيل السريع',
    ],
    'Express Delivery' => [
      'ar' => 'دمة التوصيل السريع',
    ],
  ];

  // Strings related to express delivery feature with context
  // for listing pages.
  $strings['v11'] = [
    'Express Delivery Available' => [
      'ar' => 'خدمة التوصيل السريع متوفرة',
      'context' => 'express_day_delivery_listing',
    ],
    'Same Day Delivery Available' => [
      'ar' => 'التوصيل في نفس اليوم متاح',
      'context' => 'same_day_delivery_listing',
    ],
  ];

  // Strings related to express delivery feature with context
  // for PDP pages.
  $strings['v12'] = [
    'Express Delivery Available' => [
      'ar' => 'خدمة التوصيل السريع متوفرة',
      'context' => 'express_delivery_label',
    ],
    'Same Day Delivery Available' => [
      'ar' => 'التوصيل في نفس اليوم متاح',
      'context' => 'same_day_delivery_label',
    ],
  ];

  return $strings;
}

/**
 * Get translations for given version.
 *
 * @param string $version
 *   Version number like 'v1' etc.
 *
 * @return array
 *   Translations.
 */
function _alshaya_spc_get_translations(string $version = '') {
  $translations = _alshaya_spc_translations();
  // If no version mentioned, return all version strings.
  if (empty($version)) {
    $trans_data = [];
    foreach ($translations as $trans) {
      $trans_data = array_merge($trans_data, $trans);
    }

    return $trans_data;
  }

  return $translations[$version] ?? [];
}
