<?php

/**
 * @file
 * Module file.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\acq_sku\Entity\SKU;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_html().
 */
function alshaya_spc_preprocess_html(&$variables) {
  $currency_config = [
    'currency_code' => \Drupal::config('acq_commerce.currency')->get('currency_code'),
    'currency_code_position' => \Drupal::config('acq_commerce.currency')->get('currency_code_position'),
    'decimal_points' => \Drupal::config('acq_commerce.currency')->get('decimal_points'),
  ];

  $variables['#attached']['drupalSettings']['alshaya_spc']['currency_config'] = $currency_config;

  $vat_text = \Drupal::config('alshaya_acm_product.settings')->get('vat_text');
  $variables['#attached']['drupalSettings']['alshaya_spc']['vat_text'] = $vat_text;
  $variables['#attached']['drupalSettings']['alshaya_spc']['middleware_url'] = _alshaya_spc_get_middleware_url();
  $variables['#attached']['drupalSettings']['alshaya_spc']['max_cart_qty'] = \Drupal::config('alshaya_acm.cart_config')->get('max_cart_qty');

  /* @var \Drupal\alshaya_acm_product\SkuImagesManager $sku_images_manager */
  $sku_images_manager = \Drupal::service('alshaya_acm_product.sku_images_manager');
  $variables['#attached']['drupalSettings']['alshaya_spc']['default_image'] = $sku_images_manager->getProductDefaultImageUrl();
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function alshaya_spc_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  // Changing text for cart page breadcrumb.
  if ($route_match->getRouteName() == 'acq_cart.cart') {
    $breadcrumb_links = $breadcrumb->getLinks();
    $breadcrumb_links[1]->setText(t('Shopping Bag'));
  }
}

/**
 * Implements hook_block_access().
 */
function alshaya_spc_block_access(Block $block, $operation, AccountInterface $account) {
  // Page title block should not be accessible on cart page.
  if ($operation == 'view' && $block->getPluginId() == 'page_title_block') {
    return AccessResult::forbiddenIf(\Drupal::routeMatch()->getRouteName() == 'acq_cart.cart');
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alshaya_spc_form_sku_base_form_alter(&$form, FormStateInterface $form_state) {
  unset($form['add_to_cart']['#ajax']);
  $form['#attached']['library'][] = 'alshaya_spc/add_to_cart';
  $form['#attached']['drupalSettings']['alshaya_spc']['cart_update_endpoint'] = _alshaya_spc_get_middleware_url() . '/update-cart';
}

/**
 * Get middleware url.
 *
 * @return string
 *   Middleware url.
 */
function _alshaya_spc_get_middleware_url() {
  $host_url = \Drupal::request()->getHost();
  return 'https://' . $host_url . '/middleware/public';
}

/**
 * Implements hook_alshaya_acm_product_light_product_data_alter().
 */
function alshaya_spc_alshaya_acm_product_light_product_data_alter(SKU $sku, array &$data, $type) {
  if (!empty($data) && $type == 'light' && !empty(\Drupal::requestStack()->getCurrentRequest()->query->get('context'))) {
    \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');
    $data['extra_data'] = [];
    $image = alshaya_acm_get_product_display_image($sku, 'product_teaser', 'cart');
    if (!empty($image)) {
      if ($image['#theme'] == 'image_style') {
        $data['extra_data']['cart_image'] = [
          'url' => ImageStyle::load($image['#style_name'])->buildUrl($image['#uri']),
          'title' => $image['#title'],
          'alt' => $image['#alt'],
        ];
      }
      elseif ($image['#theme'] == 'image') {
        $data['extra_data']['cart_image'] = [
          'url' => $image['#attributes']['src'],
          'title' => $image['#attributes']['title'],
          'alt' => $image['#attributes']['alt'],
        ];
      }
    }
  }
}
