<?php

/**
 * @file
 * Alshaya i18n module.
 */

/**
 * Function to import custom initial translations.
 */
function alshaya_i18n_save_translations($strings) {
  // Loop through each string for translation.
  foreach ($strings as $source => $translations) {
    // Translation context.
    $context = !empty($translations['context']) ? $translations['context'] : '';
    // Removing key so to create no problem in looping.
    unset($translations['context']);
    // First create the translation source entry.
    $source_param = [
      'source' => $source,
    ];
    // If context is available.
    if (!empty($context)) {
      $source_param += ['context' => $context];
    }
    \Drupal::service('locale.storage')->createString($source_param)->save();

    // Loop through all translations and save them.
    foreach ($translations as $langcode => $translation) {
      $conditions = ['source' => $source];
      // If context is available.
      if (!empty($context)) {
        $conditions += ['context' => $context];
      }
      $options = ['translated' => FALSE, 'untranslated' => TRUE];

      // Look for existing translation sources.
      $data = \Drupal::service('locale.storage')->getTranslations($conditions, $options);
      foreach ($data as $key => $value) {
        if (isset($value->source) && $value->source == $source) {
          // Save translation.
          $params = [
            'lid' => $value->lid,
            'language' => $langcode,
          ];
          // If context is available.
          if (!empty($context)) {
            $params += ['context' => $context];
          }
          $target = \Drupal::service('locale.storage')->createTranslation($params);
          $target->setPlurals([$translation])
            ->setCustomized()
            ->save();
        }
      }
    }
  }
}

/**
 * Implements hook_alshaya_i18n_onetime_translation_add().
 */
function alshaya_i18n_alshaya_i18n_onetime_translation_add() {
  // Reset the formula to calculate plural in arabic language.
  $formulae = \Drupal::state()->get('locale.translation.formulae', []);
  if (isset($formulae['ar'])) {
    $formulae['ar'] = [];
    $formulae['ar']['plurals'] = 5;
    $formulae['ar']['formula'][0] = 1;
    $formulae['ar']['formula'][1] = 0;
    $formulae['ar']['formula'][2] = 2;
    $formulae['ar']['formula'][3] = 3;
    $formulae['ar']['formula'][4] = 3;
    $formulae['ar']['formula'][5] = 3;
    $formulae['ar']['formula'][6] = 3;
    $formulae['ar']['formula'][7] = 3;
    $formulae['ar']['formula'][8] = 3;
    $formulae['ar']['formula'][9] = 3;
    $formulae['ar']['formula'][10] = 3;
    $formulae['ar']['formula']['default'] = 4;
    \Drupal::state()->set('locale.translation.formulae', $formulae);
  }
}
