<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\alshaya_product_zoom\Plugin\Field\FieldFormatter\ProductZoomFormatter;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_acq_sku_product_node_alter().
 */
function alshaya_acm_product_acq_sku_product_node_alter(NodeInterface $node, array $product) {
  $visible = $product['visibility'] == 1;
  $node->setPublished($visible);
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_acm_product_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product') {
    // Load the related SKU entity.
    $skuEntity = $entity->field_skus->first()->get('entity')->getValue();

    // Fetch media.
    module_load_include('inc', 'alshaya_acm_product', 'alshaya_acm_product.utility');
    $media = alshaya_acm_product_get_sku_media($skuEntity);

    // Fetch settings.
    $settings = ProductZoomFormatter::defaultSettings();
    $thumbnail_style = $settings['thumb_style'];
    $zoom_style = $settings['zoom_style'];
    $slide_style = $settings['slide_style'];

    // Create our thumbnails to be rendered for zoom.
    foreach ($media as $delta => $image) {
      $file_uri = $image->getFileUri();
      if ($delta == 0) {
        $imageZoom = ImageStyle::load($zoom_style)->buildUrl($file_uri);
        $imageMedium = ImageStyle::load($slide_style)->buildUrl($file_uri);
        $main_image = [
          'zoomurl' => $imageZoom,
          'mediumurl' => $imageMedium,
        ];
      }
      $imageSmall = ImageStyle::load($thumbnail_style)->buildUrl($file_uri);
      $imageZoom = ImageStyle::load($zoom_style)->buildUrl($file_uri);
      $imageMedium = ImageStyle::load($slide_style)->buildUrl($file_uri);
      $thumbnails[] = [
        'thumburl' => $imageSmall,
        'mediumurl' => $imageMedium,
        'zoomurl' => $imageZoom,
        'type' => 'image',
      ];
    }
    // @todo: Hardcoding videos for now.

    $videos = [
      'https://www.youtube.com/embed/eKG08z85DtY',
      'https://player.vimeo.com/video/1084537',
    ];

    foreach ($videos as $video) {
      if (strpos($video, 'youtube')) {
        $thumbnails[] = [
          'thumburl' => 'https://img.youtube.com/vi/' . ProductZoomFormatter::getYouTubeVideoId($video) . '/hqdefault.jpg',
          'url' => $video,
          'type' => 'youtube',
          'width' => 81,
          'height' => 81,
        ];
      }
      else {
        $thumbnails[] = [
          'url' => $video,
          'type' => 'vimeo',
          'width' => 81,
          'height' => 81,
        ];
      }
    }

    $build['product_zoom'] = [
      '#theme' => 'product_zoom_gallery',
      '#mainImage' => $main_image,
      '#thumbnails' => $thumbnails,
      '#properties' => ProductZoomFormatter::getRelStringForProductZoom($settings),
      '#attached' => [
        'library' => [
          'alshaya_product_zoom/product.cloud_zoom',
        ],
      ],
    ];
  }
}
