<?php

/**
 * @file
 * Module file.
 */

use Drupal\alshaya_options_list\AlshayaOptionsListHelper;
use Drupal\Core\Ajax\InsertCommand;
use Drupal\Core\Cache\Cache;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\search_api\Query\QueryInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\taxonomy\TermInterface;
use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_search_api_db_query_alter().
 */
function alshaya_product_list_search_api_db_query_alter(SelectInterface &$db_query, QueryInterface $query) {
  // If attribute product list views.
  if ($query->hasTag('views_alshaya_product_list')
    && $query->getSearchId() == 'views_block:alshaya_product_list__block_3') {
    $nid = 0;
    $attr_name = 'none';
    $attr_value = 'none';
    $current_route = \Drupal::routeMatch();
    // If view route, means either sorting of filtering is done.
    if ($current_route->getRouteName() == 'views.ajax'
      || $current_route->getRouteName() == 'facets.block.ajax') {
      $query_string = [];
      parse_str(\Drupal::requestStack()->getCurrentRequest()->getQueryString(), $query_string);

      // Get url from views.
      $view_url_data = $current_route->getRouteName() == 'views.ajax'
        ? $query_string['view_path']
        : \Drupal::requestStack()->getCurrentRequest()->getPathInfo();

      $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      // Remove current language from url.
      $view_url_data = preg_replace('/\/' . $current_language . '/', '', $view_url_data, 1);
      // Remove last `/` from url.
      $view_url_data = rtrim($view_url_data, '/');
      // Get alias in case view url data is like `/node/1212/`.
      $alias = \Drupal::service('path.alias_manager')->getAliasByPath($view_url_data);
      if ($source_path = \Drupal::service('path.alias_storage')->lookupPathSource($alias, $current_language)) {
        // Source path will be like - `/node/1212/` and we need only id.
        $nid = explode('/', $source_path)[2];
      }
    }
    elseif ($current_route->getRouteName() == 'entity.node.canonical') {
      $nid = $current_route->getParameter('node')->id();
    }

    // If node object.
    if ((($node = Node::load($nid)) instanceof NodeInterface)
      && $node->bundle() == 'product_list') {
      $node = \Drupal::service('entity.repository')->getTranslationFromContext($node);
      $attr_value = $node->get('field_attribute_value')->getString();
      $attr_name = $node->get('field_attribute_name')->getString();
    }

    // Add condition on query.
    $db_query->condition('t.' . $attr_name, $attr_value);
  }
}

/**
 * Implements hook_acq_sku_base_fields_updated().
 */
function alshaya_product_list_acq_sku_base_fields_updated(array $fields, $op = 'add') {
  /** @var \Drupal\alshaya_search_api\AlshayaSearchApiFacetsManager $facet_manager */
  $facet_manager = \Drupal::service('alshaya_search_api.facets_manager');

  $facet_source_id = 'search_api:views_block__alshaya_product_list__block_3';
  $filter_bar_id = 'facets_summary.facets_summary.filter_bar_productlist';
  $prefix = 'productlist';

  switch ($op) {
    case 'add':
      foreach ($fields as $field_code => $field) {
        if (empty($field['facet'])) {
          // We use add even when resetting. Remove facet if available.
          $facet_manager->removeFacet($field_code, $filter_bar_id, $prefix);
          continue;
        }

        $facet_manager->createFacet($field_code, $facet_source_id, $filter_bar_id, $prefix, ['name' => $field['label']]);
      }
      break;

    case 'remove':
      foreach ($fields as $field_code => $field) {
        // Remove from facets if facet is 1.
        if (!empty($field['facet'])) {
          $facet_manager->removeFacet($field_code, $filter_bar_id, $prefix);
        }
      }
      break;
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_product_list_module_implements_alter(&$implementations, $hook) {
  // This module alter should be called last.
  if ($hook == 'alshaya_search_filter_link_alter') {
    $group = $implementations['alshaya_product_list'];
    unset($implementations['alshaya_product_list']);
    $implementations['alshaya_product_list'] = $group;
  }
}

/**
 * Implements hook_alshaya_search_filter_link_alter().
 */
function alshaya_product_list_alshaya_search_filter_link_alter(&$link, array &$data) {
  static $attributes;
  // Get nids for given attribute code.
  if (empty($attributes[$data['attribute_code']])) {
    $query = \Drupal::service('database')->select('node__field_attribute_name', 'an');
    $query->addField('av', 'field_attribute_value_value');
    $query->addField('an', 'entity_id');
    $query->join('node__field_attribute_value', 'av', 'an.entity_id = av.entity_id and av.bundle = an.bundle');
    $query->condition('an.bundle', 'product_list');
    $query->condition('an.field_attribute_name_value', 'attr_' . $data['attribute_code']);
    $attributes[$data['attribute_code']] = $query->execute()->fetchAllkeyed(0, 1);
  }
  // If node exist for the given attribute code and value.
  if (!empty($attributes[$data['attribute_code']][$data['attribute_value']])) {
    $nid = $attributes[$data['attribute_code']][$data['attribute_value']];
    $alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $nid);
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $data['append_value'] = FALSE;
    $link = '/' . $langcode . $alias;
  }
}

/**
 * Alters ajax response on facet filter.
 *
 * Implements hook_alshaya_search_ajax_response_alter.
 */
function alshaya_product_list_alshaya_search_ajax_response_alter(&$response, $facet_fields) {
  $master_request = \Drupal::service('request_stack')->getMasterRequest();
  $master_route = $master_request->attributes->get('_route');
  if ($master_route === 'entity.node.canonical') {
    $node = $master_request->attributes->get('node');
    if ($node->bundle() === 'product_list') {
      $response->addCommand(new InsertCommand('.block-views-exposed-filter-blockalshaya-product-list-block-3 form .facets-hidden-container', $facet_fields));
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_product_list_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Attach the shop by brand css library to the product listing page.
  if ($entity->bundle() == 'product_list') {
    $build['#attached']['library'][] = 'alshaya_white_label/shop-by-brand';
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Create product list nodes for attribute values of attribute codes from
 * alshaya options list settings on sync-options.
 */
function alshaya_product_list_taxonomy_term_presave(TermInterface $term) {
  // Check term vocabulory.
  if ($term->bundle() != 'sku_product_option') {
    return;
  }

  // Get alshaya_options_list settings for attribute codes.
  $pages = \Drupal::config('alshaya_options_list.settings')
    ->get('alshaya_options_pages');
  foreach ($pages as $page) {
    $attribute_options = \Drupal::config('alshaya_options_list.settings')->get('alshaya_options_pages');
    $attributeCodes = array_filter($attribute_options[$page['url']]['attributes']);
  }

  // Get Term attribute code.
  $term_attribute_code = $term->get('field_sku_attribute_code')->value;

  // Check if Term has same attribute code as the alshaya_options_list
  // settings, if yes then create a product list node for that attribute value.
  if (in_array($term_attribute_code, $attributeCodes)) {
    $attribute = 'attr_' . $term_attribute_code;
    $attribute_value = $term->getName();
    try {
      $properties = [
        'field_attribute_name' => $attribute,
        'field_attribute_value' => $attribute_value,
        'type' => 'product_list',
      ];
      $entities = \Drupal::entityTypeManager()->getStorage('node')
        ->loadByProperties($properties);
      $node = array_shift($entities);
      // If node exists, we create or we skip.
      if (!($node instanceof Node)) {
        $node = Node::create([
          // The node entity bundle.
          'type' => 'product_list',
          'langcode' => 'en',
          // The user ID.
          'uid' => 1,
          'title' => $attribute_value,
          'field_attribute_value' => [
            'value' => $attribute_value,
          ],
          'field_attribute_name' => [
            'value' => $attribute,
          ],
        ]);
        $node->save();

        // Creating the translation if langcode not passed.
        /** @var \Drupal\node\NodeInterface $node_translation */
        $node_translation = $node->addTranslation('ar');
        $node_translation->setOwnerId(1);
        $node_translation->setTitle($attribute_value);
        $node_translation->set('field_attribute_name', $attribute);
        $node_translation->set('field_attribute_value', $attribute_value);
        $node_translation->save();
      }
    }
    catch (\Exception $e) {
      \Drupal::logger('alshaya_product_list')->error('Error occured while creating Product list node: @message', [
        '@message' => $e->getMessage(),
      ]);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Invalidate cache tag for options page when
 * product_list node is saved / updated.
 */
function alshaya_product_list_node_presave(NodeInterface $node) {
  if ($node->bundle() != 'product_list') {
    return;
  }
  // Invalidate option page cache.
  Cache::invalidateTags([AlshayaOptionsListHelper::OPTIONS_PAGE_CACHETAG]);
}

/**
 * Implements hook_query_TAG_NAME_alter().
 */
function alshaya_product_list_query_product_category_child_terms_alter(AlterableInterface $query) {
  // Add show_in_product_list_lhn field.
  $query->leftJoin('taxonomy_term__field_show_in_product_list_lhn', 'tplhn', 'tplhn.entity_id=tfd.tid');
  $query->addField('tplhn', 'field_show_in_product_list_lhn_value', 'field_show_in_product_list_lhn_value');
}
