<?php

/**
 * @file
 * Module file.
 */

use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_search_api_db_query_alter().
 */
function alshaya_product_list_search_api_db_query_alter(SelectInterface &$db_query, QueryInterface $query) {
  // If attribute product list views.
  if ($query->hasTag('views_alshaya_product_list')
    && $query->getSearchId() == 'views_block:alshaya_product_list__block_3') {
    $nid = 0;
    $attr_name = 'none';
    $attr_value = 'none';
    $current_route = \Drupal::routeMatch();
    // If view route, means either sorting of filtering is done.
    if ($current_route->getRouteName() == 'views.ajax') {
      $query_string = [];
      parse_str(\Drupal::requestStack()->getCurrentRequest()->getQueryString(), $query_string);
      $view_url_data = $query_string['view_path'];
      $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      // Remove current language from url.
      $view_url_data = preg_replace('/\/' . $current_language . '/', '', $view_url_data, 1);
      // Remove last `/` from url.
      $view_url_data = rtrim($view_url_data, '/');
      if ($source_path = \Drupal::service('path.alias_storage')->lookupPathSource($view_url_data, $current_language)) {
        // Source path will be like - `/node/1212/` and we need only id.
        $nid = explode('/', $source_path)[2];
      }

    }
    elseif ($current_route->getRouteName() == 'entity.node.canonical') {
      $nid = $current_route->getParameter('node')->id();
    }

    // If node object.
    if ((($node = Node::load($nid)) instanceof NodeInterface)
      && $node->bundle() == 'product_list') {
      $attr_value = $node->get('field_attribute_value')->first()->getString();
      $attr_name = $node->get('field_attribute_name')->first()->getString();
    }

    // Add condition on query.
    $db_query->condition('t.' . $attr_name, $attr_value);
  }
}

/**
 * Implements hook_acq_sku_base_fields_updated().
 */
function alshaya_product_list_acq_sku_base_fields_updated(array $fields, $op = 'add') {
  /** @var \Drupal\alshaya_search_api\AlshayaSearchApiFacetsManager $facet_manager */
  $facet_manager = \Drupal::service('alshaya_search_api.facets_manager');

  $facet_source_id = 'search_api:views_block__alshaya_product_list__block_3';
  $filter_bar_id = 'facets_summary.facets_summary.filter_bar_productlist';
  $prefix = 'productlist';

  switch ($op) {
    case 'add':
      foreach ($fields as $field_code => $field) {
        if (empty($field['facet'])) {
          // We use add even when resetting. Remove facet if available.
          $facet_manager->removeFacet($field_code, $filter_bar_id, $prefix);
          continue;
        }

        $facet_manager->createFacet($field_code, $facet_source_id, $filter_bar_id, $prefix, ['name' => $field['label']]);
      }
      break;

    case 'remove':
      foreach ($fields as $field_code => $field) {
        // Remove from facets if facet is 1.
        if (!empty($field['facet'])) {
          $facet_manager->removeFacet($field_code, $filter_bar_id, $prefix);
        }
      }
      break;
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_product_list_module_implements_alter(&$implementations, $hook) {
  // This module alter should be called last.
  if ($hook == 'alshaya_search_filter_link_alter') {
    $group = $implementations['alshaya_product_list'];
    unset($implementations['alshaya_product_list']);
    $implementations['alshaya_product_list'] = $group;
  }
}

/**
 * Implements hook_alshaya_search_filter_link_alter().
 */
function alshaya_product_list_alshaya_search_filter_link_alter(&$link, array &$data) {
  // Get node for given brand and value.
  $nids = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
    ->condition('field_attribute_name', 'attr_' . $data['attribute_code'])
    ->condition('field_attribute_value', $data['attribute_value'])
    ->execute();

  // If there are nodes, use first one.
  if (!empty($nids) && is_array($nids)) {
    $nid = reset($nids);
    $alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $nid);
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $data['append_value'] = FALSE;
    $link = '/' . $langcode . $alias;
  }
}

/**
 * Creating facet blocks and adjusting weights.
 */
function _alshaya_product_list_manage_facet_blocks() {
  $fields = [];

  \Drupal::moduleHandler()->alter('acq_sku_base_field_additions', $fields);

  foreach ($fields as $field_code => $field) {
    /** @var \Drupal\alshaya_search_api\AlshayaSearchApiFacetsManager $facet_manager */
    $facet_manager = \Drupal::service('alshaya_search_api.facets_manager');

    $facet_source_id = 'search_api:views_block__alshaya_product_list__block_3';
    $filter_bar_id = 'facets_summary.facets_summary.filter_bar_productlist';
    $prefix = 'productlist';

    if (empty($field['facet'])) {
      // We use add even when resetting. Remove facet if available.
      $facet_manager->removeFacet($field_code, $filter_bar_id, $prefix);
      continue;
    }

    // Create Facet and their blocks.
    $facet_manager->createFacet($field_code, $facet_source_id, $filter_bar_id, $prefix, ['name' => $field['label']]);
  }

  $current_theme = \Drupal::config('system.theme')->get('default');

  // Move blocks to current default theme.
  if (!empty($current_theme)) {
    alshaya_block_move_blocks_theme_to_theme($current_theme, 'alshaya_white_label');
  }

  // Adjusting weights for facet blocks.
  _alshaya_acm_product_adjust_block_weight('product_list', 'exposedformalshaya_product_listblock_3', 'search_api:views_block__alshaya_product_list__block_3');
}
