<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_commerce\SKUInterface;

/**
 * Implements hook_theme().
 */
function alshaya_click_collect_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['pdp_click_collect_default'] = [
    'render element' => 'elements',
    'variables' => [
      'state' => NULL,
      'sku' => NULL,
      'type' => NULL,
      'title' => NULL,
      'subtitle' => NULL,
      'title_price' => NULL,
      'help_text' => NULL,
      'available_at_title' => NULL,
      'store_finder_form' => NULL,
      'select_option_text' => NULL,
    ],
  ];

  $items['pdp_click_collect_all_stores'] = [
    'render element' => 'elements',
    'variables' => [
      'title' => NULL,
      'subtitle' => NULL,
      'help_text' => NULL,
      'stores' => NULL,
      'available_at_title' => NULL,
      'store_finder_form' => NULL,
    ],
  ];

  $items['pdp_click_collect_top_stores'] = [
    'render element' => 'elements',
    'variables' => [
      'stores' => NULL,
      'has_more' => NULL,
    ],
  ];

  $items['click_collect_stores_list'] = [
    'render element' => 'elements',
    'variables' => [
      'title' => NULL,
      'stores' => NULL,
    ],
  ];

  $items['click_collect_store_info_window_list'] = [
    'render element' => 'elements',
    'variables' => [
      'stores' => NULL,
    ],
  ];

  $items['click_collect_selected_store'] = [
    'render element' => 'elements',
    'variables' => [
      'store' => NULL,
    ],
  ];

  return $items;
}

/**
 * Get click and collect delivery option config.
 *
 * @return array
 *   Return array of config data.
 */
function alshaya_click_collect_get_config() {
  $config = \Drupal::config('alshaya_click_collect.settings');

  $config_data = [
    'title' => $config->get('pdp_click_collect_title'),
    'subtitle' => $config->get('pdp_click_collect_subtitle'),
    'unavailable' => $config->get('pdp_click_collect_unavailable'),
    'title_price' => (float) $config->get('pdp_click_collect_price'),
    'help_text' => $config->get('pdp_click_collect_help_text.value'),
    'select_option_text' => $config->get('pdp_click_collect_select_option_text.value'),
  ];

  \Drupal::moduleHandler()->alter('alshaya_click_and_collect_config', $config_data);
  return $config_data;
}

/**
 * Implements hook_sku_variant_info_alter().
 */
function alshaya_click_collect_sku_variant_info_alter(array &$variant, SKUInterface $child, ?SKUInterface $parent) {
  // Adding shipping options.
  \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');
  $variant['click_collect'] = alshaya_acm_product_available_click_collect($child);
}
