<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\acq_sku\Entity\SKU;
use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_theme().
 */
function alshaya_click_collect_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['pdp_click_collect_default'] = [
    'render element' => 'elements',
    'variables' => [
      'state' => NULL,
      'sku' => NULL,
      'type' => NULL,
      'title' => NULL,
      'subtitle' => NULL,
      'title_price' => NULL,
      'help_text' => NULL,
      'available_at_title' => NULL,
      'store_finder_form' => NULL,
      'select_option_text' => NULL,
    ],
  ];

  $items['pdp_click_collect_all_stores'] = [
    'render element' => 'elements',
    'variables' => [
      'title' => NULL,
      'subtitle' => NULL,
      'help_text' => NULL,
      'stores' => NULL,
      'available_at_title' => NULL,
      'store_finder_form' => NULL,
    ],
  ];

  $items['pdp_click_collect_top_stores'] = [
    'render element' => 'elements',
    'variables' => [
      'stores' => NULL,
      'has_more' => NULL,
    ],
  ];

  $items['click_collect_stores_list'] = [
    'render element' => 'elements',
    'variables' => [
      'title' => NULL,
      'stores' => NULL,
    ],
  ];

  $items['click_collect_store_info_window_list'] = [
    'render element' => 'elements',
    'variables' => [
      'stores' => NULL,
    ],
  ];

  $items['click_collect_selected_store'] = [
    'render element' => 'elements',
    'variables' => [
      'store' => NULL,
    ],
  ];

  return $items;
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function alshaya_click_collect_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() == 'acq_product' && $build['#view_mode'] == 'full') {
    /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
    $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
    $sku = $skuManager->getSkuForNode($entity);
    $sku_entity = SKU::loadFromSku($sku);

    if (empty($sku_entity)) {
      return;
    }

    // Display delivery options only if product is buyable.
    if (!alshaya_acm_product_is_buyable($sku_entity)) {
      return;
    }

    // Adding cache tags for the on-off feature.
    $build['#cache']['tags'][] = 'click-collect-cache-tag';

    // Adding shipping options.
    \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');

    $config = alshaya_click_collect_get_config();

    // Click and collect availability for given sku.
    $state = alshaya_acm_product_available_click_collect($sku);

    // Here we just show static text, we will get stores info using ajax.
    // We need lat/lon info of user to get stores.
    $store_form = \Drupal::formBuilder()->getForm('\Drupal\alshaya_click_collect\Form\ClickCollectAvailableStores');
    $build['click_and_collect'] = [
      '#theme' => 'pdp_click_collect_default',
      '#state' => $state ? 'enabled' : 'disabled',
      '#sku' => $sku,
      '#type' => $sku_entity->bundle(),
      '#title' => $config['title'],
      '#title_price' => alshaya_acm_price_get_formatted_price($config['title_price']),
      '#subtitle' => $state ? $config['subtitle'] : $config['unavailable'],
      '#help_text' => $config['help_text'],
      '#select_option_text' => $config['select_option_text'],
      '#available_at_title' => '',
      '#store_finder_form' => render($store_form),
      '#attached' => [
        'drupalSettings' => [
          'alshaya_click_collect' => [
            'pdp' => ['ajax_call' => FALSE],
            // Default site country to limit autocomplete result.
            'country' => _alshaya_custom_get_site_level_country_code(),
          ],
        ],
        'library' => [
          'alshaya_click_collect/click-and-collect.pdp',
        ],
      ],
    ];
  }
}

/**
 * Get click and collect delivery option config.
 *
 * @return array
 *   Return array of config data.
 */
function alshaya_click_collect_get_config() {
  $config = \Drupal::config('alshaya_click_collect.settings');

  $config_data = [
    'title' => $config->get('pdp_click_collect_title'),
    'subtitle' => $config->get('pdp_click_collect_subtitle'),
    'unavailable' => $config->get('pdp_click_collect_unavailable'),
    'title_price' => (float) $config->get('pdp_click_collect_price'),
    'help_text' => $config->get('pdp_click_collect_help_text.value'),
    'select_option_text' => $config->get('pdp_click_collect_select_option_text.value'),
  ];

  \Drupal::moduleHandler()->alter('alshaya_click_and_collect_config', $config_data);
  return $config_data;
}

/**
 * Implements hook_sku_variant_info_alter().
 */
function alshaya_click_collect_sku_variant_info_alter(array &$variant, SKUInterface $child, ?SKUInterface $parent) {
  // Adding shipping options.
  \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');
  $variant['click_collect'] = alshaya_acm_product_available_click_collect($child);
}

/**
 * Implements hook_block_access().
 */
function alshaya_click_collect_block_access(Block $block, $operation, AccountInterface $account) {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($route !== 'view.stores_finder.page_2') {
    return AccessResult::neutral();
  }

  $blocks_to_check = ['exposedformstores_finderpage_1', 'page_title'];
  if ($operation === 'view' && in_array($block->id(), $blocks_to_check)) {
    $feature_status = \Drupal::config('alshaya_click_collect.settings')->get('feature_status');
    return AccessResult::forbiddenIf($feature_status === 'disabled');
  }

  return AccessResult::neutral();
}
