<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_bnpl_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Need processing only for products with Full view mode.
  if ($entity->bundle() != 'acq_product' || $view_mode != 'full') {
    return;
  }

  // Add Postpay library and its settings.
  /** @var \Drupal\alshaya_bnpl\AlshayaBnplAPIHelper $bnplApiconfig */
  $bnplApiconfig = \Drupal::service('alshaya_bnpl.api_helper')->getBnplApiConfig();
  // No need to integrate the widget if the API does not have merchant id.
  if (!isset($bnplApiconfig['merchant_id']) || empty($bnplApiconfig['merchant_id'])) {
    return;
  }
  $bnplApiconfig['locale'] = 'en';

  /** @var \Drupal\alshaya_bnpl\AlshayaBnplWidgetHelper $bnplWidgetHelper */
  $bnplWidgetHelper = \Drupal::service('alshaya_bnpl.widget_helper');
  $build['postpay'] = $bnplWidgetHelper->getBnplWidgetMarkup();

  $build['#attached'] = [
    'library' => [
      'alshaya_bnpl/postpay_sdk',
      'alshaya_bnpl/postpay_pdp',
    ],
    'drupalSettings' => [
      'postpay' => $bnplApiconfig,
    ],
  ];
}
