<?php

use Drupal\Core\Site\Settings;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function alshaya_rcs_magento_placeholders_page_attachments_alter(array &$attachments) {
  $api_settings = Settings::get('alshaya_api.settings');

  $attachments['#attached']['drupalSettings']['alshayaRcs']['commerceBackend']['baseUrl'] = 'https://' . $_SERVER['HTTP_HOST'];

  // Use proxy on local env as here we don't have Cloudflare.
  if (Settings::get('env') === 'local') {
    $attachments['#attached']['drupalSettings']['alshayaRcs']['commerceBackend']['baseUrl'] = '/proxy/?url=' . $api_settings['magento_host'];
  }

  // Get the current language, and magento language prefix array,
  // And pass the store header info to use in magento API calls.
  $current_language = \Drupal::languageManager()
    ->getCurrentLanguage()
    ->getId();
  $attachments['#attached']['drupalSettings']['alshayaRcs']['commerceBackend']['store'] = Settings::get('magento_lang_prefix')[$current_language];

  // Add 404 redirect url.
  // @see \Drupal\Core\EventSubscriber\CustomPageExceptionHtmlSubscriber.
  $configured_404_page = \Drupal::configFactory()->get('system.site')->get('page.404');
  if (!empty($configured_404_page)) {
    $configured_404_page = \Drupal::service('path_alias.manager')->getAliasByPath($configured_404_page);
    $configured_404_page = '/' . \Drupal::languageManager()->getCurrentLanguage()->getId() . $configured_404_page;
  }
  else {
    // @see \Drupal\Core\EventSubscriber\DefaultExceptionHtmlSubscriber.
    $configured_404_page = Url::fromRoute('system.404')->toString();
  }

  $attachments['#attached']['drupalSettings']['alshayaRcs']['404_page'] = $configured_404_page;
}
