<?php

/**
 * Implements hook_install.
 */
function alshaya_rcs_magento_placeholders_install() {
  // Add rcs_product to the BV routes list.
  $bv_config = \Drupal::configFactory()->getEditable('bazaar_voice.settings');
  $bv_routes_list = $bv_config->get('bv_routes_list');
  $bv_routes_list = array_map('trim', explode(PHP_EOL, $bv_routes_list));
  $bv_routes_list[] = 'entity.node.canonical:rcs_product';
  $bv_routes_list = implode(PHP_EOL, $bv_routes_list);
  $bv_config->set('bv_routes_list', $bv_routes_list)->save();
}
