<?php

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Site\Settings;

/**
 * Implements hook_theme().
 */
function alshaya_rcs_magento_placeholders_theme($existing, $type, $theme, $path) {
  return [
    'node__rcs_product__full' => [
      'variables' => [],
      'base hook' => 'node',
    ],
    'node__rcs_product__full_magazine' => [
      'variables' => [
        'price_block' => [],
      ],
      'base hook' => 'node',
    ],
    'node__rcs_product__full_magazine_v2' => [
      'variables' => [],
    ],
    'rcs_commerce_price' => [
      'variables' => [
        'price' => '',
        'currency_format' => '',
        'currency_code_position' => '',
        'decimal_points' => '',
        'append_each_to_price' => '',
      ],
    ],
    'rcs_price_block' => [
      'variables' => [],
    ],
    'rcs_sku_base_form' => [
      'variables' => [],
    ],
    'page__rcs_pdp' => [
      'variable'
    ],
    'rcs_product_zoom' => [
      'variables' => [
        'mainImage' => '',
        'thumbnails' => '',
        'pager_flag' => '',
        'properties' => '',
        'labels' => '',
        'image_slider_position_pdp' => '',
        'lazy_load_placeholder' => \Drupal::config('alshaya_master.settings')->get('lazy_load_placeholder'),
      ],
    ],
    'product_thumbnails' => [
      'variables' => [],
    ],
    'product_gallery_mobile' => [
      'variables' => [],
    ],
    'form_element_select' => [
      'variables' => [],
    ],
    'rcs_pdp_delivery_option' => [
      'variables' => [],
    ],
    'rcs_pdp_delivery_option_home_delivery' => [
      'render element' => 'elements',
      'variables' => [
        'title' => NULL,
        'title_price' => NULL,
        'subtitle' => NULL,
        'options' => [],
      ],
    ],
    'rcs_pdp_delivery_option_click_and_collect' => [
      'render element' => 'elements',
      'variables' => [
        'state' => NULL,
        'sku' => NULL,
        'type' => NULL,
        'title' => NULL,
        'subtitle' => NULL,
        'title_price' => NULL,
        'help_text' => NULL,
        'available_at_title' => NULL,
        'store_finder_form' => NULL,
        'select_option_text' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function alshaya_rcs_magento_placeholders_page_attachments_alter(array &$attachments) {
  // Add more attributes to the list provided by the rcs_placeholders module.
  $attachments['#attached']['drupalSettings']['rcsPhSettings']['placeholderAttributes'] = array_merge(
    $attachments['#attached']['drupalSettings']['rcsPhSettings']['placeholderAttributes'],
    [
      'data-sku',
      'data-sku-type',
      'data-zoom-url',
      'data-src',
    ],
  );
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * @todo: Change text case to camel case for the drupalsettings.
 */
function alshaya_rcs_magento_placeholders_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() !== 'rcs_product') {
    return;
  }

  $build['price_block'] = [
    '#theme' => 'rcs_commerce_price',
  ];

  $cart_config = \Drupal::config('alshaya_acm.cart_config');
  $build['#attached']['drupalSettings']['alshaya_spc']['cart_config']['max_cart_qty'] = $cart_config->get('max_cart_qty');
  $build['#cache']['tags'] = array_merge($build['#cache']['tags'], $cart_config->getCacheTags());

  $product_settings = \Drupal::config('alshaya_acm_product.settings');
  $build['#attached']['drupalSettings']['vat_text'] = $product_settings->get('vat_text');
  $build['#attached']['drupalSettings']['alshaya_rcs']['pdp_gallery_pager_limit'] = $product_settings->get('pdp_gallery_pager_limit');
  $build['#cache']['tags'] = array_merge($build['#cache']['tags'], $product_settings->getCacheTags());

  $product_display_settings = \Drupal::config('alshaya_acm_product.display_settings');
  $build['#attached']['drupalSettings']['alshaya_rcs']['pdp_swatch_attributes'] = $product_display_settings->get('swatches.pdp');
  $build['#cache']['tags'] = array_merge($build['#cache']['tags'], $product_display_settings->getCacheTags());

  $api_settings = Settings::get('alshaya_api.settings');

  $build['#attached']['drupalSettings']['alshayaRcs']['commerceBackend'] = [
    'baseUrl' => 'https://' . $_SERVER['HTTP_HOST'],
    'languageCode' => \Drupal::languageManager()->getCurrentLanguage()->getId(),
  ];

  // Use proxy on local env as here we don't have Cloudflare.
  if (Settings::get('env') === 'local') {
    $build['#attached']['drupalSettings']['cart']['url'] = '/proxy/?url=' . $api_settings['magento_host'];
  }

  $build['#attached']['drupalSettings']['backend_language_prefix'] = Settings::get('magento_lang_prefix');

  // @todo Work on feedback https://github.com/acquia-pso/alshaya/pull/21185#discussion_r672345369.
  // Add data for showing size guide.
  $build['#attached']['drupalSettings']['alshaya_rcs']['size_guide'] = _alshaya_acm_product_get_size_guide_info(null);
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_rcs_commerce_price(array &$variables) {
  $acm_settings = \Drupal::config('alshaya_acm.settings');

  // With matchback enabled, we will have 'each' word added to price
  // based on the quantity for main product as well as matchback products
  // following the host site implementation.
  $variables['append_each_to_price'] = $acm_settings->get('show_crosssell_as_matchback') && $acm_settings->get('append_each_to_price')
    ? TRUE
    : FALSE;

  $current_language = \Drupal::languageManager()
    ->getConfigOverrideLanguage()
    ->getId();

  if (empty($config_data[$current_language])) {
    $config = \Drupal::configFactory()->get('acq_commerce.currency');
    $config_data[$current_language]['currency_format'] = $config->get('currency_code');
    $config_data[$current_language]['currency_code_position'] = $config->get('currency_code_position');
    $config_data[$current_language]['decimal_points'] = $config->get('decimal_points');
  }

  $variables['currency_format'] = $config_data[$current_language]['currency_format'];
  $variables['currency_code_position'] = $config_data[$current_language]['currency_code_position'];
}

/**
 * Implements hook_preprocess_html().
 */
function alshaya_rcs_magento_placeholders_preprocess_html(array &$variables) {
  $variables['rcs_templates'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => 'hidden',
    ],
  ];

  $price_template = [
    '#theme' => 'rcs_commerce_price',
  ];

  $price_block_template = [
    '#theme' => 'rcs_price_block'
  ];

  $variables['rcs_templates']['price'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => render($price_template),
    '#attributes' => [
      'class' => 'rcs-templates--price',
    ],
  ];

  $variables['rcs_templates']['price_block'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => render($price_block_template),
    '#attributes' => [
      'class' => 'rcs-templates--price_block',
    ],
  ];

  $product_thumbnails_template = [
    '#theme' => 'product_thumbnails',
  ];
  $variables['rcs_templates']['product_thumbnails'] = [
    '#type' => 'html_tag',
    '#tag' => 'ul',
    '#value' => render($product_thumbnails_template),
    '#attributes' => [
      'class' => 'rcs-templates--product_thumbnails',
    ],
  ];

  $product_gallery_mobile_template = [
    '#theme' => 'product_gallery_mobile',
  ];
  $variables['rcs_templates']['product_gallery_mobile'] = [
    '#type' => 'html_tag',
    '#tag' => 'ul',
    '#value' => render($product_gallery_mobile_template),
    '#attributes' => [
      'class' => 'rcs-templates--product_gallery_mobile',
    ],
  ];

  $form_element_select_template = [
    '#theme' => 'form_element_select',
  ];
  $variables['rcs_templates']['form_element_select'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => render($form_element_select_template),
    '#attributes' => [
      'class' => 'rcs-templates--form_element_select',
    ],
  ];


  $delivery_option = [
    '#theme' => 'rcs_pdp_delivery_option',
  ];
  $variables['rcs_templates']['delivery_option'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => render($delivery_option),
    '#attributes' => [
      'class' => 'rcs-templates--delivery_option',
    ],
  ];

  $delivery_option_home_delivery = [
    '#theme' => 'rcs_pdp_delivery_option_home_delivery',
  ];
  $variables['rcs_templates']['home_delivery'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => render($delivery_option_home_delivery),
    '#attributes' => [
      'class' => 'rcs-templates--delivery_option-home-delivery',
    ],
  ];

  $delivery_option_click_and_collect = [
    '#theme' => 'rcs_pdp_delivery_option_click_and_collect',
  ];
  $variables['rcs_templates']['click_and_collect'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => render($delivery_option_click_and_collect),
    '#attributes' => [
      'class' => 'rcs-templates--delivery_option-click-and-collect',
    ],
  ];

  if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::request()->attributes->get('node');
    if ($node->bundle() == 'rcs_product') {
      // Add classes to keep the styling same as acq_product node.
      $variables['attributes']['class'][] = 'nodetype--acq_product';
    }
  }
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function alshaya_rcs_magento_placeholders_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::request()->attributes->get('node');
    if ($node->bundle() == 'rcs_product') {
      $suggestions[] = 'page__rcs_pdp';
    }
  }
}

/**
 * Implements hook_theme_suggestions_product_zoom_alter().
 */
function alshaya_rcs_magento_placeholders_theme_suggestions_product_zoom_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'rcs_product_zoom';
}

/**
 * Implememts template_preprocess_HOOK().
 */
function template_preprocess_rcs_pdp_delivery_option_home_delivery(array &$variables) {
  $home_delivery_config = alshaya_acm_product_get_home_delivery_config();

  $variables['title'] = $home_delivery_config['title'];
  $variables['subtitle'] = $home_delivery_config['subtitle'];
  $variables['options'] = [
    'standard_title' => $home_delivery_config['standard_title'],
    'standard_subtitle' => $home_delivery_config['standard_subtitle'],
  ];
  $variables['#cache']['tags'] = \Drupal::config('alshaya_acm_product.home_delivery')->getCacheTags();
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_rcs_pdp_delivery_option_click_and_collect(array &$variables) {
  $cnc_settings = \Drupal::config('alshaya_click_collect.settings');

  // Adding shipping options.
  \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');

  $config = alshaya_click_collect_get_config();

  // Here we just show static text, we will get stores info using ajax.
  // We need lat/lon info of user to get stores.
  $store_form = \Drupal::formBuilder()->getForm('\Drupal\alshaya_click_collect\Form\ClickCollectAvailableStores');

  $variables['state'] = '';
  $variables['sku'] = '';
  $variables['type'] = '';
  $variables['title'] = $config['title'];
  $variables['title_price'] = alshaya_acm_price_get_formatted_price($config['title_price']);
  $variables['subtitle'] = [
    'enabled' => $config['subtitle'],
    'disabled' => $config['unavailable'],
  ];
  $variables['help_text'] = $config['help_text'];
  $variables['select_option_text'] = $config['select_option_text'];
  $variables['store_finder_form'] = render($store_form);
  $variables['#attached'] = [
    'drupalSettings' => [
      'alshaya_click_collect' => [
        'pdp' => ['ajax_call' => FALSE],
        // Default site country to limit autocomplete result.
        'country' => _alshaya_custom_get_site_level_country_code(),
        'status' => $cnc_settings->get('feature_status'),
        'subtitle' => [
          'enabled' => $config['subtitle'],
          'disabled' => $config['unavailable'],
        ],
      ],
    ],
    'library' => [
      'alshaya_click_collect/click-and-collect.pdp',
    ],
  ];

  $variables['#cache']['tags'] = $cnc_settings->getCacheTags();
  // Adding cache tags for the on-off feature.
  $variables['#cache']['tags'][] = 'click-collect-cache-tag';
}
