<?php

/**
 * @file
 * Provides base hooks to the cart functionality of Acquia Commerce connector.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function acq_cart_preprocess_acq_sku(&$variables) {
  // We would rather allow modules to implement the preprocess hook directly,
  // however the main issue there is that we can't disable cart separately so
  // we provide a hook that's only called if this module is enabled on display.
  \Drupal::moduleHandler()->alter('add_to_cart_display', $variables);
}

/**
 * Implements hook_theme().
 */
function acq_cart_theme($existing, $type, $theme, $path) {
  // Fetch the config.
  $config = \Drupal::configFactory()
    ->get('acq_commerce.currency');

  // Fetch the currency format from the config factor.
  $currency_format = $config->get('currency_code');

  // Fetch the currency code position.
  $currency_code_position = $config->get('currency_code_position');

  return [
    'acq_cart_mini_cart' => [
      'variables' => [
        'quantity' => 0,
        'total' => NULL,
      ],
      'template' => 'block--acqminicart',
    ],
  ];
}

/**
 * Implements hook_user_logout().
 */
function acq_cart_user_logout($account) {
  $cookies = \Drupal::request()->cookies->all();
  if (isset($cookies['Drupal_visitor_acq_cart_id'])) {
    user_cookie_delete('acq_cart_id');
  }
}
