<?php

/**
 * @file
 * Contains Aura related static strings.
 */

/**
 * Aura static strings.
 */
function _alshaya_aura_static_strings() {
  return [
    [
      'key' => 'form_error_valid_mobile_number',
      'value' => t('Please enter valid mobile number.'),
    ],
    [
      'key' => 'form_error_mobile_number',
      'value' => t('Please enter mobile number.'),
    ],
    [
      'key' => 'form_error_otp',
      'value' => t('Please enter OTP.'),
    ],
    [
      'key' => 'otp_send_message',
      'value' => t('We’ve sent the one time PIN to your mobile number.'),
    ],
    [
      'key' => 'didnt_receive_otp_message',
      'value' => t('Didn’t receive your one time PIN?'),
    ],
    [
      'key' => 'send_otp_helptext',
      'value' => t('We’ll send a one time PIN to your mobile number.'),
    ],
    [
      'key' => 'verify',
      'value' => t('Verify'),
    ],
    [
      'key' => 'otp_button_label',
      'value' => t('Send One Time PIN'),
    ],
    [
      'key' => 'otp_modal_title',
      'value' => t('Say hello to AURA'),
    ],
    [
      'key' => 'resend_code',
      'value' => t('Resend code'),
    ],
    [
      'key' => 'mobile_label',
      'value' => t('Mobile Number'),
    ],
    [
      'key' => 'otp_label',
      'value' => t('One time PIN'),
    ],
    [
      'key' => 'form_error_full_name',
      'value' => t('Please enter your full name.'),
    ],
    [
      'key' => 'form_error_email',
      'value' => t('Please enter email.'),
    ],
    [
      'key' => 'form_error_email_not_valid',
      'value' => t('The email address %mail is not valid.'),
    ],
    [
      'key' => 'form_error_invalid_otp',
      'value' => t('The OTP is not valid. Please try again.'),
    ],
    [
      'key' => 'form_error_send_otp_failed_message',
      'value' => t('Error in sending OTP. Please try again.'),
    ],
    [
      'key' => 'form_error_sign_up_failed_message',
      'value' => t('Error in sign up. Please try again.'),
    ],
    [
      'key' => 'form_error_mobile_already_registered',
      'value' => t('This mobile number is already registered.'),
    ],
    [
      'key' => 'form_error_email_already_registered',
      'value' => t('This email address is already registered.'),
    ],
    [
      'key' => 'form_error_empty_card',
      'value' => t('Please enter card number.'),
    ],
    [
      'key' => 'form_error_empty_points',
      'value' => t('Please enter points.'),
    ],
    [
      'key' => 'form_error_mobile_not_found',
      'value' => t('No mobile number found. Please try again.'),
    ],
  ];
}
