<?php

/**
 * @file
 * Contains Aura related translations.
 */

/**
 * Aura translation.
 */
function _alshaya_aura_react_translations() {
  return [
    'My AURA' => [
      'ar' => 'حساب أورا الخاص بي',
    ],
    'Already an AURA member?' => [
      'ar' => 'هل أنت عضو في أورا؟',
    ],
    'Link your card' => [
      'ar' => 'قم بربط بطاقتك',
    ],
    'Ready to be rewarded?' => [
      'ar' => 'هل أنت مستعد للمكافآت؟',
    ],
    'Sign up now' => [
      'ar' => 'تسجيل الاشتراك الآن',
    ],
    'Congrats! You are now part of the exclusive AURA club. You’ll now earn points as you shop online and in stores.' => [
      'ar' => 'تهانينا! أنت الآن جزء من نادي أورا الحصري. سوف تربح الآن نقاط أثناء التسوق أونلاين وفي المحلات.',
    ],
    'To use your points online, please download the AURA app and provide us with a few more details.' => [
      'ar' => 'يرجى تنزيل تطبيق أورا وتزويدنا ببعض التفاصيل الإضافية وذلك لاستخدام النقاط عبر أونلاين.',
    ],
    'An AURA card is already associated with your email address. Link your card in just one click.' => [
      'ar' => 'يُمكنك ربط بطاقة أورا ببريدك الإلكتروني من خلال ضغطة زر واحدة.',
    ],
    'Do you want to link now?' => [
      'ar' => 'هل ترغب في الربط الآن؟',
    ],
    'Not you?' => [
      'ar' => 'ليس أنت؟',
    ],
    'Card number' => [
      'ar' => 'رقم البطاقة',
    ],
    'Status' => [
      'ar' => 'مستوى العضوية',
    ],
    'Point balance' => [
      'ar' => 'رصيد النقاط',
    ],
    'points' => [
      'ar' => 'النقاط',
    ],
    'Points on hold' => [
      'ar' => 'النقاط قيد الانتظار',
    ],
    'Rewards activity' => [
      'ar' => 'تفاصيل المكافآت',
    ],
    'Loyalty Benefits' => [
      'ar' => 'مكافآت الولاء',
    ],
    'Your points will instantly be credited to your account. You’ll be able to redeem them after 14 days as per the returns & refunds policies.' => [
      'ar' => 'سيتم إضافة نقاطك على الفور إلى حسابك، سوف تتمكن من استبدال النقاط بعد 14 يوم طبقاً لسياسات الاسترداد والإرجاع.',
    ],
    'Say hello to AURA' => [
      'ar' => 'مرحباً بكم في أورا',
    ],
    'Send one time PIN' => [
      'ar' => 'إرسال رمز الاستخدام لمرة واحدة',
    ],
    'Resend code' => [
      'ar' => 'إعادة إرسال الرمز',
    ],
    'One time PIN' => [
      'ar' => 'رمز الاستخدام لمرة واحدة',
    ],
    'Country Code' => [
      'ar' => 'رمز الدولة',
    ],
    'We’ll send a one time PIN to your mobile number.' => [
      'ar' => 'سنقوم بإرسال رمز للاستخدام لمرة واحدة إلى رقم الهاتف',
    ],
    'We’ve sent the one time PIN to your mobile number.' => [
      'ar' => 'لقد قمنا بإرسال رمز للاستخدام لمرة واحدة إلى رقم الهاتف',
    ],
    'Didn’t receive your one time PIN?' => [
      'ar' => 'لم يصلكم رمز الاستخدام لمرة واحدة؟',
    ],
    'Verify' => [
      'ar' => 'تأكيد',
    ],
    'By clicking submit, you agree to have read and accepted our' => [
      'ar' => 'بالضغط على زر إرسال، فأنكم توافقون على الخاصة بنا',
    ],
    'Terms & Conditions' => [
      'ar' => 'البنود و الظروف',
    ],
    'The OTP is not valid. Please try again.' => [
      'ar' => 'رمز الاستخدام لمرة واحدة غير صالح. يرجى المحاولة لاحقاً.',
    ],
    'The OTP couldn’t be verified. Please try again.' => [
      'ar' => 'لم يتم تأكيد رمز الاستخدام لمرة واحدة. يرجى المحاولة لاحقاً.',
    ],
    'This mobile number is already registered.' => [
      'ar' => 'رقم الهاتف مسجل من قبل',
    ],
    'This email address is already registered.' => [
      'ar' => 'عنوان البريد الإلكتروني مسجل من قبل',
    ],
    'Earn AURA points every time you shop! You can redeem your points to use on future purchases. Not applicable on purchases made using AURA points.' => [
      'ar' => 'اربح نقاط أورا في كل مرة تتسوق فيها! يمكنك استبدال نقاطك لاستخدامها في عمليات الشراء المستقبلية. لا ينطبق على عمليات الشراء التي تتم باستخدام نقاط أورا.',
    ],
    'AURA points' => [
      'ar' => 'نقاط أورا',
    ],
    'Earn' => [
      'ar' => 'اربح',
    ],
    'Bespoke rewards.' => [
      'ar' => 'مكافآت بلا حدود.',
    ],
    'Bespoke lifestyles.' => [
      'ar' => 'أسلوب حياة أفضل.',
    ],
    'Good things come to those with taste. Say hello to AURA, a lifestyle program catered to your taste for refined brands and experiences.' => [
      'ar' => 'لأن أصحاب الذوق الرفيع يستحقون كل ما هو أفضل. مرحباً بكم في أورا، برنامج المكافآت الذي يقدم لكم ماركاتكم المفضلة من خلال تجربة تسوق تُحسن أسلوب حياتكم.',
    ],
    'Sign up now' => [
      'ar' => 'تسجيل الاشتراك الآن',
    ],
    'Learn more' => [
      'ar' => 'تعرف على المزيد',
    ],
    'Your AURA card number' => [
      'ar' => 'رقم بطاقة أورا الخاصة بك',
    ],
    'Sign in or create an account to use your points.' => [
      'ar' => 'سجل الدخول أو أنشيء حساب جديد لاستخدام النقاط',
    ],
    'Aura rewards' => [
      'ar' => 'مكافآت أورا',
    ],
    '(Optional)' => [
      'ar' => 'اختياري',
    ],
  ];
}
