<?php

/**
 * @file
 * Contains Aura related translations.
 */

/**
 * Aura translation.
 */
function _alshaya_aura_react_translations() {
  return [
    'v1' => [
      'My Aura' => [
        'ar' => 'حساب أورا الخاص بي',
      ],
      'Already an Aura member?' => [
        'ar' => 'هل أنت عضو في أورا؟',
      ],
      'Link your account' => [
        'ar' => 'قم بربط حسابك',
      ],
      'Ready to be rewarded?' => [
        'ar' => 'هل أنت جاهز للمكافآت؟',
      ],
      'Sign up now' => [
        'ar' => 'تسجيل الاشتراك الآن',
      ],
      'Do you want to link now?' => [
        'ar' => 'هل ترغب في الربط الآن؟',
      ],
      'Not you?' => [
        'ar' => 'ليس أنت؟',
      ],
      'Card number' => [
        'ar' => 'رقم البطاقة',
      ],
      'Status' => [
        'ar' => 'مستوى العضوية',
      ],
      'status' => [
        'ar' => 'مستوى العضوية',
      ],
      'Point balance' => [
        'ar' => 'رصيد النقاط',
      ],
      'points' => [
        'ar' => 'النقاط',
      ],
      'Points on hold' => [
        'ar' => 'النقاط قيد الانتظار',
      ],
      'Aura activity' => [
        'ar' => 'تفاصيل المكافآت',
      ],
      'Aura benefits' => [
        'ar' => 'مميزات أورا',
      ],
      'Say hello to Aura' => [
        'ar' => 'مرحباً بكم في أورا',
      ],
      'Send One Time PIN' => [
        'ar' => 'إرسال رمز الاستخدام لمرة واحدة',
      ],
      'Resend code' => [
        'ar' => 'إعادة إرسال الرمز',
      ],
      'OTP' => [
        'ar' => 'OTP',
      ],
      'Country Code' => [
        'ar' => 'رمز الدولة',
      ],
      'We’ll send a one time PIN to your mobile number.' => [
        'ar' => 'سنقوم بإرسال رمز للاستخدام لمرة واحدة إلى رقم الهاتف',
      ],
      'We’ve sent the one time PIN to your mobile number.' => [
        'ar' => 'لقد قمنا بإرسال رمز للاستخدام لمرة واحدة إلى رقم الهاتف',
      ],
      'Didn’t receive your one time PIN?' => [
        'ar' => 'لم يصلكم رمز الاستخدام لمرة واحدة؟',
      ],
      'Verify' => [
        'ar' => 'تأكيد',
      ],
      'Terms & Conditions' => [
        'ar' => 'البنود و الظروف',
      ],
      'Incorrect OTP. Please enter a valid OTP.' => [
        'ar' => 'رمز تحقق OTP غير صحيح. يرجى إعادة إدخال رمز تحقق OTP صالح',
      ],
      'The OTP couldn’t be verified. Please try again.' => [
        'ar' => 'لم يتم تأكيد رمز الاستخدام لمرة واحدة. يرجى المحاولة لاحقاً.',
      ],
      'This phone number is already registered. Please sign-in or use a different phone number.' => [
        'ar' => 'رقم الهاتف مسجل لدينا بالفعل. يرجى تسجيل الدخول أو استخدام رقم هاتف مختلف',
      ],
      'This email address is already registered. Please sign-in or use a different email address.' => [
        'ar' => 'البريد الإلكتروني مسجل لدينا بالفعل. يرجى تسجيل الدخول أو استخدام بريد إلكتروني مختلف',
      ],
      'Join Aura, our new loyalty programme, to earn and spend points while you shop, and discover exclusive benefits. Points are not earned on purchases made with points.' => [
        'ar' => 'اشترك في أورا، برنامج المكافآت الجديد، لاكتساب وصرف النقاط أثناء التسوق، واكتشف الكثير من المميزات الحصرية. لا يتم اكتساب النقاط عند الشراء باستخدام النقاط المجمعة مسبقاً.',
      ],
      'Aura points' => [
        'ar' => 'نقاط أورا',
      ],
      'Earn' => [
        'ar' => 'اربح',
      ],
      'points to reach' => [
        'ar' => 'نقاط التواصل',
      ],
      'Bespoke rewards.' => [
        'ar' => 'مكافآت بلا حدود.',
      ],
      'Personalised for you.' => [
        'ar' => 'مخصص لك.',
      ],
      'Your Aura card number' => [
        'ar' => 'رقم بطاقة أورا الخاصة بك',
      ],
      'Sign in or create an account to use your points.' => [
        'ar' => 'سجل الدخول أو أنشيء حساب جديد لاستخدام النقاط',
      ],
      'Experience Aura' => [
        'ar' => 'جرّب أورا',
      ],
      '(Optional)' => [
        'ar' => 'اختياري',
      ],
      'pts' => [
        'ar' => 'النقاط',
      ],
      'Try again' => [
        'ar' => 'المحاولة مرة أخرى',
      ],
      'Apply' => [
        'ar' => 'التقديم',
      ],
      'Unexpected error occured.' => [
        'ar' => 'حدث خطأ غير متوقع.',
      ],
      'Not a member yet?' => [
        'ar' => 'لست عضواً بعد؟',
      ],
      'Enter Aura Card Number' => [
        'ar' => 'إدخال رقم بطاقة أورا',
      ],
      'Please enter a valid phone number.' => [
        'ar' => 'يرجى إدخال رقم هاتف صحيح.',
      ],
      'Please enter phone number.' => [
        'ar' => 'يرجى إدخال رقم هاتف صحيح.',
      ],
      'Please enter OTP.' => [
        'ar' => 'يرجى إدخال رمز الاستخدام لمرة واحدة.',
      ],
      'Error in sign up. Please try again.' => [
        'ar' => 'خطأ في تسجيل الاشتراك. يرجى المحاولة مرة أخرى.',
      ],
      'Error in sending OTP. Please try again.' => [
        'ar' => 'خطأ في رمز الاستخدام لمرة واحدة. يرجى المحاولة مرة أخرى.',
      ],
      'Please enter card number.' => [
        'ar' => 'يرجى إدخال رقم البطاقة.',
      ],
      'Please enter points.' => [
        'ar' => 'يرجى إدخال النقاط.',
      ],
      'No mobile number found. Please try again.' => [
        'ar' => 'لم يتم العثور على رقم هاتف محمول. يرجى المحاولة مرة أخرى.',
      ],
      'Link Now' => [
        'ar' => 'الربط الآن',
      ],
      'Link card using' => [
        'ar' => 'ربط البطاقة باستخدام',
      ],
      'Incorrect Aura card number. Please re-enter a valid Aura card number.' => [
        'ar' => 'رقم AURA غير صحيح. يرجى إعادة إدخال رقم بطاقة AURA صحيح.',
      ],
      'Full name' => [
        'ar' => 'الاسم بالكامل',
      ],
      'Earn Aura points' => [
        'ar' => 'اربح نقاط أورا',
      ],
      'Say hello to' => [
        'ar' => 'مرحباً بكم في',
      ],
      'Paid With Aura' => [
        'ar' => 'الدفع مع أورا',
      ],
      'Balance Payable' => [
        'ar' => 'الرصيد المستحق الدفع',
      ],
      'To automatically collect and spend points on all your purchases, please' => [
        'ar' => 'لجمع النقاط وإنفاقها بشكل تلقائي في جميع عمليات الشراء، الرجاء',
      ],
      'link your account now' => [
        'ar' => 'قم بربط البطاقة الآن',
      ],
      'You have' => [
        'ar' => 'لديك',
      ],
      'You will earn' => [
        'ar' => 'سوف تربح',
      ],
      'with this purchase' => [
        'ar' => 'مع عملية الشراء هذه',
      ],
      'Earn and spend as you shop' => [
        'ar' => 'اكسب النقاط وأنفقها خلال عملية الشراء',
      ],
      'Aura points earned' => [
        'ar' => 'نقاط أورا المكتسبة',
      ],
      'You can redeem maximum' => [
        'ar' => 'يُمكنك استبدال نقاط بحد أقصى',
      ],
      'worth' => [
        'ar' => 'ما يعادل',
      ],
      'have been successfully redeemed' => [
        'ar' => 'تم استبدالها بنجاح',
      ],
      'Use your points' => [
        'ar' => 'استخدم نقاطك',
      ],
      'Use points' => [
        'ar' => 'استخدم النقاط',
      ],
      'Remove' => [
        'ar' => 'إزالة',
      ],
      'Aura points redeemed' => [
        'ar' => 'نقاط أورا التي تم استبدالها',
      ],
      'Members will earn' => [
        'ar' => 'سوف يربح الأعضاء',
      ],
      'will expire by' => [
        'ar' => 'ستنتهي بحلول',
      ],
      'Experience Aura' => [
        'ar' => 'جرّب أورا',
      ],
      'points with this purchase' => [
        'ar' => 'النقاط في عملية الشراء الحالية',
      ],
      'On completion of this purchase you will earn:' => [
        'ar' => 'عند إتمام عملية الشراء هذه، سوف تربح:',
      ],
      'Sign in' => [
        'ar' => 'تسجيل الدخول',
      ],
      'A phone number is required to sign-up. Please enter your details to proceed.' => [
        'ar' => 'رقم الهاتف مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
      ],
      'Your full name is required to sign-up. Please enter your details to proceed.' => [
        'ar' => 'الاسم الكامل مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
      ],
      'Please enter a valid email address.' => [
        'ar' => 'يرجى إدخال بريد إلكتروني صالح.',
      ],
      'An email address is required to sign-up. Please enter your details to proceed.' => [
        'ar' => 'البريد الإلكتروني مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
      ],
      'A phone number is required to link your card. Please enter your details to proceed.' => [
        'ar' => 'رقم الهاتف مطلوب لربط البطاقة. يرجى إدخال بياناتك للمتابعة.',
      ],
      'An email address is required to link your card. Please enter your details to proceed.' => [
        'ar' => 'البريد الإلكتروني مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
      ],
      'This phone number isn’t registered. Please enter the same number used during sign-up.' => [
        'ar' => 'رقم الهاتف غير مسجل. يرجى إدخال نفس الرقم المستخدم أثناء التسجيل.',
      ],
      'This email address isn’t registered. Please enter the same email address used during sign-up.' => [
        'ar' => 'البريد الإلكتروني غير مسجل. يرجى إدخال نفس البريد الإلكتروني المستخدم أثناء التسجيل.',
      ],
      'Incorrect AURA card number. Please re-enter a valid AURA card number.' => [
        'ar' => 'رقم AURA غير صحيح. يرجى إعادة إدخال رقم بطاقة AURA الصحيح.',
      ],
      'Your request couldn’t be processed. Please try again shortly.' => [
        'ar' => 'لا يمكن إتمام طلبك. يرجى المحاولة مرة أخرى',
      ],
      'The number of points exceeds your order total. Please re-enter the number of points you’d like to redeem.' => [
        'ar' => 'عدد النقاط يتجاوز إجمالي الطلبية. يرجى إعادة إدخال رقم النقاط التي ترغب في استخدامها.',
      ],
      'The number you’ve entered is invalid. Please re-enter the number of points you’d like to redeem.' => [
        'ar' => 'الرقم الذي أدخلته غير صحيح. يرجى إعادة إدخال رقم النقاط التي ترغب في استخدامها.',
      ],
      'Online' => [
        'ar' => 'خارج الشبكة',
      ],
      'Offline' => [
        'ar' => 'على الانترنت',
      ],
      'Instore' => [
        'ar' => 'في المحلات',
      ],
      'All Transactions' => [
        'ar' => 'جميع المعاملات',
      ],
      'Online / Instore' => [
        'ar' => 'على الانترنت / في المحلات',
      ],
      'Order No.' => [
        'ar' => 'رقم الطلب',
      ],
      'Cash on delivery is not available along with the Aura points.' => [
        'ar' => 'الدفع نقداً عند الاستلام غير متوفر للاستخدام مع نقاط أورا.',
      ],
      'Aura points can not be redeemed with cash on delivery.' => [
        'ar' => 'لا يمكن استبدال نقاط أورا عند استخدام خيار الدفع عند الاسلام.',
      ],
      'Aura account number' => [
        'ar' => 'رقم حساب أورا',
      ],
      'My tier' => [
        'ar' => 'باقتي',
      ],
      'Points balance' => [
        'ar' => 'رصيد النقاط',
      ],
      'Pending points' => [
        'ar' => 'النقاط المعلقة',
      ],
      'Enjoy offers and rewards? Join Aura, our new loyalty programme, to earn and spend points while you shop, and discover exclusive benefits.' => [
        'ar' => 'هل تود الاستمتع بالنقاط والمكافآت؟ ا انضم إلى أورا، برنامج المكافآت الجديد لتجميع النقاط وإنفاقها أثناء الشراء واكتشف العديد من المميزات الحصرية.',
      ],
      'Add your mobile number, Aura account number or email address below to link this purchase.' => [
        'ar' => 'أضف رقم الهاتف، أو رقم حساب أورا أو بريدك الإلكتروني في الأسفل لربط عملية الشراء الحالية.',
      ],
      'Brand' => [
        'ar' => 'الماركة',
      ],
      'Points Earned' => [
        'ar' => 'النقاط المكتسبة',
      ],
      'Points Redeemed' => [
        'ar' => 'النقاط التي تم استبدالها',
      ],
      'Join now' => [
        'ar' => 'اشترك الآن',
      ],
      'Already a member? Add your account details at checkout.' => [
        'ar' => 'هل أنت عضو بالفعل؟ أضف تفاصيل حسابك عند الدفع.',
      ],
      'Join Aura, our new loyalty programme, to earn and spend points while you shop, and discover exclusive benefits.' => [
        'ar' => ' انضم إلى أورا، برنامج المكافآت الجديد لتجميع النقاط وإنفاقها أثناء الشراء واكتشف العديد من المميزات الحصرية.',
      ],
      'As an Aura member, collect points every time you shop to spend on future purchases, and to unlock exclusive rewards.' => [
        'ar' => 'كعضو في أورا، يمكنك تجميع النقاط مع كل عملية شراء وإنفاقها في عمليات الشراء المستقبلية، إضافة إلى الحصول على الكثير من المكافآت الحصرية.',
      ],
      'points with Aura' => [
        'ar' => 'النقاط مع أورا',
      ],
      'About Aura' => [
        'ar' => 'حول أورا',
      ],
      'Join Aura to earn and spend points while you shop and enjoy exclusive benefits.' => [
        'ar' => 'اشترك في أورا واستمتع بتجميع النقاط وإنفاقها أثناء التسوق واحصل على مميزات حصرية.',
      ],
      'You currently have no Aura linked transactions.' => [
        'ar' => 'ليس لديك عمليات مرتبطة بحساب أورا حالياً',
      ],
      'To see your offers and rewards, visit your AURA MENA app or' => [
        'ar' => 'لمعرفة العروض والمكافآت الخاصة بك، قم بزيارة تطبيق أورا أو',
      ],
    ],
    'v2' => [
      'You are here' => [
        'ar' => 'أنت هنا',
      ],
      'An Aura card is already associated with your email address. Link your card in just one click.' => [
        'ar' => 'يمكنك ربط برنامج المكافآت أورا بعنوان بريدكالإلكتروني بضغطة واحدة فقط',
      ],
      'Your points for this purchase will be added to your account.' => [
        'ar' => 'سيتم إضافة النقاط الخاصة بك إلى هذاالحساب.',
      ],
      'By clicking submit, you agree to have read and accepted our' => [
        'ar' => 'عند الضغط على إرسال، أنت تقر بأنك قرأت ووافقت على',
      ],
    ],
    'v3' => [
      'You can only redeem full pending balance or use other payment method.' => [
        'ar' => 'يمكنك استرداد الرصيد المعلق بالكامل أو استخدام وسيلة دفع أخرى.',
      ],
    ],
    'v4' => [
      // To do- translation should be checked once we get it from alshaya.
      'Redeem' => [
        'ar' => 'يسترد',
        'context' => 'aura',
      ],
      // To do- translation should be checked once we get it from alshaya.
      'Aura points with this purchase.' => [
        'ar' => 'نقاط Aura مع هذا الشراء.',
        'context' => 'aura',
      ],
      'with this purchase.' => [
        'ar' => 'مع عملية الشراء هذه.',
        'context' => 'aura',
      ],
      'or' => [
        'ar' => 'أو',
        'context' => 'aura',
      ],
      'Join Aura' => [
        'ar' => 'انضم إلى أورا',
        'context' => 'aura',
      ],
      'to earn <b>!pts</b> points on this purchase.' => [
        'ar' => 'للفوز <b>!pts</b> بنقاط عند إتمام عملية الشراء.',
        'context' => 'aura',
      ],
      'To redeem points download Aura app.' => [
        'ar' => 'لاستبدال النقاط قم بتحميل أورا تطبيق.',
        'context' => 'aura',
      ],
      'App Store' => [
        'ar' => 'آب ستور',
        'context' => 'aura',
      ],
      'Play Store.' => [
        'ar' => 'بلاي ستور',
        'context' => 'aura',
      ],
      // We are using !pts as it does not encode the html into string while
      // using this in Drupal t() function.
      'Earn <span><b>!pts</b> points with Aura</span> on this purchase. To redeem points, complete your registration on the Aura MENA app.' => [
        'ar' => "يكسب <span><b>!pts</b> النقاط مع الهالة</span>على هذا الشراء. لاسترداد النقاط ، أكمل تسجيلك في تطبيق Aura MENA.",
        'context' => 'aura',
      ],
      'Congratulations' => [
        'ar' => 'تهانينا',
        'context' => 'aura',
      ],
      'You can now start building your Aura. Earn points when you shop online or in-store.' => [
        'ar' => 'يمكنك الآن البدء في بناء أورا الخاص بك. اكسب نقاط أورا عند التسوق أونلاين أو في المحلات.',
        'context' => 'aura',
      ],
      'To spend your points, complete your registration on the Aura MENA app, available on the App store and Google Play.' => [
        'ar' => 'لاستخدام النقاط في الشراء، استكمل عملية التسجيل في تطبيق أورا MENA، متوفر على آب ستور وجوجل بلاي.',
        'context' => 'aura',
      ],
      "By pressing submit, you agree to have read and accepted our <a href='!tncLink' target='_blank'>Terms & Conditions</a>" => [
        'ar' => "الضغط على زر إرسال يعني قراءتك وموافقتك على<a href='!tncLink' target='_blank'>شروطنا وأحكامنا</a>",
        'context' => 'aura',
      ],
      'Already a member?' => [
        'ar' => 'هل أنت عضو بالفعل؟',
        'context' => 'aura',
      ],
      'You will earn @pts Aura points with this purchase.' => [
        'ar' => 'سوف تفوز @pts بنقاط أورا عند إتمام عملية الشراء.',
        'context' => 'aura',
      ],
      'You will earn @pts @aura_icon points.' => [
        'ar' => 'سوف تكسب aura_icon @pts@ النقاط.',
        'context' => 'aura',
      ],
      'Earn and spend points when you shop at your favourite brands and unlock exclusive benefits. <a href="@know_more_link" target="_blank" rel="noopener noreferrer">Learn more</a>' => [
        'ar' => 'اكسب النقاط وأنفقها عند التسوق من ماركاتك المفضلة واحصل على مزايا حصرية. <a href="@know_more_link" target="_blank" rel="noopener noreferrer"> أعرف أكثر</a>',
        'context' => 'aura',
      ],
      '@aura_icon Redeem your points' => [
        'ar' => '@aura_icon تفعيل النقاط',
        'context' => 'aura',
      ],
      'You have @pts points' => [
        'ar' => 'متوفر لديك @pts نقاط',
        'context' => 'aura',
      ],
      '@pts points will expire by @date.' => [
        'ar' => '@pts تنتهي صلاحية النقاط بتاريخ @date.',
        'context' => 'aura',
      ],
      'Earn <span><b>@pts points with Aura</b></span> on this purchase' => [
        'ar' => 'اكسب <span><b>@ptsنقاط مع أورا</b></span> عند إتمام عملية الشراء ',
        'context' => 'aura',
      ],
      'Earn with Aura' => [
        'ar' => 'اكسب مع أورا',
        'context' => 'aura',
      ],
      'Link your Aura with' => [
        'ar' => 'اربط حساب أورا مع',
        'context' => 'aura',
      ],
      'Enter your details to earn points on this order.' => [
        'ar' => 'أدخل بياناتك للفوز بنقاط أورا على هذه الطلبية',
        'context' => 'aura',
      ],
      'Link your card' => [
        'ar' => 'اربط بطاقتك',
        'context' => 'aura',
      ],
      'Send OTP' => [
        'ar' => 'أرسل رمز التحقق',
        'context' => 'aura',
      ],
      'Apply' => [
        'ar' => 'قدّم',
        'context' => 'aura',
      ],
      'Link Now' => [
        'ar' => 'اربط الآن',
        'context' => 'aura',
      ],
      'Didn’t receive the OTP?' => [
        'ar' => 'لم تستلم رمز التحقق؟',
        'context' => 'aura',
      ],
      'Aura account number' => [
        'ar' => 'رقم حساب أورا',
        'context' => 'aura',
      ],
      'A One Time Password (OTP) has been sent to your mobile number @mobile' => [
        'ar' => 'تم إرسال رمز التحقق (OTP) إلى رقم هاتفك @mobile',
        'context' => 'aura',
      ],
      'One Time Pin' => [
        'ar' => 'كلمة مرور لمرة واحدة',
        'context' => 'aura',
      ],
      'Learn more' => [
        'ar' => 'أعرف أكثر',
        'context' => 'aura',
      ],
      'Hi @firstName,<br>An Aura account is associated with your email address. Link your Aura with just one click.' => [
        'ar' => 'مرحباً @firstName,<br> حساب أورا مرتبط ببريدك الإلكتروني. اربط حسابك بضغطة واحدة.',
        'context' => 'aura',
      ],
      'Do you want to link now?' => [
        'ar' => 'هل ترغب في الربط الآن؟',
        'context' => 'aura',
      ],
      'Aura Card Number' => [
        'ar' => 'رقم بطاقة أورا',
        'context' => 'aura',
      ],
      'Link your Aura' => [
        'ar' => 'اربط بطاقتك',
        'context' => 'aura',
      ],
      'Resend' => [
        'ar' => 'أعد الإرسال',
        'context' => 'aura',
      ],
      '<b>@points points</b> worth <b>@currencyCode @money</b> have been successfully redeemed for this purchase' => [
        'ar' => '<b>@points قيمة</b><span> النقاط </span><b>@currencyCode @money</b> تم استبدالها بنجاح لإتمام عملية الشراء',
        'context' => 'aura',
      ],
      'Check your points value:' => [
        'ar' => 'تحقق من قيمة نقاطك:',
        'context' => 'aura',
      ],
      'A card number is required to link your card. Please enter your details to proceed.' => [
        'ar' => 'رقم البطاقة يحتاج الربط مع بطاقتك. يرجى ادخال بياناتك للاستمرار.',
        'context' => 'aura',
      ],
      'Congratulations! You are now part of Aura, the loyalty experience personalised for you. You can now earn points when you shop online or instore.' => [
        'ar' => 'تهانينا! أنت الآن جزء من أورا، برنامج المكافآت المصمم خصيصاً لك. اجمع النقاط كل مرة تتسوق فيها أونلاين أو في المحلات.',
        'context' => 'aura',
      ],
      'To use your points online, complete your registration on the Aura MENA app.' => [
        'ar' => 'استخدام نقاطك أونلاين، أكمل التسجيل عبر تطبيق Aura MENA.',
        'context' => 'aura',
      ],
      'To use your points online, please download the Aura MENA app and provide us with a few more details.' => [
        'ar' => 'يرجى تنزيل تطبيق أورا وتزويدنا ببعض التفاصيل الإضافية وذلك لاستخدام النقاط عبر أونلاين.',
        'context' => 'aura',
      ],
      'Sign In' => [
        'ar' => 'تسجيل الدخول',
        'context' => 'aura',
      ],
      'Add your account details at shopping bag.' => [
        'ar' => 'أضف تفاصيل حسابك في حقيبة التسوق.',
        'context' => 'aura',
      ],
      'Your points will be credited to your Aura account. You will be able to redeem these a day after your order is delivered.' => [
        'ar' => 'سيتم إضافة نقاطك إلى حسابك في أورا. وستتمكن من إستردادها بعد يوم من توصيل الطلبية.',
        'context' => 'aura',
      ],
    ],
    'v5' => [
      'Earn <span><b>!pts</b> points with Aura</span> on this purchase.' => [
        'ar' => 'اربح <span> <b>!pts</b> من النقاط مع Aura </span> على عملية الشراء هذه.',
        'context' => 'aura',
      ],
    ],
    'v6' => [
      'Aura Loyalty Card' => [
        'ar' => 'بطاقة الولاء من أورا',
        'context' => 'aura',
      ],
    ],
    'v7' => [
      'Earn @pts points with @aura_icon' => [
        'ar' => 'اكسب @pts نقاط مع @aura_icon',
        'context' => 'aura',
      ],
    ],
    'v8' => [
      'an Aura loyalty account no. @card_number is associated with your email address. It just takes one click to link.' => [
        'ar' => ' رقم حساب مكافآت أورا @card_number مرتبط ببريدك الإلكتروني. خطوة واحدة تفصلك عن ربط حسابك.',
        'context' => 'aura',
      ],
      'An Aura loyalty card is already associated with your email address. It just takes one click to link.' => [
        'ar' => 'حساب ولاء أورا مرتبط بالفعل بعنوان بريدك الإلكتروني. يمكنك ربط الحساب بضغطة واحدة.',
        'context' => 'aura',
      ],
      'Aura membership number' => [
        'ar' => 'رقم عضوية أورا',
        'context' => 'aura',
      ],
      'Your Tier Progress' => [
        'ar' => 'تم التقدم في المستوى',
        'context' => 'aura',
      ],
      'To spend your points online, please download Aura Mena app available both on App Store and Play Store.' => [
        'ar' => 'للاستفادة من نقاطك عبر الأونلاين، يرجى تحميل تطبيق أورا الشرق الأوسط المتوفر على أبل ستور، وسوق بلاي.',
        'context' => 'aura',
      ],
      'Start spending to earn points' => [
        'ar' => 'ابدأ الشراء لكسب النقاط',
        'context' => 'aura',
      ],
    ],
    'v9' => [
      'Buy and get rewards and exclusive offers with AURA | [alshaya_seo:brand_name]' => [
        'ar' => 'اشترى الأن واحصل على عروض حصرية من اورا | [alshaya_seo:brand_name]',
        'context' => 'aura',
      ],
      'Download AURA now to get personalized offers and rewards for each purchase you make from [alshaya_seo:brand_name] online or instore in [alshaya_seo:cities] and all of [alshaya_seo:country]' => [
        'ar' => 'حمل تطبيق اورا الان واحصل على عروض خاصة بك و نقاط استرجاع على كل عملية شراء تقوم بها من [alshaya_seo:brand_name] اونلاين او من خلال اى من متاجرنا فى [alshaya_seo:cities] و فى حمع انحاء [alshaya_seo:country]',
        'context' => 'aura',
      ],
    ],
    'v10' => [
      'To spend your points online, please download Aura Mena app available both on <a href="@appStoreLink">App Store</a> and <a href="@googlePlayLink">Play Store</a>.' => [
        'ar' => 'للاستفادة من نقاطك أونلاين، يرجى تحميل تطبيق أورا مينا المتوفر عبر <a href="@appStoreLink">آب ستور</a> و<a href="@googlePlayLink">بلاي ستور</a>.',
        'context' => 'aura',
      ],
    ],
    'v11' => [
      'To use your points online, please download the Aura MENA app available both on <strong>App Store</strong> and <strong>Play Store</strong>.' => [
        'ar' => 'لاستخدام النقاط أونلاين، يرجى تحميل تطبيق أورا مينا المتوفر عبر <strong>آب ستور </strong>و <strong>بلاي ستور </strong>',
        'context' => 'aura',
      ],
    ],
    'v12' => [
      'You can now start building your Aura. Earn points every time you shop online or instore.' => [
        'ar' => 'يمكنك الآن الاستمتاع بتجربة تسوق فريدة مع أورا. اكسب النقاط عند تسوق في محلاتنا أو أونلاين.',
        'context' => 'aura',
      ],
      'Use your points on future purchases or to access a range of rewards and experiences on the Aura app.' => [
        'ar' => 'استخدم النقاط المكتسبة في عمليات الشراء القادمة أو للاستمتاع بدخول مميز للعديد من المكافآت والتجارب الممتعة عبر تطبيقنا.',
        'context' => 'aura',
      ],
    ],
  ];
}

/**
 * Get translations for given version.
 *
 * @param string $version
 *   Version number like 'v1' etc.
 *
 * @return array
 *   Translations.
 */
function _alshaya_aura_react_get_translations(string $version = '') {
  $translations = _alshaya_aura_react_translations();
  // If no version mentioned, return all version strings.
  if (empty($version)) {
    $trans_data = [];
    foreach ($translations as $trans) {
      $trans_data = array_merge($trans_data, $trans);
    }

    return $trans_data;
  }

  return $translations[$version] ?? [];
}
