<?php

/**
 * @file
 * Contains Aura related translations.
 */

/**
 * Aura translation.
 */
function _alshaya_aura_react_translations() {
  return [
    'My AURA' => [
      'ar' => 'حساب أورا الخاص بي',
    ],
    'Already an AURA member?' => [
      'ar' => 'هل أنت عضو في أورا؟',
    ],
    'Link your card' => [
      'ar' => 'قم بربط بطاقتك',
    ],
    'Ready to be rewarded?' => [
      'ar' => 'هل أنت مستعد للمكافآت؟',
    ],
    'Sign up now' => [
      'ar' => 'تسجيل الاشتراك الآن',
    ],
    'Congrats! You are now part of the exclusive AURA club. You’ll now earn points as you shop online and in stores.' => [
      'ar' => 'تهانينا! أنت الآن جزء من نادي أورا الحصري. سوف تربح الآن نقاط أثناء التسوق أونلاين وفي المحلات.',
    ],
    'To use your points online, please download the AURA app and provide us with a few more details.' => [
      'ar' => 'يرجى تنزيل تطبيق أورا وتزويدنا ببعض التفاصيل الإضافية وذلك لاستخدام النقاط عبر أونلاين.',
    ],
    'An AURA card is already associated with your email address. Link your card in just one click.' => [
      'ar' => 'يُمكنك ربط بطاقة أورا ببريدك الإلكتروني من خلال ضغطة زر واحدة.',
    ],
    'Do you want to link now?' => [
      'ar' => 'هل ترغب في الربط الآن؟',
    ],
    'Not you?' => [
      'ar' => 'ليس أنت؟',
    ],
    'Card number' => [
      'ar' => 'رقم البطاقة',
    ],
    'Status' => [
      'ar' => 'مستوى العضوية',
    ],
    'Point balance' => [
      'ar' => 'رصيد النقاط',
    ],
    'points' => [
      'ar' => 'النقاط',
    ],
    'Points on hold' => [
      'ar' => 'النقاط قيد الانتظار',
    ],
    'Rewards activity' => [
      'ar' => 'تفاصيل المكافآت',
    ],
    'Loyalty benefits' => [
      'ar' => 'مكافآت الولاء',
    ],
    'Your points will instantly be credited to your account. You’ll be able to redeem them after 14 days as per the returns & refunds policies.' => [
      'ar' => 'سيتم إضافة نقاطك على الفور إلى حسابك، سوف تتمكن من استبدال النقاط بعد 14 يوم طبقاً لسياسات الاسترداد والإرجاع.',
    ],
    'Say hello to AURA' => [
      'ar' => 'مرحباً بكم في أورا',
    ],
    'Send one time PIN' => [
      'ar' => 'إرسال رمز الاستخدام لمرة واحدة',
    ],
    'Resend code' => [
      'ar' => 'إعادة إرسال الرمز',
    ],
    'One time PIN' => [
      'ar' => 'رمز الاستخدام لمرة واحدة',
    ],
    'Country Code' => [
      'ar' => 'رمز الدولة',
    ],
    'We’ll send a one time PIN to your mobile number.' => [
      'ar' => 'سنقوم بإرسال رمز للاستخدام لمرة واحدة إلى رقم الهاتف',
    ],
    'We’ve sent the one time PIN to your mobile number.' => [
      'ar' => 'لقد قمنا بإرسال رمز للاستخدام لمرة واحدة إلى رقم الهاتف',
    ],
    'Didn’t receive your one time PIN?' => [
      'ar' => 'لم يصلكم رمز الاستخدام لمرة واحدة؟',
    ],
    'Verify' => [
      'ar' => 'تأكيد',
    ],
    'By clicking submit, you agree to have read and accepted our' => [
      'ar' => 'بالضغط على زر إرسال، فأنكم توافقون على الخاصة بنا',
    ],
    'Terms & Conditions' => [
      'ar' => 'البنود و الظروف',
    ],
    'Incorrect OTP. Please enter a valid OTP.' => [
      'ar' => 'رمز تحقق OTP غير صحيح. يرجى إعادة إدخال رمز تحقق OTP صالح',
    ],
    'The OTP couldn’t be verified. Please try again.' => [
      'ar' => 'لم يتم تأكيد رمز الاستخدام لمرة واحدة. يرجى المحاولة لاحقاً.',
    ],
    'This phone number is already registered. Please sign-in or use a different phone number.' => [
      'ar' => 'رقم الهاتف مسجل لدينا بالفعل. يرجى تسجيل الدخول أو استخدام رقم هاتف مختلف',
    ],
    'This email address is already registered. Please sign-in or use a different email address.' => [
      'ar' => 'البريد الإلكتروني مسجل لدينا بالفعل. يرجى تسجيل الدخول أو استخدام بريد إلكتروني مختلف',
    ],
    'Earn AURA points every time you shop! You can redeem your points to use on future purchases. Not applicable on purchases made using AURA points.' => [
      'ar' => 'اربح نقاط أورا في كل مرة تتسوق فيها! يمكنك استبدال نقاطك لاستخدامها في عمليات الشراء المستقبلية. لا ينطبق على عمليات الشراء التي تتم باستخدام نقاط أورا.',
    ],
    'AURA points' => [
      'ar' => 'نقاط أورا',
    ],
    'Earn' => [
      'ar' => 'اربح',
    ],
    'Bespoke rewards.' => [
      'ar' => 'مكافآت بلا حدود.',
    ],
    'Bespoke lifestyles.' => [
      'ar' => 'أسلوب حياة أفضل.',
    ],
    'Good things come to those with taste. Say hello to AURA, a lifestyle program catered to your taste for refined brands and experiences.' => [
      'ar' => 'لأن أصحاب الذوق الرفيع يستحقون كل ما هو أفضل. مرحباً بكم في أورا، برنامج المكافآت الذي يقدم لكم ماركاتكم المفضلة من خلال تجربة تسوق تُحسن أسلوب حياتكم.',
    ],
    'Learn more' => [
      'ar' => 'تعرف على المزيد',
    ],
    'Your AURA card number' => [
      'ar' => 'رقم بطاقة أورا الخاصة بك',
    ],
    'Sign in or create an account to use your points.' => [
      'ar' => 'سجل الدخول أو أنشيء حساب جديد لاستخدام النقاط',
    ],
    'Aura rewards' => [
      'ar' => 'مكافآت أورا',
    ],
    '(Optional)' => [
      'ar' => 'اختياري',
    ],
    'pts' => [
      'ar' => 'النقاط',
    ],
    'Try again' => [
      'ar' => 'المحاولة مرة أخرى',
    ],
    'Apply' => [
      'ar' => 'التقديم',
    ],
    'Unexpected error occured.' => [
      'ar' => 'حدث خطأ غير متوقع.',
    ],
    'Not a member yet?' => [
      'ar' => 'لست عضواً بعد؟',
    ],
    'Enter Aura Card Number' => [
      'ar' => 'إدخال رقم بطاقة أورا',
    ],
    'Please enter valid mobile number.' => [
      'ar' => 'يرجى إدخال رقم هاتف صحيح.',
    ],
    'Please enter mobile number.' => [
      'ar' => 'يرجى إدخال رقم الهاتف.',
    ],
    'Please enter OTP.' => [
      'ar' => 'يرجى إدخال رمز الاستخدام لمرة واحدة.',
    ],
    'Error in sign up. Please try again.' => [
      'ar' => 'خطأ في تسجيل الاشتراك. يرجى المحاولة مرة أخرى.',
    ],
    'Error in sending OTP. Please try again.' => [
      'ar' => 'خطأ في رمز الاستخدام لمرة واحدة. يرجى المحاولة مرة أخرى.',
    ],
    'Please enter card number.' => [
      'ar' => 'يرجى إدخال رقم البطاقة.',
    ],
    'Please enter points.' => [
      'ar' => 'يرجى إدخال النقاط.',
    ],
    'No mobile number found. Please try again.' => [
      'ar' => 'لم يتم العثور على رقم هاتف محمول. يرجى المحاولة مرة أخرى.',
    ],
    'Link Now' => [
      'ar' => 'الربط الآن',
    ],
    'Link card using' => [
      'ar' => 'ربط البطاقة باستخدام',
    ],
    'Incorrect AURA card number. Please re-enter a valid AURA card number.' => [
      'ar' => 'رقم AURA غير صحيح. يرجى إعادة إدخال رقم بطاقة AURA صحيح.',
    ],
    'Your loyalty points will be credited to this account.' => [
      'ar' => 'سيتم إضافة نقاط الولاء إلى هذا الحساب.',
    ],
    'Full name' => [
      'ar' => 'الاسم بالكامل',
    ],
    'Earn Aura points' => [
      'ar' => 'اربح نقاط أورا',
    ],
    'Say hello to' => [
      'ar' => 'مرحباً بكم في',
    ],
    'Paid With Aura' => [
      'ar' => 'الدفع مع أورا',
    ],
    'Balance Payable' => [
      'ar' => 'الرصيد المستحق الدفع',
    ],
    'To enable auto accrual and rewards redemption' => [
      'ar' => 'لتفعيل النقاط المستحقة واسترداد المكافآت',
    ],
    'link your card now' => [
      'ar' => 'قم بربط البطاقة الآن',
    ],
    'You Have' => [
      'ar' => 'لديك',
    ],
    'You will earn' => [
      'ar' => 'سوف تربح',
    ],
    'with this purchase' => [
      'ar' => 'مع عملية الشراء هذه',
    ],
    'Earn and redeem as you shop' => [
      'ar' => 'اربح واستبدل النقاط أثناء تسوقك',
    ],
    'Aura points earned' => [
      'ar' => 'نقاط أورا المكتسبة',
    ],
    'You can redeem maximum' => [
      'ar' => 'يُمكنك استبدال نقاط بحد أقصى',
    ],
    'worth' => [
      'ar' => 'ما يعادل',
    ],
    'have been successfully redeemed' => [
      'ar' => 'تم استبدالها بنجاح',
    ],
    'Use your points' => [
      'ar' => 'استخدم نقاطك',
    ],
    'Use points' => [
      'ar' => 'استخدم النقاط',
    ],
    'Remove' => [
      'ar' => 'إزالة',
    ],
    'Aura points redeemed' => [
      'ar' => 'نقاط أورا التي تم استبدالها',
    ],
    'Members will earn' => [
      'ar' => 'سوف يربح الأعضاء',
    ],
    'will expire by' => [
      'ar' => 'ستنتهي بحلول',
    ],
    'Aura' => [
      'ar' => 'أورا',
    ],
    'reward points with this purchase' => [
      'ar' => 'نقاط المكافآت مع عملية الشراء هذه',
    ],
    'On completion of this purchase you will earn:' => [
      'ar' => 'عند إتمام عملية الشراء هذه، سوف تربح:',
    ],
    'Sign in' => [
      'ar' => 'تسجيل الدخول',
    ],
    'A phone number is required to sign-up. Please enter your details to proceed.' => [
      'ar' => 'رقم الهاتف مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
    ],
    'Your full name is required to sign-up. Please enter your details to proceed.' => [
      'ar' => 'الاسم الكامل مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
    ],
    'Please enter a valid email address.' => [
      'ar' => 'يرجى إدخال بريد إلكتروني صالح.',
    ],
    'An email address is required to sign-up. Please enter your details to proceed.' => [
      'ar' => 'البريد الإلكتروني مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
    ],
    'A phone number is required to link your card. Please enter your details to proceed.' => [
      'ar' => 'رقم الهاتف مطلوب لربط البطاقة. يرجى إدخال بياناتك للمتابعة.',
    ],
    'An email address is required to link your card. Please enter your details to proceed.' => [
      'ar' => 'البريد الإلكتروني مطلوب للتسجيل. يرجى إدخال بياناتك للمتابعة',
    ],
    'This phone number isn’t registered. Please enter the same number used during sign-up.' => [
      'ar' => 'رقم الهاتف غير مسجل. يرجى إدخال نفس الرقم المستخدم أثناء التسجيل.',
    ],
    'This email address isn’t registered. Please enter the same email address used during sign-up.' => [
      'ar' => 'البريد الإلكتروني غير مسجل. يرجى إدخال نفس البريد الإلكتروني المستخدم أثناء التسجيل.',
    ],
    'Incorrect AURA card number. Please re-enter a valid AURA card number.' => [
      'ar' => 'رقم AURA غير صحيح. يرجى إعادة إدخال رقم بطاقة AURA الصحيح.',
    ],
    'Your request couldn’t be processed. Please try again shortly.' => [
      'ar' => 'لا يمكن إتمام طلبك. يرجى المحاولة مرة أخرى',
    ],
    'The number of points exceeds your order total. Please re-enter the number of points you’d like to redeem.' => [
      'ar' => 'عدد النقاط يتجاوز إجمالي الطلبية. يرجى إعادة إدخال رقم النقاط التي ترغب في استخدامها.',
    ],
    'The number you’ve entered is invalid. Please re-enter the number of points you’d like to redeem.' => [
      'ar' => 'الرقم الذي أدخلته غير صحيح. يرجى إعادة إدخال رقم النقاط التي ترغب في استخدامها.',
    ],
  ];
}
