<?php

/**
 * @file
 * Contains Aura related static strings.
 */

/**
 * Aura static strings.
 */
function _alshaya_aura_static_strings() {
  return [
    [
      'key' => 'form_error_valid_mobile_number',
      'value' => t('Please enter a valid phone number.'),
    ],
    [
      'key' => 'form_error_mobile_number',
      'value' => t('Please enter phone number.'),
    ],
    [
      'key' => 'form_error_otp',
      'value' => t('Please enter OTP.'),
    ],
    [
      'key' => 'otp_send_message',
      'value' => t('We’ve sent the one time PIN to your mobile number.'),
    ],
    [
      'key' => 'didnt_receive_otp_message',
      'value' => t('Didn’t receive your one time PIN?'),
    ],
    [
      'key' => 'send_otp_helptext',
      'value' => t('We’ll send a one time PIN to your mobile number.'),
    ],
    [
      'key' => 'verify',
      'value' => t('Verify'),
    ],
    [
      'key' => 'otp_button_label',
      'value' => t('Send One Time PIN'),
    ],
    [
      'key' => 'otp_modal_title',
      'value' => t('Say hello to AURA'),
    ],
    [
      'key' => 'resend_code',
      'value' => t('Resend code'),
    ],
    [
      'key' => 'mobile_label',
      'value' => t('Mobile Number'),
    ],
    [
      'key' => 'otp_label',
      'value' => t('One time PIN'),
    ],
    [
      'key' => 'form_error_full_name',
      'value' => t('Your full name is required to sign-up. Please enter your details to proceed.'),
    ],
    [
      'key' => 'form_error_email',
      'value' => t('Please enter email.'),
    ],
    [
      'key' => 'form_error_email_not_valid',
      'value' => t('Please enter a valid email address.'),
    ],
    [
      'key' => 'form_error_invalid_otp',
      'value' => t('Incorrect OTP. Please enter a valid OTP.'),
    ],
    [
      'key' => 'form_error_send_otp_failed_message',
      'value' => t('Error in sending OTP. Please try again.'),
    ],
    [
      'key' => 'form_error_sign_up_failed_message',
      'value' => t('Error in sign up. Please try again.'),
    ],
    [
      'key' => 'form_error_mobile_already_registered',
      'value' => t('This phone number is already registered. Please sign-in or use a different phone number.'),
    ],
    [
      'key' => 'form_error_email_already_registered',
      'value' => t('This email address is already registered. Please sign-in or use a different email address.'),
    ],
    [
      'key' => 'form_error_empty_card',
      'value' => t('Please enter card number.'),
    ],
    [
      'key' => 'form_error_empty_points',
      'value' => t('Please enter points.'),
    ],
    [
      'key' => 'form_error_mobile_not_found',
      'value' => t('No mobile number found. Please try again.'),
    ],
    [
      'key' => 'cart_page_aura_header',
      'value' => t('Aura rewards'),
    ],
    [
      'key' => 'cart_page_aura_accrual_label',
      'value' => t('On completion of this purchase you will earn:'),
    ],
    [
      'key' => 'checkout_you_have',
      'value' => t('You Have'),
    ],
    [
      'key' => 'checkout_you_will_earn',
      'value' => t('You will earn'),
    ],
    [
      'key' => 'checkout_with_this_purchase',
      'value' => t('with this purchase'),
    ],
    [
      'key' => 'checkout_use_your_points',
      'value' => t('Use your points'),
    ],
    [
      'key' => 'checkout_use_points',
      'value' => t('Use points'),
    ],
    [
      'key' => 'checkout_aura_block_title',
      'value' => t('Aura rewards'),
    ],
    [
      'key' => 'checkout_optional',
      'value' => t('(Optional)'),
    ],
    [
      'key' => 'checkout_earn_and_redeem',
      'value' => t('Earn and redeem as you shop'),
    ],
    [
      'key' => 'checkout_members_will_earn',
      'value' => t('Members will earn'),
    ],
    [
      'key' => 'checkout_already_member_question',
      'value' => t('Already an AURA member?'),
    ],
    [
      'key' => 'checkout_not_member_question',
      'value' => t('Not a member yet?'),
    ],
    [
      'key' => 'checkout_apply',
      'value' => t('Apply'),
    ],
    [
      'key' => 'checkout_no_card_found_try_again',
      'value' => t('Incorrect AURA card number. Please re-enter a valid AURA card number.'),
    ],
    [
      'key' => 'checkout_points_to_be_credited_message',
      'value' => t('Your loyalty points will be credited to this account.'),
    ],
    [
      'key' => 'earn',
      'value' => t('Earn'),
    ],
    [
      'key' => 'aura',
      'value' => t('Aura'),
    ],
    [
      'key' => 'reward_points_with_purchase',
      'value' => t('reward points with this purchase'),
    ],
    [
      'key' => 'pts',
      'value' => t('pts'),
    ],
    [
      'key' => 'our_members_will_earn',
      'value' => t('Our members will earn'),
    ],
    [
      'key' => 'points',
      'value' => t('points'),
    ],
    [
      'key' => 'you_can_redeem_maximum',
      'value' => t('You can redeem maximum'),
    ],
    [
      'key' => 'worth',
      'value' => t('worth'),
    ],
    [
      'key' => 'have_been_redeemed',
      'value' => t('have been successfully redeemed'),
    ],
    [
      'key' => 'remove',
      'value' => t('Remove'),
    ],
    [
      'key' => 'something_went_wrong',
      'value' => t('Your request couldn’t be processed. Please try again shortly.'),
    ],
    [
      'key' => 'not_you_question',
      'value' => t('Not you?'),
    ],
    [
      'key' => 'sign_up_now',
      'value' => t('Sign up now'),
    ],
    [
      'key' => 'loyalty_card_placeholder',
      'value' => t('Card number'),
    ],
    [
      'key' => 'auto_accrual_message',
      'value' => t('To enable auto accrual and rewards redemption'),
    ],
    [
      'key' => 'link_your_card_now',
      'value' => t('link your card now'),
    ],
    [
      'key' => 'signup_empty_mobile',
      'value' => t('A phone number is required to sign-up. Please enter your details to proceed.'),
    ],
    [
      'key' => 'signup_empty_email',
      'value' => t('An email address is required to sign-up. Please enter your details to proceed.'),
    ],
    [
      'key' => 'link_card_empty_mobile',
      'value' => t('A phone number is required to link your card. Please enter your details to proceed.'),
    ],
    [
      'key' => 'link_card_empty_email',
      'value' => t('An email address is required to link your card. Please enter your details to proceed.'),
    ],
    [
      'key' => 'link_card_empty_card_number',
      'value' => t('A card number is required to link your card. Please enter your details to proceed.'),
    ],
    [
      'key' => 'mobile_not_registered',
      'value' => t('This phone number isn’t registered. Please enter the same number used during sign-up.'),
    ],
    [
      'key' => 'email_not_registered',
      'value' => t('This email address isn’t registered. Please enter the same email address used during sign-up.'),
    ],
    [
      'key' => 'invalid_card_number',
      'value' => t('Incorrect AURA card number. Please re-enter a valid AURA card number.'),
    ],
    [
      'key' => 'points_exceed_order_total',
      'value' => t('The number of points exceeds your order total. Please re-enter the number of points you’d like to redeem.'),
    ],
    [
      'key' => 'invalid_points',
      'value' => t('The number you’ve entered is invalid. Please re-enter the number of points you’d like to redeem.'),
    ],
  ];
}
