<?php

/**
 * @file
 * Install, update and uninstall functions for the alshaya_config module.
 */

/**
 * Implements hook_update_N().
 *
 * Creates config for `alshaya_config` module.
 */
function alshaya_config_update_8601() {
  /* @var \Drupal\alshaya_config\AlshayaConfigManager $config_manager*/
  $config_manager = \Drupal::service('alshaya_config.manager');
  $config_manager->updateConfigs(
    ['alshaya_config.settings'],
    'alshaya_config'
  );
}
