<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_mc_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product') {
    /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
    $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
    $sku = $skuManager->getSkuForNode($entity);
    $sku_entity = SKU::loadFromSku($sku);

    if ($sku_entity instanceof SKU && $view_mode == 'full') {
      $product_info = \Drupal::service('acq_sku.product_info_helper');
      $build['short_desc'] = $product_info->getValue($sku_entity, 'short_desc', $view_mode, '');
      $build['description'] = $product_info->getValue($sku_entity, 'description', $view_mode, '');
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_mc_acq_sku_view(array &$build, EntityInterface $sku_entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'modal') {
    $product_info = \Drupal::service('acq_sku.product_info_helper');
    $build['short_desc'] = $product_info->getValue($sku_entity, 'short_desc', $view_mode, '');
    $build['description'] = $product_info->getValue($sku_entity, 'description', $view_mode, '');
  }
}
