<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_add_to_bag_library_info_alter(&$libraries, $extension) {
  // Alter the add to bag utility library to replace the base JS file with the
  // utility file provided by this module.
  if ($extension === 'alshaya_acm_product') {
    $self_module_path = drupal_get_path('module', 'alshaya_rcs_add_to_bag');
    if (isset($libraries['add_to_bag_utility'])) {
      $options = $libraries['add_to_bag_utility']['js']['js/alshaya_acm_add_to_bag.utility.js'];
      unset($libraries['add_to_bag_utility']['js']['js/alshaya_acm_add_to_bag.utility.js']);
      $libraries['add_to_bag_utility']['js']["/$self_module_path/js/alshaya_rcs_add_to_bag.utility.js"] = $options;
      $libraries['add_to_bag_utility']['dependencies'] = [
        'rcs_magento_placeholders/rcs_magento_placeholders',
        'alshaya_master/common_functions',
      ];
      // Get color swatch in product drawer.
      if (\Drupal::service('module_handler')->moduleExists('alshaya_rcs_color_split')) {
        $libraries['add_to_bag_utility']['dependencies'][] = 'alshaya_rcs_color_split/rcs_grouped_products';
      }
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_rcs_add_to_bag_page_attachments_alter(array &$page) {
  $add_to_bag_altered_feature_status = &drupal_static('add_to_bag_altered_feature_status');
  if (!$add_to_bag_altered_feature_status) {
    return;
  }

  // Attach add to bag utility.
  $current_route = \Drupal::routeMatch();
  $current_route_name = $current_route->getRouteName();
  $checkout_routes = [
    'alshaya_spc.checkout.confirmation',
    'alshaya_spc.checkout',
  ];
  if (!in_array($current_route_name, $checkout_routes)) {
    $page['#attached']['library'][] = 'alshaya_acm_product/add_to_bag_utility';
    // Get click and collect settings on search and listing page.
    $cnc_settings = \Drupal::config('alshaya_click_collect.settings');
    $page['#attached']['drupalSettings']['alshaya_click_collect'] = [
      'status' => $cnc_settings->get('feature_status'),
    ];
  }
}
