<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_add_to_bag_library_info_alter(&$libraries, $extension) {
  // Alter the add to bag utility library to replace the base JS file with the
  // utility file provided by this module.
  if ($extension === 'alshaya_acm_product') {
    $self_module_path = drupal_get_path('module', 'alshaya_rcs_add_to_bag');
    if (isset($libraries['add_to_bag_utility'])) {
      $options = $libraries['add_to_bag_utility']['js']['js/alshaya_acm_add_to_bag.utility.js'];
      unset($libraries['add_to_bag_utility']['js']['js/alshaya_acm_add_to_bag.utility.js']);
      $libraries['add_to_bag_utility']['js']["/$self_module_path/js/alshaya_rcs_add_to_bag.utility.js"] = $options;
      $libraries['add_to_bag_utility']['dependencies'] = [
        'rcs_magento_placeholders/rcs_magento_placeholders',
        'alshaya_master/common_functions',
      ];
    }
  }
}
