<?php

/**
 * @file
 * Module file for Alshaya ACM Product Position.
 */

use Drupal\Core\Database\Query\SelectInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_search_api_db_query_alter().
 */
function alshaya_acm_product_position_search_api_db_query_alter(SelectInterface &$db_query, QueryInterface $query) {
  if ($query->hasTag('views_alshaya_product_list')) {
    $sorts =& $query->getSorts();

    // Check if nid is there in sorts, we are using it for position.
    if (!isset($sorts['nid'])) {
      return;
    }

    // Remove all query sorts, we will sort in db_query.
    $sorts = [];

    // Find the tid.
    $tid = NULL;
    $conditions = $query->getConditionGroup()->getConditions();
    foreach ($conditions as $condition) {
      if ($condition) {
        $query_conditions = $condition->getConditions();
        if ($query_conditions[0]->getField() == 'tid') {
          $tid = $query_conditions[0]->getValue();
          // First tid in the array is always the current tid.
          $tid = is_array($tid) ? $tid[0] : $tid;
          break;
        }
      }
    }

    if ($tid) {
      $db_query->leftJoin('acq_sku_position', 'acq_sku_position', '(t.nid = acq_sku_position.nid AND acq_sku_position.tid = :tid AND acq_sku_position.position_type = :position_type)', [
        ':tid' => $tid,
        ':position_type' => 'position',
      ]);

      // If no position found for product, set the default position.
      $db_query->addExpression('IFNULL(acq_sku_position.position, 99999999)', 'no_position');

      // First order by stock (always).
      $db_query->orderBy('stock', QueryInterface::SORT_DESC);

      // Order by position.
      $db_query->orderBy('no_position', QueryInterface::SORT_ASC);

      // Order by name if two products have same position (to avoid duplicity).
      $db_query->orderBy('t.name_1', QueryInterface::SORT_ASC);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function alshaya_acm_product_position_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-alshaya-product-list-block-1') {
    // Best seller descending option removed.
    unset($form['sort_bef_combine']['#options']['nid DESC']);
  }
}
