<?php

/**
 * @file
 * Module file for Alshaya RCS Geolocation.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function alshaya_rcs_geolocation_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() !== 'rcs_product') {
    return;
  }
  /** @var  \Drupal\alshaya_acm_product\SkuManager $sku_manager **/
  $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');
  $pdp_layout = $sku_manager->getPdpLayout($entity, $build['#view_mode']);
  if (str_contains($pdp_layout, 'magazine_v2')) {
    return;
  }

  $api_url = '/alshaya-locations/stores-list';
  $config = alshaya_click_collect_get_config();

  $build['#attached']['library'][] = 'alshaya_geolocation/alshaya-store-click-collect-list';
  $store_labels = \Drupal::service('alshaya_geolocation.store_utility')->storeLabels();
  $build['#attached']['drupalSettings']['storeLabels'] = [
    'apiUrl' => $api_url,
    'title' => $config['title'],
    'title_price' => alshaya_acm_price_get_formatted_price($config['title_price']),
    'subtitle_texts' => [
      'enabled' => $config['subtitle'],
      'disabled' => $config['unavailable'],
    ],
    'help_text' => $config['help_text'],
    'available_at_title' => '',
    'select_option_text' => $config['select_option_text'],
    'state' => $config['feature_status'],
    'search_proximity_radius' => $store_labels['search_proximity_radius'],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_geolocation_library_info_alter(&$libraries, $extension) {
  $self_module_path = drupal_get_path('module', 'alshaya_rcs_geolocation');

  if ($extension === 'alshaya_geolocation'
    && isset($libraries['alshaya-store-click-collect-list'])
  ) {
    $cnc_library = &$libraries['alshaya-store-click-collect-list'];
    // Alter the geolocation library to replace the base JS file with the
    // utility file provided by this module.
    $options = $cnc_library['js']['js/alshaya_geolocation.utility.js'];
    unset($cnc_library['js']['js/alshaya_geolocation.utility.js']);
    $cnc_library['js']["/$self_module_path/js/alshaya_geolocation_rcs.utility.js"] = $options;
    $cnc_library['dependencies'] = [
      'core/jquery',
      'core/drupalSettings',
      'alshaya_acm_product/product_utility',
    ];
  }
}
