<?php

/**
 * @file
 * Contains general hooks and alters.
 */

/**
 * Implements hook_alshaya_profile_installed().
 */
function alshaya_acm_promotion_alshaya_profile_installed(array $modules) {
  try {
    // Sync the promotions.
    \Drupal::service('acq_promotion.promotions_manager')->syncPromotions();
  }
  catch (\Exception $e) {
    \Drupal::logger('alshaya_acm_promotion')->error('Error occurred while syncronizing promotions during install: @error', ['@error' => $e->getMessage()]);
  }
}

/**
 * Implements hook_views_data_alter().
 */
function alshaya_acm_promotion_views_data_alter(array &$data) {
  $data['search_api_index_product']['field_skus']['argument']['id'] = 'alshaya_sku_ignore_whitespaces';
}

/**
 * Implements hook_theme().
 */
function alshaya_acm_promotion_theme($existing, $type, $theme, $path) {
  return [
    'cart_top_promotions' => [
      'variables' => [
        'promotions' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_registry_alter().
 */
function alshaya_acm_promotion_theme_registry_alter(&$theme_registry) {
  $theme_registry['acq_commerce_price']['variables']['promotions'] = NULL;
}
