<?php

/**
 * @file
 * Alshaya PBK brand module.
 */

/**
 * Implements hook_alshaya_performance_preload_alter().
 */
function alshaya_pbk_transac_alshaya_performance_preload_alter(array &$preload) {
  $themeHandler = \Drupal::service('theme_handler');
  $themePath = $themeHandler->getTheme($themeHandler->getDefault())->getPath();
  $fonts_directory_path = '/' . $themePath . '/fonts';

  $preload[] = [
    'as' => 'style',
    'href' => 'https://fonts.googleapis.com/css?family=Cairo:300,400,600,700|Open+Sans:300,400,600,700&subset=arabic&display=swap',
    'crossorigin' => 'crossorigin',
    'type' => 'text/css',
  ];
  $preload[] = [
    'as' => 'style',
    'href' => $fonts_directory_path . '/alshaya-icons.woff?12adm',
    'crossorigin' => 'crossorigin',
    'type' => 'font/woff',
  ];
}
