<?php

/**
 * @file
 * Contains new pdp related translations.
 */

/**
 * New pdp translation.
 */
function _alshaya_pdp_react_translations() {
  return [
    'Add To Bag' => [
      'ar' => 'أضف الى الحقيبة',
    ],
    'product details' => [
      'ar' => 'تفاصيل المنتج',
    ],
    'Item Code:' => [
      'ar' => 'رمز الصنف:',
    ],
    'click & collect' => [
      'ar' => 'انقر واستلم',
    ],
    'Share this page' => [
      'ar' => 'شارك هذه الصفحة',
    ],
    'Copy page link' => [
      'ar' => 'نسخ ارتباط الصفحة',
    ],
    'Check in-store availability:' => [
      'ar' => 'تحقق من التوفر في المتجر:',
    ],
  ];
}
