<?php

/**
 * @file
 * Alshaya vs transac module file.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_alshaya_stores_finder_store_update_alter().
 */
function alshaya_vs_transac_alshaya_stores_finder_store_update_alter(&$node, array $store) {
  if (isset($store['included_in_store'])) {
    $node->get('field_brand')->setValue(trim($store['included_in_store']));
  }
}

/**
 * Implements hook_preprocess_views_view_fields().
 */
function alshaya_vs_transac_preprocess_views_view_fields__stores_finder(&$variables) {
  $view = $variables['view'];
  if (!in_array($view->current_display, ['attachment_1', 'page_3', 'page_2', 'page_1'])) {
    return;
  }
  // Change the position of the field brand, to display it after store address.
  if (isset($variables['fields']['field_brand'])) {
    $fields = $variables['fields'];
    unset($fields['field_brand']);
    $new_fields = [];
    foreach ($fields as $field => $field_object) {
      $new_fields[$field] = $field_object;
      if ($field == 'field_store_address') {
        $new_fields['field_brand'] = $variables['fields']['field_brand'];
      }
    }
    $variables['fields'] = $new_fields;
  }
}

/**
 * Implements hook_acq_sku_base_field_additions_alter().
 */
function alshaya_vs_transac_acq_sku_base_field_additions_alter(array &$fields = []) {
  $alshaya_bbw_transac_fields = \Drupal::config('alshaya_vs_transac.sku_base_fields')->get('fields');
  $fields = array_merge($fields, $alshaya_bbw_transac_fields);
}

/**
 * Implements hook_ENTITY_TYPE_load() for node entities.
 */
function alshaya_vs_transac_node_load($nodes) {
  /** @var \Drupal\node\NodeInterface $node */
  foreach ($nodes as $node) {
    if ($node->bundle() === 'acq_product') {
      $sku = SKU::loadFromSku($node->get('field_skus')->first()->getString());

      if ($sku instanceof SKU) {
        // This is done for all Meta title, Page title.
        $node->setTitle(_alshaya_vs_transac_get_title($sku, 'meta'));
      }
    }
  }
}

/**
 * Implements hook_alshaya_acm_product_build_alter().
 */
function alshaya_vs_transac_alshaya_acm_product_build_alter(&$build, SKUInterface $sku, $context = 'pdp') {
  $title = _alshaya_vs_transac_get_title($sku, $context);

  if ($context == 'search') {
    $build['#product_label'] = [
      '#markup' => $title,
    ];

    $settings = \Drupal::config('alshaya_acm_product.display_settings');

    $swatches_display_status = $settings->get('color_swatches');
    if ($swatches_display_status) {
      /** @var \Drupal\alshaya_acm_product\SkuManager $sku_manager */
      $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');

      $swatches = $sku_manager->getSwatches($sku);
      if ($swatches) {
        $swatch_plp_limit = $settings->get('swatch_plp_limit');
        $build['#swatches'] = array_slice($swatches, 0, $swatch_plp_limit, TRUE);
        $build['#swatch_more_text'] = count($swatches) > $swatch_plp_limit
          ? t('+ @swatch_count more', ['@swatch_count' => count($swatches) - $swatch_plp_limit])
          : FALSE;
      }
    }
  }
  else {
    $build['title'] = [
      '#markup' => $title,
    ];
  }
}

/**
 * Get the concatenated title based on context.
 *
 * @param \Drupal\acq_commerce\SKUInterface $sku
 *   SKU Entity.
 * @param string $context
 *   Context to get the title for.
 *
 * @return string
 *   Title.
 */
function _alshaya_vs_transac_get_title(SKUInterface $sku, $context = 'pdp') {
  $new = $sku->get('attr_sku_definition')->getString();
  $collection = $sku->get('attr_product_collection')->getString();
  $short_description = $sku->label();

  if ($context === 'pdp') {
    $title = '<span class="title--sub">' . $collection . '</span>';
    $title .= '<span class="title--main">' . $new . ' ' . $short_description . '</span>';
  }
  else {
    $title = implode(' ', [$new, $collection, $short_description]);
  }

  return $title;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_vs_transac_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product') {
    $sku = $entity->get('field_skus')->first()->getString();
    $sku_entity = SKU::loadFromSku($sku);

    if ($sku_entity instanceof SKU && $view_mode == 'full') {
      $description_value = '';
      $short_desc = [];

      if ($body = $entity->get('body')->getValue()) {
        $description_value = $body[0]['value'];
        $short_desc['label'] = [
          '#markup' => t('Short Description'),
        ];

        $short_desc_len = \Drupal::config('alshaya_acm_product.display_settings')->get('short_desc_characters');
        $short_desc_html = text_summary($description_value, NULL, $short_desc_len);
        $short_desc['value'] = [
          '#markup' => $short_desc_html . '...',
        ];

        // If short description is the same as description,
        // do not show 'Read More' button.
        if (strlen($description_value) <= $short_desc_len) {
          $build['read_more_style']['value'] = [
            '#markup' => 'display:none;',
          ];
        }
      }
      else {
        $build['read_more_style']['value'] = [
          '#markup' => 'display:none;',
        ];
      }

      $description['value'] = [
        '#markup' => $description_value,
      ];

      // Add all variables to $build in the sequence in
      // which they should be displayed.
      // $build['short_desc'] contains the description that should be
      // displayed before 'Read More'.
      $build['short_desc'] = $short_desc;
      $build['description'][] = $description;
    }
  }
}

/**
 * Config of marker label position for arabic.
 *
 * @return array
 *   Return array of arabic settings override.
 */
function _alshaya_vs_transac_marker_label_position_ar() {
  return [
    'x' => 7,
    'y' => 17,
    'single_x' => 10,
    'single_y' => 17,
  ];
}
