<?php

/**
 * @file
 * Module file.
 */
use Drupal\alshaya_hm_images\SkuAssetManager;

/**
 * Implements hook_acq_sku_import_alter().
 */
function alshaya_hm_images_acq_sku_product_sku_alter($sku, $product) {
  // Process assets data & create attributes which are needed for sorting
  // the assets while displaying them.
  $sku->attr_assets = _alshaya_hm_images_acq_sku_process_assets($product);
}

/**
 * Helper function to process asset attributes & calculate sorting params.
 *
 * @param array $product
 *   Product array containing assets to be processed.
 *
 * @return string
 *   Serialized & processed assets.
 */
function _alshaya_hm_images_acq_sku_process_assets($product) {
  $assets = [];
  if (isset($product['extension'], $product['extension']['assets'])) {
    $assets = $product['extension']['assets'];
    foreach ($assets as $key => $asset) {
      $asset_type_parts = explode('/', $asset['Data']['AssetType']);
      $assets[$key]['sortAssetType'] = end($asset_type_parts);
      $face_type = SkuAssetManager::LP_DEFAULT_ANGLE;

      if (!empty($asset['Data']['Angle']['Facing']) && !empty($asset['Data']['Angle']['Identifier'])) {
        $face_type = $asset['Data']['Angle']['Facing'] . $asset['Data']['Angle']['Identifier'];
      }
      $assets[$key]['sortFacingType'] = $face_type;
    }
  }

  return serialize($assets);
}

/**
 * Implements hook_theme().
 */
function alshaya_hm_images_theme($existing, $type, $theme, $path) {
  return [
    'alshaya_assets_gallery' => [
      'variables' => [
        'mainImage' => '',
        'hoverImage' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_acq_sku_gallery_view_alter().
 */
function alshaya_hm_images_acq_sku_gallery_view_alter(&$elements, $skus) {
  foreach ($elements as $delta => $element) {
    // Check if the gallery has a main image. If not, look for assets.
    if (empty($element['#gallery']['#mainImage'])) {
      $sku = $skus[$delta];
      // Get the assets.
      $sku_assets_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
      $assets = $sku_assets_manager->getSkuAsset($sku, 'plp', 'plp');

      // If no assets attached & the sku is configurable, try to use the
      // assets attached with first child sku attached.
      if ((!$assets) && ($sku->bundle() === 'configurable')) {
        $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');
        $child_skus = $sku_manager->getChildSkus($sku);
        foreach ($child_skus as $child_sku) {
          if ($assets = $sku_assets_manager->getSkuAsset($child_sku, 'plp', 'plp')) {
            break;
          }
        }
      }
      $plp_assets = $sku_assets_manager->processAssetsForListing($sku, $assets);

      if (isset($plp_assets['mainImage'])) {
        $sku_gallery = [
          '#theme' => 'alshaya_assets_gallery',
          '#mainImage' => $plp_assets['mainImage'],
          '#attached' => [
            'library' => [
              'alshaya_hm_images/hm_images',
            ],
          ],
        ];

        if (isset($plp_assets['hoverImage'])) {
          $sku_gallery['#hoverImage'] = $plp_assets['hoverImage'];
        }

        $elements[$delta]['#gallery'] = $sku_gallery;
      }
    }
  }
}

/**
 * Implements hook_acq_sku_pdp_gallery_media_alter().
 */
function alshaya_hm_images_acq_sku_pdp_gallery_media_alter(&$main_image, &$thumbnails, $sku) {
  if (empty($main_image)) {
    $sku_assets_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
    $main_image = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_main');
    $thumbnails = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_thumbnail');

    $zoom_images = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_zoom');
    $fullscreen_images = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_fullscreen');
    $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');

    if ((!$main_image) && ($sku->bundle() === 'configurable')) {
      $child_skus = $sku_manager->getChildSkus($sku);
      foreach ($child_skus as $child_sku) {
        if ($main_image = $sku_assets_manager->getSkuAsset($child_sku, 'pdp', 'pdp_main')) {
          $thumbnails = $sku_assets_manager->getSkuAsset($child_sku, 'pdp', 'pdp_thumbnail');
          $zoom_images = $sku_assets_manager->getSkuAsset($child_sku, 'pdp', 'pdp_zoom');
          $fullscreen_images = $sku_assets_manager->getSkuAsset($child_sku, 'pdp', 'pdp_fullscreen');
          break;
        }
      }
    }


    foreach ($thumbnails as $key => $thumbnail) {
      $thumbnails[$key]['zoomurl'] = $zoom_images[$key]['url'];
      $thumbnails[$key]['thumburl'] = $thumbnails[$key]['url'];
      $thumbnails[$key]['mediumurl'] = $main_image[$key]['url'];
      $thumbnails[$key]['type'] = 'image';
      $thumbnails[$key]['fullurl'] = $fullscreen_images[$key]['url'];
    }

    foreach ($main_image as $key => $image) {
      $temp_image['zoomurl'] = $zoom_images[$key]['url'];
      $temp_image['mediumurl'] = $main_image[$key]['url'];
      break;
    }
    $main_image = $temp_image;
  }
}

/**
 * Implements hook_acq_sku_teaser_media_alter().
 */
function alshaya_hm_images_acq_sku_teaser_media_alter(&$build, $sku_entity) {
  if (empty($build['image'])) {
    $sku_assets_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
    $teaser_assets = $sku_assets_manager->getSkuAsset($sku_entity, 'teaser', 'teaser');
    $teaser_image = $sku_assets_manager->processAssetsForTeaser($sku_entity, $teaser_assets);
    $image = [
      '#theme' => 'image',
      '#attributes' => array(
        'src' => $teaser_image['url'],
      ),
    ];

    $build['image'] = $image;
  }
}

