<?php

/**
 * @file
 * Module file.
 */

use Drupal\alshaya_hm_images\SkuAssetManager;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_acq_sku_import_alter().
 */
function alshaya_hm_images_acq_sku_product_sku_alter($sku, $product) {
  // Process assets data & create attributes which are needed for sorting
  // the assets while displaying them.
  $sku->attr_assets = _alshaya_hm_images_acq_sku_process_assets($product);
}

/**
 * Helper function to process asset attributes & calculate sorting params.
 *
 * @param array $product
 *   Product array containing assets to be processed.
 *
 * @return string
 *   Serialized & processed assets.
 */
function _alshaya_hm_images_acq_sku_process_assets($product) {
  $assets = [];
  if (isset($product['extension'], $product['extension']['assets'])) {
    $assets = $product['extension']['assets'];
    foreach ($assets as $key => $asset) {
      $asset_type_parts = explode('/', $asset['Data']['AssetType']);
      $assets[$key]['sortAssetType'] = end($asset_type_parts);
      $face_type = SkuAssetManager::LP_DEFAULT_ANGLE;

      if (!empty($asset['Data']['Angle']['Facing']) && !empty($asset['Data']['Angle']['Identifier'])) {
        $face_type = $asset['Data']['Angle']['Facing'] . $asset['Data']['Angle']['Identifier'];
      }
      $assets[$key]['sortFacingType'] = $face_type;
    }
  }

  return serialize($assets);
}

/**
 * Implements hook_theme().
 */
function alshaya_hm_images_theme($existing, $type, $theme, $path) {
  return [
    'alshaya_assets_gallery' => [
      'variables' => [
        'mainImage' => '',
        'hoverImage' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_acq_sku_gallery_view_alter().
 */
function alshaya_hm_images_acq_sku_gallery_view_alter(&$elements, $skus) {
  foreach ($elements as $delta => $element) {
    // Check if the gallery has a main image. If not, look for assets.
    if (empty($element['#gallery']['#mainImage'])) {
      $sku = $skus[$delta];
      // Get the assets.
      $sku_assets_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
      $main_image_assets = $sku_assets_manager->getSkuAsset($sku, 'plp', 'plp');
      $hover_image_assets = $sku_assets_manager->getSkuAsset($sku, 'plp_hover', 'plp');

      // If no assets attached & the sku is configurable, try to use the
      // assets attached with first child sku attached.
      if ((!$main_image_assets) && (!$hover_image_assets) && ($sku->bundle() === 'configurable')) {
        $main_image_assets = $sku_assets_manager->getChildSkuAssets($sku, 'plp', 'plp');
        $hover_image_assets = $sku_assets_manager->getChildSkuAssets($sku, 'plp_hover', 'plp');
      }

      $plp_main_image = (!empty($main_image_assets)) ? $main_image_assets[0] : NULL;
      $plp_hover_image = (!empty($hover_image_assets)) ? $hover_image_assets[0] : NULL;

      if ($plp_main_image) {
        $sku_gallery = [
          '#theme' => 'alshaya_assets_gallery',
          '#mainImage' => $plp_main_image,
          '#attached' => [
            'library' => [
              'alshaya_hm_images/hm_images',
            ],
          ],
        ];

        if ($plp_hover_image) {
          $sku_gallery['#hoverImage'] = $plp_hover_image;
        }

        $elements[$delta]['#gallery'] = $sku_gallery;
      }
    }
  }
}

/**
 * Implements hook_acq_sku_pdp_gallery_media_alter().
 */
function alshaya_hm_images_acq_sku_pdp_gallery_media_alter(&$main_image, &$thumbnails, $sku) {
  if (empty($main_image)) {
    $sku_assets_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
    $main_image = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_main');
    $thumbnails = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_thumbnail');

    $zoom_images = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_zoom');
    $fullscreen_images = $sku_assets_manager->getSkuAsset($sku, 'pdp', 'pdp_fullscreen');

    if ((!$main_image) && ($sku->bundle() === 'configurable')) {
      $thumbnails = $sku_assets_manager->getChildSkuAssets($sku, 'pdp', 'pdp_thumbnail');
      $zoom_images = $sku_assets_manager->getChildSkuAssets($sku, 'pdp', 'pdp_zoom');
      $fullscreen_images = $sku_assets_manager->getChildSkuAssets($sku, 'pdp', 'pdp_fullscreen');
    }


    foreach ($thumbnails as $key => $thumbnail) {
      $thumbnails[$key]['zoomurl'] = $zoom_images[$key]['url'];
      $thumbnails[$key]['thumburl'] = $thumbnails[$key]['url'];
      $thumbnails[$key]['mediumurl'] = $main_image[$key]['url'];
      $thumbnails[$key]['type'] = 'image';
      $thumbnails[$key]['fullurl'] = $fullscreen_images[$key]['url'];
    }

    $temp_image = [];
    foreach ($main_image as $key => $image) {
      $temp_image['zoomurl'] = $zoom_images[$key]['url'];
      $temp_image['mediumurl'] = $main_image[$key]['url'];
      break;
    }

    $main_image = $temp_image;
  }
}

/**
 * Implements hook_acq_sku_teaser_media_alter().
 */
function alshaya_hm_images_acq_sku_teaser_media_alter(&$build, $sku_entity) {
  if (empty($build['image'])) {
    $sku_assets_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
    $teaser_assets = $sku_assets_manager->getSkuAsset($sku_entity, 'teaser', 'teaser');
    $teaser_image = !empty($teaser_assets) ? $teaser_assets[0] : NULL;

    if (!empty($teaser_image)) {
      $image = [
        '#theme' => 'image',
        '#attributes' => array(
          'src' => $teaser_image['url'],
        ),
      ];

      $build['image'] = $image;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_hm_images_form_sku_base_form_alter(&$form, FormStateInterface $form_state) {
  $tree = $form_state->get('tree');
  if (!empty($tree['parent'])) {
    $parent_sku = $tree['parent'];
    $sku_asset_manager = \Drupal::service('alshaya_hm_images.skuassetsmanager');
    $config_factory = \Drupal::service('config.factory');
    $swatch_type = $config_factory->get('alshaya_hm_images.settings')->get('swatch_type');
    $config_override = $sku_asset_manager->overrideConfig($parent_sku, 'swatch');
    if (!empty($config_override['swatch_type'])) {
      $swatch_type = $config_override['swatch_type'];
    }
    if (isset($form['ajax']['configurables']['color'])) {
      $options = $form['ajax']['configurables']['color']['#options'];

      foreach ($options as $key => $option) {
        if (isset($tree['options']['color:' . $key])) {
          $sku_option = $tree['options']['color:' . $key];
          if ($swatch_type === 'miniature_image') {
            $asset = $sku_asset_manager->getSkuAsset($sku_option, 'swatch', 'swatch');
            $sku_configurable_options_color[$key] = [
              'display_value' => '<img src="' . $asset[0]['url']->toString() . '">',
              'display_label' => $sku_option->get('attr_color_label')->value,
              'swatch_type' => $swatch_type,
            ];
          }
          else {
            $sku_configurable_options_color[$key] = [
              'display_value' => $sku_option->get('attr_rgb_color')->value,
              'display_label' => $sku_option->get('attr_color_label')->value,
              'swatch_type' => $swatch_type,
            ];
          }
        }
      }

      if (!empty($sku_configurable_options_color)) {
        $form['ajax']['configurables']['color']['#attached']['drupalSettings']['sku_configurable_options_color'] = $sku_configurable_options_color;
      }
    }
  }
}
