<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\acq_sku\Entity\SKU;
use Drupal\alshaya_media_assets\Services\SkuAssetManagerInterface;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_alshaya_master_post_drupal_install().
 */
function alshaya_hm_images_alshaya_master_post_drupal_install() {
  // Add fields to store the values from attributes as fields.
  /** @var \Drupal\acq_sku\SKUFieldsManager $sku_fields_manager */
  $sku_fields_manager = \Drupal::service('acq_sku.fields_manager');

  $sku_fields_manager->updateFieldMetaInfo('color_label', [
    'configurable' => 1,
    'label' => 'Color',
  ]);
}

/**
 * Implements hook_alshaya_acm_product_light_product_data_alter().
 */
function alshaya_hm_images_alshaya_acm_product_light_product_data_alter(SKU $sku, array &$data, $type) {
  // If not light product, no need to process further.
  if ($type != 'light') {
    return;
  }

  $data['swatches'] = [];

  $swatches_display_status = (bool) \Drupal::config('alshaya_acm_product.display_settings')->get('color_swatches');
  if (!empty($data['color']) || !$swatches_display_status) {
    return;
  }

  /** @var \Drupal\alshaya_media_assets\Services\SkuAssetManagerInterface $sku_assets_manager */
  $sku_assets_manager = \Drupal::service('alshaya_media_assets.skuassetsmanager');
  // Get colors for the SKU.
  $colors = $sku_assets_manager->getColorsForSku($sku);

  foreach ($colors as $key => $color) {
    $data['swatches'][] = [
      'key' => $key,
      'color_code' => $color,
    ];
  }
}

/**
 * Implements hook_alshaya_acm_product_pdp_swath_type_alter().
 */
function alshaya_hm_images_alshaya_acm_product_pdp_swath_type_alter(SKUInterface $sku, array &$color_options_list, SKUInterface $variant_sku) {
  /** @var \Drupal\alshaya_media_assets\Services\SkuAssetManagerInterface $sku_asset_manager */
  $sku_asset_manager = \Drupal::service('alshaya_media_assets.skuassetsmanager');
  $swatch_type = $sku_asset_manager->getSkuSwatchType($sku);

  $assets = [];
  if (strtoupper($swatch_type) !== SkuAssetManagerInterface::LP_SWATCH_RGB) {
    $assets = $sku_asset_manager->getSkuAssets($variant_sku, 'swatch');
  }

  if (!empty($assets)) {
    $url = ImageStyle::load('pdp_gallery_thumbnail')->buildUrl($assets[0]['drupal_uri']);
    $color_options_list[key($color_options_list)]['display_value'] = '<img loading="lazy" src="' . file_url_transform_relative($url) . '">';
    $color_options_list[key($color_options_list)]['swatch_type'] = $swatch_type;
  }
}
