<?php

/**
 * @file
 * Alshaya JS Optimisations Module file.
 */

use Drupal\alshaya_js_optimisations\AlshayaJsOptimisationHelper;

/**
 * Implements hook_library_info_alter().
 */
function alshaya_js_optimisations_library_info_alter(&$libraries, $extension) {
  $jsService = \Drupal::service('alshaya_js_optimisations.helper');

  // Fetch Critical JS settings once,
  // instead of calling on every info_alter, per page request.
  if (!isset(AlshayaJsOptimisationHelper::$criticalJsEnabled)) {
    $jsService->fetchCriticalJsSettings();
  }

  // Preconditions.
  if (!AlshayaJsOptimisationHelper::$criticalJsEnabled || empty(AlshayaJsOptimisationHelper::$resolvedLibraries)) {
    return;
  }

  $processed_libraries = AlshayaJsOptimisationHelper::$resolvedLibraries;

  foreach ($libraries as $library => $library_item) {
    if (empty($library_item['js'])) {
      continue;
    }

    // Enforce JS load on footer.
    $library_item['header'] = FALSE;

    foreach ($library_item['js'] as $path => $library_config) {
      $attributes = !empty($library_config['attributes']) ? $library_config['attributes'] : [];
      $weight = !empty($library_config['weight']) ? $library_config['weight'] : 0;

      // Add script categories attributes and weights.
      if (
        !empty($processed_libraries[$extension]) &&
        !empty($processed_libraries[$extension][$library]) &&
        !empty($processed_libraries[$extension][$library]['attributes']) &&
        !empty($processed_libraries[$extension][$library]['attributes']['data-group']) &&
        !empty($processed_libraries[$extension][$library]['weight'])
      ) {
        $attributes = array_merge(
          $attributes,
          $processed_libraries[$extension][$library]['attributes']
        );
        $library_config['weight'] = $processed_libraries[$extension][$library]['weight'];

        // Include existing weights as fraction.
        if ($weight !== 0) {
          $library_config['weight'] = $library_config['weight'] + $weight / 100;
        }
      }

      /**
       * TEMPORARY CODE for (D9 vs jQuery UI) compatibility with Critical JS.
       */
      if (str_contains($path, 'jquery.ui')) {
        $attributes['data-group'] = 'd9-jquery-ui';
        // Reset to original library weight.
        $library_config['weight'] = $weight;
        unset($attributes['defer']);
      }
      // End of TEMPORARY CODE.

      // Add 'defer' on all ungrouped libraries.
      if (empty($attributes['data-group'])) {
        $attributes['defer'] = TRUE;
      }

      // Aggregate asset libraries with attributes.
      $library_config['perf-preprocess'] = $library_config['preprocess'] ?? TRUE;

      $library_config['attributes'] = $attributes;
      $library_item['js'][$path] = $library_config;
    }

    $libraries[$library] = $library_item;
  }
}

/**
 * Implements hook_js_alter().
 */
function alshaya_js_optimisations_js_alter(&$javascripts) {
  $js_optimisations = \Drupal::config('alshaya_js_optimisations.settings');

  $mapping = [];
  $critical_js = $js_optimisations->get('critical_js');

  $status_critical_js = !empty($critical_js) && $critical_js['status'];
  $status_uglification = $js_optimisations->get('enable_uglification');

  if ($status_uglification) {
    $mapping = file_get_contents('build/js-performance-build.json');

    if (!empty($mapping)) {
      $mapping = json_decode($mapping, TRUE);
    }
    else {
      $status_uglification = FALSE;
    }
  }

  if (!$status_critical_js && !$status_uglification) {
    // Critical JS and Uglification disabled.
    return;
  }

  foreach ($javascripts as $key => $value) {
    if ($value['type'] !== 'file') {
      // Processing not required for external scripts.
      continue;
    }

    // Enforce load on footer on all local scripts.
    if ($status_critical_js) {
      $value['preprocess'] = $value['perf-preprocess'];
      $value['scope'] = 'footer';

      /**
       * TEMPORARY CODE for (D9 vs jQuery UI) compatibility with Critical JS.
       */
      if (
        isset($value['attributes']) &&
        isset($value['attributes']['data-group']) &&
        $value['attributes']['data-group'] === 'd9-jquery-ui'
      ) {
        // Include existing weights as fraction.
        $value['weight'] = -31 + $value['weight'] / 100;
      }
      // End of TEMPORARY CODE.
    }

    // Replace the uglified JS if available in the mapping.
    if ($status_uglification && in_array($key, $mapping['source'])) {
      $value['data'] = 'build/' . $value['data'];
      $value['minified'] = TRUE;
    }

    $javascripts[$key] = $value;
  }
}

/**
 * Implements hook_cache_flush().
 *
 * Rebuild the JS categories for processed libraries.
 *
 * @todo Find a better approach to rebuild the processed libraries.
 */
function alshaya_js_optimisations_cache_flush() {
  $js_optimisations = \Drupal::service('config.factory')
    ->getEditable('alshaya_js_optimisations.settings');
  $critical_js = $js_optimisations->get('critical_js');

  if (!empty($critical_js) && $critical_js['status']) {
    $processed_libraries = \Drupal::service('alshaya_js_optimisations.helper')
      ->generateProcessedLibraries($critical_js);
    $js_optimisations->set('critical_js.processed_libraries', $processed_libraries)->save();
  }
}
