<?php

/**
 * @file
 * Alshaya JS Optimisations Module file.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_library_info_alter().
 */
function alshaya_js_optimisations_library_info_alter(&$libraries, $extension) {
  // Critical JS Implementation.
}

/**
 * Implements hook_js_alter().
 */
function alshaya_js_optimisations_js_alter(&$javascripts, AttachedAssetsInterface $assets) {
  // Alter the JS file only if js uglification is enabled.
  if (\Drupal::config('alshaya_js_optimisations.settings')->get('enable_uglification')) {
    $mapping = file_get_contents('build/mapping.json');
    // Proceed only if file is present.
    if ($mapping) {
      $mapping = json_decode($mapping, TRUE);
      // Iterate through all the javascript files and replace with the updated
      // mapping if present.
      foreach ($javascripts as $key => $value) {
        if (array_key_exists($key, $mapping)) {
          $javascripts[$key]['data'] = $mapping[$key];
        }
      }
    }
  }
}
