<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_fl_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product') {
    $sku = $entity->get('field_skus')->first()->getString();
    $sku_entity = SKU::loadFromSku($sku);

    if ($sku_entity instanceof SKU && $view_mode == 'full') {
      $return = _alshaya_fl_get_product_description($sku_entity);
      $build['short_desc'] = $return['short_desc'];
      $build['description'] = $return['description'];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_fl_acq_sku_view(array &$build, EntityInterface $sku_entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'modal') {
    $return = _alshaya_fl_get_product_description($sku_entity);
    $build['short_desc'] = $return['short_desc'];
    $build['description'] = $return['description'];
  }
}

/**
 * Get product description from SKU.
 */
function _alshaya_fl_get_product_description($sku_entity) {
  if ($overview = $sku_entity->get('attr_description')->getValue()) {
    $overview_desc['value'] = [
      '#markup' => $overview[0]['value'],
    ];
    $return['short_desc'] = $overview_desc;
    $return['description'][] = $overview_desc;
  }

  return $return;
}

/**
 * Implements hook_preprocess_block().
 */
function alshaya_fl_transac_preprocess_block(&$variables) {
  // Set alshaya-private-card image path.
  $image_path = drupal_get_path('module', 'alshaya_fl_transac') . '/images/alshaya-priv-card.svg';
  if ($variables['base_plugin_id'] == 'join_the_club') {
    $variables['content']['image']['#uri'] = $image_path;
  }
}
