<?php

/**
 * @file
 * Module file with hooks specific to COS brand.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_cos_transac_rcs_module_implements_alter(&$implementations, $hook) {
  // Make sure the hook on the brand overrides runs last.
  if ($hook == 'rcs_handlebars_templates_alter') {
    $group = $implementations['alshaya_cos_transac_rcs'];
    unset($implementations['alshaya_cos_transac_rcs']);
    $implementations['alshaya_cos_transac_rcs'] = $group;
  }
}

/**
 * Implements hook_alshaya_rcs_product_query_fields_alter().
 */
function alshaya_cos_transac_rcs_alshaya_rcs_product_query_fields_alter(array &$fields) {
  array_push(
    $fields['items'],
    'composition',
    'washing_instructions',
    'article_warning'
  );
}

/**
 * Implements hook_rcs_handlebars_templates_alter().
 */
function alshaya_cos_transac_rcs_rcs_handlebars_templates_alter(&$templates, $entity) {
  if (!$entity || $entity->bundle() !== 'rcs_product') {
    return;
  }

  $templates['product.block.description'] = 'alshaya_cos_transac_rcs';
  $templates['product.block.description_details'] = 'alshaya_cos_transac_rcs';

  /** @var  \Drupal\alshaya_acm_product\SkuManager $sku_manager **/
  $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');

  if ($sku_manager->getPdpLayout($entity) == 'pdp-magazine') {
    $templates['product.block.short_description.pdp-magazine'] = "alshaya_cos_transac_rcs";
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_cos_transac_rcs_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'rcs_product') {
    $build['#attached']['library'][] = 'alshaya_cos_transac_rcs/product';
    $build['#attached']['library'][] = 'alshaya_pims_assets/swatch';
  }
}

/**
 * Implements hook_add_to_bag_library_alter().
 */
function alshaya_cos_transac_rcs_add_to_bag_library_alter(array &$libraries) {
  // Alter swatch images for cos.
  $libraries['add_to_bag_utility']['dependencies'][] = 'alshaya_pims_assets/swatch';
}
