<?php

/**
 * @file
 * The Module file.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\block\Entity\Block;

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_bbw_module_implements_alter(&$implementations, $hook) {
  // Alter page_attachments implementation for alshaya_bbw to call at last.
  if ($hook == 'page_attachments') {
    unset($implementations['back_to_top']);
  }
}
