<?php

/**
 * @file
 * Contains form alter for sku base form.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\acq_sku\Entity\SKU;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function alshaya_cart_notification_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Altering Sku base form, which is the form implementation for Simple,
  // Grouped and Configurable products.
  if ($form_id == 'sku_base_form') {
    // Adding a form element a placeholder to populate as a cart notification.
    $form['cart_notification_modal'] = [
      '#markup' => '',
      '#prefix' => '<div id = "cart_notification">',
      '#suffix' => '</div>',
    ];

    $form['add_to_cart']['#ajax'] = [
      'callback' => '_submit_the_form',
      'wrapper' => 'cart_notification',
    ];

    // Attach the js file with the add to cart form.
    $form['#attached']['library'][] = 'core/drupal.ajax';
    $form['#attached']['library'][] = 'core/drupal.dialog.ajax';
    $form['#attached']['library'][] = 'alshaya_cart_notification/cart_notification_js';
  }
}

/**
 * AJAX callback for the add to cart submit button.
 */
function _submit_the_form(&$form, FormStateInterface $form_state) {

  // Product name.
  $string_sku = SKU::load($form_state->getValue('sku_id'))->getSKU();
  $product_value = SKU::loadFromSKU($string_sku)->get('name')->getValue();
  $product_name = $product_value[0]['value'];

  // Quantity.
  $quantity = $form_state->getValue('quantity');

  // Generating cart link.
  $url = Url::fromRoute('acq_cart.cart');
  $internal_link = \Drupal::l(t('View Cart'), $url)->getGeneratedLink();

  // Product Image.
  // @todo: Add correct image for notification once MMCPA-365 is over.
  // Adding a dummy image for now.
  $image = '<img src="http://media.laredoute.com/products1/72by72/2/8/5/500775662_1008_CO_1_1200.jpg"/>';

  $html = '<div class ="notification"><div class="1-col">';
  $html .= $image . 'Qty: <span class = "qty">' . $quantity . '</span></div>';
  $html .= '<div class="2-col"><span class ="name">' . $product_name . '</span>';
  $html .= ' has been added to your cart.';
  $html .= $internal_link;
  $html .= '</div></div>';

  // Ajax Response.
  $response = new AjaxResponse();
  $response->addCommand(new HtmlCommand('#cart_notification', $html));

  return $response;
}
