<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\rcs_magento_placeholders\Graphql\ArrayGraphQL;

/**
 * Implements hook_js_settings_alter().
 */
function rcs_magento_placeholders_js_settings_alter(&$settings, AttachedAssetsInterface $assets) {
  // Invoke hook to get default values.
  $query_fields = \Drupal::moduleHandler()->invokeAll('rcs_graphql_query_fields');

  // Allow other modules to alter the data.
  \Drupal::moduleHandler()->alter('rcs_graphql_query_fields', $query_fields);

  // Convert array to graphql.
  foreach ($query_fields as $query => $fields) {
    $query_fields[$query] = ArrayGraphQL::convert($fields);
  }

  // Expose via drupal settings.
  $settings['rcs_magento_placeholders']['graphql_query_fields'] = $query_fields;
}
