<?php

/**
 * @file
 * Module file.
 */

use Drupal\rcs_magento_placeholders\Graphql\ArrayGraphQL;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_page_attachments().
 */
function rcs_magento_placeholders_page_attachments(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  // Invoke hook to get default values.
  $query_fields = \Drupal::moduleHandler()->invokeAll('rcs_graphql_query_fields');

  // Allow other modules to alter the data.
  \Drupal::moduleHandler()->alter('rcs_graphql_query_fields', $query_fields);

  // Convert array to graphql.
  foreach ($query_fields as $query => $fields) {
    $query_fields[$query] = ArrayGraphQL::convert($fields);
  }

  $script = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => Markup::create('var rcsGraphqlQueryFields = ' . json_encode($query_fields) . ';'),
    ],
    'rcs_magento_placeholders',
  ];
  array_unshift($attachments['#attached']['html_head'], $script);
}
