<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_olapic_library_info_alter(&$libraries, $extension) {
  // Unset the `alshaya_olapic_sdk` library as for rcs, we will have to load the
  // olapic script after the RCS entity is loaded.
  if ($extension === 'alshaya_olapic' && isset($libraries['alshaya_olapic_sdk'])) {
    unset($libraries['alshaya_olapic_sdk']);
  }
}
