<?php

/**
 * @file
 * Primary module hooks for Alshaya Customer Portal module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_node_view().
 */
function alshaya_customer_portal_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $node = $build['#node'];
  if ($node->bundle() == 'static_html') {
    // Get current node's static html field.
    $body = $node->get('body')->value;
    // Check if the [customer_portal:iframe] token is there in the content.
    if (preg_match('/\[customer_portal\:iframe\]/', $body)) {
      $user = \Drupal::currentUser();
      $user = \Drupal::entityTypeManager()->getStorage('user')->load($user->id());
      $bubbleable_metadata = new BubbleableMetadata();
      $body = \Drupal::token()->replace($body, ['user' => $user], [], $bubbleable_metadata);
      $bubbleable_metadata->applyTo($build['body']);
      // Replace the text in the body with the token replaced text.
      $build['body'][0]['#text'] = $body;
    }
  }
}
