<?php

/**
 * @file
 * Dynamic yield.
 *
 * Adds the required Javascript to your site to allow tracking by the Dynamic
 * yield.
 */

use Drupal\dynamic_yield\Event\DyPageType;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_page_attachments().
 */
function dynamic_yield_page_attachments(array &$page) {

  /** @var \Drupal\dynamic_yield\DynamicYieldService $dynamic_yield */
  $dynamic_yield = \Drupal::service('dynamic_yield.dynamic_yield');

  if (!(\Drupal::service('router.admin_context')->isAdminRoute()) && $dynamic_yield->getSectionId()) {

    // Add DY script tags to header.
    $static_script = [[
      '#tag' => 'script',
      '#attributes' => [
        'src' => $dynamic_yield->getDynamicYieldStaticScriptCode(),
      ],
    ],
      'spath',
    ];
    array_unshift($page['#attached']['html_head'], $static_script);
    $dynamic_script = [[
      '#tag' => 'script',
      '#attributes' => [
        'src' => $dynamic_yield->getDynamicYieldDynamicScriptCode(),
      ],
    ],
      'dpath',
    ];
    array_unshift($page['#attached']['html_head'], $dynamic_script);

    // Dispatch the DyPageType event to set the context.
    $request = \Drupal::request();
    \Drupal::service('event_dispatcher')->dispatch(DyPageType::DY_SET_CONTEXT, new DyPageType($request, $dynamic_yield));
    $language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
    $context = [
      'type' => $dynamic_yield->getDyContext(),
      'lng' => $language,
    ];
    $js = 'window​.DY = ​window​.DY || {};';
    $js = $js . 'DY.recommendationContext = ' . Json::encode($context) . ';';
    $context_script = [[
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => $js,
    ],
      'dycontext',
    ];
    array_unshift($page['#attached']['html_head'], $context_script);

    // Add DY preconnect and dns-prefetch link tags to header.
    $prefetch_urls = [
      '//rcom-eu.dynamicyield.com',
      '//st-eu.dynamicyield.com',
      '//cdn-eu.dynamicyield.com',
    ];
    foreach ($prefetch_urls as $key => $prefetch_url) {
      $rel = 'dns-prefetch';
      $tag = 'dy_dns_prefetch' . $key;
      $link_tag = _dynamic_yield_get_head_link_tag($rel, $prefetch_url, $tag);
      array_unshift($page['#attached']['html_head'], $link_tag);
    }
    foreach ($prefetch_urls as $key => $prefetch_url) {
      $rel = 'preconnect';
      $tag = 'dy_preconnect' . $key;
      $link_tag = _dynamic_yield_get_head_link_tag($rel, $prefetch_url, $tag);
      array_unshift($page['#attached']['html_head'], $link_tag);
    }

  }
  $page['#cache']['tags'][] = 'config:dynamic_yield.settings';
}

/**
 * Get prefetch link tags.
 *
 * @param string $rel
 *   Rel attribute.
 * @param string $href
 *   Link tag href.
 * @param string $tag
 *   HTML head tag for alter.
 *
 * @return array
 *   Link tag array.
 */
function _dynamic_yield_get_head_link_tag($rel, $href, $tag) {
  return [
    [
      '#tag' => 'link',
      '#attributes' => [
        'rel' => $rel,
        'href' => $href,
      ],
    ],
    $tag,
  ];
}
