<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\acq_sku\Entity\SKU;

 /**
 * Implements hook_alshaya_search_algolia_object_alter().
 */
function alshaya_pdp_pretty_path_alshaya_search_algolia_object_alter(array &$object) {
  /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
  $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
  $swatch_attribute = $skuManager->getPdpSwatchAttributes();

  if (!empty($swatch_attribute)) {
    /** @var \Drupal\alshaya_pdp_pretty_path\Service\AlshayaPdpPrettyPathHelper $pdpPrettyPathHelper */
    $pdpPrettyPathHelper = \Drupal::service('alshaya_pdp_pretty_path.helper');
    $pdpPrettyPathHelper->prepareAndIndexSwatchUrls($object, $swatch_attribute);
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_pdp_pretty_path_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $current_uri = \Drupal::request()->getRequestUri();
  if (($entity->bundle() !== 'acq_product') && stripos($current_uri, '/-', 0) === false) {
    return;
  }

  if ($view_mode === 'full') {
    /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
    $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
    $sku = $skuManager->getSkuForNode($entity);
    $sku = !empty($sku) ? SKU::loadFromSku($sku) : NULL;
    // If not able to load SKU return.
    if (!($sku instanceof SKU)) {
      return;
    }

    $settingsKey = 'productInfo';
    $param = mb_substr($current_uri, stripos($current_uri, '/-') + 2);
    $clean_param = preg_replace('/.html/', '', $param);

    $build['#attached']['library'][] = 'alshaya_pdp_pretty_path/pdp_pretty_path_detail';
    $build['#attached']['drupalSettings'][$settingsKey][$sku->getSku()]['swatch_param'] = $clean_param ?? '';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_pdp_pretty_path_library_info_alter(&$libraries, $extension) {
  if ($extension === 'alshaya_acm_product') {
    unset($libraries['product_pdp_path']['js']['js/alshaya_acm_product.pdp_path.js']);
  }
}
