<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_payment_tabby_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Need processing only for products with Full, Modal, Matchback view mode.
  if ($entity->bundle() != 'acq_product') {
    return;
  }

  if (in_array($view_mode, ['full', 'modal', 'matchback'])) {
    /** @var \Drupal\alshaya_payment_tabby\AlshayaTabbyHelper $AlshayaTabbyHelper */
    $AlshayaTabbyHelper = \Drupal::service('alshaya_payment_tabby.helper');
    $AlshayaTabbyHelper->getTabbyPaymentBuild($build);
  }
}
