<?php

/**
 * @file
 * Contains hook implementations for Alshaya Product Zoom module.
 */

/**
 * Implements hook_theme().
 */
function alshaya_product_zoom_theme($existing, $type, $theme, $path) {
  return [
    'product_zoom' => [
      'variables' => [
        'mainImage' => '',
        'thumbnails' => '',
        'pager_flag' => '',
        'properties' => '',
        'labels' => '',
        'image_slider_position_pdp' => '',
      ],
      'template' => 'product_zoom',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function alshaya_product_zoom_preprocess_node(&$variables) {
  // Add PDP slider position config to variable so it is available in themes.
  $pdp_image_slider_position = \Drupal::config('alshaya_acm_product.settings')->get('image_slider_position_pdp');
  $variables['image_slider_position_pdp'] = 'slider-position-' . $pdp_image_slider_position;
  // Add PDP slider position config to drupalSettings so we can use it in JS.
  $variables['#attached']['drupalSettings']['alshaya_white_label']['image_slider_position_pdp'] = 'slider-position-' . $pdp_image_slider_position;
}
