<?php

/**
 * @file
 * Contains hook implementations for Alshaya Product Zoom module.
 */

/**
 * Implements hook_theme().
 */
function alshaya_product_zoom_theme($existing, $type, $theme, $path) {
  return [
    'product_zoom' => [
      'variables' => [
        'mainImage' => '',
        'thumbnails' => '',
        'pager_flag' => '',
        'properties' => '',
        'labels' => '',
        'image_slider_position_pdp' => '',
        'lazy_load_placeholder' => \Drupal::config('alshaya_master.settings')->get('lazy_load_placeholder'),
      ],
      'template' => 'product_zoom',
    ],
    'alshaya_magazine' => [
      'variables' => [
        'sku' => '',
        'thumbnails' => '',
        'pager_flag' => '',
        'properties' => '',
        'labels' => '',
        'lazy_load_placeholder' => \Drupal::config('alshaya_master.settings')->get('lazy_load_placeholder'),
        'product_title' => NULL,
        'price_block' => NULL,
        'price_block_identifier' => NULL,
        'tabby' => NULL,
        'postpay' => NULL,
      ],
      'template' => 'alshaya_magazine',
    ],
    'matchback_gallery' => [
      'variables' => [
        'mainImage' => '',
        'thumbnails' => '',
        'pager_flag' => '',
        'properties' => '',
        'labels' => '',
        'image_slider_position_pdp' => '',
      ],
      'template' => 'matchback_gallery',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function alshaya_product_zoom_preprocess_node(&$variables) {
  if (isset($variables['view_mode'])) {
    if ($variables['view_mode'] == 'full' || $variables['view_mode'] == 'modal') {
      $skuManager = \Drupal::service('alshaya_acm_product.skumanager');

      // Add PDP slider position config to variable so it is available
      // in themes.
      $pdp_image_slider_position = '';

      if (isset($variables['node']) && $variables['node']->bundle() === 'acq_product') {
        $pdp_image_slider_position = $skuManager->getImageSliderPosition($variables['node']);
      }

      $variables['image_slider_position_pdp'] = 'slider-position-' . $pdp_image_slider_position;

      // Add PDP slider position config to drupalSettings so we can use it
      // in JS.
      $variables['#attached']['drupalSettings']['alshaya_white_label']['image_slider_position_pdp'] = 'slider-position-' . $pdp_image_slider_position;
    }
  }
}
