<?php

/**
 * @file
 * Contains hook implementations for Alshaya Product Zoom module.
 */

/**
 * Implements hook_theme().
 */
function alshaya_product_zoom_theme($existing, $type, $theme, $path) {
  return [
    'product_zoom' => [
      'variables' => [
        'mainImage' => '',
        'thumbnails' => '',
        'properties' => '',
      ],
      'template' => 'product_zoom',
    ],
    'product_zoom_gallery' => [
      'variables' => [
        'thumbnails' => '',
      ],
      'template' => 'product_zoom_gallery',
    ],
  ];
}
