<?php

/**
 * @file
 * Install file for alshaya_store_finder_transac.
 */

/**
 * Implements hook_update().
 *
 * Install the stores finder transac settings.
 */
function alshaya_stores_finder_transac_update_8001() {
  alshaya_config_install_configs(['alshaya_stores_finder_transac.settings'], 'alshaya_stores_finder_transac');
  alshaya_config_install_configs(['views.view.stores_finder'], 'alshaya_stores_finder');
}
