<?php

/**
 * @file
 * Module file.
 */

use Drupal\alshaya_addressbook\AlshayaAddressBookManagerInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function alshaya_stores_finder_transac_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['store_address'] = [
    'render element' => 'elements',
    'variables' => [
      'address' => [],
    ],
  ];

  return $items;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_stores_finder_transac_node_view(array &$build,
                                       EntityInterface $entity,
                                       EntityViewDisplayInterface $display,
                                       $view_mode) {
  if ($entity->bundle() !== 'store') {
    return;
  }

  /** @var \Drupal\alshaya_addressbook\AlshayaAddressBookManager $address_book_manager */
  $address_book_manager = \Drupal::service('alshaya_addressbook.manager');

  $build['field_store_address'] = [];

  $address_values = $entity->get('field_address')->getValue();

  if (empty($address_values)) {
    return;
  }

  $build['field_store_address'] = [
    '#theme' => 'store_address',
    '#address' => reset($address_values),
  ];
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function alshaya_stores_finder_transac_preprocess_views_view_field__field_store_address(&$variables) {
  /** @var \Drupal\alshaya_addressbook\AlshayaAddressBookManager $address_book_manager */
  $address_book_manager = \Drupal::service('alshaya_addressbook.manager');

  /** @var \Drupal\alshaya_stores_finder_transac\StoresFinderUtility $store_finder_utility */
  $store_finder_utility = \Drupal::service('alshaya_stores_finder_transac.utility');

  /* @var \Drupal\node\Entity\Node $node */
  $node = $variables['row']->_entity;
  /* @var \Drupal\Core\Entity\EntityRepository $entity_repository */
  $entity_repository = \Drupal::service('entity.repository');
  $current_langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  // Get correct translated node in current language.
  $node = $entity_repository->getTranslationFromContext($node, $current_langcode);
  $variables['output'] = $store_finder_utility->getStoreAddress($node);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_stores_finder_transac_form_node_store_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\alshaya_addressbook\AlshayaAddressBookManager $address_book_manager */
  $address_book_manager = \Drupal::service('alshaya_addressbook.manager');

  // Set the default country.
  $form['field_address']['widget'][0]['address']['#default_value']['country_code'] = _alshaya_custom_get_site_level_country_code();
}
