<?php

/**
 * @file
 * Module file for alshaya_kw.
 */

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_tokens_alter().
 */
function alshaya_kw_tokens_alter(array &$replacements, array $context, BubbleableMetadata $bubbleable_metadata) {
  if ($context['type'] == 'alshaya_seo' && isset($context['tokens']['cities'])) {
    $token_service = \Drupal::token();
    $replacements['[alshaya_seo:cities]'] = $token_service->replace('[alshaya_seo:city1]', $context['data'], $context['options']);
  }
}
