<?php

/**
 * @file
 * The Module file.
 */

/**
 * Implements hook_theme().
 */
function alshaya_ve_non_transac_theme($existing, $type, $theme, $path) {
  $items = [];
  $items['book_appointment'] = [
    'variables' => [
      'iframe_url' => NULL,
    ],
  ];
  return $items;
}

/**
 * Implements hook_acquia_search_get_list_of_possible_cores_alter().
 */
function alshaya_ve_non_transac_acquia_search_get_list_of_possible_cores_alter(&$possible_core_ids, $core_service) {

  // @codingStandardsIgnoreLine
  global $acsf_site_code;

  $ah_env = preg_replace('@[^a-zA-Z0-9]+@', '', $core_service->ah_env);

  // During the production deployment, `01update` env is used and there we
  // don't have appropriate solr cores. So use `01live` solr.
  if ($ah_env == '01update') {
    $ah_env = '01live';
  }
  // For non-prod env, we have env likes `01dev3up`, `01qaup` which are used
  // during release/deployment. We just remove last `up` from the env name
  // to use the original env. For example - original env for `01dev3up` will
  // be `01dev3`.
  elseif (substr($ah_env, -2) == 'up') {
    $ah_env = substr($ah_env, 0, -2);
  }

  array_unshift($possible_core_ids, $core_service->acquia_identifier . '.' . $ah_env . '.' . $acsf_site_code);

}
