<?php

/**
 * @file
 * Contains form alter for sku base form.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alshaya_acm_cart_notification_form_sku_base_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Attach the js file with the add to cart form.
  $form['#attached']['library'][] = 'core/drupal.ajax';
  $form['#attached']['library'][] = 'core/drupal.dialog.ajax';
  $form['#attached']['library'][] = 'alshaya_acm_cart_notification/cart_notification_js';
  $form['#attached']['drupalSettings']['currency_code'] = \Drupal::config('acq_commerce.currency')->getRawData()['currency_code'];
  $form['#attached']['drupalSettings']['ajaxSpinnerMessageInterval'] = (int) \Drupal::config('alshaya_master.settings')->get('ajax_spinner_message_interval');
  $form['#attached']['drupalSettings']['addToCartNotificationTime'] = \Drupal::config('alshaya_acm_cart_notification.settings')->get('notification_time');
}

/**
 * Implements hook_theme().
 */
function alshaya_acm_cart_notification_theme($existing, $type, $theme, $path) {
  return [
    'add_to_cart_error' => [
      'variables' => [
        'message' => '',
      ],
      'template' => 'add-to-cart-error',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function alshaya_acm_cart_notification_theme_suggestions_input_alter(array &$suggestions, array $variables) {
  $routmatch = \Drupal::routeMatch();
  if ($routmatch->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::request()->attributes->get('node');

    $is_add_to_cart = !empty($variables['element']['#id']) && ($variables['element']['#id'] == 'edit-add-to-cart');
    if ($node->bundle() == 'acq_product' && $is_add_to_cart) {
      $suggestions[] = 'input__add_to_cart';
    }
  }
}

/**
 * Implements hook_sku_variant_info_alter().
 */
function alshaya_acm_cart_notification_sku_variant_info_alter(array &$variant, SKUInterface $child, SKUInterface $parent) {
  /** @var \Drupal\acq_sku\ProductInfoHelper $productInfoHelper */
  $productInfoHelper = \Drupal::service('acq_sku.product_info_helper');
  // Include the utility file to get product image.
  \Drupal::moduleHandler()->loadInclude('alshaya_acm_product', 'inc', 'alshaya_acm_product.utility');
  $variant['cart_title'] = $productInfoHelper->getTitle($child, 'basket');
  $image = alshaya_acm_get_product_display_image($child, 'pdp_gallery_thumbnail', 'cart');

  // Prepare image style url.
  if (!empty($image['#uri'])) {
    $image = file_url_transform_relative(ImageStyle::load($image['#style_name'])->buildUrl($image['#uri']));
  }

  $variant['cart_image'] = is_string($image) ? $image : '';
}
