<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_paragraphs module.
 */

/**
 * Implements hook_update_N().
 *
 * Update paragraphs.
 */
function alshaya_paragraphs_update_8001() {
  $paragraph_banner_target = \Drupal::configFactory()->getEditable('core.entity_view_display.paragraph.banner.default');
  $paragraph_banner_target->set('content.field_link.settings.target', '0')->save();
}
