<?php

/**
 * @file
 * Alshaya paragraphs module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_paragraphs_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
  $form['promo_block_config'] = [
    '#type' => 'select',
    '#title' => t('Promo block display configuration'),
    '#options' => [
      1 => t('Image and button is clickable'),
      2 => t('Only button is clickable'),
    ],
    '#default_value' => \Drupal::configFactory()
      ->getEditable('alshaya_paragraphs.settings')
      ->get('promo_block_config'),
  ];

  $form['#submit'][] = '_alshaya_paragraphs_site_information_submit';
}

/**
 * Submit handler for the site information form.
 */
function _alshaya_paragraphs_site_information_submit($form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('alshaya_paragraphs.settings')
    ->set('promo_block_config', $form_state->getValue('promo_block_config'))
    ->save();
}
