<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\node\Entity\Node;
use Drupal\acq_sku\Entity\SKU;
use Drupal\alshaya_color_split\AlshayaColorSplitManager;
use Drupal\acq_commerce\SKUInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_sofa_sectional_node_view(array &$build, Node $entity, EntityViewDisplay $display, $view_mode) {
  if ($entity->bundle() !== 'acq_product' && $view_mode !== 'full') {
    return;
  }

  // Add cache tag.
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], ['config:alshaya_sofa_sectional.settings']);

  // Get sofa sectional configuration.
  $config = \Drupal::config('alshaya_sofa_sectional.settings');

  if (!$config->get('enabled')) {
    return;
  }

  // Get category ids from config.
  $category_ids = $config->get('category_ids');

  // Get category ids from product field.
  $categories = $entity->get('field_category')->getValue();
  $categories = array_column($categories, 'target_id');

  // Check if category ids from field are present in config.
  $categories = array_intersect($categories, $category_ids);
  if (!empty($categories)) {
    // If category ids present in config attach library.
    $build['#attached']['library'][] = 'alshaya_sofa_sectional/sofa_sectional';
    $build['#attached']['library'][] = 'alshaya_sofa_sectional/sofa_sectional_utilities';
    $build['#attached']['library'][] = 'alshaya_white_label/sofa-sectional';
  }
}

/**
 * Implements hook_alshaya_acm_product_skubaseform_alter().
 */
function alshaya_sofa_sectional_alshaya_acm_product_skubaseform_alter(&$form, SKUInterface $sku_entity) {
  // Get sofa sectional configuration.
  $config = \Drupal::config('alshaya_sofa_sectional.settings');

  if (!$config->get('enabled') || empty($sku_entity)) {
    return;
  }

  /** @var \Drupal\alshaya_acm_product\SkuManager $sku_manager */
  $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');

  /** @var \Drupal\alshaya_acm_product\SkuImagesManager $sku_images_manager */
  $sku_images_manager = \Drupal::service('alshaya_acm_product.sku_images_manager');

  // Get the sku from the Sku entity.
  $sku = $sku_entity->getSku();

  $configurables = $form['#attached']['drupalSettings']['configurableCombinations'][$sku]['configurables'];

  // Get the swatches data.
  $swatches = $sku_images_manager->getAllSwatchData($sku_entity);
  if (!empty($swatches)) {
    foreach ($swatches as $attribute_code => $attribute_values) {
      // Mark the attributes which are swatches.
      if (in_array($attribute_code, array_keys($configurables))
      && !$configurables[$attribute_code]['is_swatch']) {
        $configurables[$attribute_code]['is_swatch'] = TRUE;
        $configurables[$attribute_code]['swatches'] = [];
        foreach ($swatches[$attribute_code] as $swatch) {
          $configurables[$attribute_code]['swatches'][] = [
            'label' => $swatch['display_label'],
            'data' => $swatch['display_value'] ?? $swatch['image_url'] ?? NULL,
            'value' => $swatch['value'],
            'type' => $swatch['swatch_type'],
            'child_sku_code' => $swatch['child_sku_code'],
          ];
        }
      }
    }
  }

  // Reassign with the updates values.
  $form['#attached']['drupalSettings']['configurableCombinations'][$sku]['configurables'] = $configurables;
}
