<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_sofa_sectional module.
 */

/**
 * Implements hook_update_N().
 *
 * Alshaya sofa sectional translations.
 */
function alshaya_sofa_sectional_install() {
  // Add translations.
  $strings = [
    'your selection summary' => [
      'ar' => '',
    ],
    'Select options 1 to @length' => [
      'ar' => '',
    ],
    'Clear Options' => [
      'ar' => '',
    ],
  ];

  alshaya_i18n_save_translations($strings);
}
