<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\node\Entity\Node;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_sofa_sectional_node_view(array &$build, Node $entity, EntityViewDisplay $display, $view_mode) {
  if ($entity->bundle() !== 'acq_product' && $view_mode !== 'full') {
    return;
  }

  // Add cache tag.
  $build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'] ?? [], ['config:alshaya_sofa_sectional.settings']);

  // Get sofa sectional configuration.
  $config = \Drupal::config('alshaya_sofa_sectional.settings');

  if (!$config->get('enabled')) {
    return;
  }

  // Get category ids from config.
  $category_ids = $config->get('category_ids');

  // Get category ids from product field.
  $categories = $entity->get('field_category')->getValue();
  $categories = array_column($categories, 'target_id');

  // Check if category ids from field are present in config.
  $categories = array_intersect($categories, $category_ids);
  if (!empty($categories)) {
    // If category ids present in config attach library.
    $build['#attached']['library'][] = 'alshaya_sofa_sectional/sofa_sectional';
    $build['#attached']['library'][] = 'alshaya_white_label/sofa-sectional';
  }
}
