<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_preprocess_block().
 */
function alshaya_menus_preprocess_block(&$variables) {
  switch ($variables['base_plugin_id']) {
    case 'system_menu_block':
      $super_category_config = \Drupal::config('alshaya_acm_product_category.super_category.settings');
      // Check super category feature status.
      if (!$super_category_config->get('status')) {
        return;
      }

      // Check current menu type.
      if (!in_array($variables['derivative_plugin_id'], $super_category_config->get('footer_menu_blocks'))) {
        return;
      }

      // Update block cache context.
      $variables['content']['#cache']['contexts'][] = 'url.path';

      // Default parent term id.
      $parent_id = $super_category_config->get('default_category_tid');

      /** @var \Drupal\alshaya_acm_product_category\ProductCategoryTree $product_category_tree */
      $product_category_tree = \Drupal::service('alshaya_acm_product_category.product_category_tree');
      $term = $product_category_tree->getCategoryTermFromRoute();
      if (!empty($term)) {
        $parent_id = $product_category_tree->getCategoryTermRootParent($term);
      }
      // Get all the menu items.
      $items = &$variables['content']['#items'];

      // Loop through each item, & remove item that isn't in parent term id.
      foreach ($items as $id => $item) {
        $menu_link = $item['original_link'];
        $options = $menu_link->getOptions();
        $super_category = !empty($options['super_category']) ? array_filter($options['super_category']) : NULL;
        if (!empty($term) && !empty($super_category)) {
          if (!in_array($parent_id, $super_category)) {
            unset($items[$id]);
          }
        }
      }
      break;
  }
}
