<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Locale\CountryManager;

/**
 * Utility function to get the site level country code.
 *
 * @return string
 *   Country code.
 */
function _alshaya_custom_get_site_level_country_code() {
  $default_site_country = &drupal_static(__FUNCTION__);
  if (empty($default_site_country)) {
    $default_site_country = \Drupal::config('system.date')->get('country.default');
    if (empty($default_site_country)) {
      // If no default country is set, take the first as default.
      $full_country_list = \Drupal::service('address.country_repository')->getList();
      $default_site_country = key($full_country_list);
    }
  }
  return $default_site_country;
}

/**
 * Utility function to get the country name.
 *
 * @return string
 *   Country name.
 */
function get_country_name() {
  $country_name = 'Kuwait';
  $default_site_country = \Drupal::config('system.date')->get('country.default');
  $countries = CountryManager::getStandardList();
  foreach ($countries as $key => $value) {
    if ($key == $default_site_country) {
      $country_name = (string) $value;
      break;
    }
  }
  return $country_name;
}
