<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Locale\CountryManager;

/**
 * Utility function to get the site level country code.
 *
 * @return string
 *   Country code.
 */

function _alshaya_custom_get_site_level_country_code() {
  $default_site_country = &drupal_static(__FUNCTION__);
  if (empty($default_site_country)) {
    $default_site_country = \Drupal::config('system.date')->get('country.default');
    if (empty($default_site_country)) {
      // If no default country is set, take the first as default.
      $full_country_list = \Drupal::service('address.country_repository')->getList();
      $default_site_country = key($full_country_list);
    }
  }
  return $default_site_country;
}

/**
 * Utility function to get the country name.
 *
 * @return string
 *   Country name.
 */
function _alshaya_custom_get_site_level_country_name() {
  $country_name = '';
  $default_site_country = _alshaya_custom_get_site_level_country_code();
  $countries = CountryManager::getStandardList();
  if (isset($countries[$default_site_country])) {
    $default_site_country = $countries[$default_site_country];
  }
  return $default_site_country;
}