<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_admin module.
 */

/**
 * Implements hook_uninstall().
 *
 * Reset config. We need to ensure all the configuration added in the module
 * is deleted to allow the ON/OFF code to work.
 */
function alshaya_admin_uninstall() {
  Drupal::configFactory()->getEditable('views.view.content_product.yml')->delete();
  \Drupal::configFactory()->getEditable('views.view.content.yml')->delete();
}
