<?php

/**
 * @file
 * Acquia Commerce customer module file.
 *
 * Provides base hooks to the customer profile functionality of Acquia Commerce
 * connector.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function acq_customer_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'user') {
    $fields = [];
    $fields['acq_customer_id'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Customer ID'))
      ->setDescription(t('Remote ID used to identify user'))
      ->setDisplayOptions('form', [
        'type' => 'number',
        'weight' => 30,
        'default_value' => 0,
      ])
      ->setDisplayConfigurable('form', TRUE);

    return $fields;
  }
}

/**
 * Implements hook_theme().
 */
function acq_customer_theme($existing, $type, $theme, $path) {
  return [
    'user_order' => [
      'render element' => 'elements',
      'variables' => ['order' => NULL],
    ],
  ];
}
