<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_page_attachments_alter().
 */
function sprinklr_page_attachments_alter(array &$page) {
  $sprinklr_settings = \Drupal::config('sprinklr.settings');
  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'] ?? [], $sprinklr_settings->getCacheTags());

  $sprinklr_helper = \Drupal::service('sprinklr.helper');
  // Skip the processing of sprinklr chatbot if sprinklr feature is disabled.
  if (!$sprinklr_helper->isSprinklrFeatureEnabled()) {
    return;
  }

  $app_id = $sprinklr_settings->get('app_id');
  // Skip the processing of sprinklr chatbot if app id is not provided.
  if (empty($app_id)) {
    return;
  }

  // Return if sprinklr is not enabled on current path.
  if (!$sprinklr_helper->isSprinklrEnabledOnCurrentPath()) {
    return;
  }

  // Attach sprinklr library to the allowed urls only if
  // sprinklr app id is provided.
  $page['#attached']['drupalSettings']['sprinklr']['appId'] = $app_id;
  $page['#attached']['library'][] = 'sprinklr/sprinklr';
}
