<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_cron().
 *
 * Ensure password expiration is not applied for sync user.
 */
function alshaya_password_polic_cron() {
  // Load user used to sync from Conductor to Drupal.
  $user = user_load_by_name(Settings::get('alshaya_acm_user_username'));

  // Don't do anything if user not found.
  if (empty($user)) {
    return;
  }

  // Get current timestamp.
  $timestamp = gmdate(DATETIME_DATETIME_STORAGE_FORMAT, REQUEST_TIME);

  // Reset last pass reset and expiration flag.
  $user->set('field_last_password_reset', $timestamp);
  $user->set('field_password_expiration', '0');
  $user->save();
}
