<?php

/**
 * @file
 * Contains BazaarVoice related static strings.
 */

/**
 * BazaarVoice strings.
 */
function _alshaya_bazaar_voice_static_strings() {
  return [
    [
      'key' => 'default_error',
      'value' => t('Sorry, something went wrong. Please try again later'),
    ],
    [
      'key' => 'edit',
      'value' => t('Edit'),
    ],
    [
      'key' => 'location',
      'value' => t('Location'),
    ],
    [
      'key' => 'date',
      'value' => t('Date'),
    ],
    [
      'key' => 'time',
      'value' => t('Time'),
    ],
    [
      'key' => 'continue',
      'value' => t('Continue'),
    ],
    [
      'key' => 'yes',
      'value' => t('Yes'),
    ],
    [
      'key' => 'no',
      'value' => t('No'),
    ],
    [
      'key' => 'close',
      'value' => t('Close'),
    ],
    [
      'key' => 'delete',
      'value' => t('Delete'),
    ],
    [
      'key' => 'cancel',
      'value' => t('Cancel'),
    ],
    [
      'key' => 'confirmation_header',
      'value' => t('Thank you for booking at Boots.'),
    ],
    [
      'key' => 'confirmation_subheader',
      'value' => t('A confirmation will be sent through email. Manage your appointments online.'),
    ],
    [
      'key' => 'email_address_label',
      'value' => t('Email address'),
    ],
    [
      'key' => 'show_less',
      'value' => t('Show less'),
    ],
    [
      'key' => 'read_more',
      'value' => t('Read more'),
    ],
    [
      'key' => 'empty_field_default_error',
      'value' => t('Please enter value for %fieldTitle.'),
    ],
    [
      'key' => 'empty_select_field_default_error',
      'value' => t('Please select value for %fieldTitle.'),
    ],
    [
      'key' => 'valid_email_error',
      'value' => t('The email address %mail is not valid. Please enter a valid email address.'),
    ],
    [
      'key' => 'text_min_chars_limit_error',
      'value' => t('Please enter a minimum of %minLength characters for %fieldTitle.'),
    ],
    [
      'key' => 'reviews',
      'value' => t('reviews'),
    ],
    [
      'key' => 'write_a_review',
      'value' => t('Write a review'),
    ],
    [
      'key' => 'star',
      'value' => t('star'),
    ],
    [
      'key' => 'stars',
      'value' => t('stars'),
    ],
    [
      'key' => 'post_a_comment',
      'value' => t('Post a Comment'),
    ],
    [
      'key' => 'post_comment',
      'value' => t('post comment'),
    ],
    [
      'key' => 'terms_and_condition',
      'value' => t('Terms and condition'),
    ],
    [
      'key' => 'comment',
      'value' => t('Comment'),
    ],
    [
      'key' => 'screen_name',
      'value' => t('Screen name'),
    ],
    [
      'key' => 'review_comment_submission',
      'value' => t('Thanks for submitting your comment! It is currently being moderated and will be visible shortly.'),
    ],
    [
      'key' => 'write_review_submission',
      'value' => t('Thanks for submitting your review! It is currently being moderated and will be visible shortly.'),
    ],
    [
      'key' => 'review_recommendation_text',
      'value' => t('I would recommend this product.'),
    ],
    [
      'key' => 'clear_all',
      'value' => t('Clear all'),
    ],
    [
      'key' => 'ratings_reviews',
      'value' => t('Ratings + Reviews'),
    ],
    [
      'key' => 'report',
      'value' => t('Report'),
    ],
    [
      'key' => 'reported',
      'value' => t('Reported'),
    ],
    [
      'key' => 'previous_page',
      'value' => t('Previous Page'),
    ],
    [
      'key' => 'next_page',
      'value' => t('Next Page'),
    ],
    [
      'key' => 'rating',
      'value' => t('Rating'),
    ],
    [
      'key' => 'next_page',
      'value' => t('Next Page'),
    ],
    [
      'key' => 'no_review_found',
      'value' => t('No review found.'),
    ],
    [
      'key' => 'filter_sort',
      'value' => t('Filter + Sort'),
    ],
    [
      'key' => 'bv_auth_confirmation_message',
      'value' => t('Thank you for your contribution.'),
    ],
    [
      'key' => 'submission_msg',
      'value' => t('We have verified your submission. If the content is approved it will be published within 72 hours.'),
    ],
    [
      'key' => 'survey_exp_not_likely',
      'value' => t('Not at all likely'),
    ],
    [
      'key' => 'survey_exp_extremely_likely',
      'value' => t('Extremely likely'),
    ],
    [
      'key' => 'upload_pics',
      'value' => t('Show us how it looks! Upload up to 5 pics'),
    ],
    [
      'key' => 'upload_photo',
      'value' => t('Upload a Photo'),
    ],
    [
      'key' => 'recommend_this_product',
      'value' => t('I would like to recommend this product.'),
    ],
    [
      'key' => 'post_review',
      'value' => t('Post review'),
    ],
    [
      'key' => 'review_guidelines',
      'value' => t('Review Guidelines'),
    ],
    [
      'key' => 'review',
      'value' => t('Review'),
    ],
    [
      'key' => 'vote',
      'value' => t('Vote'),
    ],
    [
      'key' => 'true_to_size',
      'value' => t('True to size'),
    ],
    [
      'key' => 'no_user_review_found',
      'value' => t('You have not submitted any reviews.'),
    ],
    [
      'key' => 'no_reviews_yet',
      'value' => t('No reviews yet'),
    ],
    [
      'key' => 'first_to_review',
      'value' => t('Tell others what you think. Be the first to review this product!'),
    ],
    [
      'key' => 'load_more',
      'value' => t('Load more'),
    ],
    [
      'key' => 'selectlist_placeholder',
      'value' => t('Select...'),
    ],
  ];
}
