<?php

/**
 * @file
 * Contains BazaarVoice related translations.
 */

/**
 * BazaarVoice translation.
 */
function _alshaya_bazaar_voice_translations() {
  $strings = [];
  $strings['v1'] = [
    'Write a review' => [
      'ar' => 'كتابة مراجعة',
    ],
    'Ratings + Reviews' => [
      'ar' => 'التقييمات + المراجعات',
    ],
    'True to size' => [
      'ar' => 'نفس المقاس',
    ],
    'Clear all' => [
      'ar' => 'امسح كل التعليق',
    ],
    'star' => [
      'ar' => 'نجمة',
    ],
    'of' => [
      'ar' => 'من',
    ],
    'Item Code' => [
      'ar' => 'رمز المنتج',
    ],
    'Thanks for submitting your comment! It is currently being moderated and will be visible shortly.' => [
      'ar' => 'شكرا لإرسال تعليقك! سوف نقوم بمراجعته، وسيظهر على الموقع قريباً.',
    ],
    'stars' => [
      'ar' => 'نجوم',
    ],
    'Was this @contentTypeDisplayValue helpful?' => [
      'ar' => 'هل كانت هذه المراجعة مفيدة؟',
    ],
    'Filter + Sort' => [
      'ar' => 'الفرز والتصنيف',
    ],
    'Upload a Photo' => [
      'ar' => 'حمّل صورة',
    ],
    'Extremely likely' => [
      'ar' => 'من المرجح جداً',
    ],
    'Not at all likely' => [
      'ar' => 'من المستبعد جداً',
    ],
    'Post review' => [
      'ar' => 'انشر التقييم',
    ],
    'Report' => [
      'ar' => 'إبلاغ',
    ],
    'post comment' => [
      'ar' => 'كتابة تعليق',
    ],
    'Screen name' => [
      'ar' => 'اسم المستخدم',
    ],
    '@customerCount% of Customers Recommended the Product' => [
      'ar' => '@customerCount% من الزبائن ينصحون بشراء هذا المنتج',
    ],
    'Terms and condition' => [
      'ar' => 'الشروط والأحكام',
    ],
    'Rating' => [
      'ar' => 'التقييم',
    ],
    'Post a Comment' => [
      'ar' => 'كتابة تعليق',
    ],
    'Select...' => [
      'ar' => 'أختر...',
    ],
    'Please enter value for %fieldTitle.' => [
      'ar' => 'يرجى إدخال بيانات إلى %fieldTitle.',
    ],
    'Please select value for %fieldTitle.' => [
      'ar' => 'يرجى اختيار بيانات %fieldTitle.',
    ],
    'Show us how it looks! Upload up to 5 pics' => [
      'ar' => 'أرنا كيف يبدو المنتج! حمّل لغاية 5 صور',
    ],
    'Review Guidelines' => [
      'ar' => 'إرشادات المراجعة',
    ],
    'Yes' => [
      'ar' => 'نعم',
    ],
    'No' => [
      'ar' => 'لا',
    ],
    'The email address %mail is not valid. Please enter a valid email address.' => [
      'ar' => 'البريد الإلكتروني %mail غير صالح. يرجى إدخال بريد إلكتروني صالح.',
    ],
    'Please enter a minimum of %minLength characters for %fieldTitle.' => [
      'ar' => 'الرجاء إدخال %minLength حرف كحد أدنى لـ %fieldTitle.',
    ],
    'Thanks for submitting your review! It is currently being moderated and will be visible shortly.' => [
      'ar' => 'شكراً على إبداء رأيك! سوف نقوم بمراجعته لكي يتم نشره في أقرب وقت.',
    ],
    'I would like to recommend this product.' => [
      'ar' => 'سوف أوصي بهذا المنتج',
    ],
    'You have already reviewed the product.' => [
      'ar' => 'لقدم قمت بعرض المنتج من قبل.',
    ],
    'years' => [
      'ar' => 'سنوات',
    ],
    'Review' => [
      'ar' => 'المراجعة',
    ],
    'reviews' => [
      'ar' => 'مراجعة',
    ],
    'Reviews' => [
      'ar' => 'مراجعة',
    ],
    'Vote' => [
      'ar' => 'تصويت',
    ],
    'Load more' => [
      'ar' => 'تحميل المزيد من',
    ],
    'No reviews yet.' => [
      'ar' => 'لم تتم مراجعته بعد.',
    ],
    'Tell others what you think. Be the first to review this product.' => [
      'ar' => 'أخبر الآخرين عن رأيك. كن أول من يراجع هذا المنتج.',
    ],
    'View review' => [
      'ar' => 'عرض المراجعة',
    ],
    'Featured' => [
      'ar' => 'أهم المراجعات',
    ],
    'Top' => [
      'ar' => 'أفضل',
    ],
    'Contributor' => [
      'ar' => 'المراجعين',
    ],
    'Verified Purchaser' => [
      'ar' => 'مشترٍ معتمد',
    ],
    'Expert' => [
      'ar' => 'خبير',
    ],
    'Staff' => [
      'ar' => 'موظف',
    ],
    'Original posted on' => [
      'ar' => 'تم نشرها في الأصل على',
    ],
    'Translate with Google' => [
      'ar' => 'الترجمة باستخدام جوجل',
    ],
    'Back to Original Review' => [
      'ar' => 'الرجوع للمراجعة الأصلي',
    ],
    'Back to Original Comment' => [
      'ar' => 'الرجوع للتعليق الأصلي',
    ],
  ];

  // Strings to show message to unauthorized user to write a review.
  $strings['v2'] = [
    'Please login with the email address used to purchase this product to write a review.' => [
      'ar' => 'يرجى تسجيل الدخول من خلال البريد الالكتروني المستخدم لشراء هذا المنتج كي تتمكن من كتابة مراجعة.',
    ],
    'Please complete your review in the same language as your selected view to proceed.' => [
      'ar' => 'يرجى استكمال التقييم باللغة المختارة عند التصفح.',
    ],
    'Top Rated' => [
      'ar' => 'أعلى التقييمات',
    ],
  ];

  return $strings;
}

/**
 * Get translations for given version.
 *
 * @param string $version
 *   Version number like 'v1' etc.
 *
 * @return array
 *   Translations.
 */
function _alshaya_bazaar_voice_get_translations(string $version = '') {
  $translations = _alshaya_bazaar_voice_translations();
  // If no version mentioned, return all version strings.
  if (empty($version)) {
    $trans_data = [];
    foreach ($translations as $trans) {
      $trans_data = array_merge($trans_data, $trans);
    }

    return $trans_data;
  }

  return $translations[$version] ?? [];
}
