<?php

/**
 * @file
 * Contains BazaarVoice related translations.
 */

/**
 * BazaarVoice translation.
 */
function _alshaya_bazaar_voice_translations() {
  return [
    'Write a review' => [
      'ar' => 'كتابة مراجعة',
    ],
    'Ratings + Reviews' => [
      'ar' => 'التقييمات + المراجعات',
    ],
    'True to size' => [
      'ar' => 'نفس المقاس',
    ],
    'stars' => [
      'ar' => 'نجوم',
    ],
    'Was this @contentTypeDisplayValue helpful?' => [
      'ar' => 'هل كانت هذه المراجعة مفيدة؟',
    ],
    'Filter + Sort' => [
      'ar' => 'الفرز والتصنيف',
    ],
    'Upload a Photo' => [
      'ar' => 'حمّل صورة',
    ],
    'Extremely likely' => [
      'ar' => 'من المرجح جداً',
    ],
    'Not at all likely' => [
      'ar' => 'من المستبعد جداً',
    ],
    'Post review' => [
      'ar' => 'انشر التقييم',
    ],
    'Report' => [
      'ar' => 'إبلاغ',
    ],
    'post comment' => [
      'ar' => 'كتابة تعليق',
    ],
    'Screen name' => [
      'ar' => 'اسم المستخدم',
    ],
    '@customerCount% of Customers Recommended the Product' => [
      'ar' => '@customerCount% من الزبائن ينصحون بشراء هذا المنتج',
    ],
    'Terms and condition' => [
      'ar' => 'الشروط والأحكام',
    ],
    'Rating' => [
      'ar' => 'التقييم',
    ],
    'Post a Comment' => [
      'ar' => 'كتابة تعليق',
    ],
    'Select...' => [
      'ar' => 'أختر...',
    ],
    'Please enter value for %fieldTitle.' => [
      'ar' => 'يرجى ادخال قيمة إلى %fieldTitle.',
    ],
    'Please select value for %fieldTitle.' => [
      'ar' => 'يرجى اختيار قيمة إلى %fieldTitle.',
    ],
  ];
}
