<?php

/**
 * @file
 * Module file.
 */

use Drupal\acq_commerce\SKUInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\acq_sku\Entity\SKU;

/**
 * Implements hook_alshaya_acm_product_build_alter().
 */
function alshaya_bazaar_voice_alshaya_acm_product_build_alter(&$build, SKUInterface $sku, $context = 'pdp') {
  if ($context !== 'pdp') {
    return;
  }
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
  $basic_configs = $alshayaBazaarVoice->getBasicConfigurations();
  // Disable BazaarVoice Rating and Review in PDP
  // if checkbox is checked in bazaarVoice Settings Form.
  if ($basic_configs['pdp_rating_reviews']) {
    return;
  }

  /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
  $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
  $productNode = $skuManager->getDisplayNode($sku->getSku());

  if ($productNode instanceof NodeInterface) {
    // Get sanitized sku.
    $sanitized_sku = $skuManager->getSanitizedSku($sku->getSku());
    $settings = $alshayaBazaarVoice->getProductBazaarVoiceDetails($sku, $productNode, $sanitized_sku, $basic_configs);

    // Get the current pdp layout.
    $config = \Drupal::config('alshaya_acm_product.settings');
    $product_pdp_layout = $config->get('pdp_layout');

    if (!empty($productNode->get('field_select_pdp_layout')->getValue()[0]['value'])) {
      $product_pdp_layout = $productNode->get('field_select_pdp_layout')->getValue()[0]['value'];
    }

    $build['reviews_rating']['#markup'] = '<div id="reviews-rating"></div>';
    $build['reviews_section']['#markup'] = '<div id="reviews-section"></div>';

    if ($product_pdp_layout !== 'magazine_v2') {
      $build['#attached']['library'][] = 'alshaya_bazaar_voice/rating';
      $build['#attached']['library'][] = 'alshaya_bazaar_voice/reviews';
    }

    $build['#attached']['library'][] = 'alshaya_bazaar_voice/iovation';
    $build['#cache']['contexts'][] = 'url.query_args:bv_authtoken';
    $build['#attached']['drupalSettings']['productInfo'][$sanitized_sku]['alshaya_bazaar_voice'] = $settings;
  }
}

/**
 * Implements hook_theme().
 */
function alshaya_bazaar_voice_theme($existing, $type, $theme, $path) {
  return [
    'alshaya_strings' => [
      'variables' => [
        'strings' => [],
      ],
      'template' => 'alshaya-bazaar-voice-strings',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function alshaya_bazaar_voice_page_attachments(array &$page) {
  // Configurations must be on page before iovation's JavaScript loads.
  // Add script to generate the device finger printing string.
  $page['#attached']['html_head'][] = [[
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#attributes' => [
      'type' => 'text/javascript',
      ],
    '#value' => 'window.IGLOO = window.IGLOO || {
    "bbout_element_id" : "ioBlackBox","enable_rip" : true,"enable_flash" : false,"install_flash" : false,"loader" : {"version" : "general5","fp_static" : false}};',
    ],
    'fppath',
    ];
}

/**
 * Implements hook_alshaya_spc_checkout_confirmation_order_build_alter().
 * Updating build array for bv pixel integration.
 *
 * @param array $build
 *   Reference to the build array of spc confirmation.
 * @param string $order
 *   Order details array.
 */
function alshaya_bazaar_voice_alshaya_spc_checkout_confirmation_order_build_alter(array &$build, $order) {
  /** @var \Drupal\bazaar_voice\BazaarVoiceApiHelper $bazaar_voice */
  $bazaar_voice_api_helper = \Drupal::service('bazaar_voice.api_helper');
  if (!empty($build['#attached']['drupalSettings'])){
    if ($bazaar_voice_api_helper->isBvConfigurationsAvailable()) {
      $bazaarvoice_config = \Drupal::config('bazaar_voice.settings');
      $locale = $bazaarvoice_config->get('locale');
      // Attach bvpixel library to order confirmation page.
      $build['#attached']['library'][] = 'alshaya_bazaar_voice/bvpixel_tracking';
      if(!empty($build['#attached']['drupalSettings']['order_details'])) {
        $build['#attached']['drupalSettings']['order_details']['bv_extra_params'] = [
          'currency' => $order['base_currency_code'] ?? '',
          'tax' => $order['base_tax_amount'] ?? '',
          'shipping' => $order['shipping_incl_tax'] ?? '',
          'city' => $order['shipping']['address']['city'] ?? '',
          'country' => $order['shipping']['address']['country_id'] ?? '',
          'nickname' => $order['customer_firstname'] ?? '',
          'customer_is_guest' => $order['customer_is_guest'] ?? '',
          'customer_id' => $order['customer_id'] ?? '',
          'locale' => $locale ?? '',
        ];
      }
    }
  }
}

/**
 * Implements allowed values callback.
 */
function alshaya_bazaar_voice_write_review_fields() {
  $write_review_fields = [];
  /** @var \Drupal\alshaya_bazaar_voice\AlshayaBazaarVoice $alshaya_bazaar_voice */
  $alshaya_bazaar_voice = \Drupal::service('alshaya_bazaar_voice.service');
  // Get optional fields and set based on categories.
  $fields_config = $alshaya_bazaar_voice->getWriteReviewFieldsConfig();
  foreach ($fields_config as $key => $value) {
    if ($value['#visible'] && $value['#type'] !== 'processed_text' && !$value['#required']) {
      $write_review_fields[$value['#id']] = $value['#title'];
    }
  }

  return $write_review_fields;
}

/**
 * Implements hook_alshaya_my_account_links_alter().
 */
function alshaya_bazaar_voice_alshaya_my_account_links_alter(array &$links) {
  // Add reviews links for my account page.
  $links['user_reviews'] = [
    'text' => t('Reviews'),
    'route' => 'alshaya_bazaar_voice.user_reviews',
    'weight' => 41,
  ];
}

/**
 * Implements hook_alshaya_srp_sort_settings_form_alter().
 */
function alshaya_bazaar_voice_form_alshaya_srp_sort_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['sort_options']['#options']['attr_bv_average_overall_rating'] = t('Top Rated');
}

/**
 * Implements hook_bazaar_voice_settings_form_alter().
 */
function alshaya_bazaar_voice_form_bazaar_voice_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = '_alshaya_bazaar_voice_plp_rating_reviews';
}

/**
 * Update configs for rating filter and top rated in plp/slp.
 */
function _alshaya_bazaar_voice_plp_rating_reviews($form, FormStateInterface $form_state) {
  $slp_settings = Drupal::configFactory()->getEditable('alshaya_search.settings');
  $plp_settings = Drupal::configFactory()->getEditable('alshaya_acm_product_position.settings');
  $facet_block = Block::load('bvrating');
  if ($form_state->getValue('plp_rating_reviews')) {
    // Disable top rated option.
    $slp_settings->set('sort_options.attr_bv_average_overall_rating', '');
    $plp_settings->set('sort_options.attr_bv_average_overall_rating', '');
    // Disable rating filter block.
    $facet_block->disable();
  } else {
    // Enable top rated option.
    $slp_settings->set('sort_options.attr_bv_average_overall_rating', 'attr_bv_average_overall_rating');
    $plp_settings->set('sort_options.attr_bv_average_overall_rating', 'attr_bv_average_overall_rating');
    // Enable rating filter block.
    $facet_block->enable();
  }
  // Save the settings.
  $slp_settings->save();
  $plp_settings->save();
  $facet_block->save();
}

/**
 * Implements hook_algolia_react_common_configs_alter().
 */
function alshaya_bazaar_voice_algolia_react_common_configs_alter(&$response) {
  /** @var \Drupal\alshaya_bazaar_voice\Service\AlshayaBazaarVoice $alshayaBazaarVoice */
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
  $basic_configs = $alshayaBazaarVoice->getBasicConfigurations();
  $response['commonAlgoliaSearch']['showReviewsRating'] = 1;
  if ($basic_configs['plp_rating_reviews']) {
    $response['commonAlgoliaSearch']['showReviewsRating'] = 0;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function alshaya_bazaar_voice_preprocess_node(&$variables) {
  // Add bazaavoice related strings.
  if ($variables['node']->bundle() === 'acq_product') {
    $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
    $variables['bazaar_voice_strings'] = $alshayaBazaarVoice->getBazaarvoiceStrings();
  }
}

/**
 * Implements hook_alshaya_acm_customer_build_product_details_alter().
 */
function alshaya_bazaar_voice_alshaya_acm_customer_recent_order_build_alter(array &$build) {
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
  $basic_configs = $alshayaBazaarVoice->getBasicConfigurations();
  // Return if bazaarvoice disabled in my account.
  if ($basic_configs['myaccount_rating_reviews']) {
    return;
  }
  $bazaarvoiceSettings = [];
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
  foreach (array_keys($build['recent_order']) as $key) {
    foreach ($build['recent_order'][$key]['#order']['items'] as $item_key => $item) {
      $build['recent_order'][$key]['#order']['items'][$item_key]['bazaarvoice_link'] = TRUE;
      $bazaarvoiceSettings[$item['sku']] = $alshayaBazaarVoice->getMyAccountProductSettings($item['sku'], $basic_configs);
    }
    $build['recent_order'][$key]['#attached'] = $alshayaBazaarVoice->getOrdersPageAttachment($bazaarvoiceSettings);
  }
  if (!isset($build['strings'])) {
    $build['strings'] = $alshayaBazaarVoice->getBazaarvoiceStrings();
  }
}

/**
 * Implements hook_alshaya_acm_customer_orders_details_build_alter().
 */
function alshaya_bazaar_voice_alshaya_acm_customer_orders_details_build_alter(array &$order, array &$build) {
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
  $basic_configs = $alshayaBazaarVoice->getBasicConfigurations();
  // Return if bazaarvoice disabled in my account.
  if ($basic_configs['myaccount_rating_reviews']) {
    return;
  }
  $bazaarvoiceSettings = [];
  $alshayaBazaarVoice = \Drupal::service('alshaya_bazaar_voice.service');
  foreach ($order['items'] as $key => $item) {
    $bazaarvoiceSettings[$item['sku']] = $alshayaBazaarVoice->getMyAccountProductSettings($item['sku'], $basic_configs);
  }
  if (!empty($bazaarvoiceSettings)) {
    $build['#attached'] = $alshayaBazaarVoice->getOrdersPageAttachment($bazaarvoiceSettings); 
    foreach(array_keys($build['#products']) as $key) {
      $build['#products'][$key]['bazaarvoice_link'] = TRUE;
    }
  }
  $build['#strings'] = $alshayaBazaarVoice->getBazaarvoiceStrings();
}
