<?php

/**
 * @file
 * Contains BazaarVoice related static strings.
 */

/**
 * BazaarVoice strings.
 */
function _alshaya_bazaar_voice_static_strings() {
  return [
    [
      'key' => 'default_error',
      'value' => t('Sorry, something went wrong. Please try again later'),
    ],
    [
      'key' => 'edit',
      'value' => t('Edit'),
    ],
    [
      'key' => 'location',
      'value' => t('Location'),
    ],
    [
      'key' => 'date',
      'value' => t('Date'),
    ],
    [
      'key' => 'time',
      'value' => t('Time'),
    ],
    [
      'key' => 'continue',
      'value' => t('Continue'),
    ],
    [
      'key' => 'yes',
      'value' => t('Yes'),
    ],
    [
      'key' => 'no',
      'value' => t('No'),
    ],
    [
      'key' => 'close',
      'value' => t('Close'),
    ],
    [
      'key' => 'delete',
      'value' => t('Delete'),
    ],
    [
      'key' => 'cancel',
      'value' => t('Cancel'),
    ],
    [
      'key' => 'confirmation_header',
      'value' => t('Thank you for booking at Boots.'),
    ],
    [
      'key' => 'confirmation_subheader',
      'value' => t('A confirmation will be sent through email. Manage your appointments online.'),
    ],
    [
      'key' => 'first_name_label',
      'value' => t('First name'),
    ],
    [
      'key' => 'last_name_label',
      'value' => t('Last name'),
    ],
    [
      'key' => 'email_address_label',
      'value' => t('Email address'),
    ],
    [
      'key' => 'show_less',
      'value' => t('Show less'),
    ],
    [
      'key' => 'read_more',
      'value' => t('Read more'),
    ],
    [
      'key' => 'empty_field_default_error',
      'value' => t('Please enter value for this field.'),
    ],
    [
      'key' => 'empty_select_field_default_error',
      'value' => t('Please select value for this field.'),
    ],
    [
      'key' => 'valid_email_error',
      'value' => t('The email address %mail is not valid.'),
    ],
    [
      'key' => 'text_min_chars_limit_error',
      'value' => t('Minimum characters limit for this field is %minLength characters.'),
    ],
  ];
}
