<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_preprocess_template().
 */
function alshaya_cos_transac_preprocess_product_zoom(&$vars) {
  $pdp_magazine_override = \Drupal::config('alshaya_acm_product.settings')->get('pdp_magazine_override');
  // Set pdp_magazine_override to show swatch images in mobile with classic gallery in magazine layout.
  if ($pdp_magazine_override) {
    $vars['pdp_magazine_override'] = $pdp_magazine_override;
  }
}
