<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_acm_knet module.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_install().
 */
function alshaya_acm_knet_install() {
  // Configure K-Net settings.
  $config = \Drupal::configFactory()->getEditable('alshaya_acm_knet.settings');

  $settings = Settings::get('alshaya_acm_knet.settings');

  foreach ($settings as $key => $value) {
    $config->set($key, $value);
  }

  $config->save();
}
