<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\acq_cart\CartInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_alshaya_acm_checkout_pre_place_order().
 */
function alshaya_acm_knet_alshaya_acm_checkout_pre_place_order(CartInterface $cart) {
  $session = \Drupal::request()->getSession();
  $selected_payment = $session->get('selected_payment_method');

  // We want to redirect to K-Net only if payment method is K-Net.
  if ($selected_payment != 'knet') {
    return;
  }

  /** @var \Drupal\alshaya_knet\Helper\KnetHelper $knetHelper */
  $knetHelper = \Drupal::service('alshaya_knet.helper');

  $order_id = $cart->getExtension('real_reserved_order_id');
  $totals = $cart->totals();

  try {
    $knetHelper->setCartId($cart->id());
    $knetHelper->setCurrentUserId(\Drupal::currentUser()->id());
    $knetHelper->setCustomerId($cart->customerId());
    $knetHelper->setOrderId($order_id);
    $request = $knetHelper->initKnetRequest($totals['grand']);

    $response = new RedirectResponse($request['url']);
    $response->send();
    exit;
  }
  catch (\Exception $e) {
    // Log message in watchdog.
    \Drupal::logger('alshaya_acm_knet')->error($e->getMessage());

    \Drupal::service('alshaya_acm.cart_helper')->cancelCartReservation($e->getMessage());

    // Show generic message to user.
    drupal_set_message(t('Sorry, we are unable to process your payment. Please contact our customer service team for assistance.'), 'error');

    $response = new RedirectResponse(Url::fromRoute('acq_checkout.form', ['step' => 'payment'])->toString());
    $response->send();
    exit;
  }
}
