<?php

/**
 * @file
 * Install, update and uninstall functions for the alshaya_main_menu module.
 */

/**
 * Implements hook_update_N().
 *
 * Adding config for the mega menu highlights.
 */
function alshaya_main_menu_update_8401() {
  $configs = [
    'alshaya_main_menu.settings',
    'language.config.ar.alshaya_main_menu.settings',
  ];
  alshaya_config_install_configs($configs, 'alshaya_main_menu');
}
