<?php

/**
 * @file
 * Module file for Alshaya Olapic.
 */


 /**
  * Implements hook_library_info_build().
  */

 function alshaya_olapic_library_info_build() {
    $config = \Drupal::config('alshaya_olapic.settings');
    $olapic_external_script_url = $config->get('olapic_external_script_url');
    $libraries = [];
    if (!empty($olapic_external_script_url)) {
      $libraries['alshaya_olapic_widget'] = [
        'footer' => true,
        'js' => [
          $olapic_external_script_url => [
            'type' => 'external',
            'attributes' => [
              'async' => "async",
            ],
          ],
        ],
      ];
   }
   return $libraries;
 }

 /**
  * Implements hook_theme().
  */
 function alshaya_olapic_theme($existing, $type, $theme, $path) {
   return [
     'olapic_widget' => [
       'variables' => [
         'instance_id' => '',
         'div_id' => '',
         'dynamic_product_id' => '',
       ],
       'template' => 'olapic_widget',
     ],
   ];
 }
