<?php

/**
 * @file
 * Module file for Alshaya Olapic.
 */

/**
 * Implements hook_library_info_build().
 */
function alshaya_olapic_library_info_build() {
  $config = \Drupal::config('alshaya_olapic.settings');
  $olapic_external_script_url = $config->get('olapic_external_script_url');
  $libraries = [];
  if (!empty($olapic_external_script_url)) {
    $libraries['alshaya_olapic_sdk'] = [
      'js' => [
        $olapic_external_script_url => [
          'type' => 'external',
          'attributes' => [
            'defer' => TRUE,
          ],
        ],
      ],
    ];
  }
  return $libraries;
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_olapic_library_info_alter(&$libraries, $extension) {
  if (
    $extension === 'alshaya_olapic' &&
    isset($libraries['alshaya_olapic_sdk']) &&
    isset($libraries['alshaya_olapic_widget'])
  ) {
    foreach ($libraries['alshaya_olapic_widget']['js'] as $source => $options) {
      if (!isset($options['attributes'])) {
        $options['attributes'] = [];
      }
      $options['attributes']['defer'] = TRUE;
      $libraries['alshaya_olapic_widget']['js'][$source] = $options;
    }
    $libraries['alshaya_olapic_widget']['dependencies'][] = 'alshaya_olapic/alshaya_olapic_sdk';
  }
}

/**
 * Implements hook_theme().
 */
function alshaya_olapic_theme($existing, $type, $theme, $path) {
  return [
    'olapic_widget' => [
      'variables' => [
        'instance_id' => '',
        'div_id' => '',
        'dynamic_product_id' => '',
        'tag' => '',
        'data_olapic' => '',
        'data_apikey' => '',
      ],
      'template' => 'olapic_widget',
    ],
  ];
}

/**
 * Updated build array for olapic checkout pixel.
 *
 * @param array $build
 *   Reference to the build array of spc confirmation.
 * @param string $data_apikey
 *   Olapic data api key.
 * @param string $base_currency_code
 *   Olapic data currency code.
 */
function alshaya_olapic_checkout_pixel_build_alter(array &$build, $data_apikey, $base_currency_code) {
  if (!empty($build['#attached']['drupalSettings'])) {
    $config = \Drupal::config('alshaya_olapic.settings');
    $olapic_checkout_pixel_external_script_url = $config->get('olapic_checkout_pixel_external_script_url') ?? '';
    $drupalSettings = $build['#attached']['drupalSettings'];
    $country_code = strtoupper(_alshaya_custom_get_site_level_country_code());
    $build['#attached']['library'][] = 'alshaya_olapic/olapic_checkout_pixel';
    $cartObject = [
      'products' => array_values($drupalSettings['order_details']['items']) ?? '',
      'transaction_id' => $drupalSettings['order_details']['order_number'] ?? '',
      'currency' => $base_currency_code ?? '',
      'country' => $country_code ?? '',
      'data_apikey' => $data_apikey ?? '',
      'olapic_checkout_pixel_external_script_url' => $olapic_checkout_pixel_external_script_url ?? '',
    ];
    $build['#attached']['drupalSettings']['cartObject'] = $cartObject;
  }
}
