<?php

/**
 * @file
 * Alshaya MUJI transac module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\acq_sku\Entity\SKU;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_mu_transac_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'acq_product') {

    if ($view_mode == 'full') {
      /** @var \Drupal\alshaya_acm_product\SkuManager $skuManager */
      $skuManager = \Drupal::service('alshaya_acm_product.skumanager');
      $sku = $skuManager->getSkuForNode($entity);
      $sku_entity = SKU::loadFromSku($sku);
      if ($sku_entity instanceof SKU) {
        $return = _alshaya_mu_transac_get_product_description($sku_entity);
        $build['short_desc'] = $return['short_desc'];
        $build['description'] = $return['description'];
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_mu_transac_acq_sku_view(array &$build, EntityInterface $sku_entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'modal') {
    $return = _alshaya_mu_transac_get_product_description($sku_entity);
    $build['short_desc'] = $return['short_desc'];
    $build['description'] = $return['description'];
  }
}

/**
 * Get product description from SKU.
 */
function _alshaya_mu_transac_get_product_description($sku_entity) {
  $return = [];

  if ($body = $sku_entity->get('attr_description')->getString()) {
    $return['short_desc']['value'] = [
      '#markup' => $body,
    ];
  }

  $details['label'] = [
    '#markup' => t('Details'),
  ];
  $details['value'] = [
    "#theme" => 'item_list',
    '#items' => [],
  ];

  if ($details1 = $sku_entity->get('attr_short_description1')->getString()) {
    $details['value']['#items'][] = $details1;
  }
  if ($details2 = $sku_entity->get('attr_short_description2')->getString()) {
    $details['value']['#items'][] = $details2;
  }

  if (!empty($details['value']['#items'])) {
    $return['description'][] = $details;
  }

  $materials_care['label'] = [
    '#markup' => t('Materials'),
  ];
  $materials_care['value'] = [
    "#theme" => 'item_list',
    '#items' => [],
  ];

  if ($materials_care1 = $sku_entity->get('attr_material_en')->getString()) {
    $materials_care['value']['#items'][] = $materials_care1;
  }

  if (!empty($materials_care['value']['#items'])) {
    $return['description'][] = $materials_care;
  }

  return $return;
}
