<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Field\FieldFilteredMarkup;
use Drupal\alshaya_pdp_layouts\Event\PreprocessMagazineEvent;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Set dynamic allowed values for the select pdp layout field.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function alshaya_pdp_layouts_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $alshaya_pdp_layouts = \Drupal::service('plugin.manager.alshaya_pdp_layouts');
  $layouts = $alshaya_pdp_layouts->getDefinitions();
  $pdp_layout_options = [];
  foreach ($layouts as $key => $value) {
    $pdp_layout_options[$key] = $value['label']->__toString();
  }

  return $pdp_layout_options;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_pdp_layouts_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_acq_product_edit_form' || $form_id == 'node_acq_product_form') {
    $product_settings_form = \Drupal::config('alshaya_acm_product.settings');
    $global_layout = $product_settings_form->get('pdp_layout');
    // Adding a description to show the inherit settings for PDP layout.
    $form['field_select_pdp_layout']['widget']['#description'] = FieldFilteredMarkup::create(t('Inherit layout will apply the layout selected globally: @global_layout', ['@global_layout' => $global_layout]));
    // Changing the label of the none option.
    $form['field_select_pdp_layout']['widget']['#options']['_none'] = t('Inherit');
  }
}

/**
 * Implements hook_preprocess_alshaya_magazine().
 */
function alshaya_pdp_layouts_preprocess_alshaya_magazine(&$vars) {
  $event = new PreprocessMagazineEvent($vars);

  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(PreprocessMagazineEvent::EVENT_NAME, $event);
  $vars = $event->getVariables();
}

/**
 * Implements hook_alshaya_context_key_from_layout_alter().
 */
function alshaya_pdp_layouts_alshaya_context_key_from_layout_alter(string &$context_key, string $pdp_layout) {
  $alshaya_pdp_layouts = \Drupal::service('plugin.manager.alshaya_pdp_layouts');
  $plugin_manager = $alshaya_pdp_layouts->createInstance($pdp_layout, []);
  $context_key = $plugin_manager->getCotextFromPdpLayout($context_key, $pdp_layout);
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_pdp_layouts_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  $sharethis_manager = \Drupal::service('sharethis.manager');
  $data_options = $sharethis_manager->getOptions();
  $path = $node->toUrl()->setAbsolute()->toString();
  $title = $node->getTitle();
  // Node types to show share panel.
  $enabled_types = $data_options['node_types'];
  // Condition to render share this on the selected node types.
  if (isset($enabled_types[$node->bundle()]) && $enabled_types[$node->bundle()] === $node->bundle() && $display->getcomponent('sharethis')) {
    $st_js = $sharethis_manager->sharethisIncludeJs();
    $content = $sharethis_manager->renderSpans($data_options, $title, $path);
    $build['#attached']['drupalSettings']['sharethis'] = $st_js;
    $build['#attached']['drupalSettings']['sharethis']['content'] = $content['st_spans'];
    $build['#attached']['library'][] = 'sharethis/sharethispickerexternalbuttonsws';
    $build['#attached']['library'][] = 'sharethis/sharethispickerexternalbuttons';
    $build['#attached']['library'][] = 'sharethis/sharethis';
  }
}
