<?php

/**
 * @file
 * Contains Appointment related static strings.
 */

/**
 * Appointment strings.
 */
function _alshaya_appointment_static_strings() {
  return [
    [
      'key' => 'select_store_button',
      'value' => t('Select Store'),
    ],
    [
      'key' => 'loading_map_placeholder',
      'value' => t('Loading Map'),
    ],
    [
      'key' => 'loading_stores_placeholder',
      'value' => t('Loading Stores'),
    ],
    [
      'key' => 'prev',
      'value' => t('Prev'),
    ],
    [
      'key' => 'next',
      'value' => t('Next'),
    ],
    [
      'key' => 'sign_in_header',
      'value' => t('I have an account'),
    ],
    [
      'key' => 'sign_in_subheader',
      'value' => t('Log in for faster booking and to manage your appointments online'),
    ],
    [
      'key' => 'sign_in_button',
      'value' => t('Sign in'),
    ],
    [
      'key' => 'or',
      'value' => t('Or'),
    ],
    [
      'key' => 'social_sign_in_header',
      'value' => t('Sign in with'),
    ],
    [
      'key' => 'sign_up_google',
      'value' => t('sign up with Google'),
    ],
    [
      'key' => 'sign_up_facebook',
      'value' => t('sign up with Facebook'),
    ],
    [
      'key' => 'sign_up_header',
      'value' => t("I don't have an account"),
    ],
    [
      'key' => 'register',
      'value' => t('Register'),
    ],
    [
      'key' => 'continue_as_guest',
      'value' => t('Continue as Guest'),
    ],
    [
      'key' => 'back',
      'value' => t('BACK'),
    ],
    [
      'key' => 'default_error',
      'value' => t('Sorry, something went wrong. Please try again later'),
    ],
    [
      'key' => 'selection_header',
      'value' => t('You have chosen'),
    ],
    [
      'key' => 'program_label',
      'value' => t('Appointment category'),
    ],
    [
      'key' => 'activity_label',
      'value' => t('Appointment type'),
    ],
    [
      'key' => 'edit',
      'value' => t('Edit'),
    ],
    [
      'key' => 'location',
      'value' => t('Location'),
    ],
    [
      'key' => 'date',
      'value' => t('Date'),
    ],
    [
      'key' => 'time',
      'value' => t('Time'),
    ],
    [
      'key' => 'morning',
      'value' => t('Morning'),
    ],
    [
      'key' => 'afternoon',
      'value' => t('Afternoon'),
    ],
    [
      'key' => 'evening',
      'value' => t('Evening'),
    ],
    [
      'key' => 'store_select_header',
      'value' => t("Select a store that's convenient for you"),
    ],
    [
      'key' => 'store_not_found',
      'value' => t('No stores are available in this location. Please try a different area.'),
    ],
    [
      'key' => 'stores_near_me_label',
      'value' => t('Display Stores Near Me'),
    ],
    [
      'key' => 'store_search_label',
      'value' => t('Find your closest location'),
    ],
    [
      'key' => 'miles',
      'value' => t('Miles'),
    ],
    [
      'key' => 'list_view_label',
      'value' => t('List view'),
    ],
    [
      'key' => 'map_view_label',
      'value' => t('Map view'),
    ],
    [
      'key' => 'store_timing_label',
      'value' => t('Store Timings'),
    ],
    [
      'key' => 'unavailable_timelsots_message',
      'value' => t('Time slots are unavailable on this date. Please Select next date.'),
    ],
    [
      'key' => 'select_timeslot_label',
      'value' => t('Select date & time that suits you'),
    ],
    [
      'key' => 'first_available_slot_label',
      'value' => t('The first available appointment is on'),
    ],
    [
      'key' => 'book_time_slot_button',
      'value' => t('Book Time Slot'),
    ],
    [
      'key' => 'continue',
      'value' => t('Continue'),
    ],
    [
      'key' => 'select_program_label',
      'value' => t('Select Appointment Category'),
    ],
    [
      'key' => 'number_of_companion_question',
      'value' => t('How many people do you want to book the appointment for?'),
    ],
    [
      'key' => 'appointment_for_you_many',
      'value' => t('Is one of these appointments for you?'),
    ],
    [
      'key' => 'appointment_for_you_one',
      'value' => t('Is this appointment for you?'),
    ],
    [
      'key' => 'yes',
      'value' => t('Yes'),
    ],
    [
      'key' => 'no',
      'value' => t('No'),
    ],
    [
      'key' => 'and',
      'value' => t('And'),
    ],
    [
      'key' => 'store_location_label',
      'value' => t('Store Location'),
    ],
    [
      'key' => 'customer_details_label',
      'value' => t('Customer details'),
    ],
    [
      'key' => 'close',
      'value' => t('Close'),
    ],
    [
      'key' => 'delete',
      'value' => t('Delete'),
    ],
    [
      'key' => 'cancel',
      'value' => t('Cancel'),
    ],
    [
      'key' => 'dob_label',
      'value' => t('Date of Birth'),
    ],
    [
      'key' => 'edit_store',
      'value' => t('Edit Store'),
    ],
    [
      'key' => 'edit_time',
      'value' => t('Edit time'),
    ],
    [
      'key' => 'edit_companion',
      'value' => t('Edit Companion'),
    ],
    [
      'key' => 'appointment_summary_label',
      'value' => t('Appointment Summary'),
    ],
    [
      'key' => 'appointment_booked_by_label',
      'value' => t('Appointment Booked by'),
    ],
    [
      'key' => 'confirmation_header',
      'value' => t('Thank you for booking at Boots.'),
    ],
    [
      'key' => 'confirmation_subheader',
      'value' => t('A confirmation will be sent through email. Manage your appointments online.'),
    ],
    [
      'key' => 'add_to_calendar_label',
      'value' => t('Add to My Calendar'),
    ],
    [
      'key' => 'print',
      'value' => t('Print'),
    ],
    [
      'key' => 'view_appointments_button',
      'value' => t('View My Appointments'),
    ],
    [
      'key' => 'continue_shopping_button',
      'value' => t('Continue shopping'),
    ],
    [
      'key' => 'book_an_appointment_button',
      'value' => t('Book an Appointment'),
    ],
    [
      'key' => 'customer_details_subheader',
      'value' => t('We will only use these details if we need to contact you about the appointment.'),
    ],
    [
      'key' => 'first_name_label',
      'value' => t('First name'),
    ],
    [
      'key' => 'last_name_label',
      'value' => t('Last name'),
    ],
    [
      'key' => 'email_address_label',
      'value' => t('Email address'),
    ],
    [
      'key' => 'mobile_label',
      'value' => t('Telephone/ Mobile'),
    ],
    [
      'key' => 'companion_label',
      'value' => t('Companion'),
    ],
    [
      'key' => 'details',
      'value' => t('Details'),
    ],
    [
      'key' => 'add_companion_label',
      'value' => t('Add Companion'),
    ],
    [
      'key' => 'show_less',
      'value' => t('Show less'),
    ],
    [
      'key' => 'read_more',
      'value' => t('Read more'),
    ],
    [
      'key' => 'empty_field_default_error',
      'value' => t('Please enter value for this field.'),
    ],
    [
      'key' => 'valid_mobile_error',
      'value' => t('Please enter valid mobile number.'),
    ],
    [
      'key' => 'valid_email_error',
      'value' => t('The email address %mail is not valid.'),
    ],
    [
      'key' => 'apple_calendar',
      'value' => t('Apple Calendar'),
    ],
    [
      'key' => 'google',
      'value' => t('Google'),
    ],
    [
      'key' => 'outlook',
      'value' => t('Outlook'),
    ],
    [
      'key' => 'outlookdotcom',
      'value' => t('Outlook.com'),
    ],
    [
      'key' => 'yahoo',
      'value' => t('Yahoo'),
    ],
    [
      'key' => 'selectlist_placeholder',
      'value' => t('Select...'),
    ],
  ];
}

/**
 * My Appointments strings.
 */
function _alshaya_appointment_my_appointments_static_strings() {
  return [
    [
      'key' => 'no_appointments',
      'value' => t('No appointments booked.'),
    ],
    [
      'key' => 'book_new_appointment_label',
      'value' => t('Book new Appointment'),
    ],
    [
      'key' => 'activity_label',
      'value' => t('Appointment type'),
    ],
    [
      'key' => 'date',
      'value' => t('Date'),
    ],
    [
      'key' => 'time',
      'value' => t('Time'),
    ],
    [
      'key' => 'and',
      'value' => t('and'),
    ],
    [
      'key' => 'store_location_label',
      'value' => t('Store Location'),
    ],
    [
      'key' => 'customer_details_label',
      'value' => t('Customer details'),
    ],
    [
      'key' => 'close',
      'value' => t('close'),
    ],
    [
      'key' => 'edit',
      'value' => t('Edit'),
    ],
    [
      'key' => 'delete',
      'value' => t('Delete'),
    ],
    [
      'key' => 'cancel',
      'value' => t('Cancel'),
    ],
    [
      'key' => 'cancel_appointment_confirmation_question',
      'value' => t('Are you sure you want to cancel appointment for !type?'),
    ],
    [
      'key' => 'ok',
      'value' => t('OK'),
    ],
    [
      'key' => 'dob_label',
      'value' => t('Date of Birth'),
    ],
    [
      'key' => 'customer_label',
      'value' => t('Customer'),
    ],
  ];
}
