<?php

/**
 * @file
 * Contains Appointment related translations.
 */

/**
 * Appointment translation.
 */
function _alshaya_appointment_translations() {
  return [
    'Appointment Booked by' => [
      'ar' => 'تم حجز الموعد بواسطة',
    ],
    'Companion' => [
      'ar' => 'المرافق',
    ],
    'Add Companion' => [
      'ar' => 'أضف مرافق',
    ],
    'Book an Appointment' => [
      'ar' => 'احجز موعد',
    ],
    'Telephone/ Mobile' => [
      'ar' => 'الهاتف/التليفون المحمول',
    ],
    'Thank you for booking at Boots.' => [
      'ar' => 'شكراً لك على حجز موعد لدى بوتس.',
    ],
    'A confirmation will be sent through email. Manage your appointments online.' => [
      'ar' => 'سيتم إرسال تأكيد عبر البريد الإلكتروني. قم بإدارة مواعيدك أونلاين.',
    ],
    'Add to my calendar' => [
      'ar' => 'أضف إلى التقويم الخاص بي',
    ],
    'Appointment Summary' => [
      'ar' => 'ملخص الموعد',
    ],
    'Customer details' => [
      'ar' => 'تفاصيل العميل',
    ],
    'Confirmation' => [
      'ar' => 'التأكيد',
    ],
    'Login / Guest' => [
      'ar' => 'سجل الدخول/زائر',
    ],
    'Select time slot' => [
      'ar' => 'اختيار الوقت',
    ],
    'Select store' => [
      'ar' => 'اختيار المحل',
    ],
    'Select Store' => [
      'ar' => 'اختيار المحل',
    ],
    'Book new Appointment' => [
      'ar' => 'حجز موعد جديد',
    ],
    'Select Appointment Category' => [
      'ar' => 'اختيار فئة الموعد',
    ],
    'How many people do you want to book the appointment for?' => [
      'ar' => 'كم عدد الأشخاص الذين تريد حجز موعد لهم؟',
    ],
    'Is one of these appointments for you?' => [
      'ar' => 'هل أحد هذه المواعيد لك؟',
    ],
    'Yes' => [
      'ar' => 'نعم',
    ],
    'No' => [
      'ar' => 'لا',
    ],
    'Please Select' => [
      'ar' => 'يرجى الاختيار',
    ],
    'Continue' => [
      'ar' => 'إكمال',
    ],
    'You have chosen' => [
      'ar' => 'لقد اخترت',
    ],
    'Appointment category' => [
      'ar' => 'فئة الموعد',
    ],
    'Appointment type' => [
      'ar' => 'نوع الموعد',
    ],
    'Location' => [
      'ar' => 'الموقع',
    ],
    'Miles' => [
      'ar' => 'الأميال',
    ],
    'Store Timings' => [
      'ar' => 'أوقات عمل المحل',
    ],
    "Select a store that's convenient for you" => [
      'ar' => 'اختيار محل مناسب لك',
    ],
    'Display Stores Near Me' => [
      'ar' => 'عرض المحلات القريبة مني',
    ],
    'or' => [
      'ar' => 'أو',
    ],
    'Find your closest location' => [
      'ar' => 'البحث عن أقرب موقع إليك',
    ],
    'BACK' => [
      'ar' => 'العودة',
    ],
    'Select' => [
      'ar' => 'اختر',
    ],
    'Loading Stores' => [
      'ar' => 'تحميل المتاجر',
    ],
    'Loading Map' => [
      'ar' => 'تحميل الخريطة',
    ],
    'Select date & time that suits you' => [
      'ar' => 'اختر التاريخ والوقت الذي يناسبك',
    ],
    'Book Time Slot' => [
      'ar' => 'حجز موعد زمني',
    ],
    'The first available appointment is on' => [
      'ar' => 'الموعد الأول المتاح',
    ],
    'Morning' => [
      'ar' => 'الصباح',
    ],
    'Afternoon' => [
      'ar' => 'بعد الظهر',
    ],
    'Evening' => [
      'ar' => 'المساء',
    ],
    'Log in for faster booking and to manage your appointments online' => [
      'ar' => 'تسجيل الدخول لحجز أسرع وإدارة المواعيد',
    ],
    'Sign in with' => [
      'ar' => 'تسجيل الدخول باستخدام',
    ],
    'Sign in' => [
      'ar' => 'تسجيل الدخول',
    ],
    "I don't have an account" => [
      'ar' => 'ليس لدي حساب',
    ],
    'Continue as Guest' => [
      'ar' => 'المتابعة كضيف',
    ],
    'We will only use these details if we need to contact you about the appointment.' => [
      'ar' => 'لن نستخدم هذه التفاصيل إلا إذا كنا بحاجة إلى الاتصال بك بشأن الموعد',
    ],
    'Add to My Calendar' => [
      'ar' => 'أضف إلى التقويم الخاص بي',
    ],
    'I have an account' => [
      'ar' => 'لدي حساب على الموقع',
    ],
    'Time slots are unavailable on this date. Please Select next date.' => [
      'ar' => 'الفترات الزمنية غير متوفرة في هذا اليوم. يرجى تحديد اليوم التالي.',
    ],
    'Is this appointment for you?' => [
      'ar' => 'هل هذا الموعد لك؟',
    ],
    'No appointments booked.' => [
      'ar' => 'لم يتم حجز المواعيد.',
    ],
    'Store Location' => [
      'ar' => 'موقع المتجر',
    ],
    'Close' => [
      'ar' => 'إغلاق',
    ],
    'Are you sure you want to cancel appointment for !type?' => [
      'ar' => '؟ !type هل أنت متأكد أنك تريد إلغاء موعد',
    ],
    'Date of Birth' => [
      'ar' => 'تاريخ الولادة',
    ],
    'Edit Store' => [
      'ar' => 'تحرير المتجر',
    ],
    'Edit time' => [
      'ar' => 'تعديل الوقت',
    ],
    'Edit Companion' => [
      'ar' => 'تحرير الرفيق',
    ],
    'View My Appointments' => [
      'ar' => 'عرض المواعيد الخاصة بي',
    ],
    'Please enter value for this field.' => [
      'ar' => 'الرجاء إدخال قيمة.',
    ],
    'My appointments' => [
      'ar' => 'المواعيد الخاصة بي',
    ],
    'Select...' => [
      'ar' => 'أختر...',
    ],
    'Apple Calendar' => [
      'ar' => 'Apple Calendar',
    ],
    'Google' => [
      'ar' => 'Google',
    ],
    'Outlook' => [
      'ar' => 'Outlook',
    ],
    'Outlook.com' => [
      'ar' => 'Outlook.com',
    ],
    'Yahoo' => [
      'ar' => 'Yahoo',
    ],
    'Customer' => [
      'ar' => 'العميل',
    ],
  ];
}
