<?php

/**
 * @file
 * Module file.
 */

/**
 * Get appointment middleware url.
 *
 * @return string
 *   Middleware url.
 */
function _alshaya_appointment_get_middleware_url() {
  return '/appointment/public';
}

/**
 * Implements hook_alshaya_my_account_links_alter().
 */
function alshaya_appointment_alshaya_my_account_links_alter(array &$links) {
  // Add My apppointment link.
  $links['alshaya_appointment'] = [
    'text' => t('My appointments'),
    'route' => 'alshaya_appointment.user_booked_appointment',
    'weight' => 200,
  ];
}

/**
 * Implements hook_theme().
 */
function alshaya_appointment_theme($existing, $type, $theme, $path) {
  return [
    'appointment_booking' => [
      'variables' => [
        'strings' => [],
      ],
    ],
    'customer_appointments' => [
      'variables' => [
        'strings' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_appointment_page_attachments_alter(&$page) {
  // Add GTM events for Appointment booking.
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() == 'alshaya_appointment.page') {
    $page['#attached']['library'][] = 'alshaya_appointment/gtm_appointment_booking';
  }
}
