<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function alshaya_rcs_listing_theme($existing, $type, $theme, $path) {
  return [
    'alshaya_rcs_lhn_tree' => [
      'template' => 'alshaya-rcs-lhn',
      'variables' => [
        'lhn_cat_tree' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function alshaya_rcs_listing_preprocess_page(&$variables) {
  // Initialising the variable to check the sidebar visibilty.
  // This will be disable by default.
  $variables['enable_lhn_tree'] = 0;

  $routematch = \Drupal::routeMatch();
  if ($routematch->getRouteName() == 'entity.taxonomy_term.canonical') {
    $term = $routematch->getParameter('taxonomy_term');
    if ($term->bundle() == 'rcs_category') {
      // Add description placeholder for mobile view.
      $variables['category_term_name'] = $term->getName();
      $variables['category_term_description'] = '#rcs.category.description#';

      // Taking the sidebar visibility check from config for PLP.
      $variables['enable_lhn_tree'] = \Drupal::config('alshaya_acm_product_category.settings')->get('enable_lhn_tree');
    }
  }
}
