<?php

/**
 * @file
 * Module file for Alshaya GoInStore.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_page_attachments().
 */
function alshaya_goinstore_page_attachments(array &$attachments) {
  $settings = \Drupal::config('alshaya_goinstore.settings');
  $alshaya_goinstore_enabled = $settings->get('enabled');
  // Do nothing if Goinstore is not enabled or is a admin page.
  if (!$alshaya_goinstore_enabled || \Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }
  $attachments['#attached']['library'][] = 'alshaya_goinstore/goinstore';
}
