<?php

/**
 * @file
 * Contains hooks to be invoked while installting/updating the module.
 */

use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 */
function alshaya_rum_install() {
  $roles_access_rum_config = ['webmaster', 'administrator'];

  foreach ($roles_access_rum_config as $role_id) {
    $role = Role::load($role_id);
    $role->grantPermission('configure real usage monitoring config');
    $role->save();
  }
}
