<?php

/**
 * @file
 * Contains Online Returns related translations.
 */

/**
 * Online Returns translation.
 */
function _alshaya_online_returns_translations() {
  $strings = [
    'v1' => [
      'orders can only be returned at stores' => [
        'ar' => 'يمكن إرجاع الطلبيات عبر المحلات فقط',
        'context' => 'online_returns',
      ],
      'Not eligible for Return' => [
        'ar' => 'غير قابل للإرجاع',
        'context' => 'online_returns',
      ],
      'Return Items Online' => [
        'ar' => 'إرجاع المنتجات عبر الموقع الإلكتروني',
        'context' => 'online_returns',
      ],
      'Search for a nearby store' => [
        'ar' => 'البحث عن أقرب المحلات إليك',
        'context' => 'online_returns',
      ],
      'Or return directly at any one of our stores' => [
        'ar' => 'من محلاتناّأو الإرجاع مباشرة عبر أي',
        'context' => 'online_returns',
      ],
      'Find Stores' => [
        'ar' => 'اكتشف أقرب محل',
        'context' => 'online_returns',
      ],
      '1. Select items to return' => [
        'ar' => '1. اختر المنتج المطلوب إرجاعه',
        'context' => 'online_returns',
      ],
      'Unit Price' => [
        'ar' => 'سعر الوحدة',
        'context' => 'online_returns',
      ],
      'Order ID' => [
        'ar' => 'الرقم التعريفي للطلبية',
        'context' => 'online_returns',
      ],
      'Total' => [
        'ar' => 'الإجمالي',
        'context' => 'online_returns',
      ],
      'items' => [
        'ar' => 'المنتجات',
        'context' => 'online_returns',
      ],
      'item' => [
        'ar' => 'المنتج',
        'context' => 'online_returns',
      ],
      'Order Total' => [
        'ar' => 'إجمالي الطلبية',
        'context' => 'online_returns',
      ],
      'Return window closed on @date' => [
        'ar' => 'سيتم إغلاق نافذة الإرجاع بتاريخ @date',
        'context' => 'online_returns',
      ],
      'You have until @date to return the items' => [
        'ar' => 'الموعد النهائي لإرجاع المنتجات هو @date',
        'context' => 'online_returns',
      ],
      'Continue' => [
        'ar' => 'تابع',
        'context' => 'online_returns',
      ],
      'Reason for Return' => [
        'ar' => 'سبب الإرجاع',
        'context' => 'online_returns',
      ],
      'Select quantity' => [
        'ar' => 'اختر الكمية',
        'context' => 'online_returns',
      ],
      'Choose a reason' => [
        'ar' => 'اختر السبب',
        'context' => 'online_returns',
      ],
      "If you're trying to leave the Online Returns page, please note, any changes made will be lost." => [
        'ar' => 'يرجى العلم بأنك ستفقد جميع التغييرات في حال مغادرة صفحة الإرجاع عبر الموقع الإلكتروني',
        'context' => 'online_returns',
      ],
      '1 item' => [
        'ar' => '1 item AR',
        'context' => 'online_returns',
      ],
      '@count items' => [
        'ar' => '@count items AR',
        'context' => 'online_returns',
      ],
      '2. Return and refund details' => [
        'ar' => '2. تفاصيل الإرجاع ورد الأموال',
        'context' => 'online_returns',
      ],
      'Your refund will be credited back to the following payment methods.' => [
        'ar' => 'سيتم رد المال إلى وسائل الدفع التالية',
        'context' => 'online_returns',
      ],
      'Refund Method' => [
        'ar' => 'وسيلة رد المال',
        'context' => 'online_returns',
      ],
      '@card_type Card' => [
        'ar' => 'بطاقة  @card_type',
        'context' => 'online_returns',
      ],
      'ending in' => [
        'ar' => 'تنتهي بتاريخ',
        'context' => 'online_returns',
      ],
      'Estimated refund in 3-5 business days after we receive the item' => [
        'ar' => 'الوقت المقدر لعملية رد المال ما بين 3 – 5 أيام عمل بعد استلام المنتج',
        'context' => 'online_returns',
      ],
      'Refund Amount' => [
        'ar' => 'المبلغ المسترد',
        'context' => 'online_returns',
      ],
      'Your refund amount will be notified to you through mail once we receive the items in warehouse' => [
        'ar' => 'سيتم إخطارك بالمبلغ المسترد عبر البريد الإلكتروني بمجرد استلام المنتج في المستودع',
        'context' => 'online_returns',
      ],
      'Pick-up Details' => [
        'ar' => 'تفاصيل استلام المنتج',
        'context' => 'online_returns',
      ],
      'Your Items to Return will be picked up in 3 - 4 days.' => [
        'ar' => 'سيتم استلام المنتج المطلوب إرجاعه خلال 3 – 4 أيام',
        'context' => 'online_returns',
      ],
      'Pick-up Address' => [
        'ar' => 'عنوان الاستلام',
        'context' => 'online_returns',
      ],
      'Last used address and phone number will be applied' => [
        'ar' => 'آخر عنوان ورقم هاتف تم استخدامهم',
        'context' => 'online_returns',
      ],
      'Confirm Your Return' => [
        'ar' => 'تأكيد عملية الإرجاع',
        'context' => 'online_returns',
      ],
      'Don\'t want to return?' => [
        'ar' => 'لا ترغب في الإرجاع؟',
        'context' => 'online_returns',
      ],
      'Go back to Order Details' => [
        'ar' => 'العودة إلى تفاصيل الطلبية',
        'context' => 'online_returns',
      ],
      'Return Request' => [
        'ar' => 'طلب الإرجاع',
        'context' => 'online_returns',
      ],
      '@card_type card ending in @card_number' => [
        'ar' => 'بطاقة @card_type تنتهي في @card_number',
        'context' => 'online_returns',
      ],
      'Return ID' => [
        'ar' => 'العنوان التعريفي لعملية الإرجاع',
        'context' => 'online_returns',
      ],
      'Pick-up From' => [
        'ar' => 'الاستلام من',
        'context' => 'online_returns',
      ],
      'Return Details' => [
        'ar' => 'تفاصيل عملية الإرجاع',
        'context' => 'online_returns',
      ],
      'Note - You can cancel this return order before 24hrs from the time of pick-up.' => [
        'ar' => 'ملاحظة -  يمكنك إلغاء طلب الإرجاع قبل 24 ساعة من موعد الاستلام',
        'context' => 'online_returns',
      ],
      'Return ID: @return_id' => [
        'ar' => 'الرقم التعريفي لعملية الإرجاع: @return_id',
        'context' => 'online_returns',
      ],
      'Delivered Items' => [
        'ar' => 'المنتجات التي تم توصيلها',
      ],
      'Online Returns' => [
        'ar' => 'طلبات الإرجاع أونلاين',
        'context' => 'online_returns',
      ],
      'Returned Items' => [
        'ar' => 'المنتجات التي تم إرجاعها',
        'context' => 'online_returns',
      ],
      'Store Returns' => [
        'ar' => 'طلبات الإرجاع عبر المحل',
        'context' => 'online_returns',
      ],
      'Return Confirmation' => [
        'ar' => 'تأكيد عملية الإرجاع',
        'context' => 'online_returns',
      ],
      'What\'s next?' => [
        'ar' => 'ما التالي؟',
        'context' => 'online_returns',
      ],
      'Go to order details' => [
        'ar' => 'الذهاب إلى تفاصيل الطلبية',
        'context' => 'online_returns',
      ],
      'Items to return' => [
        'ar' => 'المنتجات المطلوب إرجاعها',
        'context' => 'online_returns',
      ],
      'Ineligible for return' => [
        'ar' => 'قابلة للإرجاع',
        'context' => 'online_returns',
      ],
      'Cancel Return' => [
        'ar' => 'إلغاء طلب الإرجاع',
        'context' => 'online_returns',
      ],
      'Cancel Return Request' => [
        'ar' => 'إلغاء طلب الإرجاع',
        'context' => 'online_returns',
      ],
      'Are you sure you would like to cancel this return request?' => [
        'ar' => 'هل أنت متأكد أنك تريد إلغاء طلب الإرجاع هذا؟',
        'context' => 'online_returns',
      ],
      'Return request has been successfully placed.' => [
        'ar' => '.تم تسجيل طلب الارجاع بنجاح',
        'context' => 'online_returns',
      ],
      'Print Return Label' => [
        'ar' => 'طباعة ملصق الإرجاع',
        'context' => 'online_returns',
      ],
      'Eligible for return until @date' => [
        'ar' => 'قابل للإرجاع حتى @date',
        'context' => 'online_returns',
      ],
      'Online returns can be placed once existing returns are processed.' => [
        'ar' => '.يمكن تقديم طلبات الإرجاع أونلاين بعد استكمال طلبات الإرجاع الحالية',
        'context' => 'online_returns',
      ],
      'One or more products selected are not eligible for a return as they are on promotion. Please select a different product to proceed.' => [
        'ar' => 'المنتج أو المنتجات المختارة لا يمكن استبدالها ﻷنها ضمن فترة التنزيلات. يرجى اختيار منتج آخر للمتابعة.',
        'context' => 'online_returns',
      ],
      'Total Refund Amount' => [
        'ar' => 'إجمالي المبلغ المسترد',
        'context' => 'online_returns',
      ],
      'Selected Item is Promotional Item' => [
        'ar' => 'بعض المنتجات المختارة مشمولة بالعروض',
        'context' => 'online_returns',
      ],
      'To receive refund for promotional items, all items related to the promotion has to be returned.' => [
        'ar' => 'رد أموال المنتجات المشمولة بالعروض، يجب إرجاع جميع المنتجات المرتبطة بالعرض.',
        'context' => 'online_returns',
      ],
      'Deselect this item' => [
        'ar' => 'إلغاء تحديد هذا المنتج',
        'context' => 'online_returns',
      ],
      'Clicking continue will select all items in this promotion.' => [
        'ar' => 'الضغط على المتابعة سوف يقوم بتحديد كل المنتاج المشمولة بهذا العرض',
        'context' => 'online_returns',
      ],
      'Big Ticket Item' => [
        'ar' => 'منتج من طلبية كبيرة',
        'context' => 'online_returns',
      ],
      'Kindly contact customer care for initiating the online returns for Big Ticket Items.' => [
        'ar' => 'يرجى التواصل مع خدمة الزبائن للإعدادات المتعلقة باسترجاع المنتجات ذات الطلبية الكبيرة',
        'context' => 'online_returns',
      ],
      'Cancelled Items' => [
        'ar' => 'المنتجات الملغاه',
        'context' => 'online_returns',
      ],
    ],
    'v2' => [
      'Free online returns within 14 days' => [
        'ar' => 'خدمة الإرجاع المجاني أونلاين متوفرة حتى 14 يوماً',
        'context' => 'online_returns',
      ],
      '<b>FREE Returns</b> Now Available Online!' => [
        'ar' => '<b>خدمة الإرجاع مجاناً </b> متوفرة أونلاين وفي المحلات',
        'context' => 'online_returns',
      ],
    ],
    'v3' => [
      'Your refund will be credited immediately after the item is returned to warehouse' => [
        'ar' => 'سيتم إخطارك بالمبلغ المسترد عبر البريد الإلكتروني بمجرد استلام المنتج في المستودع',
        'context' => 'online_returns',
      ],
      'To return this order, please contact our customer service on @contact_number' => [
        'ar' => 'لإرجاع هذه الطلبية، يرجى التواصل مع خدمة الزبائن عبر رقم الهاتف @contact_number',
        'context' => 'online_returns',
      ],
    ],
  ];

  return $strings;
}

/**
 * Get translations for given version.
 *
 * @param string $version
 *   Version number like 'v1' etc.
 *
 * @return array
 *   Translations.
 */
function _alshaya_online_returns_get_translations(string $version = '') {
  $translations = _alshaya_online_returns_translations();
  // If no version mentioned, return all version strings.
  if (empty($version)) {
    $trans_data = [];
    foreach ($translations as $trans) {
      $trans_data = array_merge($trans_data, $trans);
    }

    return $trans_data;
  }

  return $translations[$version] ?? [];
}
