<?php

/**
 * @file
 * Install file.
 */

/**
 * Implements hook_install().
 */
function alshaya_search_algolia_install() {
  // Move top search block to proper theme.
  alshaya_block_move_blocks_theme_to_theme(
    \Drupal::service('theme_handler')->getDefault(),
    'alshaya_white_label'
  );

  // Mark everything for reindexation for search index.
  _alshaya_search_api_reindex(['acquia_search_index']);
}
