<?php

/**
 * @file
 * Module file with hooks specific to HM brand.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_hm_transac_rcs_module_implements_alter(&$implementations, $hook) {
  // Make sure the hook on the brand overrides runs last.
  if ($hook == 'rcs_handlebars_templates_alter') {
    $group = $implementations['alshaya_hm_transac_rcs'];
    unset($implementations['alshaya_hm_transac_rcs']);
    $implementations['alshaya_hm_transac_rcs'] = $group;
  }
}

/**
 * Implements hook_rcs_handlebars_templates_alter().
 */
function alshaya_hm_transac_rcs_rcs_handlebars_templates_alter(&$templates, $entity) {
  if (!$entity || $entity->bundle() !== 'rcs_product') {
    return;
  }

  // @todo This is copied from COS module.
  // We need to work on the description section for HM.
  $templates['product.block.description'] = 'alshaya_hm_transac_rcs';
  $templates['product.block.description_details'] = 'alshaya_hm_transac_rcs';

  /** @var  \Drupal\alshaya_acm_product\SkuManager $sku_manager **/
  $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');

  if ($sku_manager->getPdpLayout($entity) == 'pdp-magazine') {
    $templates['product.block.short_description.pdp-magazine'] = "alshaya_hm_transac_rcs";
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_hm_transac_rcs_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'rcs_product') {
    $build['#attached']['library'][] = 'alshaya_hm_transac_rcs/product';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_hm_transac_rcs_page_attachments_alter(array &$page) {

  // Attach add to bag utility.
  $current_route = \Drupal::routeMatch();
  $current_route_name = $current_route->getRouteName();
  $checkout_routes = [
    'alshaya_spc.checkout.confirmation',
    'alshaya_spc.checkout',
  ];
  if (!in_array($current_route_name, $checkout_routes)) {
    $page['#attached']['library'][] = 'alshaya_pims_assets/swatch';
  }
}
