<?php

/**
 * @file
 * Install file.
 */

use Drupal\alshaya_config\AlshayaConfigManager;

/**
 * Implements hook_update_N().
 *
 * Update free design services form.
 */
function alshaya_furnitures_free_design_services_update_8001() {
  $manager = \Drupal::service('alshaya_config.manager');

  $manager->updateConfigs(
    ['webform.webform.free_design_services'],
    'alshaya_furnitures_free_design_services',
    'install',
    AlshayaConfigManager::MODE_REPLACE
  );
}
