<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\mobile_number\MobileNumberUtilInterface;

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_furnitures_free_design_services_module_implements_alter(&$implementations, $hook) {
  // To call the element_info_alter at the end for final changes.
  if ($hook == 'element_info_alter') {
    $group = $implementations['alshaya_furnitures_free_design_services'];
    unset($implementations['alshaya_furnitures_free_design_services']);
    $implementations['alshaya_furnitures_free_design_services'] = $group;
  }
}

/**
 * Implements hook_webform_submission_form_alter().
 */
function alshaya_furnitures_free_design_services_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (empty($form['#webform_id']) || $form['#webform_id'] != 'free_design_services') {
    return;
  }
  // Webform doesn't have mobile_number webform element, it doesn't show with
  // the design that we did for mobile number form element. we have to do form
  // alter and replace it with form element.
  if (isset($form['elements']['contact_information']['mobile_number'])) {
    $entity = $form_state->getFormObject()->getEntity();
    $mobile_number = !empty($entity->getData()) ? $entity->getData()['mobile_number'] : '';

    $form['elements']['contact_information']['mobile_number'] = [
      '#title' => t('Mobile number'),
      '#type' => 'mobile_number',
      '#verify' => MobileNumberUtilInterface::MOBILE_NUMBER_VERIFY_NONE,
      '#tfa' => NULL,
      '#required' => $form['elements']['contact_information']['mobile_number']['#required'],
      '#default_value' => ['value' => _alshaya_acm_checkout_clean_address_phone($mobile_number)],
    ];
  }

  if ($form_id == 'webform_submission_free_design_services_add_form') {
    /** @var \Drupal\alshaya_stores_finder_transac\StoresFinderUtility $storeFinderUtility */
    $storeFinderUtility = \Drupal::service('alshaya_stores_finder_transac.utility');
    $form['elements']['preferred_store']['#type'] = 'select';
    $form['elements']['preferred_store']['#empty_option'] = t('Select @title', ['@title' => $form['elements']['preferred_store']['#title']]);
    $form['elements']['preferred_store']['#options'] = $storeFinderUtility->getStores(FALSE);

    $form['#validate'][] = 'alshaya_furnitures_free_design_services_form_webform_submission_free_design_services_validate';
  }
}

/**
 * Form validate callback to update address area ids to values.
 */
function alshaya_furnitures_free_design_services_form_webform_submission_free_design_services_validate(array &$form, FormStateInterface $form_state) {
  if ($form_state->getErrors()) {
    return;
  }

  $address = $form_state->getValue('address');

  /** @var \Drupal\alshaya_master\Service\AlshayaEntityHelper $helper */
  $helper = \Drupal::service('alshaya_master.entity_helper');

  if (isset($address['administrative_area'])) {
    $address['administrative_area'] = $helper->getLabelInSiteDefaultLanguage('taxonomy_term', $address['administrative_area']);
  }
  if (isset($address['area_parent'])) {
    $address['administrative_area'] .= ', ' . $helper->getLabelInSiteDefaultLanguage('taxonomy_term', $address['area_parent']);
  }

  $form_state->setValue('address', $address);
}

/**
 * Implements template_preprocess_webform_confirmation().
 */
function alshaya_furnitures_free_design_services_preprocess_webform_confirmation(array &$variables) {
  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = $variables['webform'];

  if ($webform->id() != 'free_design_services') {
    return;
  }

  $variables['message']['#markup'] = $webform->getElement('banner')['#text'] . $variables['message']['#markup'];
}

/**
 * Processor for the country in address field.
 */
function _alshaya_furnitures_free_design_services_process_address_form(array &$element, FormStateInterface $form_state) {
  if (isset($element['#webform_element']) && $element['#webform'] == 'free_design_services') {
    /** @var \Drupal\alshaya_addressbook\AlshayaAddressBookManager $address_book_manager */
    $address_book_manager = \Drupal::service('alshaya_addressbook.manager');

    // Hide all the fields which we couldn't map.
    foreach ($address_book_manager->getMagentoUnmappedFields() as $field_code) {
      $element[$field_code]['#access'] = FALSE;
    }

    // Hide all disabled fields.
    foreach ($address_book_manager->getMagentoDisabledFields() as $field_code => $magento_field_code) {
      $element[$field_code]['#access'] = FALSE;
    }

    // For webform, we show name fields separately.
    $element['given_name']['#access'] = FALSE;
    $element['family_name']['#access'] = FALSE;

    $is_element_required = $element['#required'] ?? FALSE;
    $element['address_line1']['#required'] = $is_element_required;
    $element['dependent_locality']['#required'] = $is_element_required;
  }

  return $element;
}

/**
 * Implements hook_element_info_alter().
 */
function alshaya_furnitures_free_design_services_element_info_alter(array &$info) {
  if (isset($info['address']['#process'])) {
    $info['address']['#process'][] = '_alshaya_furnitures_free_design_services_process_address_form';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_furnitures_free_design_services_form_webform_submission_free_design_services_add_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (\Drupal::currentUser()->isAuthenticated()) {
    $current_user = \Drupal::entityTypeManager()->getStorage('user')->load(\Drupal::currentUser()->id());
    $form['elements']['contact_information']['full_name']['#default_value'] = $current_user->get('field_first_name')->getString() . ' ' . $current_user->get('field_last_name')->getString() ?? '';
    $form['elements']['contact_information']['email']['#default_value'] = $current_user->get('mail')->getString();
    $form['elements']['contact_information']['mobile_number']['#default_value'] = ['value' => _alshaya_acm_checkout_clean_address_phone($current_user->get('field_mobile_number')->value ?? '')];

    $profiles = \Drupal::entityTypeManager()->getStorage('profile')->loadByProperties([
      'type' => 'address_book',
      'uid' => $current_user->id(),
      'is_default' => 1,
    ]);

    if ($profiles && $profile = reset($profiles)) {
      /** @var \Drupal\alshaya_addressbook\AlshayaAddressBookManager $manager */
      $manager = \Drupal::service('alshaya_addressbook.manager');
      $address = $manager->getAddressArrayFromMagentoAddress($manager->getAddressFromEntity($profile));

      $form['elements']['address']['#webform_composite_elements']['address_line2']['#default_value'] = $address['address_line2'];
      $form['elements']['address']['#webform_composite_elements']['dependent_locality']['#default_value'] = $address['dependent_locality'];
      $form['elements']['address']['#webform_composite_elements']['administrative_area']['#default_value'] = $address['administrative_area'];
      $form['elements']['address']['#webform_composite_elements']['locality']['#default_value'] = $address['area_parent'];
      $form['elements']['address']['#webform_composite_elements']['address_line1']['#default_value'] = $address['address_line1'];
    }
  }
}
