<?php

/**
 * @file
 * Constains hooks and alters for Alshaya Department page.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_department_page_form_node_department_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // We will show only those categories who don't have a department page yet.
  $tids = array_keys($form['field_product_category']['widget']['#options']);

  foreach ($tids as $tid) {
    if ($page_exists = alshaya_department_page_page_exists($tid)) {
      // Unset the value.
      unset($form['field_product_category']['widget']['#options'][$tid]);
    }
  }
}

/**
 * Helper function which checks for existance of a department page.
 *
 * @param int $tid
 *   tid of the Category.
 *
 * @return bool
 *   Returns FALSE if page not found, else returns the $node_id of the page.
 */
function alshaya_department_page_page_exists($tid) {
  static $department_pages;

  // We cache the nid-tid relationship for a single page request.
  if (empty($department_pages)) {
    // Load all the department page - category relationships.
    $query = \Drupal::database()->select('node__field_product_category', 'nfpc');
    $query->addField('nfpc', 'field_product_category_target_id', 'tid');
    $query->addField('nfpc', 'entity_id', 'nid');
    $department_pages = $query->execute()->fetchAllKeyed();
  }

  // Check if we have department page available for tid passed in args.
  if (isset($department_pages[$tid])) {
    return $department_pages[$tid];
  }

  return FALSE;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function alshaya_department_page_node_presave(EntityInterface $entity) {
  // Allows for clearing of blocks based on node type.
  // Used for mega menu block.
  $tags = ['node_type:' . $entity->getType()];
  Cache::invalidateTags($tags);
}
