<?php

/**
 * @file
 * Provides base hooks to the base Acquia Commerce connector.
 */

use Drupal\acq_commerce\Conductor\APIWrapper;

/**
 * For the all.
 */
const LINKED_SKU_TYPE_ALL = 'all';

/**
 * For the upsell.
 */
const LINKED_SKU_TYPE_UPSELL = 'upsell';

/**
 * For the cross_sell.
 */
const LINKED_SKU_TYPE_CROSSSELL = 'crosssell';

/**
 * For the related.
 */
const LINKED_SKU_TYPE_RELATED = 'related';

/**
 * Implements hook_page_attachments().
 */
function acq_commerce_page_attachments(array &$attachments) {
  // Add CSS for the Commerce icon in the toolbar if the user has access to it.
  $can_view_commerce_admin = \Drupal::currentUser()->hasPermission('access commerce administration pages');
  $can_view_toolbar = \Drupal::currentUser()->hasPermission('access toolbar');
  if ($can_view_commerce_admin && $can_view_toolbar) {
    $attachments['#attached']['library'][] = 'acq_commerce/drupal.acq_commerce.toolbar';
  }
}

/**
 * Implements hook_theme().
 */
function acq_commerce_theme($existing, $type, $theme, $path) {
  return [
    'acq_commerce_price' => [
      'variables' => [
        'price' => '',
        'currency_format' => '',
        'currency_code_position' => '',
      ],
    ],
  ];
}

/**
 * Format price value with currency.
 *
 * Default template: acq-commerce-price.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - price: a price value.
 */
function template_preprocess_acq_commerce_price(array &$variables) {
  // Fetch the config.
  $config = \Drupal::configFactory()->get('acq_commerce.currency');

  // Fetch the currency format from the config factor.
  $variables['currency_format'] = $config->get('currency_code');

  // Fetch the currency code position.
  $variables['currency_code_position'] = $config->get('currency_code_position');

  $variables['price'] = acq_commerce_get_clean_price($variables['price']);

  $variables['price'] = number_format($variables['price'], $config->get('decimal_points'));

  // To invalidate the cache on currency config update.
  $variables['#cache']['tags'][] = 'config:acq_commerce.currency';
}

/**
 * Helper function to clean commerce price.
 *
 * For now we encounter only one issue - comma in price when value is more than
 * thousand. We might encounter more issues later.
 *
 * @param mixed $price
 *   Price received from commerce.
 *
 * @return mixed
 *   Cleaned price value.
 */
function acq_commerce_get_clean_price($price) {
  // Remove the comma coming from Commerce, we will add while formatting.
  // Casting to float or using floatval stops at comma and doesn't return
  // whole value.
  // NumberFormatter.parse requires locale, we don't have expected value
  // available anywhere in the system for now (kw_AR) so not using it.
  return str_replace(',', '', $price);
}

/**
 * Helper function to check if exception is related to API being down.
 *
 * @param \Exception $e
 *   Exception object.
 *
 * @return bool
 *   True if exception is related to API being down.
 */
function acq_commerce_is_exception_api_down_exception(\Exception $e) {
  return acq_commerce_is_code_api_down_code($e->getCode());
}

/**
 * Helper function to check if exception code is related to API being down.
 *
 * @param int $code
 *   Exception code.
 *
 * @return bool
 *   True if exception code is related to API being down.
 */
function acq_commerce_is_code_api_down_code($code) {
  return ($code == APIWrapper::API_DOWN_ERROR_CODE);
}

/**
 * Function to return global error message to be used when API is down.
 *
 * Not adding this to config or creating form, this can be updated using
 * translation interface.
 *
 * @return string
 *   Error message string.
 */
function acq_commerce_api_down_global_error_message() {
  return t('Sorry, something went wrong and we are unable to process your request right now. Please try again later.')->render();
}
