/search:
  get:
    description: Get a list of suggestion based on a given string.
    queryParameters:
      filter:
        type: string
        default: keywords
      q:
        type: string
        description: The searched text.
    responses:
      200:
        body:
          type: array
          items:
            type: object
            properties:
              value:
                type: string
                description: The suggested string.
              label:
                type: string
                description: "HTML used by Drupal to display the suggestion in
                the list. This attribute probably won't be used by Mobile Apps."
          example:
            [
              {
                "value": "dress",
                "label": "  <div class=\"search-api-autocomplete-suggestion\">\n<span class=\"autocomplete-suggestion-user-input\">dres</span><span class=\"autocomplete-suggestion-suggestion-suffix\">s</span></div>\n"
              },
              {
                "value": "dresses",
                "label": "  <div class=\"search-api-autocomplete-suggestion\">\n<span class=\"autocomplete-suggestion-user-input\">dres</span><span class=\"autocomplete-suggestion-suggestion-suffix\">ses</span></div>\n"
              },
              {
                "value": "dressing",
                "label": "  <div class=\"search-api-autocomplete-suggestion\">\n<span class=\"autocomplete-suggestion-user-input\">dres</span><span class=\"autocomplete-suggestion-suggestion-suffix\">sing</span></div>\n"
              }
            ]
