get:
  description: Get the data related to delivery methods.
  responses:
    200:
      body:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            order_description:
              type: string
            cart_description:
              type: string
            codes:
              type: object
              properties:
                method:
                  type: string
                carrier:
                  type: string
                code:
                  type: string
        example:
          [
            {
              "name": "Alshaya Standard Delivery",
              "order_description": "Your order will be delivered at the following address",
              "cart_description": "Standard delivery in 1-2 days",
              "codes":
                {
                  "method": "deliverymatrix",
                  "carrier": "alshayadelivery",
                  "code": "alshayadelivery_deliverymatrix",
                }
            },
            {
              "name": "Click and Collect",
              "order_description": "Your order will be available for pickup at the following store",
              "cart_description": "Click and Collect",
              "codes":
                {
                  "method": "click_and_collect",
                  "carrier": "click_and_collect",
                  "code": "click_and_collect_click_and_collect",
                }
            }
          ]
