get:
  description: Get the social media urls. It will return the urls indexed by
  social media type as contributed in Drupal footer.
  responses:
    200:
      body:
        type: array
        items:
          type: object
          properties:
            media:
              type: string
              description: The social media name (facebook, twitter, ...).
            url:
              type: string
        example:
          [
            {
              "media": "facebook",
              "url": "https://www.facebook.com/hm",
            },
            {
              "media": "instagram",
              "url": "https://www.instagram.com/hm/",
            }
          ]
