<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\node\NodeInterface;

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_free_design_services_form_webform_submission_free_design_services_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['elements']['preferred_store']['#type'] = 'select';
  $form['elements']['preferred_store']['#empty_option'] = t('Select @title', ['@title' => $form['elements']['preferred_store']['#title']]);
  $form['elements']['preferred_store']['#options'] = _alshaya_free_design_services_get_all_stores();

  $form['#validate'][] = 'alshaya_free_design_services_form_webform_submission_free_design_services_validate';
}

/**
 * Form validate callback to update address area ids to values.
 */
function alshaya_free_design_services_form_webform_submission_free_design_services_validate(array &$form, FormStateInterface $form_state) {
  if ($form_state->getErrors()) {
    return;
  }

  $address = $form_state->getValue('address');

  if (isset($address['administrative_area'])) {
    $address['administrative_area'] = _alshaya_free_design_services_get_taxonomy_term_label($address['administrative_area']);
  }
  if (isset($address['area_parent'])) {
    $address['administrative_area'] .= ', ' . _alshaya_free_design_services_get_taxonomy_term_label($address['area_parent']);
  }

  $form_state->setValue('address', $address);
}

/**
 * Wrapper function to get translated term label from tid.
 *
 * @param mixed $tid
 *   Term id.
 *
 * @return string
 *   Term label or tid if term not found.
 */
function _alshaya_free_design_services_get_taxonomy_term_label($tid) {
  /** @var \Drupal\taxonomy\TermStorageInterface $termStorage */
  $termStorage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $term = $termStorage->load($tid);

  if ($term instanceof TermInterface) {
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

    if ($term->language()->getId() != $langcode && $term->hasTranslation($langcode)) {
      $term = $term->getTranslation('en');
    }

    return $term->label();
  }

  return $tid;
}

/**
 * Wrapper function to get store options array.
 *
 * @return array
 *   Array for #options with store code as key and title as value.
 */
function _alshaya_free_design_services_get_all_stores() {
  static $options;

  if (is_array($options)) {
    return $options;
  }

  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  // Check once in cache now.
  $cid = 'alshaya_free_design_services_all_stores_' . $langcode;
  $cache = \Drupal::cache()->get($cid);
  if ($cache && $cache->data) {
    $options = $cache->data;
    return $options;
  }

  $options = [];

  $stores = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
    'type' => 'store',
    'status' => NodeInterface::PUBLISHED,
  ]);

  /** @var \Drupal\node\NodeInterface $store */
  foreach ($stores as $store) {
    if ($store->language()->getId() != $langcode && $store->hasTranslation($langcode)) {
      $store = $store->getTranslation($langcode);
    }

    $options[$store->get('field_store_locator_id')->getString()] = $store->label();
  }

  \Drupal::cache()->set($cid, $options, Cache::PERMANENT, ['node_type:store']);

  return $options;
}

/**
 * Implements template_preprocess_webform_confirmation().
 */
function alshaya_free_design_services_preprocess_webform_confirmation(array &$variables) {
  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = $variables['webform'];

  if ($webform->id() != 'free_design_services') {
    return;
  }

  $variables['message']['#markup'] = $webform->getElement('banner')['#text'] . $variables['message']['#markup'];
}
