<?php

/**
 * @file
 * The Module file.
 */

use Drupal\alshaya_seo_transac\AlshayaGtmManager;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_gtm_list_name_alter().
 */
function alshaya_vs_gtm_list_name_alter(&$listName) {
  $product_category_tree = \Drupal::service('alshaya_acm_product_category.product_category_tree');
  $term = $product_category_tree->getCategoryTermFromRoute();
  $super_cat = $product_category_tree->getCategoryTermRequired();
  $super_cat_name = $super_cat['label'];
  $major_cat_name = '';
  if ($term instanceof TermInterface) {
    if ($term->getName() != $super_cat_name) {
      $major_cat_name = $term->getName();
    }
  }

  if ($listName == 'PLP') {
    $listName = $listName . '|' . $super_cat_name . '|' . $major_cat_name;
  }

  elseif ($listName == 'PDP-placeholder' || $listName == 'PDP') {
    $listName = $listName . '|' . $super_cat_name;
  }

  elseif ($listName == 'Search Results Page') {
    $keywords = \Drupal::request()->get('keywords');
    if ($keywords) {
      $listName = 'SRP|' . $super_cat_name . '|' . strtolower($keywords);
    }
    else {
      $listName = 'SRP|' . $super_cat_name;
    }
  }
  elseif (empty($listName) && \Drupal::service('path.matcher')->isFrontPage()) {
    // We maintain the same format here as for the other list names.
    // We require this for the product carousels in the homepage.
    $listName = AlshayaGtmManager::LIST_GTM_MAPPING['alshaya_master.home'] . '|' . $super_cat_name;
  }
}
