<?php

/**
 * @file
 * The Module file.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_form_alter().
 */
function alshaya_vs_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::moduleHandler()->moduleExists('alshaya_email_signup') && $form_id == 'webform_submission_alshaya_email_signup_form') {
    $lang = \Drupal::languageManager()->getDefaultLanguage()->getId();
    $uuid = '19207aad-0e43-4d3a-96d7-c74141f75bb1';
    $entity_manager = \Drupal::getContainer()->get('entity.manager');
    $block = $entity_manager->loadEntityByUuid('block_content', $uuid);
    if (!empty($block)) {
      $build = $entity_manager->getViewBuilder('block_content')->view($block, 'full', $lang);

      // Add the title to text so it is searchable.
      $build['search_title'] = [
        '#prefix' => '<h2>',
        '#plain_text' => $block->label(),
        '#suffix' => '</h2>',
        '#weight' => -1000
      ];

      $form['info_block'] = [
        '#type' => 'item',
        '#markup' => \Drupal::getContainer()->get('renderer')->renderPlain($build),
        '#weight' => -100,
        '#prefix' => '<div class="form--content">',
        '#suffix' => '</div>'
      ];
    }
  }
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function alshaya_vs_block_view_system_menu_block_alter(array &$build, BlockPluginInterface $block) {
  if ($build['#id'] == 'main_navigation_level2') {
    $build['#pre_render'][] = '_alshaya_vs_main_menu_second_lvl_default_content';
  }
}

function _alshaya_vs_main_menu_second_lvl_default_content(array $build) {
  if (empty($build['content']['#items'])) {
    $content = _alshaya_vs_main_menu_get_victoria_secret_child_menus();
    $content['#attributes']['class'][] = 'navigation__sub-menu';
    $content['#attached']['library'][] = 'whitelabel/menu-sub-navigation';
    $content['#theme'] = 'menu';
    $build['content']['#markup'] = \Drupal::service('renderer')->render($content);
  }
  return $build;
}

function _alshaya_vs_main_menu_get_victoria_secret_child_menus() {
  $menu_tree = \Drupal::menuTree();
  $menu_name = 'main';

  // Build the typical default set of menu tree parameters.
  $parameters = $menu_tree->getCurrentRouteMenuTreeParameters($menu_name);
  $parameters->setMinDepth(1);
  $parameters->setMaxDepth(1);
  $basicParameters = $parameters;

  $tree = $menu_tree->load($menu_name, $basicParameters);
  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkNodeAccess'],
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
  ];
  $tree = $menu_tree->transform($tree, $manipulators);
  foreach ($tree as $element) {
    $title = Html::cleanCssIdentifier(strtolower($element->link->getTitle()));
    if ($title == 'victorias-secret') {
      $parentID = $element->link->getPluginId();
    }
  }

  // Build the typical default set of menu tree parameters.
  //$parameters = $menu_tree->getCurrentRouteMenuTreeParameters($menu_name);
  $basicParameters->setRoot($parentID);
  $basicParameters->expandedParents = array();
  // $parameters->setMinDepth(1);
  // $parameters->setMaxDepth(1);
  // Load the tree based on this set of parameters.
  $tree = $menu_tree->load(NULL, $basicParameters);
  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkNodeAccess'],
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
  ];
  $tree = $menu_tree->transform($tree, $manipulators);
  return $menu_tree->build($tree);
}
