<?php

/**
 * @file
 * Module file for Alshaya RCS Super category.
 */

use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_rcs_placeholders_processor_path_alter().
 */
function alshaya_rcs_super_category_rcs_placeholders_processor_path_alter(string &$path) {
  $mapping = &drupal_static(__FUNCTION__, []);

  if (isset($mapping[$path])) {
    $path = $mapping[$path];
    return;
  }

  $term = &drupal_static('super_category_term', []);
  if (empty($term)) {
    $term = \Drupal::service('alshaya_acm_product_category.product_category_tree')->getCategoryTermFromRoute();
  }

  if ($term instanceof TermInterface) {

    // We need original path for storing in static cache.
    $original_path = $path;

    $path_arr = explode('/', $path);
    // @todo store the term in static cache for later use.
    unset($path_arr[1]);

    $path = implode('/', $path_arr);
    $mapping[$original_path] = $path;
  }
}

/**
 * Implements hook_alshaya_rcs_main_menu_alter().
 */
function alshaya_rcs_super_category_alshaya_rcs_main_menu_alter(&$variables) {
  // Assign super category from url as category in menu.
  $term = &drupal_static('super_category_term', []);
  if (empty($term)) {
    $term = \Drupal::service('alshaya_acm_product_category.product_category_tree')->getCategoryTermFromRoute();
  }
  if ($term instanceof TermInterface) {
    $variables['category_id'] = $term->id();
  }
}
