<?php

/**
 * @file
 * Contains alshaya_aura.module.
 */

/**
 * Implements hook_theme().
 */
function alshaya_aura_theme() {
  $theme = [
    'aura_rewards_header' => [
      'variables' => [
        'learn_more_link' => '',
      ],
    ],
    'aura_pending_enrollment' => [
      'variables' => [],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_page_attachments().
 */
function alshaya_aura_page_attachments(array &$page) {
  $page['#attached']['drupalSettings']['aura']['enabled'] = 1;
}
