<?php

/**
 * @file
 * Contains install, update, uninstall hooks for alshaya_aura module.
 */

/**
 * Implements hook_install().
 *
 * Move AURA blocks to current theme.
 */
function alshaya_aura_install() {
  $configs = [
    'block.block.aurarewardsheader',
    'block.block.pendingfullenrollment',
  ];

  \Drupal::service('alshaya_config.manager')->updateConfigs($configs, 'alshaya_aura', 'optional');
}
