<?php

/**
 * @file
 * Contains alshaya_aura.module.
 */

use Drupal\alshaya_user\Plugin\Block\MyAccountLinks;
use Drupal\block\Entity\Block;

/**
 * Implements hook_theme().
 */
function alshaya_aura_theme() {
  $theme = [
    'aura_rewards_header' => [
      'variables' => [
        'learn_more_link' => '',
      ],
      'template' => 'aura-rewards-header',
    ],
    'aura_pending_enrollment' => [
      'variables' => [],
    ],
    'aura_rewards_header_authenticated' => [
      'variables' => [
        'aura_user' => [],
      ],
      'template' => 'aura-rewards-header-authenticated',
    ],
    'aura_rewards_header_popup' => [
      'variables' => [],
      'template' => 'aura-rewards-header-popup',
    ],
    'aura_rewards_menu_item' => [
      'variables' => [
        'aura_user' => [],
      ],
      'template' => 'aura-rewards-menu-item',
    ],
  ];

  return $theme;
}

/**
 * Implements hook_page_attachments().
 */
function alshaya_aura_page_attachments(array &$page) {
  $page['#attached']['drupalSettings']['aura']['enabled'] = 1;
  $page['#attached']['drupalSettings']['aura']['user_points_route'] = '/get/aura/user-points';
  $page['#attached']['library'][] = 'alshaya_aura/aura_header_library';
  $page['#attached']['library'][] = 'alshaya_white_label/aura-loyalty-global';
}

/**
 * Implements hook_preprocess_alshaya_main_menu_level1() for menu template.
 */
function alshaya_aura_preprocess_alshaya_main_menu_level1(array &$variables) {

  $block = Block::load('aurarewardsheader');
  $block_content = \Drupal::entityTypeManager()
    ->getViewBuilder('block')
    ->view($block);
  $variables['aura_rewards_header'] = $block_content;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_aura_preprocess_html(&$variables) {
  if ($variables['logged_in']) {
    $my_account_links_routes = array_column(MyAccountLinks::getMyAccountLinks(), 'route');
    if (in_array(\Drupal::routeMatch()->getRouteName(), $my_account_links_routes)) {
      // Add class to body to distinguish between my account and other pages.
      $variables['attributes']['class'][] = 'aura-my-account';
    }
  }
}
