<?php

/**
 * @file
 * Contains alshaya_aura.module.
 */

/**
 * Implements hook_theme().
 */
function alshaya_aura_theme() {
  $theme = [
    'aura_rewards_header' => [
      'variables' => [
        'learn_more_link' => '',
      ],
    ],
    'aura_pending_enrollment' => [
      'variables' => [],
    ],
    'my_loyalty_club' => [
      'variables' => [],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_alshaya_my_account_links_alter().
 */
function alshaya_aura_alshaya_my_account_links_alter(array &$links) {
  // Add My Loyalty Club link.
  $links['alshaya_loyalty_club'] = [
    'text' => t('My Loyalty Club'),
    'route' => 'alshaya_aura.loyalty_club',
    'weight' => 11,
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function alshaya_aura_preprocess_page(&$variables) {
  $variables['#attached']['drupalSettings']['aura']['enabled'] = 1;
}
