<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_library_info_alter().
 */
function alshaya_rcs_dynamic_yield_library_info_alter(&$libraries, $extension) {
  // Add the dependency of rcs dynamic yield library, So that the RCS global
  // function can be used.
  if ($extension === 'dynamic_yield'
    && isset($libraries['dynamic_yield.script_injection'])
    && \Drupal::config('dynamic_yield.settings')->get('dy_injection') === 'frontend') {
    $libraries['dynamic_yield.script_injection']['dependencies'][] = 'alshaya_rcs_dynamic_yield/rcs_dynamic_yield';
  }
}
