<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_alshaya_i18n_onetime_translation_add().
 */
function alshaya_contact_alshaya_i18n_onetime_translation_add() {
  // Set contact form translation.
  $contact_content = \Drupal::languageManager()->getLanguageConfigOverride('ar', 'webform.webform.alshaya_contact');
  $contact_content->set('title', 'اتصل بنا');
  $contact_content->set('elements', "select_your_preference_of_channel_of_communication:\n  '#title': 'حدد قناة الاتصال المفضلة لديك'\n  '#options':\n    Email: 'البريد الإكتروني'\n    Mobile: 'رقم الجوال'\nfirst_name:\n  '#title': 'الاسم الأول'\nlast_name:\n  '#title': 'اسم العائلة'\nmobile_number:\n  '#title': 'رقم الجوال'\nemail:\n  '#title': 'عنوان البريد الإلكتروني'\nmessage:\n  '#title': 'رسالة نصية:'\n");
  $contact_content->set('handlers.email.settings.body', "<strong>تفضيلات التواصل</strong> - [webform_submission:values:select_your_preference_of_channel_of_communication]<br />\r\n<br />\r\n<strong>اسم</strong> -&nbsp;[webform_submission:values:first_name]&nbsp;[webform_submission:values:last_name]<br />\r\n<br />\r\n<strong>رقم الجوال</strong> -&nbsp;[webform_submission:values:first_name]&nbsp;[webform_submission:values:mobile_number]<br />\r\n<br />\r\n<strong>عنوان البريد الإلكتروني</strong> -&nbsp;[webform_submission:values:first_name]&nbsp;[webform_submission:values:email]<br />\r\n<br />\r\n<strong>رسالة</strong> -&nbsp;<br />\r\n<br />\r\n[webform_submission:values:first_name]&nbsp;[webform_submission:values:message]");
  $contact_content->set('settings.confirmation_message', 'شكرا لإتصالك بنا. سنقوم بالرد عليك في أقرب وقت ممكن!');
  $contact_content->save();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_contact_form_webform_submission_alshaya_contact_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attributes']['class'][] = 'webform-submission-alshaya-contact-form';

  $form['elements']['first_name']['#attributes']['specialchar'] = 'specialchar';
  $form['elements']['last_name']['#attributes']['specialchar'] = 'specialchar';
  $form['elements']['first_name']['#maxlength'] = 50;
  $form['elements']['last_name']['#maxlength'] = 50;
  // Override mail validation pattern.
  $form['#attached']['library'][] = 'alshaya_user/email_validator_override';

  // Custom validation for contact form.
  $form['#validate'][] = '_alshaya_contact_alshaya_contact_form_validate';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_contact_form_webform_submission_alshaya_contact_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();
  $mobile_number = $entity->getData()['mobile_number'];

  $form['elements']['mobile_number']['#default_value'] = [
    'value' => $mobile_number,
  ];
}

/**
 * Custom validation for alshaya contact form.
 */
function _alshaya_contact_alshaya_contact_form_validate(&$form, FormStateInterface $form_state) {
  // Validate if mobile number is entered if preference of channel of
  // communication is mobile.
  $values = $form_state->getValues();
  if ($values['select_your_preference_of_channel_of_communication'] == 'Mobile') {
    if (strlen($values['mobile_number']['mobile']) < 5) {
      $form_state->setErrorByName('mobile_number', t('@title is required.', ['@title' => $form['elements']['mobile_number']['#title']]));
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function alshaya_contact_element_info_alter(array &$info) {
  if (isset($info['mobile_number']['#process'])) {
    $info['mobile_number']['#process'][] = '_alshaya_contact_mobile_number_process';
  }
}

/**
 * Processor for the mobile number field to disable the country code.
 */
function _alshaya_contact_mobile_number_process(array &$element, FormStateInterface $form_state) {
  if ($form_state->getBuildInfo()['form_id'] == 'webform_submission_alshaya_contact_add_form') {
    $element['mobile']['#required'] = FALSE;
    $element['mobile']['#states'] = [
      'required' => [
        ['input[name="select_your_preference_of_channel_of_communication"]' => ['value' => 'Mobile']],
      ],
    ];
  }
  return $element;
}
