<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function alshaya_contact_webform_submission_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'alshaya_contact') {
    $data = $entity->getData();
    $data['mobile_number'] = $data['mobile_number']['value'];
    $entity->setData($data);
  }
}

/**
 * Implements hook_alshaya_onetime_translation_add().
 */
function alshaya_contact_alshaya_i18n_onetime_translation_add() {
  // Set contact form translation.
  $contact_content = \Drupal::languageManager()->getLanguageConfigOverride('ar', 'webform.webform.alshaya_contact');
  $contact_content->set('title', 'اتصل بنا');
  $contact_content->set('elements', "select_your_preference_of_channel_of_communication:\n  '#title': 'حدد قناة الاتصال المفضلة لديك'\n  '#options':\n    Email: 'البريد الإكتروني'\n    Mobile: 'رقم الجوال'\nfirst_name:\n  '#title': 'الاسم الأول'\nlast_name:\n  '#title': 'اسم العائلة'\nmobile_number:\n  '#title': 'رقم الجوال'\nemail:\n  '#title': 'عنوان البريد الإلكتروني'\nmessage:\n  '#title': 'رسالة نصية: (اختياري)'\n");
  $contact_content->set('handlers.email.settings.body', "<strong>تفضيلات التواصل</strong> - [webform_submission:values:select_your_preference_of_channel_of_communication]<br />\r\n<br />\r\n<strong>اسم</strong> -&nbsp;[webform_submission:values:first_name]&nbsp;[webform_submission:values:last_name]<br />\r\n<br />\r\n<strong>رقم الجوال</strong> -&nbsp;[webform_submission:values:first_name]&nbsp;[webform_submission:values:mobile_number]<br />\r\n<br />\r\n<strong>عنوان البريد الإلكتروني</strong> -&nbsp;[webform_submission:values:first_name]&nbsp;[webform_submission:values:email]<br />\r\n<br />\r\n<strong>رسالة</strong> -&nbsp;<br />\r\n<br />\r\n[webform_submission:values:first_name]&nbsp;[webform_submission:values:message]");
  $contact_content->set('settings.confirmation_message', 'شكرا لإتصالك بنا. سنقوم بالرد عليك في أقرب وقت ممكن!');
  $contact_content->save();
}
