<?php

/**
 * @file
 * Module file with hooks specific to NB brand.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_nb_transac_rcs_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'rcs_product') {
    $build['#attached']['library'][] = 'alshaya_nb_transac_rcs/product';
  }
}

/**
 * Implements hook_algolia_react_common_configs_alter().
 */
function alshaya_nb_transac_rcs_algolia_react_common_configs_alter(&$response) {
  $response['commonAlgoliaSearch']['showProductInfo'] = TRUE;
}

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_nb_transac_rcs_module_implements_alter(&$implementations, $hook) {
  // Make sure the hook on the brand overrides runs last.
  if ($hook == 'rcs_handlebars_templates_alter') {
    $group = $implementations['alshaya_nb_transac_rcs'];
    unset($implementations['alshaya_nb_transac_rcs']);
    $implementations['alshaya_nb_transac_rcs'] = $group;
  }
}

/**
 * Implements hook_rcs_handlebars_templates_alter().
 */
function alshaya_nb_transac_rcs_rcs_handlebars_templates_alter(&$templates, $entity) {
  if (!$entity || $entity->bundle() !== 'rcs_product') {
    return;
  }

  $templates['product.block.description'] = 'alshaya_nb_transac_rcs';
  $templates['product.block.description_details'] = 'alshaya_nb_transac_rcs';
  $templates['product.block.short_description.pdp'] = 'alshaya_nb_transac_rcs';
  $templates['gallery.product.product_zoom'] = 'alshaya_nb_transac_rcs';
  $templates['product.block.name'] = 'alshaya_nb_transac_rcs';
}

/**
 * Implements hook_alshaya_rcs_product_product_options_to_query().
 */
function alshaya_nb_transac_rcs_alshaya_rcs_product_product_options_to_query() {
  return [
    'uk_size',
    'european_size',
    'gender',
    'nb_product_type',
  ];
}

/**
 * Implements hook_alshaya_rcs_product_query_fields_alter().
 */
function alshaya_nb_transac_rcs_alshaya_rcs_product_query_fields_alter(array &$fields) {
  array_push(
    $fields['items'],
    'primary_material',
    'technologies',
    'feature_bullets',
    'green_leaf_notice',
    'green_leaf',
    'gender',
    'nb_product_type',
  );
  array_push($fields['items']['... on ConfigurableProduct']['variants']['product'],
    'width_description',
    'swatch_image',
    'swatch_image_url',
    'weight',
    'weight_text',
    'uk_size',
    'european_size',
    'article_number',
  );
}

/**
 * Implements hook_block_view_alter().
 */
function alshaya_nb_transac_rcs_block_view_alter(array &$build, BlockPluginInterface $block) {
  // Add plp click library for NB.
  if ($build['#configuration']['id'] == 'alshaya_algolia_react_autocomplete') {
    $build['#attached']['drupalSettings']['navigateOnSwatchClick'] = FALSE;
  }
}

/**
 * Implements hook_library_info_alter().
 */
function alshaya_nb_transac_rcs_library_info_alter(&$libraries, $extension) {
  // Unset plp-swatch-hover library.
  if ($extension === 'alshaya_white_label' && isset($libraries['plp-swatch-hover'])) {
    unset($libraries['plp-swatch-hover']);
  }
}
