<?php

/**
 * @file
 * Contains general hooks and alters.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_acm_form_customer_cart_form_alter(&$form, FormStateInterface $form_state) {
  $range = range(1, \Drupal::config('alshaya_acm.cart_config')->get('max_cart_qty'));
  // Using array_combine to ensure we have same data in key and value.
  $cartQuantityOptions = array_combine($range, $range);

  $product_count = 0;
  $form['cart']['#header'][] = t('Remove');

  foreach ($form['cart'] as $id => $item) {
    if (is_array($item) && isset($item['quantity'])) {
      $form['cart'][$id]['quantity']['#type'] = 'select';
      $form['cart'][$id]['quantity']['#options'] = $cartQuantityOptions;

      $product_count += $form['cart'][$id]['quantity']['#default_value'];

      $remove_url = Url::fromUserInput('/cart/remove/' . $id);
      $form['cart'][$id]['remove'] = Link::fromTextAndUrl(t('Remove'), $remove_url)->toRenderable();
    }
  }

  // Set Form title.
  $form['#title'] = t("Cart (%count)", ['%count' => $product_count]);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_acm_form_sku_base_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $range = range(1, \Drupal::config('alshaya_acm.cart_config')->get('max_cart_qty'));
  // Using array_combine to ensure we have same data in key and value.
  $cartQuantityOptions = array_combine($range, $range);

  $form['quantity']['#type'] = 'select';
  $form['quantity']['#options'] = $cartQuantityOptions;
  unset($form['quantity']['#size']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alshaya_acm_form_multistep_default_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Create the cart page link.
  $url = Url::fromRoute('acq_cart.cart');
  $link = \Drupal::l('Back to Basket', $url)->getGeneratedLink();
  $form['back_to_cart'] = [
    '#markup' => $link,
    '#weight' => -5,
  ];
}

/**
 * Implements hook_theme().
 */
function alshaya_acm_theme($existing, $type, $theme, $path) {
  return [
    'checkout_summary' => [
      'variables' => [
        'cart_link' => '',
        'number_of_items' => '',
        'products' => '',
        'subtotal' => '',
        'tax' => '',
        'discount' => '',
        'ordertotal' => '',
        'currency_format' => '',
        'currency_code_position' => '',
        'delivery_address' => '',
        'delivery_method' => '',
        'delivery_label' => '',
        'address_label' => '',
        'shipping_url' => '',
      ],
      'template' => 'block--checkout-summary',
    ],
  ];
}
