<?php

/**
 * @file
 * Cache tags cleanup.
 *
 * Add hook delete to add entry to custom table
 * for all deleted entities.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function cache_tags_cleanup_entity_delete(EntityInterface $entity) {
	try {
		\Drupal::database()->insert("cache_tags_cleanup_queue")
	    ->fields([
	      'entity_id' => $entity->id(),
	      'entity_type' => $entity->getEntityTypeId(),
	      'deleted_on' => time(),
	    ])
	    ->execute();
    }
	catch (\Exception $e) {
	  $logger = \Drupal::logger('cache_tags_cleanup')->error('Exception while inserting data into cache_tags_cleanup_queue. Message: @message.', [
	    '@message' => $e->getMessage(),
	  ]);
	}
}
