<?php

/**
 * @file
 * Main file of Menu Link Attributes module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alshaya_modal_form_menu_link_content_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $menu_link = $form_state->getFormObject()->getEntity();
  $menu_link_options = $menu_link->link->first()->options ?: [];

  $form['modal'] = [
    '#type' => 'checkbox',
    '#title' => t('Open in modal?'),
    '#description' => t('Open this link as modal window.'),
    '#default_value' => isset($menu_link_options['modal']) ? $menu_link_options['modal'] : FALSE,
  ];

  $form['actions']['submit']['#submit'][] = 'alshaya_modal_menu_link_content_form_submit';
}

/**
 * Submit handler for the menu form alter.
 */
function alshaya_modal_menu_link_content_form_submit($form, FormStateInterface $form_state) {
  $menu_link = $form_state->getFormObject()->getEntity();
  $options = ['modal' => $form_state->getValue('modal')];
  $menu_link_options = $menu_link->link->first()->options;

  $menu_link->link->first()->options = array_merge($menu_link_options, $options);
  $menu_link->save();
}

/**
 * Implements hook_preprocess_menu().
 */
function alshaya_modal_preprocess_menu(&$variables) {
  alshaya_modal_set_attributes($variables['items']);
  $variables['#attached']['library'][] = 'core/drupal.dialog.ajax';
}

/**
 * Set the attributes on the given items.
 *
 * @param array $items
 *   List of menu items.
 */
function alshaya_modal_set_attributes(array &$items) {
  foreach ($items as &$item) {
    $url_modal = $item['url']->getOption('modal') ?: FALSE;

    if ($url_modal) {
      $url_attributes = $item['url']->getOption('attributes') ?: [];
      $url_attributes['class'][] = 'use-ajax';

      $item['url']->setOption('attributes', $url_attributes);
    }

    if (!empty($item['below'])) {
      alshaya_modal_set_attributes($item['below']);
    }
  }
}
