<?php

/**
 * @file
 * Primary module hooks for Alshaya Exponea module.
 */

/**
 * Implements hook_page_attachments().
 */
function alshaya_exponea_page_attachments(array &$attachments) {

  // Add Exponea manifest to head.
  $exponea_link = [
    '#tag' => 'link',
    '#attributes' => [
      'rel' => 'manifest',
      'href' => '/manifest.json',
    ],
  ];
  $attachments['#attached']['html_head'][] = [$exponea_link, 'link'];
}
