<?php

/**
 * @file
 * Contains general hooks and alters.
 */

/**
 * Implements hook_alshaya_rcs_product_query_fields_alter().
 */
function alshaya_media_assets_alshaya_rcs_product_query_fields_alter(array &$fields) {
  array_push(
    $fields['items']['... on ConfigurableProduct']['variants']['product'],
    'assets_swatch',
    'assets_pdp',
    'assets_cart',
  );

  // Query for teaser assets for product recommendations.
  if (isset($fields['items']['upsell_products'])) {
    $fields['items']['upsell_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  }
  if (isset($fields['items']['related_products'])) {
    $fields['items']['related_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  }
  if (isset($fields['items']['crosssell_products'])) {
    $fields['items']['crosssell_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function alshaya_media_assets_page_attachments_alter(&$attachments) {
  // Ignore admin paths.
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  // We override the default media library with the assets library.
  foreach ($attachments['#attached']['library'] as $key => $value) {
    if ($value === 'alshaya_rcs_product/rcs_product_images') {
      // Remove the default library.
      unset($attachments['#attached']['library'][$key]);
      // Add assets library.
      $attachments['#attached']['library'][] = 'alshaya_media_assets/rcs_product_images';
      break;
    }
  }
}
