<?php

/**
 * @file
 * Contains general hooks and alters.
 */

/**
 * Implements hook_alshaya_rcs_product_query_fields_alter().
 */
function alshaya_media_assets_alshaya_rcs_product_query_fields_alter(array &$fields) {
  array_push($fields['items'], 'asset_type');

  array_push(
    $fields['items']['... on ConfigurableProduct']['variants']['product'],
    'assets_swatch',
    'assets_pdp',
    'assets_cart',
  );

  // Query for teaser assets for product recommendations.
  if (isset($fields['items']['upsell_products'])) {
    $fields['items']['upsell_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  }
  if (isset($fields['items']['related_products'])) {
    $fields['items']['related_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  }
  if (isset($fields['items']['crosssell_products'])) {
    $fields['items']['crosssell_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  }
}

/**
 * Implements hook_ENTITY_view().
 */
function alshaya_media_assets_page_attachments(&$attachments) {
  // Ignore admin paths.
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }
  // @todo Add the library to individual render arrays of pages rather than
  // adding it in a generalized way like this.
  $attachments['#attached']['library'][] = 'alshaya_media_assets/rcs_product_images';
}

/**
 * Implements hook_alshaya_reset_config_configs_to_reset_alter().
 */
function alshaya_media_assets_alshaya_reset_config_configs_to_reset_alter(array &$reset) {
  // We need pims_base_url to be set per Magento instance.
  // We add it to the list of configs to be reset so it is done with other
  // configs like Connector URL, Magento URL, etc.
  $reset[] = 'alshaya_media_assets.settings';
}

/**
 * Implements hook_alshaya_acm_switch_magento_configs_alter().
 */
function alshaya_media_assets_alshaya_acm_switch_magento_configs_alter(array &$configs) {
  // We need pims_base_url to be set per Magento instance.
  // We add below for configs to be switched so it is set for Magento instance.
  $configs['alshaya_media_assets.settings'] = 'pims_base_url';
}
