<?php

/**
 * Implements hook_rcs_placeholders_graphql_query_alter().
 */
function alshaya_media_assets_rcs_placeholders_graphql_query_alter(&$queries) {
  array_push(
    $queries['products']['items'],
    'asset_type',
  );

  array_push(
    $queries['products']['items']['... on ConfigurableProduct']['variants']['product'],
    'assets_swatch',
    'assets_pdp',
    'assets_cart',
  );

  // Query for teaser assets for product recommendations.
  $queries['products']['items']['upsell_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  $queries['products']['items']['related_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
  $queries['products']['items']['crosssell_products']['... on ConfigurableProduct'] = ['variants' => ['product' => ['assets_teaser']]];
}

/**
 * Implements hook_ENTITY_view().
 */
function alshaya_media_assets_page_attachments(&$attachments) {
  $attachments['#attached']['library'][] = 'alshaya_media_assets/rcs_product_images';
}
