<?php

/**
 * @file
 * Module file with hooks specific to DH brand.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_module_implements_alter().
 */
function alshaya_dh_transac_rcs_module_implements_alter(&$implementations, $hook) {
  // Make sure the hook on the brand overrides runs last.
  if ($hook == 'rcs_handlebars_templates_alter') {
    $group = $implementations['alshaya_dh_transac_rcs'];
    unset($implementations['alshaya_dh_transac_rcs']);
    $implementations['alshaya_dh_transac_rcs'] = $group;
  }
}

/**
 * Implements hook_rcs_handlebars_templates_alter().
 */
function alshaya_dh_transac_rcs_rcs_handlebars_templates_alter(&$templates, $entity) {
  // @todo This code is copied from COS. Please update the code to have proper
  // description available for DH and remove the unnecessary templates.
  if (!$entity || $entity->bundle() !== 'rcs_product') {
    return;
  }

  $templates['product.block.description'] = 'alshaya_dh_transac_rcs';
  $templates['product.block.description_details'] = 'alshaya_dh_transac_rcs';

  /** @var  \Drupal\alshaya_acm_product\SkuManager $sku_manager **/
  $sku_manager = \Drupal::service('alshaya_acm_product.skumanager');

  if ($sku_manager->getPdpLayout($entity) == 'pdp-magazine') {
    $templates['product.block.short_description.pdp-magazine'] = "alshaya_dh_transac_rcs";
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function alshaya_dh_transac_rcs_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'rcs_product') {
    $build['#attached']['library'][] = 'alshaya_dh_transac_rcs/product';
  }
}
