<?php

/**
 * @file
 * Module file.
 */

use Drupal\alshaya_color_split\AlshayaColorSplitConfig;

/**
 * Attach required information around color split.
 *
 * @param array $attachments
 *   An array containing attachment information.
 */
function _alshaya_rcs_color_split_attach_info(array &$attachments) {
  $attachments['#attached']['library'][] = 'alshaya_rcs_color_split/rcs_grouped_products';

  $attachments['#attached']['drupalSettings']['alshayaColorSplit']['colorAttribute'] = AlshayaColorSplitConfig::get('attribute_code_color_id');
  $attachments['#attached']['drupalSettings']['alshayaColorSplit']['colorLabel'] = AlshayaColorSplitConfig::get('color_label_cart_form');
  // Add the cache tags for the color split config.
  $color_split_config = \Drupal::config('alshaya_color_split.settings');
  $attachments['#cache'] = ['tags' => []];
  $attachments['#cache']['tags'] = array_merge($attachments['#cache']['tags'], $color_split_config->getCacheTags());
}

/**
 * Implements hook_alshaya_rcs_product_order_build_alter().
 */
function alshaya_rcs_color_split_alshaya_rcs_product_order_build_alter(array &$build) {
  _alshaya_rcs_color_split_attach_info($build);
}

/**
 * Implements hook_page_attachments().
 */
function alshaya_rcs_color_split_page_attachments(array &$attachments) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  if (!in_array($route_name, [
    'entity.node.canonical',
    'acq_cart.cart',
    'alshaya_spc.checkout',
    'alshaya_spc.checkout.confirmation',
  ])) {
    return;
  }

  _alshaya_rcs_color_split_attach_info($attachments);
}

/**
 * Implements hook_rcs_placeholders_graphql_query_alter().
 */
function alshaya_rcs_color_split_rcs_placeholders_graphql_query_alter(&$queries) {
  $display_settings = \Drupal::config('alshaya_acm_product.display_settings');
  // Get hex value of color.
  $color_code_attribute = $display_settings->get('color_attribute_config')['configurable_color_code_attribute'];
  // Remove the "attr_" prefix.
  $color_code_attribute = str_replace('attr_', '', $color_code_attribute);

  array_push(
    $queries['products']['items']['... on ConfigurableProduct']['variants']['product'],
    AlshayaColorSplitConfig::get('attribute_code_color_id'),
    $color_code_attribute,
  );
}
