<?php

/**
 * @file
 * Alshaya email signup module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alshaya_jus_non_transac_form_webform_submission_alshaya_email_signup_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['elements']['exclusive_deals']['#suffix'] = '';
  $form['actions']['submit']['#value'] = t('Subscribe');
}
