<?php

/**
 * @file
 * Alshaya email signup module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alshaya_jus_non_transac_form_webform_submission_alshaya_email_signup_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['elements']['exclusive_deals']['#suffix'] = '';
  $form['actions']['submit']['#value'] = t('Subscribe');
}

/**
 * Implements hook_views_pre_view().
 */
function alshaya_jus_non_transac_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'product_list' && ($display_id === 'page_1')) {
    $parameters = \Drupal::routeMatch()->getParameters()->get('arg_0');
    $header_text = '';
    $header_text = '<strong>' . $parameters . '</strong><br />' . t('@total items');
    $view->setHandlerOption($display_id, 'header', 'result', 'content', $header_text);
  }
}
